### PR TITLE
add paddle-job

### PR DESCRIPTION
**Pull request by panpanli521**
The paddle-job folder contains prototypes for running Paddle jobs which are based on PaddlePaddle (PArallel Distributed Deep LEarning) framework. This framework is an easy-to-use, efficient, flexible and scalable deep learning platform, which is originally developed by Baidu scientists and engineers for the purpose of applying deep learning to many products.

---
This change is [Reviewable](https://reviewable.io/reviews/kubeflow/kubeflow/2828)

### CODE REVIEW

**Comment by 3a78f807111** [comment]
I signed it!

**Comment by pdmack** [comment]
Can you double-check your CLA info?

**Comment by 3a78f807111** [comment]
I checked my existing CLA data and found that the email is not set on my git commits. Then I set the email on my git, but this PR is still not approved. What can I do next? @pdmack

**Comment by panpanli521** [comment]
I signed it!

**Pull request merged**
