### PR TITLE
Add kfctl config for k8s only

### LINKED ISSUE #3626: kfctl without platform not working
```
kfctl init ${KFAPP}
cd ${KFAPP}
kfctl generate k8s -V
```
This will give error:
`ERRO[0000] Couldn't find component istio-crds filename="kustomize/kustomize.go:454"`

After removed the istio components from app.yaml, the generate succeeds.
But apply failed with:
```
Error: couldn't apply KfApp:  (kubeflow.error): Code 500 with message: kfApp Apply failed for kustomize:  (kubeflow.error): Code 500 with message: couldn't create resources from /Users/lunkai/kfdev/kops-test/kf0708/kustomize/minio.yaml Error: persistentvolumes "minio-pv" is forbidden: error querying GCE PD volume dls-kf-storage-artifact-store: disk is not found
```

See #3618 3618

### PR DESCRIPTION
**Pull request by lluunn**
Related to #3618 
fix #3626 . 

Create Cluster | Install Istio | Use Istio | Flags
-- | -- | -- | --
Yes | Yes | Yes | `kfctl --platform=gcp --use_istio=true`
No | Yes | Yes | `kfctl --config=kfctl_k8s_istio.yaml`
No | No | Yes | `kfctl --config=kfctl_k8s_istio.yaml` (modify config first, see comment in the file)

/cc @jlewi @kunmingg @yanniszark 

I didn't use existing_arrikto because that also installs some dex thing.

---
This change is [Reviewable](https://reviewable.io/reviews/kubeflow/kubeflow/3663)

### CODE REVIEW

**Comment by jlewi** [comment]
@lluunn Overally looks good. Instead of having separate config files. Should we just have a single config file and maybe comment out the ISTIO package or maybe leave it in but add a comment telling people to comment it out if they don't want to install ISTIO?

This will get a little easier once I submit the changes to kfctl to use KfDef.Applications.

In the meantime, I think we should try to minimize the number of configs that we maintain.

Also could you please open up an issue about adding an E2E test?

Thanks

**Comment by lluunn** [comment]
Merged the config, and added comment.
Thanks

**Pull request merged**
