### PR TITLE
[tf-notebook-image] add tf 1.11 cpu and gpu images

### PR DESCRIPTION
**Pull request by r2d4**
This change is [Reviewable](https://reviewable.io/reviews/kubeflow/kubeflow/1786)

### CODE REVIEW

**Comment by r2d4** [comment]
Fixes https://github.com/kubeflow/kubeflow/issues/1740

**Comment by richardsliu** [comment]
Could you tag the v0.3.1 images? The doc is here: https://github.com/kubeflow/kubeflow/blob/master/docs_dev/releasing.md

You'll need to run this script: https://github.com/kubeflow/kubeflow/blob/master/releasing/run_apply_image_tags.sh

Something like:
```
IMAGE_PATTERN=".*tensorflow.*notebook-1\.11\.0.*:v0.3.1.*"
./run_apply_image_tags.sh "${IMAGE_PATTERN}"
```

**Comment by r2d4** [comment]
@richardsliu ok I ran that. 
```
└───▶ releasing/run_apply_image_tags.sh "${IMAGE_PATTERN}"
+ PATTERN='.*tensorflow.*notebook-1\.11\.0.*:v0.3.1.*'
+++ dirname releasing/run_apply_image_tags.sh
++ cd releasing
++ pwd
+ DIR=/usr/local/google/home/mrick/go/src/github.com/kubeflow/kubeflow/releasing
++ cd /usr/local/google/home/mrick/go/src/github.com/kubeflow/kubeflow/releasing/..
++ pwd
+ ROOT_DIR=/usr/local/google/home/mrick/go/src/github.com/kubeflow/kubeflow
+ export PYTHONPATH=/usr/local/buildtools/current/sitecustomize:/usr/local/google/home/mrick/go/src/github.com/kubeflow/kubeflow/../git_kubeflow-testing/py
+ PYTHONPATH=/usr/local/buildtools/current/sitecustomize:/usr/local/google/home/mrick/go/src/github.com/kubeflow/kubeflow/../git_kubeflow-testing/py
+ python /usr/local/google/home/mrick/go/src/github.com/kubeflow/kubeflow/releasing/apply_image_tags.py --images_file=/usr/local/google/home/mrick/go/src/github.com/kubeflow/kubeflow/releasing/image_tags.yaml '--pattern=.*tensorflow.*notebook-1\.11\.0.*:v0.3.1.*'
INFO|2018-10-26T15:01:15|/usr/local/google/home/mrick/go/src/github.com/kubeflow/kubeflow/releasing/apply_image_tags.py|54| Done.
```

**Comment by richardsliu** [comment]
@r2d4 Looks like TensorFlow 1.12 is out: https://github.com/tensorflow/tensorflow/releases

Since this is not merged yet, do you want to just add the images in the same PR?

**Pull request merged**
