### PR TITLE
Remove gpu_model.jsonnet

### LINKED ISSUE #983: presubmit failing:  couldn't open import "X": no match locally or in the Jsonnet library path
```
INFO|2018-06-12T22:38:36|/src/kubeflow/testing/py/kubeflow/testing/util.py|62| level=error msg="find objects: RUNTIME ERROR: couldn't open import \"kubeflow/tf-serving/tf-serving.libsonnet\": no match locally or in the Jsonnet library paths\n\t<extvar:__ksonnet/components>:5:23-72\tthunk <tfServing> from <object <anonymous>>\n\t<extvar:__ksonnet/components>:21:20-29\tthunk <server> from <object <anonymous>>\n\t<extvar:__ksonnet/components>:(21:20)-(33:6)\tthunk <server> from <object <anonymous>>\n\t<extvar:__ksonnet/components>:36:7-13\tthunk from <thunk from <thunk from <object <anonymous>>>>\n\t<std>:1218:53-54\tthunk from <thunk from <function <anonymous>>>\n\t<std>:1216:24-25\tthunk from <thunk <t> from <function <anonymous>>>\n\t<builtin>\tbuiltin function <type>\n\t<std>:1217:8-9\tfunction <anonymous>\n\t<std>:1165:25-26\tthunk from <thunk <ta> from <function <anonymous>>>\n\t<builtin>\tbuiltin function <type>\n\t<std>:1167:29-31\tthunk from <function <anonymous>>\n\t<builtin>\tbuiltin function <primitiveEquals>\n\t<std>:1167:8-36\tfunction <anonymous>\n\t\t\n\t<std>:1218:45-55\tthunk from <function <anonymous>>\n\t<std>:1208:10-11\tfunction <isContent>\n\t<std>:1165:25-26\tthunk from <thunk <ta> from <function <anonymous>>>\n\t<builtin>\tbuiltin function <type>\n\t<std>:1167:29-31\tthunk from <function <anonymous>>\n\t<builtin>\tbuiltin function <primitiveEquals>\n\t<std>:1167:8-36\tfunction <anonymous>\n\t\t\n\t<std>:1218:35-56\tfunction <anonymous>\n\t<builtin>\tbuiltin function <flatMap>\n\t<std>:1222:20-35\tthunk from <function <anonymous>>\n\t<std>:1208:10-11\tfunction <isContent>\n\t<std>:1165:25-26\tthunk from <thunk <ta> from <function <anonymous>>>\n\t<builtin>\tbuiltin function <type>\n\t<std>:1167:29-31\tthunk from <function <anonymous>>\n\t<builtin>\tbuiltin function <primitiveEquals>\n\t<std>:1167:8-36\tfunction <anonymous>\n\t\t\n\t<std>:1222:10-36\tfunction <anonymous>\n\t<builtin>\tbuiltin function <flatMap>\n\t<builtin>\tbuiltin function <$objectFlatMerge>\n\t<extvar:__ksonnet/components>:(35:5)-(38:8)\tobject <anonymous>\n\tDuring manifestation\t\n"

Traceback (most recent call last):
  File "/usr/lib/python2.7/runpy.py", line 174, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/src/kubeflow/testing/py/kubeflow/testing/run_e2e_workflow.py", line 320, in <module>
    final_result = main()
  File "/src/kubeflow/testing/py/kubeflow/testing/run_e2e_workflow.py", line 310, in main
    return run(args, file_handler)
  File "/src/kubeflow/testing/py/kubeflow/testing/run_e2e_workflow.py", line 183, in run
    util.run(["ks", "show", env, "-c", w.component], cwd=w.app_dir)
  File "/src/kubeflow/testing/py/kubeflow/testing/util.py", line 74, in run
    " ".join(command), process.returncode), "\n".join(output))
subprocess.CalledProcessError: Command 'cmd: ks show kubeflow-presubmit-tf-serving-image-979-4a8bc1c-2052-ebfd -c workflows exited with code 1' returned non-zero exit status 1
```

Is this ks version issue?

### PR DESCRIPTION
**Pull request by lluunn**
Fix #983

We are testing GPU serving in workflows, and not using this gpu_model.

---
This change is [Reviewable](https://reviewable.io/reviews/kubeflow/kubeflow/984)

### CODE REVIEW

**Comment by ankushagarwal** [comment]
/lgtm
/approve

Thanks for fixing this!

**Comment by jlewi** [comment]
nit: PR descriptions should explain what the bug is and what the fix is.

Is this removing our GPU test for serving?

**Comment by lluunn** [comment]
Thanks.
Updated the description. We are testing GPU serving using workflows component. gpu_model is unused.

**Pull request merged**
