### PR TITLE
Fix for issue 1050 - camelCase for some recently fixed params. 

### LINKED ISSUE #1050: camelCase for some recently fixed params
These should be camelCase:
```
// @optionalParam AmbassadorServiceType string ClusterIP The service type for the API Gateway.
// @optionalParam AmbassadorImage string quay.io/datawire/ambassador:0.30.1 The image for the API Gateway.
// @optionalParam StatsdImage string quay.io/datawire/statsd:0.30.1 The image for the Stats and Monitoring.
```

### PR DESCRIPTION
**Pull request by ashahba**
fixes #1050 
First round of changes include updating `image_gpu, num_schedulers, num_servers, num_workers, num_gpus and giturl` in files:

```
kubeflow/mxnet-job/prototypes/mxnet-job.jsonnet
kubeflow/pytorch-job/prototypes/pytorch-job.jsonnet
kubeflow/weaveflux/README.md
kubeflow/weaveflux/all.libsonnet
kubeflow/weaveflux/prototypes/weaveflux.jsonnet
```

More is on the way but I need the get green light on this first before making the rest of changes that I mentioned in here: https://github.com/kubeflow/kubeflow/issues/1050#issuecomment-422537610

Otherwise this should be sufficient for the release and I can file a separate issue and a subsequent PR to work on that after we are done with the release.

I'm open to either one, please let me know.

---
This change is [Reviewable](https://reviewable.io/reviews/kubeflow/kubeflow/1556)

### CODE REVIEW

**Comment by ashahba** [comment]
@jlewi I did a deep search within the repo and to best of my knowledge the only param that needed a doc/README.md update is `giturl` which is already reflected here: https://github.com/kubeflow/kubeflow/pull/1556/files#diff-d69b704385e0955a4336e131a3c802b8R18

If there are other places where we keep the docs, please let me know.

**Comment by jlewi** [comment]
@ashahba Thanks I was specifically referring to the docs on our website
www.kubeflow.org
which are in kubeflow/website
Can you take a look at the docs for the components updated in this PR and see if the docs need to be updated e.g.
https://www.kubeflow.org/docs/guides/components/mxnet/

**Comment by ashahba** [comment]
Thanks @jlewi .
It looks like the only match we have in the website code, is in this file:
[tftraining.md](https://github.com/kubeflow/website/blob/master/content/docs/guides/components/tftraining.md)
and for `num_gpus`.
But those are container args for `Ps` and `worker` that are consumed by Python training scripts and they are still valid and won't be effected by this change, so no doc update is needed in this case unless I'm missing something.

Please let me know if that sounds reasonable 🙂

**Pull request merged**
