### PR TITLE
Create a minimal release process for kfctl.

### PR DESCRIPTION
**Pull request by jlewi**
* Instructions for building binaries and uploading to GitHub release page.
* We need to figure out if/how we cross-compile for linux.
  * Cross compiling seems to be unnecessary
  * The go binaries built on linux appear to work on macosx.

Fix: #2383

---
This change is [Reviewable](https://reviewable.io/reviews/kubeflow/kubeflow/2894)

### CODE REVIEW

**Comment by gabrielwen** [comment]
for my own learning: where will the binary go?

**Comment by kkasravi** [comment]
> for my own learning: where will the binary go?
/usr/local/bin. In the future brew will do this as well

**Comment by jlewi** [comment]
@gabrielwen @kkasravi Should we tar.gz the binary?

**Comment by gabrielwen** [comment]
my last compiled binary is the size of 125MB, so yes, I think we should compress it.

**Pull request merged**
