### PR TITLE
Refactor tensorflow-notebook-image/Dockerfile

### PR DESCRIPTION
**Pull request by ankushagarwal**
Remove a lot of bloat - install only the minimal set of packages
required to get started with ML. Any packages required can be installed
by the user in the notebook itself using pip install/conda install

Image size has gone down from 12GB to 3GB for cpu image

Having a lot of packages makes it very challenging to maintain them
because of version conflicts

Run everything as jovyan user - this enables user to run conda install
/ pip install without requiring sudo

Add comments on every step

Fixes https://github.com/kubeflow/kubeflow/issues/668
Fixes https://github.com/kubeflow/kubeflow/issues/37
Fixes https://github.com/kubeflow/kubeflow/issues/472

/assign @pdmack 
/cc @lluunn 

FYI @jlewi

---
This change is [Reviewable](https://reviewable.io/reviews/kubeflow/kubeflow/689)

### CODE REVIEW

**Comment by pdmack** [comment]
"Image size has gone down from 12GB to 3GB for cpu image"!
Um, that's awesome!

**Comment by ankushagarwal** [comment]
Tested the cpu image on dev.kubeflow.org

**Comment by pdmack** [comment]
Just building and testing locally now for completeness. Update you soon.

**Comment by pdmack** [comment]
```
tf-notebook ankush 0f7b72950646 51 seconds ago 2.79GB
```
Let's see what's under the hood...

**Comment by pdmack** [comment]
```
jovyan@2675112f13b6:~$ pip install comet_ml
Collecting comet_ml
  Downloading https://files.pythonhosted.org/packages/08/f1/dc9a87791dd770abd7433e57e0cdc6cd5e689507c734de9195105d3ed93f/comet_ml-1.0.7-py3-none-any.whl
Collecting wurlitzer>=1.0.1 (from comet_ml)
  Downloading https://files.pythonhosted.org/packages/eb/81/5171c7134d85965e85a2899aa092b5edec737356dc25d99719ac15396272/wurlitzer-1.0.1-py2.py3-none-any.whl
Collecting websocket-client>=0.44.0 (from comet_ml)
  Downloading https://files.pythonhosted.org/packages/9d/fb/f51a03e232e00d6c504dfe815aed090c894ba3f8d3f7fd9612f3e227bf24/websocket_client-0.47.0-py2.py3-none-any.whl (200kB)
    100% |████████████████████████████████| 204kB 1.2MB/s
Requirement already satisfied: six in ./.conda/lib/python3.6/site-packages (from comet_ml) (1.11.0)
Requirement already satisfied: requests>=2.18.4 in ./.conda/lib/python3.6/site-packages (from comet_ml) (2.18.4)
Requirement already satisfied: chardet<3.1.0,>=3.0.2 in ./.conda/lib/python3.6/site-packages (from requests>=2.18.4->comet_ml) (3.0.4)
Requirement already satisfied: idna<2.7,>=2.5 in ./.conda/lib/python3.6/site-packages (from requests>=2.18.4->comet_ml) (2.6)
Requirement already satisfied: urllib3<1.23,>=1.21.1 in ./.conda/lib/python3.6/site-packages (from requests>=2.18.4->comet_ml) (1.22)
Requirement already satisfied: certifi>=2017.4.17 in ./.conda/lib/python3.6/site-packages (from requests>=2.18.4->comet_ml) (2018.4.16)
Installing collected packages: wurlitzer, websocket-client, comet-ml
Successfully installed comet-ml-1.0.7 websocket-client-0.47.0 wurlitzer-1.0.1
```

**Comment by pdmack** [comment]
screen shot 2018-04-19 at 6 01 54 pm

Looks good but @ankushagarwal, @jlewi are we sure we don't want the TF benchmarks and models in there? I understand that maybe those repos and their git objects were chewing up a lot of space but we could just grab and explode their tarballs too.

**Comment by pdmack** [comment]
OK, not sure what changed on the force push but still looks great. Thanks!

/approve
/lgtm

**Comment by ankushagarwal** [comment]
@pdmack : I added gcloud install

**Pull request merged**
