### PR TITLE
Release v1.3.0-rc.0 for kubeflow/kubeflow

### PR DESCRIPTION
**Pull request by yanniszark**
Release version `v1.3.0-rc.0` to give to the manifests WG for syncing:
https://github.com/kubeflow/manifests/issues/1775

cc @kubeflow/wg-notebooks-leads

### CODE REVIEW

**Comment by yanniszark** [comment]
/hold
for reviews

**Comment by yanniszark** [comment]
I see that Prow tests don't run for the `v1.3-branch`. Pinging @PatrickXYS

**Review by PatrickXYS — APPROVED** [review]
A quick question, I assume we hardcode the image tag in v1.3-branch when building images, I was thinking about this model can also fit into other WGs' use case. 

/lgtm

**Comment by DavidSpek** [comment]
Looks good to me. Somewhat related to this PR is that I think I found and issue with the tensorboard-controller. Not sure if that should be fixed before this PR or after. It doesn’t cause an issue with the current set of manifests, but the selector for the service and the app labels are missing.

**Pull request merged**
