### PR TITLE
Cast nvidia.com/gpu value as string respective of K8s Resource Spec

### LINKED ISSUE #6014: Creating a notebook with GPU (body must be of type string: "integer"`)
Hello!

I'm trying to create a notebook with a GPU asociated, but im getting this error. Also tryed to create it by a cURL but didnt worked neither.

Error: `Notebook.kubeflow.org "testgpu" is invalid: spec.template.spec.containers.resources.limits.nvidia.com/gpu: Invalid value: "integer": spec.template.spec.containers.resources.limits.nvidia.com/gpu in body must be of type string: "integer"`

I created a notebook without an gpu associated but Tensorflow recognice that i have one.

### PR DESCRIPTION
**Pull request by edhenry**
Fixes #6014

### CODE REVIEW

**Comment by edhenry** [comment]
@googlebot I fixed it.

**Comment by edhenry** [comment]
@googlebot I fixed it.

**Comment by DavidSpek** [comment]
related to https://github.com/kubeflow/kubeflow/pull/5891/files

**Comment by edhenry** [comment]
I wasn't sure of where the casting should be made respective of the overall project architecture or patterns so if this doesn't fit please feel free to close. Good to know there was already a PR merged previously. 😊

**Comment by kimwnasptd** [comment]
This got completely under my radar, thanks for the ping @DnPlas! I see it's also discussed in https://github.com/kubeflow/kubeflow/issues/6014.

This is the backend counterpart of https://github.com/kubeflow/kubeflow/pull/5891. This should also make it into the next RC.

/lgtm
/approve

**Comment by kimwnasptd** [comment]
@edhenry could you also do a rebase/force-push on top of the latest master? This should fix the e2e tests

/ok-to-test

**Comment by edhenry** [comment]
Apologies for the delayed reply - I've been on an extended vacation. I'll
get this done in the next few days!

**Comment by DnPlas** [comment]
Hi @edhenry , do you mind rebasing as @kimwnasptd mentioned? It's been a while since this PR's been open and we should have this fix in the next release.

**Comment by kimwnasptd** [comment]
Let's give @edhenry a couple of more days to see if he can rebase on top of the latest master and get this merged.

Otherwise @DnPlas could you send a PR for this small fix? We can include this in the 1.6 release

**Comment by edhenry** [comment]
> Let's give @edhenry a couple of more days to see if he can rebase on top of the latest master and get this merged.
> 
> Otherwise @DnPlas could you send a PR for this small fix? We can include this in the 1.6 release

Apologies for the delay! Feel free to let me know if there is anything else I need to do!

Thank you!

**Pull request merged**
