### PR TITLE
always create default profile; turn off istio rbac for kfctl_k8s_istio

### PR DESCRIPTION
**Pull request by kunmingg**
* Always create a default profile by setting a default "anonymous" value for user id so that a profile would be created for user "anonymous"

* Turn off ISTIO RBAC in kfctl_k8s_istio because this config won't have the user's identity or JWTs so  ISTIO can't do service Authz.

related: https://github.com/kubeflow/kubeflow/issues/3893

---
This change is [Reviewable](https://reviewable.io/reviews/kubeflow/kubeflow/3959)

### CODE REVIEW

**Comment by kunmingg** [comment]
Verified working on `deploy to existing k8s cluster`

**Comment by jlewi** [comment]
Thanks @kunmingg I'd suggest changing the default user id to "anonymous" as opposed to default or "anonymous-user".

This way if we display it e.g. in the UI I think its a little more intelligible then just "default".

Hope you don't mind but I took a stab at updating the PR description; PTAL

**Comment by yanniszark** [comment]
@kunmingg can you also rebase to pick up the change from #3877 ?

**Comment by yanniszark** [comment]
@jlewi do we always want to create a default profile?
In case multi-user is enabled, I believe @avdaredevil 's new UI guides users through the creation of a new profile.
Maybe we should make this opt-in?

I was thinking:
* Make a new package in manifests which creates a profile.
* In case of GCP, set a parameter for the userid.
* Configs can use this package if they want to.

**Comment by kunmingg** [comment]
@yanniszark 
Creating default profile is to smooth cluster owner experience: they'll always have a profile available once cluster is up. We try to resolve some confusions during v0.6.1 adoption.
Going forward we can have manifests pkg preparing default profiles.

**Pull request merged**
