### PR TITLE
kfctl: pass correct value to repo field of KfDef

### PR DESCRIPTION
**Pull request by yanniszark**
Fixes: #3471

This commit fixes the repo value of KfDef, which is wrong.
Other code that depends on it being wrong is also corrected.

Signed-off-by: Yannis Zarkadas <yanniszark@arrikto.com>

---
This change is [Reviewable](https://reviewable.io/reviews/kubeflow/kubeflow/3472)

### CODE REVIEW

**Comment by jlewi** [comment]
@yanniszark Is this PR still relevant?

As noted in #3471 I believe this is fixed on master by the fact that we now specify repos in KfDef.Spec and store locations of the cache in KfDef.Status.

**Comment by yanniszark** [comment]
@jlewi this is fixed by the repos field addition.
Thanks for the pr gc

**Pull request closed without merging**
