### PR TITLE
Replace 'cloud' parameter with more direct names like 'params.tfDefaultImage' and 'params.platform'

### LINKED ISSUE #1227: Remove ksonnet parameter cloud
We no longer use the cloud ksonnet parameter so we should just get rid of it.

### PR DESCRIPTION
**Pull request by ashahba**
fixes #1227

---
This change is [Reviewable](https://reviewable.io/reviews/kubeflow/kubeflow/1742)

### CODE REVIEW

**Comment by ashahba** [comment]
/assign @jlewi 
I'm getting a bunch of `iam` errors during runs.
```
 O='ERROR: (gcloud.iam.service-accounts.describe) PERMISSION_DENIED: Permission iam.serviceAccounts.get is required to perform this operation on service account projects/-/serviceAccount
s/kfctl-8767-admin@kubeflow-ci.iam.gserviceaccount.com.'
+ local RESULT=1
+ '[' 1 -ne 0 ']'
+ echo Service account kfctl-8767-admin@kubeflow-ci.iam.gserviceaccount.com 'doesn'\''t' exist or you do not have permission to access service accounts.
+ return
+ for suffix in '"${accounts[@]}"'
+ SA=kfctl-8767-user@kubeflow-ci.iam.gserviceaccount.com
+ deleteSa kfctl-8767-user@kubeflow-ci.iam.gserviceaccount.com
+ local SA=kfctl-8767-user@kubeflow-ci.iam.gserviceaccount.com
Service account kfctl-8767-admin@kubeflow-ci.iam.gserviceaccount.com doesn't exist or you do not have permission to access service accounts.
++ gcloud --project=kubeflow-ci iam service-accounts describe kfctl-8767-user@kubeflow-ci.iam.gserviceaccount.com
```

I believe I'm missing some permissions to run `presubmit` tests.
Would you please double check?

Thanks.

**Comment by jlewi** [comment]
Thanks!

Any chance you could add tests for these modules like these
https://github.com/kubeflow/kubeflow/tree/master/kubeflow/core/tests

**Comment by jlewi** [comment]
I think you need to pull in the latest changes on master and rebase in order to fix the tests.

**Comment by jlewi** [comment]
Here are the logs from the failed test 

```
E  + ks apply default -c ambassador
 
E  level=error msg="find objects: RUNTIME ERROR: Field does not exist: platform\n\t/mnt/test-data-volume/kubeflow-presubmit-kfctl-1742-15370c5-3820-79aa/kfctl-79aa/ks_app/vendor/kubeflow/core/ambassador.libsonnet:149:27-42\tobject <anonymous>\n\t<std>:1165:25-26\tthunk from <thunk <ta> from <function <anonymous>>>\n\t<builtin>\tbuiltin function <type>\n\t<std>:1167:29-31\tthunk from <function <anonymous>>\n\t<builtin>\tbuiltin function <primitiveEquals>\n\t<std>:1167:8-36\tfunction <anonymous>\n\t\t\n\t/mnt/test-data-volume/kubeflow-presubmit-kfctl-1742-15370c5-3820-79aa/kfctl-79aa/ks_app/vendor/kubeflow/core/ambassador.libsonnet:157:19-27\tobject <anonymous>\n\tDuring manifestation\t\n"
 
  undefined
```

So it looks like there is a problem with the ksonnet. 

You should be able to debug locally just by creating a test app and running "ks show"

**Comment by jlewi** [comment]
Even better would be to add a unittest for the ambassador prototype here
https://github.com/kubeflow/kubeflow/tree/master/kubeflow/core/tests

**Comment by ashahba** [comment]
@jlewi this is done.
But still need to write test cases for `ambassador`.
We can address the testing here or in a separate ticket.
Let me know what you think.

Thanks.

**Comment by jlewi** [comment]
Separate PR SGTM

/lgtm
/approve

**Pull request merged**
