### PR TITLE
Old: Update CRUD web apps from Angular 8 to Angular 11 or 12

### PR DESCRIPTION
**Pull request by DavidSpek**
Closes: https://github.com/kubeflow/kubeflow/issues/5525

Angular 8 has been deprecated for a while now, with Angular 11 being the latest version. Sadly, you cannot skip version so the process to update from 8 to 11 was to first update the common code to version 9, then the web apps and confirm they are working properly. Then again for version 9 to 10 and once more for 10 to 11. 

During the update process from Angular 8 to 9 of the web apps some errors are shown that don't seem to make much sense. From what I can find this is due to the use of `npm link` to the common frontend code and this bug has been fixed in Angular 10. For this reason, I ignored the errors and tested the web app functionality manually. As no errors were logged and nothing seemed to be broken I continued. I manually tested the web apps after each update and saw no errors or problems.

I've added the commands executed for (almost) every commit in the description. To prevent getting stuck with outdated software for longer than necessary, and given the inevitable size of this PR, I would like to suggest that this PR be reviewed by manually running the resulting web-apps and confirming nothing out of the ordinary is seen there. After this PR has been merged the next step would be to look more closely into what features are now deprecated in Angular and what new features replace them. A useful overview for this can be found [here](https://update.angular.io/?l=3&v=8.2-11.0).

/cc @kimwnasptd @StefanoFioravanzo @thesuperzapper @elikatsis @yanniszark

### CODE REVIEW

**Comment by DavidSpek** [comment]
I'm guessing the failure of [this test](https://argo.kubeflow-testing.com/workflows/kubeflow-test-infra/kubeflow-kubeflow-presubmit-common-ui-5805-a05f26d-1456-6b02?tab=workflow&nodeId=kubeflow-kubeflow-presubmit-common-ui-5805-a05f26d-1456-6b02-1029517815&sidePanel=logs%3Akubeflow-kubeflow-presubmit-common-ui-5805-a05f26d-1456-6b02-1029517815%3Amain) is caused by a need to update the tests for the newer version of Angular.

**Comment by DavidSpek** [comment]
The last commit does seem to solve the initial problem with the common UI tests. Locally the test runs successfully and consistently. However, in the CI the common UI test is failing with a different unrelated error each time.

/test kubeflow-kubeflow-presubmit
--

**Comment by thesuperzapper** [comment]
@kubeflow/wg-notebooks-leads @DavidSpek I think this should be merged once we finalise the 1.3 release version, (ETA 19th April).

@kimwnasptd realistically, there is no way to test this beyond just deploying it, and checking. 
I think the focus should be on ensuring it "works" the same as it did with angular 8, and deal with stylistic refactoring AFTER in followup PRs. (Especially because we are massively out of date, and thats a security issue)

**Pull request closed without merging**
