### PR TITLE
[CentralDashboard v2] Registration dns validation fix

### PR DESCRIPTION
**Pull request by avdaredevil**
## About
Tackles P0 issue, where registration flow allows you to type or autofill incorrect values. Solution: client-side validator added :)

### Meta
/area centraldashboard
/area front-end
/priority p0
/assign @avdaredevil
/cc @prodonjs

---
This change is [Reviewable](https://reviewable.io/reviews/kubeflow/kubeflow/4283)

### CODE REVIEW

**Comment by jlewi** [comment]
/assign @prodonjs 

@prodonjs Could you review this please?

**Comment by prodonjs** [comment]
@avdaredevil - You may want to rebase and push again to see if that fixes the failing presubmit.

**Comment by avdaredevil** [comment]
@prodonjs done :)

**Pull request merged**
