### PR TITLE
[wip] fixes #2365 #2366

### LINKED ISSUE #2365: Remove --packages and --components from 'kfctl generate' (golang)
These CLI parameters are only used internally and should not be exposed at the CLI level.

### PR DESCRIPTION
**Pull request by kkasravi**
fixes
[Move --namespace parameter from generate to init in kfctl (golang)](https://github.com/kubeflow/kubeflow/issues/2366)
[Remove --packages and --components from 'kfctl generate' (golang)](https://github.com/kubeflow/kubeflow/issues/2365)

---
This change is [Reviewable](https://reviewable.io/reviews/kubeflow/kubeflow/2376)

### CODE REVIEW

**Comment by jlewi** [comment]
#2294 needs to be merged first right?

**Comment by kkasravi** [comment]
yep, this PR is based on 2294

**Comment by kkasravi** [comment]
this was folded into #2294 since comments about these changes were made in #2294

**Pull request closed without merging**
