### PR TITLE
implement gcpUtils which takes care of integrating deployment manager API (part of PR 1458)

### PR DESCRIPTION
**Pull request by kunmingg**
See previous PR:
https://github.com/kubeflow/kubeflow/pull/1458

---
This change is [Reviewable](https://reviewable.io/reviews/kubeflow/kubeflow/1460)

### CODE REVIEW

**Comment by jlewi** [comment]
Please give the PR a more descriptive name

**Comment by jlewi** [comment]
It looks like information is still stored about the application in a map[project + deployment] name.
Presumably this is because we are still storing the app on disk.

I assume this is only short term until we can make it truly state less by pulling the app on each request from git?

**Comment by kunmingg** [comment]
Yes, will do in following steps.

**Pull request merged**
