### PR TITLE
Remove unused files

### PR DESCRIPTION
**Pull request by thesuperzapper**
As part of migrating code out of this repo https://github.com/kubeflow/kubeflow/issues/7549, there is a bunch of code on this repo which does nothing anymore.

This PR removes the following content from the `kubeflow/kubeflow` repo:

- [`./docs/gke/`](https://github.com/kubeflow/kubeflow/tree/master/docs/gke):
     - This content is extremely out of date, and its specific to GKE.
- [`./docs_dev/`](https://github.com/kubeflow/kubeflow/tree/master/docs_dev)
     - This content is extremely out of date and not useful anymore, its 5-6 years since its last update.
- [`./py/`](https://github.com/kubeflow/kubeflow/tree/master/py):
     - This is the old Prow tests, which we no longer use since migrating to GitHub actions.
- [`./security/`](https://github.com/kubeflow/kubeflow/tree/master/security):
     - This content should be moved to `kubeflow/community`, see:
     -  https://github.com/kubeflow/community/pull/749
- [`./testing/gh-actions/`](https://github.com/kubeflow/kubeflow/tree/master/testing/gh-actions)
     - This is an empty folder, and was never needed for the migration to GitHub actions.
 - [`.pylintrc`](https://github.com/kubeflow/kubeflow/blob/master/.pylintrc)
     - We no longer use Pylint
- [`.style.yapf`](https://github.com/kubeflow/kubeflow/blob/master/.style.yapf)
     - We no longer use yapf
- [`prow_config.yaml`](https://github.com/kubeflow/kubeflow/blob/master/prow_config.yaml)
     - We no longer use Prow for testing on this rep.

### CODE REVIEW

**Comment by thesuperzapper** [comment]
@kimwnasptd if you agree with all these removals, please LGTM.

After that, @andreyvelich can approve (it requires a root approver).

**Review by andreyvelich — COMMENTED** [review]
Thank you for this @thesuperzapper!
Overall, lgtm.
Should we also remove security folder: https://github.com/thesuperzapper/kubeflow/tree/remove-unused-files/security @juliusvonkohout @akgraner ?


/assign @kubeflow/wg-manifests-leads @kubeflow/wg-notebooks-leads @kubeflow/kubeflow-steering-committee

**Comment by juliusvonkohout** [comment]
We should probably move the security folder to kubeflow/manifests.

**Comment by andreyvelich** [comment]
@juliusvonkohout Can you submit PR to move it under manifests repo and remove it from `kubeflow/kubeflow` ?

**Comment by thesuperzapper** [comment]
@andreyvelich @juliusvonkohout I think security info should be under [`kubeflow/community`](https://github.com/kubeflow/community) with the rest of the governance docs, otherwise old versions of the information will end up snapshotted with old versions.

**Comment by andreyvelich** [comment]
> I think security info should be under [`kubeflow/community`](https://github.com/kubeflow/community) with the rest of the governance docs, otherwise old versions of the information will end up snapshotted with old versions.

I am fine with the both as long as maintainers can take care of those assets.

**Comment by thesuperzapper** [comment]
@andreyvelich I have also removed the `./security` folder in this PR and raised a seperate one to move it to `kubeflow/community`:

- https://github.com/kubeflow/community/pull/749

**Review by andreyvelich — COMMENTED** [review]
Thanks @thesuperzapper!
/lgtm
/assign @kubeflow/kubeflow-steering-committee

**Review by terrytangyuan — APPROVED** [review]
Thanks!

/lgtm
/approve

**Pull request merged**
