### PR TITLE
Update the developer guide for kfctl.

### PR DESCRIPTION
**Pull request by jlewi**
* Add instructions for how to build kfctl and deal with build errors about
  /tmp/v2

---
This change is [Reviewable](https://reviewable.io/reviews/kubeflow/kubeflow/2794)

### CODE REVIEW

**Comment by jlewi** [comment]
Random test flake checking out the source code

```
W
+ SRC_DIR=/mnt/test-data-volume/kubeflow-presubmit-kfctl-go-2794-6ca3e4e-6696-ee75/src
+ mkdir -p /src/kubeflow
+ git clone https://github.com/kubeflow/kubeflow.git /mnt/test-data-volume/kubeflow-presubmit-kfctl-go-2794-6ca3e4e-6696-ee75/src/kubeflow/kubeflow
Cloning into '/mnt/test-data-volume/kubeflow-presubmit-kfctl-go-2794-6ca3e4e-6696-ee75/src/kubeflow/kubeflow'...
error: RPC failed; curl 56 GnuTLS recv error (-54): Error in the pull function.
fatal: The remote end hung up unexpectedly
fatal: early EOF
fatal: index-pack failed
```

**Comment by gabrielwen** [comment]
> Random test flake checking out the source code
> 
> ```
> W
> + SRC_DIR=/mnt/test-data-volume/kubeflow-presubmit-kfctl-go-2794-6ca3e4e-6696-ee75/src
> + mkdir -p /src/kubeflow
> + git clone https://github.com/kubeflow/kubeflow.git /mnt/test-data-volume/kubeflow-presubmit-kfctl-go-2794-6ca3e4e-6696-ee75/src/kubeflow/kubeflow
> Cloning into '/mnt/test-data-volume/kubeflow-presubmit-kfctl-go-2794-6ca3e4e-6696-ee75/src/kubeflow/kubeflow'...
> error: RPC failed; curl 56 GnuTLS recv error (-54): Error in the pull function.
> fatal: The remote end hung up unexpectedly
> fatal: early EOF
> fatal: index-pack failed
> ```

I have this from time to time.  seems like something wrong from github?

**Pull request merged**
