### PR TITLE
docs: minor spelling tweaks

### PR DESCRIPTION
**Pull request by brettkoonce**
This change is [Reviewable](https://reviewable.io/reviews/kubeflow/kubeflow/2993)

### CODE REVIEW

**Comment by brettkoonce** [comment]
halp

**Comment by brettkoonce** [comment]
ps i only rebased on master to force a rebuild, nothing changed since the initial commit!

**Comment by prodonjs** [comment]
So it looks like there's some kind of issue with the presubmit tests because nothing in this PR should affect functionality related to the test that is failing. We'll give it another shot tomorrow in hopes that whatever is going on in the integration test environment is cleared up.

**Pull request merged**
