### PR TITLE
Make kubebench reporter optional

### PR DESCRIPTION
**Pull request by Jeffwan**
I feel heavy to writer processor/reporter for different kind of models. Logs are enough for some of cases and I want to make reporter step optional.

---
This change is [Reviewable](https://reviewable.io/reviews/kubeflow/kubeflow/3062)

### CODE REVIEW

**Comment by Jeffwan** [comment]
@xyhuang  Hi Xinyuan, I make reporter and post-job configurable. In my case, I don't need parser. Logs is good enough for me.

**Comment by xyhuang** [comment]
thank you @Jeffwan, this looks good to me.
/lgtm
/approve

**Pull request merged**
