### PR TITLE
Automated cherry pick of #2938: lookup backend service full name Cherry pick of #2938 on v0.5-branch. #2938: lookup backend service full name

### PR DESCRIPTION
**Pull request by lluunn**
For #2716 

This change is [Reviewable](https://reviewable.io/reviews/kubeflow/kubeflow/2949)

### CODE REVIEW

**Comment by gabrielwen** [comment]
thanks!

**Comment by lluunn** [comment]
error: Error 400: The number of members in the policy (1,502) is larger than the maximum allowed size 1,500

**Pull request merged**
