### PR TITLE
Installing the latest KFP SDK package in the notebook image

### PR DESCRIPTION
**Pull request by Ark-kun**
/assign @jlewi @IronPan

---
This change is [Reviewable](https://reviewable.io/reviews/kubeflow/kubeflow/4286)

### CODE REVIEW

**Comment by Ark-kun** [comment]
Otherwise KF 0.7 ships with very old SDK version with many known issues.

**Comment by jlewi** [comment]
@Ark-kun @IronPan I thought we wanted to stop installiing the SDK in the notebook images and instead have samples explicitly install the SDK version they need because the SDK was evolving so rapidly?

**Comment by jlewi** [comment]
See kubeflow/kubeflow#3632

**Comment by Ark-kun** [comment]
> @Ark-kun @IronPan I thought we wanted to stop installiing the SDK in the notebook images and instead have samples explicitly install the SDK version they need because the SDK was evolving so rapidly?

This is also an option. I'm OK with that.
Both options are better than having a version from June that's 11 releases behind.

**Comment by jlewi** [comment]
I think its better to just remove it and have notebooks install the specific version they need.

**Pull request closed without merging**
