### PR TITLE
add gauge metrics for dashboard & alerting; add metrics for invalid a…

### PR DESCRIPTION
**Pull request by kunmingg**
* add gauge metrics for dashboard & alerting
* add metrics for invalid request
* make kubeflow version a dropdown list
* fix request latency metrics

(Gauge metrics have more aligner choices than counter)

---
This change is [Reviewable](https://reviewable.io/reviews/kubeflow/kubeflow/1846)

### CODE REVIEW

**Comment by kunmingg** [comment]
/hold
testing

**Comment by lluunn** [comment]
Can you describe more on why we need both gauge and counter in the PR description?
e.g. what's the problem of counter's aligner? what do we want to see on dashboard/alert

It's weird to use gauge type for a count.

**Comment by kunmingg** [comment]
agree its a bit weird:
because of stackdriver aligner limitation:

count: aligner only has rate/delta
* good for some alert rules

gauge: aligner has mean/min/max/std.dev/....
* good for dashboard and some alert rules

**Comment by abhi-g** [comment]
Instead of duplicating the counters can we simply replace them with the gauge counters if they serve our purpose. Having duplicates seems like an overkill.

**Pull request merged**
