### PR TITLE
Fix the TFCnn prototype which was broken by #444.

### LINKED ISSUE #458: tf-cnn fails to create
I'm not sure if this is a kubeflow issue or a ksonnet one, but when I try to follow the directions on tf-cnn from [here](https://github.com/kubeflow/kubeflow/blob/5be0cb57513b6a09fd01f12df5b0c28ff0e94024/user_guide.md#run-the-tfcnn-example) I get the following error:

```
 knobby  ~/kubeflow  ks generate tf-cnn mycnnjob --name=mycnnjob --namespace=kf-test
INFO  Writing component at '/home/knobby/kubeflow/components/mycnnjob.jsonnet'
 knobby  ~/kubeflow  ks apply cdk -c mycnnjob
ERROR generate objects for namespace : unable to read /home/knobby/kubeflow/environments/cdk/main.jsonnet: RUNTIME ERROR: Missing argument: tp
-------------------------------------------------
	/home/knobby/kubeflow/components/mycnnjob.jsonnet:85:7-51	thunk <job> from <$>

      tfJob.parts.tfJob(name, namespace, replicas) + {

-------------------------------------------------
	/home/knobby/kubeflow/components/mycnnjob.jsonnet:(85:7)-(90:8)	thunk <job> from <$>

      tfJob.parts.tfJob(name, namespace, replicas) + {
        spec+: {
          tfImage: image,
          terminationPolicy: { chief: { replicaName: "WORKER", replicaIndex: 0 } },
        },
      };

-------------------------------------------------
	/home/knobby/kubeflow/components/mycnnjob.jsonnet:92:31-34	thunk from <thunk from <thunk from <$>>>

std.prune(k.core.v1.list.new([job]))

-------------------------------------------------
	<std>:1022:60-61	thunk from <thunk from <function <anonymous>>>

            [ std.prune(x) for x in a if isContent($.prune(x)) ]

-------------------------------------------------
	<std>:1020:28-29	thunk from <thunk <t> from <function <anonymous>>>

        local t = std.type(a);

-------------------------------------------------
	<builtin>	builtin function <type>

-------------------------------------------------
	<std>:1021:12-13	function <anonymous>

        if t== "array" then

-------------------------------------------------
	<std>:969:29-30	thunk from <thunk <ta> from <function <anonymous>>>

        local ta = std.type(a);

-------------------------------------------------
	<builtin>	builtin function <type>

-------------------------------------------------
	<std>:971:33-35	thunk from <function <anonymous>>

        if !std.primitiveEquals(ta, tb) then

-------------------------------------------------
	... (skipped 17 frames)
-------------------------------------------------
	<std>:971:33-35	thunk from <function <anonymous>>

        if !std.primitiveEquals(ta, tb) then

-------------------------------------------------
	<builtin>	builtin function <primitiveEquals>

-------------------------------------------------
	<std>:971:12-40	function <anonymous>

        if !std.primitiveEquals(ta, tb) then

-------------------------------------------------
		

-------------------------------------------------
	<std>:1025:45-71	function <anonymous>

            for x in std.objectFields(a) if isContent(std.prune(a[x]))

-------------------------------------------------
	<builtin>	builtin function <flatMap>

-------------------------------------------------
	<builtin>	builtin function <$objectFlatMerge>

-------------------------------------------------
	/home/knobby/kubeflow/components/mycnnjob.jsonnet:92:1-37	$

std.prune(k.core.v1.list.new([job]))

-------------------------------------------------
	<extvar:__ksonnet/components>:2:13-70	object <anonymous>

  mycnnjob: import "/home/knobby/kubeflow/components/mycnnjob.jsonnet",

-------------------------------------------------
	During manifestation
```

```
 knobby  ~/kubeflow  1  ks version
ksonnet version: 0.9.1
jsonnet version: v0.9.5
client-go version: 1.8
```

### PR DESCRIPTION
**Pull request by jlewi**
* #444 add an argument for the termination policy but the TFCnn prototype
  isn't setting it.

* The TFCnn prototype overrides the termination policy so we can just pass null
  for the TP.

* Fix #458

---
This change is [Reviewable](https://reviewable.io/reviews/kubeflow/kubeflow/461)

### CODE REVIEW

**Comment by sfabel** [comment]
@jlewi - this doesn't fix it for me, unfortunately. I'm getting

"RUNTIME ERROR: Function expected 3 positional argument(s), but got 4"

**Comment by jlewi** [comment]
@sfabel Did you create a new app and re-add the registry? I suspect your vendor/kubeflow/tf-job/tf-job.libsonnet  file is outdated. Can you push your Kubeflow app to GitHub so I can take a look?

**Comment by jlewi** [comment]
The test appears to have passed but was still marked as a failure probably because of the exit code.

**Pull request merged**
