### PR TITLE
Typo in nvidia inference server README

### PR DESCRIPTION
**Pull request by cliveseldon**
This change is [Reviewable](https://reviewable.io/reviews/kubeflow/kubeflow/1569)

### CODE REVIEW

**Comment by jlewi** [comment]
The most recent failure is kfctl apply gcp container failing with.

```
failed to get container status {"docker" "2ce0faf061dd167252a0007b2a9ead2e6fd847c804a2236b244b9a3a4a29b64f"}: rpc error: code = Unknown desc = Error: No s
uch container: 2ce0faf061dd167252a0007b2a9ead2e6fd847c804a2236b244b9a3a4a29b64f
```

Never seen this before. 

/test all

**Comment by jlewi** [comment]
This is already fixed at Master
https://github.com/kubeflow/kubeflow/blob/master/scripts/gke/deployment_manager_configs/cluster.jinja#L68

@cliveseldon I think you just need to rebase to pick up the changes.

**Comment by abhi-g** [comment]
thanks @jlewi for looking into the test failures.

**Comment by jlewi** [comment]
I'm going to go ahead and just merge this manually since its just a doc change.

**Pull request merged**
