### PR TITLE
adds pull sha for kustomize e2e

### PR DESCRIPTION
**Pull request by swiftdiaries**
https://github.com/kubeflow/manifests/pull/139 needs this to ensure that E2E tests can be run from `kubeflow/manifests` on each PR as a presubmit test

---
This change is [Reviewable](https://reviewable.io/reviews/kubeflow/kubeflow/3492)

### CODE REVIEW

**Comment by abhi-g** [comment]
@swiftdiaries you might need to merge master to resolve conflict

**Comment by swiftdiaries** [comment]
Thanks @abhi-g ! I've fixed the conflict.

**Comment by jlewi** [comment]
Sorry for the slow reply
/lgtm
/approve

**Comment by swiftdiaries** [comment]
Thank you !

**Pull request merged**
