### PR TITLE
CP to V0.1 branch: TF notebook slimming, joyvan pip installs, and new gcr.io locations

### PR DESCRIPTION
**Pull request by pdmack**
/assign @ankushagarwal 
/cc @jlewi 
/cc @willb 

From Slack discussion of potentially cutting a 0.1.1 release

---
This change is [Reviewable](https://reviewable.io/reviews/kubeflow/kubeflow/703)

### CODE REVIEW

**Comment by pdmack** [comment]
@jlewi manually fixed `kubeflow/core/tests/tf-job_test.jsonnet` but question still stands I suppose.

**Comment by ankushagarwal** [comment]
@pdmack I am not sure why `tf-job_test` would fail. I tried checking out this PR and reverting your changes to tf-job_test and it still passes

`jsonnet eval ~/git/kubeflow/kubeflow/core/tests/tf-job_test.jsonnet --jpath ~/git/kubeflow/kubeflow/core`

**Pull request merged**
