### PR TITLE
docs(TOC): add auto-generated TOC for all docs

### PR DESCRIPTION
**Pull request by DjangoPeng**
Fix https://github.com/kubeflow/kubeflow/issues/603

---
This change is [Reviewable](https://reviewable.io/reviews/kubeflow/kubeflow/604)

### CODE REVIEW

**Comment by DjangoPeng** [comment]
/assign @jlewi @gaocegege 

PTAL

**Comment by DjangoPeng** [comment]
If we have the TOC, more readers would pay more attention to the `requirements` section and double check whether they match conditions. 

BTW: should we add the usage or introduction of doctoc into developer guide?

**Comment by jlewi** [comment]
This is great.

Are there instructions somewhere on how to generate the TOC?

**Comment by gaocegege** [comment]
lgtm but there is a conflict, please resolve it :smile:

**Comment by DjangoPeng** [comment]
When https://github.com/kubeflow/kubeflow/pull/602 merged, I'll resolve and rebase them in the meantime.

**Pull request merged**
