### PR TITLE
Improve tf serving e2e test

### LINKED ISSUE #198: e2e test for http-proxy
Follow up of this https://github.com/kubeflow/kubeflow/pull/183

To Do
  - [x] ksonnet template
  - [ ] E2E tests
  - [x] Documentation explaining how to use it
  - [ ] Discussion of the API

### LINKED ISSUE #1031: unflake TF serving testing
https://github.com/kubeflow/kubeflow/blob/master/testing/test_tf_serving.py#L106

We are comparing the result as text. We should compare the result numbers with some tolerance.

E.g. see #1030

### PR DESCRIPTION
**Pull request by lluunn**
Fix #1031 
  - now compares the result with tolerance

Fix #198
  - predict with http. Http proxy send gRPC requests, so it tests both grpc and http.

---
This change is [Reviewable](https://reviewable.io/reviews/kubeflow/kubeflow/1271)

### CODE REVIEW

**Comment by jlewi** [comment]
DId you consider creating a simple deterministic model ( #337) that does something like x + 1?  I think this is fine as a short term solution but I think that approach might be better longer term.

**Comment by lluunn** [comment]
Makes sense. I will do that in a followup PR.

**Pull request merged**
