### PR TITLE
fixes 'kfctl creates invalid IAM policy binding file if email not set'

### LINKED ISSUE #2707: kfctl creates invalid IAM policy binding file if email not set
I didn't set `-email` when calling `kfctl init`. 

As a result I ended up with the following iam policy binding YAML file.

This turns out to generate an error when trying to apply it because we are missing an email for the user 

```
- members:
  - user:
  roles:
  - roles/iap.httpsResourceAccessor
```

Full YAML

```
bindings:
- members:
  - serviceAccount:kfctl-2220-76b7-admin@kubeflow-ci-deployment.iam.gserviceaccount.com
  roles:
  # Grant permissions needed to push the app to a cloud repository
  - roles/source.admin
  # servicemanagement.admin is needed by CloudEndpoints controller so we can create a service to get a hostname.
  - roles/servicemanagement.admin
  # Network admin is needed to enable IAP and configure network settings like backend timeouts and health checks
  - roles/compute.networkAdmin
- members:
  - serviceAccount:kfctl-2220-76b7-user@kubeflow-ci-deployment.iam.gserviceaccount.com
  roles:
  # Grant permissions needed to submit builds to Google Cloud Container Builder
  - roles/cloudbuild.builds.editor
  # roles/viewer is required for viewing the logs of a GCB build
  - roles/viewer
  # Grant permissions needed to push the app to a cloud repository
  - roles/source.admin
  - roles/storage.admin
  - roles/bigquery.admin
  - roles/dataflow.admin
  - roles/ml.admin
  - roles/dataproc.editor
  - roles/cloudsql.admin
- members:
  - serviceAccount:kfctl-2220-76b7-vm@kubeflow-ci-deployment.iam.gserviceaccount.com
  roles:
  # VM service account is used to write logs
  - roles/logging.logWriter
  # VM service account is used to write monitoring data
  - roles/monitoring.metricWriter
  # VM service account is used to pull image from gcr
  - roles/storage.objectViewer
- members:
  - user:
  roles:
  - roles/iap.httpsResourceAccessor

```

/cc @gabrielwen

### PR DESCRIPTION
**Pull request by kkasravi**
fixes #2707 

---
This change is [Reviewable](https://reviewable.io/reviews/kubeflow/kubeflow/2718)

### CODE REVIEW

**Comment by jlewi** [comment]
Marking WIP into blocking PRs are merged.

**Comment by kkasravi** [comment]
@gabrielwen this fix may be a bit of a hack - running gcloud to get the account if it's not provided. You may have a better way.

**Comment by gabrielwen** [comment]
> @gabrielwen this fix may be a bit of a hack - running gcloud to get the account if it's not provided. You may have a better way.

Looks fine to me.  It's just if it were me, I wouldn't depend on shell out as much as possible.  `gcloud config get-value` reads from `~/.config/gcloud` and returns the value we need.  The benefit of using shell out, though, is that `gcloud` already takes care of finding files and parsing information for us.

**Comment by kkasravi** [comment]
@kunmingg @lluunn this is ready to merge, please approve

**Pull request merged**
