### PR TITLE
Adding support for linux/ppc64le in CI for centraldashboard multi-arc…

### PR DESCRIPTION
**Pull request by amitmukati-2604**
…h docker images

### CODE REVIEW

**Comment by amitmukati-2604** [comment]
- The workflow "centraldb_docker_publish" releases docker image for Linux-amd64.
- Added docker-build-multi-arch and build-push-multi-arch targets in the Makefile of the Tensorboard-controller component.
- Dropping docker-build and docker-push from the workflow.
- Keeping these steps will increase the workflow runtime.
- Docker-build-push-multi-arch builds and pushes the images for Linux-amd64 and Linux-ppc64le

**Comment by kimwnasptd** [comment]
@apo-ger could you also take a stab at it? Should be the same with the rest of the updates we did for ppc64le

/cc @apo-ger

**Comment by apo-ger** [comment]
/remove-lgtm

Actually I'm getting an error while trying to build the image locally:
```
$ make docker-build-multi-arch 

cd ../ && docker buildx build --platform linux/amd64 --tag centraldashboard:v1.5.0-rc.0-244-g7db9c951-dirty -f centraldashboard/Dockerfile .
[+] Building 4.2s (12/13)                                                                                                                                              
 => [internal] load build definition from Dockerfile                                                                                                              0.0s
 => => transferring dockerfile: 32B                                                                                                                               0.0s
 => [internal] load .dockerignore                                                                                                                                 0.0s
 => => transferring context: 2B                                                                                                                                   0.0s
 => [internal] load metadata for docker.io/library/node:12.22.12-alpine                                                                                           0.0s
 => [internal] load metadata for docker.io/library/node:12.22.12-bullseye                                                                                         0.5s
 => [build 1/5] FROM docker.io/library/node:12.22.12-bullseye@sha256:39a3111124caad4e785552f3dcb387caa1cd6749510530f289f107475be96b67                             0.0s
 => [internal] load build context                                                                                                                                 0.0s
 => => transferring context: 152.10kB                                                                                                                             0.0s
 => [serve 1/3] FROM docker.io/library/node:12.22.12-alpine                                                                                                       0.0s
 => CACHED [serve 2/3] WORKDIR /app                                                                                                                               0.0s
 => CACHED [build 2/5] RUN apt update -qq && apt install -qq -y chromium gnulib                                                                                   0.0s
 => CACHED [build 3/5] COPY . /centraldashboard                                                                                                                   0.0s
 => CACHED [build 4/5] WORKDIR /centraldashboard                                                                                                                  0.0s
 => ERROR [build 5/5] RUN BUILDARCH="$(dpkg --print-architecture)" &&  npm rebuild &&     if [ "$BUILDARCH" = "arm64" ]  ||      [ "$BUILDARCH" = "armhf" ]; the  3.6s
------                                                                                                                                                                 
 > [build 5/5] RUN BUILDARCH="$(dpkg --print-architecture)" &&  npm rebuild &&     if [ "$BUILDARCH" = "arm64" ]  ||      [ "$BUILDARCH" = "armhf" ]; then     export CFLAGS=-Wno-error &&     export CXXFLAGS=-Wno-error;      fi &&     npm install &&     npm test &&     npm run build &&     npm prune --production:                     
#0 1.341 npm WARN saveError ENOENT: no such file or directory, open '/centraldashboard/package.json'                                                                   
#0 1.349 npm notice created a lockfile as package-lock.json. You should commit this file.                                                                              
#0 1.352 npm WARN enoent ENOENT: no such file or directory, open '/centraldashboard/package.json'                                                                      
#0 1.357 npm WARN centraldashboard No description
#0 1.361 npm WARN centraldashboard No repository field.
#0 1.366 npm WARN centraldashboard No README data
#0 1.370 npm WARN centraldashboard No license field.
#0 1.370 
#0 3.310 up to date in 2.018s
#0 3.311 found 0 vulnerabilities
#0 3.311 
#0 3.567 npm ERR! code ENOENT
#0 3.568 npm ERR! syscall open
#0 3.568 npm ERR! path /centraldashboard/package.json
#0 3.568 npm ERR! errno -2
#0 3.569 npm ERR! enoent ENOENT: no such file or directory, open '/centraldashboard/package.json'
#0 3.570 npm ERR! enoent This is related to npm not being able to find a file.
#0 3.570 npm ERR! enoent 
#0 3.573 
#0 3.573 npm ERR! A complete log of this run can be found in:
#0 3.573 npm ERR!     /root/.npm/_logs/2023-02-01T13_38_03_098Z-debug.log
------
ERROR: failed to solve: executor failed running [/bin/sh -c BUILDARCH="$(dpkg --print-architecture)" &&  npm rebuild &&     if [ "$BUILDARCH" = "arm64" ]  ||      [ "$BUILDARCH" = "armhf" ]; then     export CFLAGS=-Wno-error &&     export CXXFLAGS=-Wno-error;      fi &&     npm install &&     npm test &&     npm run build &&     npm prune --production]: exit code: 254
make: *** [Makefile:31: docker-build-multi-arch] Error 1
```

**Pull request merged**
