### PR TITLE
Adds Kferror interface

### PR DESCRIPTION
**Pull request by gabrielwen**
Relates #2712

We will use this error interface to carry error information and status code used for monitoring.

---
This change is [Reviewable](https://reviewable.io/reviews/kubeflow/kubeflow/2769)

### CODE REVIEW

**Comment by kunmingg** [comment]
@kkasravi 
Shall we just fill status here into app.yaml status when needed?

**Comment by kkasravi** [comment]
Yes, that would probably work

**Comment by kunmingg** [comment]
@gabrielwen 
You might need to rebase

**Comment by gabrielwen** [comment]
> @gabrielwen
> You might need to rebase

I shouldn't need to as this PR doesn't touch any existing files.

**Pull request merged**
