### PR TITLE
Move basic auth username/password to ENV

### PR DESCRIPTION
**Pull request by gabrielwen**
Relates to #2661

---
This change is [Reviewable](https://reviewable.io/reviews/kubeflow/kubeflow/2713)

### CODE REVIEW

**Comment by jlewi** [comment]
@gabrielwen Can you look at why the test failed and open an issue if the failure is unrelated to this PR?

**Comment by kunmingg** [comment]
Can we pass them during apply instead of save as ENV?
These might be too sensitive to save locally

**Comment by gabrielwen** [comment]
failure doesn't make sense to me, rerunning it.
```
Cloning into '/mnt/test-data-volume/kubeflow-presubmit-kfctl-go-2713-66ab02d-6331-e948/src/kubeflow/tf-operator'...
error: RPC failed; curl 56 GnuTLS recv error (-54): Error in the pull function.
fatal: The remote end hung up unexpectedly
fatal: early EOF
fatal: index-pack failed
```

**Comment by gabrielwen** [comment]
seems like something wrong with deepcopy:
```
util.py                     71 INFO     Makefile:72: recipe for target 'pkg/apis/apps/gcp/v1alpha1/zz_generated.deepcopy.go' failed
util.py                     71 INFO     make: *** [pkg/apis/apps/gcp/v1alpha1/zz_generated.deepcopy.go] Error 255
util.py                     45 INFO     Running: make build-kfctl
cwd=/mnt/test-data-volume/kubeflow-presubmit-kfctl-go-2713-66ab02d-6337-0d08/src/kubeflow/kubeflow/bootstrap
util.py                     60 INFO     Subprocess output:
util.py                     71 INFO     /root/go/bin/deepcopy-gen -i github.com/kubeflow/kubeflow/bootstrap/pkg/apis/apps/gcp/... -O zz_g
enerated.deepcopy
util.py                     71 INFO     F0315 20:26:27.057077    8649 deepcopy.go:126] Failed loading boilerplate: open k8s.io/code-gener
ator/hack/boilerplate.go.txt: no such file or directory
util.py                     71 INFO     Makefile:72: recipe for target 'pkg/apis/apps/gcp/v1alpha1/zz_generated.deepcopy.go' failed
util.py                     71 INFO     make: *** [pkg/apis/apps/gcp/v1alpha1/zz_generated.deepcopy.go] Error 255
util.py                     45 INFO     Running: make build-kfctl
cwd=/mnt/test-data-volume/kubeflow-presubmit-kfctl-go-2713-66ab02d-6337-0d08/src/kubeflow/kubeflow/bootstrap
util.py                     60 INFO     Subprocess output:
util.py                     71 INFO     /root/go/bin/deepcopy-gen -i github.com/kubeflow/kubeflow/bootstrap/pkg/apis/apps/gcp/... -O zz_g
enerated.deepcopy
util.py                     71 INFO     F0315 20:26:37.651054    9499 deepcopy.go:126] Failed loading boilerplate: open k8s.io/code-gener
ator/hack/boilerplate.go.txt: no such file or directory
util.py                     71 INFO     Makefile:72: recipe for target 'pkg/apis/apps/gcp/v1alpha1/zz_generated.deepcopy.go' failed
util.py                     71 INFO     make: *** [pkg/apis/apps/gcp/v1alpha1/zz_generated.deepcopy.go] Error 255
util.py                     45 INFO     Running: make build-kfctl
cwd=/mnt/test-data-volume/kubeflow-presubmit-kfctl-go-2713-66ab02d-6337-0d08/src/kubeflow/kubeflow/bootstrap
util.py                     60 INFO     Subprocess output:
util.py                     71 INFO     /root/go/bin/deepcopy-gen -i github.com/kubeflow/kubeflow/bootstrap/pkg/apis/apps/gcp/... -O zz_g
enerated.deepcopy
util.py                     71 INFO     F0315 20:26:48.012311   10346 deepcopy.go:126] Failed loading boilerplate: open k8s.io/code-gener
ator/hack/boilerplate.go.txt: no such file or directory
util.py                     71 INFO     Makefile:72: recipe for target 'pkg/apis/apps/gcp/v1alpha1/zz_generated.deepcopy.go' failed
util.py                     71 INFO     make: *** [pkg/apis/apps/gcp/v1alpha1/zz_generated.deepcopy.go] Error 255
generated xml file: /mnt/test-data-volume/kubeflow-presubmit-kfctl-go-2713-66ab02d-6337-0d08/output/artifacts/junit_kfctl-build-test.xml
========================== 1 failed in 143.72 seconds ==========================
```

**Comment by gabrielwen** [comment]
Issue filed: kubeflow/testing#334

**Comment by gabrielwen** [comment]
Fixes #2715

**Pull request merged**
