### PR TITLE
Use valid commit for kubeflow/components/common module.

### PR DESCRIPTION
**Pull request by jrykr**
Makes the notebook controller API importable for 3rd party applications. 

See #5308

### CODE REVIEW

**Comment by swiftdiaries** [comment]
Could you please open a PR to add yourself to the Kubeflow org?

**Comment by jrykr** [comment]
PR opened for Kubeflow org addition.

**Comment by MartinForReal** [comment]
From my point of view, the notebook controller should depend on the code in the same commit. If we remove the replace statement here, we should maintain a release tag for the common component which is something we won't do in the near future.

**Comment by jrykr** [comment]
@MartinForReal  The problem with the current situation is that there are lots of reasons for a team to want to manage notebook servers outside of kubectl or jupyter-web-app, but builds that depend on the notebook controller API will fail. To me, this is worth solving because we do want to encourage a simple workflow for development on top of Kubeflow. 

What about leaving the replace statement unchanged while adding a valid pseudo-version? I think this would:

1. Enable third-party builds, i.e., builds where notebook-controller is not the main module.
2. Avoid creating the obligation to maintain a release tag in components/common.
3. Continue using the relative path when notebook-controller is the main module.

Thoughts?

**Comment by yanniszark** [comment]
> What about leaving the replace statement unchanged while adding a valid pseudo-version?
If this works as described, it would be ideal.
Have you tested it in a sample repo?

**Comment by jrykr** [comment]
> have you tested it in a sample repo?

@yanniszark  Yes, I have confirmed this. 

Amended accordingly.

**Comment by yanniszark** [comment]
@jrykr thanks! Is it possible to also add a comment with the explanation of what we did as a comment in `go.mod` (and in the commit)?
Something over the replace statement, like:
```
We use the latest `kubeflow/common` to build the notebook-controller, but also import a
certain commit to support importing the Notebook API. According to the go.mod docs [1]:

> exclude and replace directives only operate on the current (“main”) module. exclude and
> replace directives in modules other than the main module are ignored when building the
> main module. The replace and exclude statements, therefore, allow the main module
> complete control over its own build, without also being subject to complete control by
> dependencies.

[1]: https://github.com/golang/go/wiki/Modules#gomod
```

**Comment by jrykr** [comment]
@yanniszark Makes sense. Amended with a shorter comment in `go.mod`, expanded in the commit message.

**Comment by jrykr** [comment]
@yanniszark Bumping this.

**Comment by yanniszark** [comment]
For some reason, it didn't pick up the approve...

/approve

**Pull request merged**
