### PR TITLE
ModelDB V2 support in KubeFlow

### PR DESCRIPTION
**Pull request by mvartakAtVerta**
Updates to include:
- Removing MongoDB
- Rewriting API from the ground up
- Pluggable backend systems
- UI redone

---
This change is [Reviewable](https://reviewable.io/reviews/kubeflow/kubeflow/2757)

### CODE REVIEW

**Comment by mvartakAtVerta** [comment]
cc @jlewi @richardsliu @lluunn

**Comment by mvartakAtVerta** [comment]
I signed it!

**Comment by mvartakAtVerta** [comment]
I signed it!

**Comment by pdmack** [comment]
This looks great but @jlewi we are adding to our ksonnet tech debt.

**Comment by mvartakAtVerta** [comment]
@pdmack @jlewi ModelDB V1 (in KF since 0.4) was already using ksonnet, so it isn't "new" debt per se, if that helps. This change updates the images and adds MySQL instead of Mongo. 

We are happy to be on the hook to rewrite jsonnet to support Kustomize or helm as per the community decision!

**Comment by pdmack** [comment]
@mvartakAtVerta totally understood. Certainly not intended as a slight towards the work but more fodder for some strategy to tackle the ksonnet "question". And I have some ideas on that. 😉 

/approve
/lgtm

**Comment by pdmack** [comment]
"Kubeflow" btw 😄

**Comment by mpvartak** [comment]
Totally understand! Please let us know how we can help with the move to the new solution.

**Pull request merged**
