### PR TITLE
Cherry-picks for 1.3.1

### PR DESCRIPTION
**Pull request by kimwnasptd**
Manually cherry picked the bugfixes we had in `master` branch to include them in the new `1.3.1` tag that we will cut.

I've also edited the initial authors of the commits in order to avoid issues with the CLA and to avoid from having people type `I consent` to the google bot.

The next step will be to build all the images with the `1.3.1` tags and update manifests

cc @kubeflow/wg-notebooks-leads
/cc @yanniszark

### CODE REVIEW

**Comment by DavidSpek** [comment]
https://github.com/kubeflow/kubeflow/pull/5998 is missing in this PR.

**Comment by kimwnasptd** [comment]
> #5998 is missing in this PR.

This was intentional. We will rebuild all the images and use the `1.3.1` tag instead, as we do now for `1.3`

**Comment by DavidSpek** [comment]
@kimwnasptd My bad, you are correct. I distinctly remember the `master-*` tagged images being deployed for some reason, but I must be mixing up what situation that was.

**Comment by kimwnasptd** [comment]
No worries.

Also, @DavidSpek I see that the CI is failing to build the RStudio image with the following error
```
INFO[0175] Running: [/bin/bash -c curl -sL "https://download2.rstudio.org/server/bionic/${RSTUDIO_ARCH}/rstudio-server-${RSTUDI
O_VERSION/v/}-${RSTUDIO_ARCH}.deb" -o /tmp/rstudio-server.deb  && gpg --keyserver keys.gnupg.net --recv-keys 3F32EE77E331692F
&& dpkg-sig --verify /tmp/rstudio-server.deb  && dpkg -i /tmp/rstudio-server.deb  && rm -f /tmp/rstudio-server.deb  && mv -n /v
ar/run/rstudio-server* /run  && echo "lock-type=advisory" > /etc/rstudio/file-locks  && echo "www-frame-origin=same" >> /etc/rs
tudio/rserver.conf  && chown -R ${NB_USER}:users /etc/rstudio  && chown -R ${NB_USER}:users /run/rstudio-server*  && chown -R $
{NB_USER}:users /usr/lib/rstudio-server  && chown -R ${NB_USER}:users /var/lib/rstudio-server]
gpg: directory '/home/jovyan/.gnupg' created
gpg: keybox '/home/jovyan/.gnupg/pubring.kbx' created
gpg: keyserver receive failed: No name
error building image: error building stage: failed to execute command: waiting for process to exit: exit status 2
```
https://argo.kubeflow-testing.com/workflows/kubeflow-test-infra/kubeflow-kubeflow-presubmit-nb-rstudio-6007-10af3fc-1328-1171?tab=workflow&nodeId=kubeflow-kubeflow-presubmit-nb-rstudio-6007-10af3fc-1328-1171-4006263469

Have you seen this before?

I'll also rerun the tests to check if this was a fluke
/retest

**Comment by DavidSpek** [comment]
I think that failure is just some random error related to Kaniko, not the RStudio image itself. I think I've seen this once before and rerunning solved the problem. It might be a good idea to update the Kaniko image tag to the new version. In the future we can have Renovate do this for us, since the image tags in the CI pipelines are easy to be forgotten.

**Comment by DavidSpek** [comment]
Sorry, I'm doing too many things at once. It does seem like it is related to the RStudio image and has to do with the package validation for RStudio. The strange thing is that it didn't cause problems in the past, so I think it might be an external problem. I'll look into the cause right away.

**Comment by DavidSpek** [comment]
@kimwnasptd The first thing I though of is that `keys.gnupg.net` might be down or experiencing issues, which seems like it might be the case. Looking into it more now.

**Comment by DavidSpek** [comment]
The pgp server is indeed down. Luckily I've found an alternative server that is up and works as it should. I'll create a PR to change the server in the RStudio image so this doesn't block things.

**Comment by kimwnasptd** [comment]
@DavidSpek thanks! Lets wait a little bit though to see if they will fix the gpg server issue within the day.

If not lets merge your PR and cherry-pick the commit

**Comment by DavidSpek** [comment]
@kimwnasptd I just revised the PR so that an additional keyserver is added to the command, instead of replacing the current keyserver. This is likely what we would want to do anyways to avoid having a single point of failure (it seems a lot of keyservers are often down).

**Comment by yanniszark** [comment]
Thanks @kimwnasptd @DavidSpek !
/lgtm
/approve

**Pull request merged**
