### PR TITLE
[Jupyter-Web-App]:Add basic E2E Tests

### PR DESCRIPTION
**Pull request by kimwnasptd**
This test has two basic test cases for now.

* Navigate to index page and ensure that no error appeared
* Navigate to form page and ensure that no error appeared

cc @jlewi @fediazgon 
/assign @jlewi

---
This change is [Reviewable](https://reviewable.io/reviews/kubeflow/kubeflow/4773)

### CODE REVIEW

**Comment by kimwnasptd** [comment]
@jlewi the code is ready in terms of the testing logic.
The next steps would be to discuss how to integrate them with the existing tests. Also, the test file requires some python packages so I guess we will have to create a new container to run them?

/assign @avdaredevil 
@avdaredevil Do you also want to take a look at this since you are also working on E2E testing for the Central Dashboard?

**Comment by jlewi** [comment]
Thanks @kimwnasptd 

Should we avoid closing #3657 until we have this integrated with CI?

**Comment by kimwnasptd** [comment]
@jlewi sure.

**Comment by jlewi** [comment]
@kimwnasptd Do you want to investigate the test failure so we could get this merged?

**Comment by kimwnasptd** [comment]
Sure, I'll take a look in a little bit and I'll report back

**Comment by kimwnasptd** [comment]
The testing-argo website returns 500 for this presubmit test run from yesterday.
I'll re-run the tests to see I'll be able to connect to argo

/retest

**Pull request merged**
