### PR TITLE
notebook CR shows container status

### PR DESCRIPTION
**Pull request by lluunn**
for #2723 

With a bad image, kubectl describe notebook:
```
Status:
  Conditions:
    Type:  Ready
  Container State:
    Waiting:
      Message:     Back-off pulling image "some_bad_image"
      Reason:      ImagePullBackOff
  Ready Replicas:  0
```

Correct image:
```
Status:
  Conditions:
    Type:  Ready
  Container State:
    Running:
      Started At:  2019-03-25T20:51:45Z
  Ready Replicas:  1
```

I think we can remove condition later?

This change is [Reviewable](https://reviewable.io/reviews/kubeflow/kubeflow/2787)

### CODE REVIEW

**Comment by jlewi** [comment]
Weird; the test failed with

```
W
level=error msg="no prototype names matched 'spark-operator'"
```

**Comment by jlewi** [comment]
/test all

#2811 for spark operator test failures. 

@lluunn Could you try rebasing since its passing in the latest periodic?

If its still failing we might just need to disable the spark operator tests for now.

**Comment by lluunn** [comment]
thanks

**Comment by jlewi** [comment]
The good news is the spark operator test seemed to pass.

Looks like kfctl go build failed. Looks like a flake caused by the test timing out because of problems pulling the dependencies.

[logs](https://pantheon.corp.google.com/logs/viewer?project=kubeflow-ci&_ga=2.225405724.-720060064.1532059791&_gac=1.188941017.1553366450.CjwKCAjwstfkBRBoEiwADTmnEHB4EsCQkymxInUJfA875uharmvOzl6RadXtmxRqVYzya7mIGRmEERoC5-kQAvD_BwE&minLogLevel=0&expandAll=false&timestamp=2019-03-26T03:08:52.830000000Z&customFacets=&limitCustomFacetWidth=true&dateRangeStart=2019-03-25T13:02:28.746Z&dateRangeEnd=2019-03-26T13:02:28.746Z&interval=P1D&resource=k8s_container%2Fcluster_name%2Fkf-v0-4-n00%2Fnamespace_name%2Fkubeflow%2Fcontainer_name%2Ftensorflow&advancedFilter=resource.type%3D%22k8s_container%22%0Aresource.labels.pod_name%3D%22kubeflow-presubmit-kfctl-go-2787-09e21b5-6712-2f26-1555903895%22%0A&scrollTimestamp=2019-03-26T06:00:31.398378121Z)

**Comment by lluunn** [comment]
The failures are spark and kfctl go

**Comment by lluunn** [comment]
Test error: The node was low on resource: nodefs

**Comment by lluunn** [comment]
failure: The node was low on resource: nodefs.
/retest

**Comment by jlewi** [comment]
Woo Hoo! tests pass
/lgtm
/approve

**Pull request merged**
