### PR TITLE
Update default images for jupyterhub spawner

### PR DESCRIPTION
**Pull request by ankushagarwal**
Provide a dropdown with images for each tensorflow minor version.

We now pin down a tensorflow version for our jupyterhub image builds.

Related #375 #467 #471

---
This change is [Reviewable](https://reviewable.io/reviews/kubeflow/kubeflow/491)

### CODE REVIEW

**Comment by pdmack** [comment]
/lgtm

Any ideas on parameterizing these?

**Comment by ankushagarwal** [comment]
I haven't given much thought to parametrizing these since it's only 6 images.

**Comment by ankushagarwal** [comment]
After https://github.com/kubeflow/kubeflow/pull/471 we are no longer building tensorflow nightly builds.

**Pull request closed without merging**
