### PR TITLE
Cherrypicked #2305 from master branch to v0.4-branch

### PR DESCRIPTION
**Pull request by svalleru**
Cherrypicked #2305 from master branch to v0.4-branch

This change is [Reviewable](https://reviewable.io/reviews/kubeflow/kubeflow/2314)

### CODE REVIEW

**Comment by abhi-g** [comment]
Thanks @svalleru 
/ok-to-test

**Comment by svalleru** [comment]
@jlewi is this a valid test failure? 
are there any docs on kubeflow ci infra that can help me debug this?

**Comment by jlewi** [comment]
Might be a test flake.

/test all

Some instructions for debugging test failures are here
https://github.com/kubeflow/testing#debugging-failed-tests

**Comment by jlewi** [comment]
I'm going to close this PR since we are in the process of releasing 0.5 and it looks like 0.4 has manged without the fix.

**Pull request closed without merging**
