### PR TITLE
Release v1.8.0-rc.1

### PR DESCRIPTION
**Pull request by DnPlas**
Bump release version v1.8.0-rc.0 -> v1.8.0-rc.1

cc: @kimwnasptd

### CODE REVIEW

**Comment by kimwnasptd** [comment]
It looks like we still have a race where our tests will directly `kubectl wait pod` but the Deployment object might not yet have created the Pods. To resolve this I suggest that we wait for the Deployment instead of the Pod.

@DnPlas we could copy-paste the logic for this from my original PR in https://github.com/kubeflow/kubeflow/pull/7252 (the part that we wait for the deployment, not the one that we patch it)

Could you send a PR for this? Asking you since we are burning with the release and I can help merge this fast

also cc @thesuperzapper since this is related to our discussion on the CI

**Comment by kimwnasptd** [comment]
@TobiasGoerke could you help us debug the failing unit tests for the PVCViewer Controller? 

I see the following relevant logs, that come from the following line in the code
https://github.com/kubeflow/kubeflow/blob/08eaaba1095455b3b44485e697bae8324ad8eaf8/components/pvcviewer-controller/controllers/pvcviewer_controller_test.go#L387C1-L387C7

```
• [FAILED] [0.027 seconds]
PVCViewer controller
/home/runner/work/kubeflow/kubeflow/components/pvcviewer-controller/controllers/pvcviewer_controller_test.go:30
  When RWO Scheduling is used
  /home/runner/work/kubeflow/kubeflow/components/pvcviewer-controller/controllers/pvcviewer_controller_test.go:370
    [It] Does not generate affinities for RWX PVCs
    /home/runner/work/kubeflow/kubeflow/components/pvcviewer-controller/controllers/pvcviewer_controller_test.go:371

Begin Captured GinkgoWriter Output >>
    STEP: Creating a RWX PVC and mounting Pod 09/19/23 19:33:32.07
    STEP: Creating a PVCViewer for the RWX PVC 09/19/23 19:33:32.074
    1.6951520120758505e+09	DEBUG	controller-runtime.webhook.webhooks	received request	{"webhook": "/mutate-kubeflow-org-v1alpha1-pvcviewer", "UID": "3936385e-5bda-4b4a-9a48-17d3bee931af", "kind": "kubeflow.org/v1alpha1, Kind=PVCViewer", "resource": {"group":"kubeflow.org","version":"v1alpha1","resource":"pvcviewers"}}
    1.6951520120759068e+09	INFO	pvcviewer-resource	default	{"name": "test-pvcviewer"}
    1.6951520120759153e+09	INFO	pvcviewer-resource	Inferring default podSpec	{"name": "test-pvcviewer"}
    1.6951520120760825e+09	DEBUG	controller-runtime.webhook.webhooks	wrote response	{"webhook": "/mutate-kubeflow-org-v1alpha1-pvcviewer", "code": 200, "reason": "", "UID": "3936385e-5bda-4b4a-9a48-17d3bee931af", "allowed": true}
    1.6951520120772035e+09	DEBUG	controller-runtime.webhook.webhooks	received request	{"webhook": "/validate-kubeflow-org-v1alpha1-pvcviewer", "UID": "32162513-9212-4426-a50f-964ace887c19", "kind": "kubeflow.org/v1alpha1, Kind=PVCViewer", "resource": {"group":"kubeflow.org","version":"v1alpha1","resource":"pvcviewers"}}
    1.6951520120772767e+09	INFO	pvcviewer-resource	validate create	{"name": "test-pvcviewer"}
    1.6951520120772908e+09	DEBUG	controller-runtime.webhook.webhooks	wrote response	{"webhook": "/validate-kubeflow-org-v1alpha1-pvcviewer", "code": 200, "reason": "", "UID": "32162513-9212-4426-a50f-964ace887c19", "allowed": true}
    1.6951520120787518e+09	INFO	Creating Deployment	{"controller": "pvcviewer", "controllerGroup": "kubeflow.org", "controllerKind": "PVCViewer", "PVCViewer": {"name":"test-pvcviewer","namespace":"test-9"}, "namespace": "test-9", "name": "test-pvcviewer", "reconcileID": "0d3ed72e-7f25-4e6d-b47e-ad6be1c725e7"}
    1.6951520120819845e+09	INFO	Updating status	{"controller": "pvcviewer", "controllerGroup": "kubeflow.org", "controllerKind": "PVCViewer", "PVCViewer": {"name":"test-pvcviewer","namespace":"test-9"}, "namespace": "test-9", "name": "test-pvcviewer", "reconcileID": "0d3ed72e-7f25-4e6d-b47e-ad6be1c725e7"}
...
    1.695152012089806e+09	ERROR	Reconciler error	{"controller": "pvcviewer", "controllerGroup": "kubeflow.org", "controllerKind": "PVCViewer", "PVCViewer": {"name":"test-pvcviewer","namespace":"test-9"}, "namespace": "test-9", "name": "test-pvcviewer", "reconcileID": "e0663be8-fa85-45ae-84e6-a552e2d3c4b5", "error": "PVCViewer.kubeflow.org \"test-pvcviewer\" not found"}
    sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).reconcileHandler
    	/home/runner/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.13.1/pkg/internal/controller/controller.go:326
    sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem
    	/home/runner/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.13.1/pkg/internal/controller/controller.go:273
    sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func2.2
    	/home/runner/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.13.1/pkg/internal/controller/controller.go:234
  << End Captured GinkgoWriter Output

**Comment by TobiasGoerke** [comment]
> @TobiasGoerke could you help us debug the failing unit tests for the PVCViewer Controller?
> 
> I see the following relevant logs, that come from the following line in the code https://github.com/kubeflow/kubeflow/blob/08eaaba1095455b3b44485e697bae8324ad8eaf8/components/pvcviewer-controller/controllers/pvcviewer_controller_test.go#L387C1-L387C7
> 
> ```
> • [FAILED] [0.027 seconds]
> PVCViewer controller
> /home/runner/work/kubeflow/kubeflow/components/pvcviewer-controller/controllers/pvcviewer_controller_test.go:30
>   When RWO Scheduling is used
>   /home/runner/work/kubeflow/kubeflow/components/pvcviewer-controller/controllers/pvcviewer_controller_test.go:370
>     [It] Does not generate affinities for RWX PVCs
>     /home/runner/work/kubeflow/kubeflow/components/pvcviewer-controller/controllers/pvcviewer_controller_test.go:371
> 
> Begin Captured GinkgoWriter Output >>
>     STEP: Creating a RWX PVC and mounting Pod 09/19/23 19:33:32.07
>     STEP: Creating a PVCViewer for the RWX PVC 09/19/23 19:33:32.074
>     1.6951520120758505e+09	DEBUG	controller-runtime.webhook.webhooks	received request	{"webhook": "/mutate-kubeflow-org-v1alpha1-pvcviewer", "UID": "3936385e-5bda-4b4a-9a48-17d3bee931af", "kind": "kubeflow.org/v1alpha1, Kind=PVCViewer", "resource": {"group":"kubeflow.org","version":"v1alpha1","resource":"pvcviewers"}}
>     1.6951520120759068e+09	INFO	pvcviewer-resource	default	{"name": "test-pvcviewer"}
>     1.6951520120759153e+09	INFO	pvcviewer-resource	Inferring default podSpec	{"name": "test-pvcviewer"}
>     1.6951520120760825e+09	DEBUG	controller-runtime.webhook.webhooks	wrote response	{"webhook": "/mutate-kubeflow-org-v1alpha1-pvcviewer", "code": 200, "reason": "", "UID": "3936385e-5bda-4b4a-9a48-17d3bee931af", "allowed": true}
>     1.6951520120772035e+09	DEBUG	controller-runtime.webhook.webhooks	received request	{"webhook": "/validate-kubeflow-org-v1alpha1-pvcviewer", "UID": "32162513-9212-4426-a50f-964ace887c19", "kind": "kubeflow.org/v1alpha1, Kind=PVCViewer", "resource": {"group":"kubeflow.org","version":"v1alpha1","resource":"pvcviewers"}}
>     1.6951520120772767e+09	INFO	pvcviewer-resource	validate create	{"name": "test-pvcviewer"}
>     1.6951520120772908e+09	DEBUG	controller-runtime.webhook.webhooks	wrote response	{"webhook": "/validate-kubeflow-org-v1alpha1-pvcviewer", "code": 200, "reason": "", "UID": "32162513-9212-4426-a50f-964ace887c19", "allowed": true}
>     1.6951520120787518e+09	INFO	Creating Deployment	{"controller": "pvcviewer", "controllerGroup": "kubeflow.org", "controllerKind": "PVCViewer", "PVCViewer": {"name":"test-pvcviewer","namespace":"test-9"}, "namespace": "test-9", "name": "test-pvcviewer", "reconcileID": "0d3ed72e-7f25-4e6d-b47e-ad6be1c725e7"}
>     1.6951520120819845e+09	INFO	Updating status	{"controller": "pvcviewer", "controllerGroup": "kubeflow.org", "controllerKind": "PVCViewer", "PVCViewer": {"name":"test-pvcviewer","namespace":"test-9"}, "namespace": "test-9", "name": "test-pvcviewer", "reconcileID": "0d3ed72e-7f25-4e6d-b47e-ad6be1c725e7"}
> ...
>     1.695152012089806e+09	ERROR	Reconciler error	{"controller": "pvcviewer", "controllerGroup": "kubeflow.org", "controllerKind": "PVCViewer", "PVCViewer": {"name":"test-pvcviewer","namespace":"test-9"}, "namespace": "test-9", "name": "test-pvcviewer", "reconcileID": "e0663be8-fa85-45ae-84e6-a552e2d3c4b5", "error": "PVCViewer.kubeflow.org \"test-pvcviewer\" not found"}
>     sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).reconcileHandler
>     	/home/runner/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.13.1/pkg/internal/controller/controller.go:326
>     sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem
>     	/home/runner/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.13.1/pkg/internal/controller/controller.go:273
>     sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func2.2
>     	/home/runner/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.13.1/pkg/internal/controller/controller.go:234
>   << End Captured GinkgoWriter Output
> ```

Not sure why this test starts failing now and without changes. I've only been able to reproduce the error about twice by running a few hundred times and have yet to see it in production. Judging by [this issue](https://github.com/kubernetes-sigs/controller-runtime/issues/1881) and [this one](https://github.com/kubernetes/kubernetes/issues/82130), we're not alone with this issue and I'd assume its related to a race condition in our testing environment. 
Could you please re-trigger the pipeline? If it continues to fail, I'd suggest we ignore this test for now and wait for an upstream fix.

**Comment by DnPlas** [comment]
> > @TobiasGoerke could you help us debug the failing unit tests for the PVCViewer Controller?
> > I see the following relevant logs, that come from the following line in the code https://github.com/kubeflow/kubeflow/blob/08eaaba1095455b3b44485e697bae8324ad8eaf8/components/pvcviewer-controller/controllers/pvcviewer_controller_test.go#L387C1-L387C7
> > ```
> > • [FAILED] [0.027 seconds]
> > PVCViewer controller
> > /home/runner/work/kubeflow/kubeflow/components/pvcviewer-controller/controllers/pvcviewer_controller_test.go:30
> >   When RWO Scheduling is used
> >   /home/runner/work/kubeflow/kubeflow/components/pvcviewer-controller/controllers/pvcviewer_controller_test.go:370
> >     [It] Does not generate affinities for RWX PVCs
> >     /home/runner/work/kubeflow/kubeflow/components/pvcviewer-controller/controllers/pvcviewer_controller_test.go:371
> > 
> > Begin Captured GinkgoWriter Output >>
> >     STEP: Creating a RWX PVC and mounting Pod 09/19/23 19:33:32.07
> >     STEP: Creating a PVCViewer for the RWX PVC 09/19/23 19:33:32.074
> >     1.6951520120758505e+09	DEBUG	controller-runtime.webhook.webhooks	received request	{"webhook": "/mutate-kubeflow-org-v1alpha1-pvcviewer", "UID": "3936385e-5bda-4b4a-9a48-17d3bee931af", "kind": "kubeflow.org/v1alpha1, Kind=PVCViewer", "resource": {"group":"kubeflow.org","version":"v1alpha1","resource":"pvcviewers"}}
> >     1.6951520120759068e+09	INFO	pvcviewer-resource	default	{"name": "test-pvcviewer"}
> >     1.6951520120759153e+09	INFO	pvcviewer-resource	Inferring default podSpec	{"name": "test-pvcviewer"}
> >     1.6951520120760825e+09	DEBUG	controller-runtime.webhook.webhooks	wrote response	{"webhook": "/mutate-kubeflow-org-v1alpha1-pvcviewer", "code": 200, "reason": "", "UID": "3936385e-5bda-4b4a-9a48-17d3bee931af", "allowed": true}
> >     1.6951520120772035e+09	DEBUG	controller-runtime.webhook.webhooks	received request	{"webhook": "/validate-kubeflow-org-v1alpha1-pvcviewer", "UID": "32162513-9212-4426-a50f-964ace887c19", "kind": "kubeflow.org/v1alpha1, Kind=PVCViewer", "resource": {"group":"kubeflow.org","version":"v1alpha1","resource":"pvcviewers"}}
> >     1.6951520120772767e+09	INFO	pvcviewer-resource	validate create	{"name": "test-pvcviewer"}
> >     1.6951520120772908e+09	DEBUG	controller-runtime.webhook.webhooks	wrote response	{"webhook": "/validate-kubeflow-org-v1alpha1-pvcviewer", "code": 200, "reason": "", "UID": "32162513-9212-4426-a50f-964ace887c19", "allowed": true}
> >     1.6951520120787518e+09	INFO	Creating Deployment	{"controller": "pvcviewer", "controllerGroup": "kubeflow.org", "controllerKind": "PVCViewer", "PVCViewer": {"name":"test-pvcviewer","namespace":"test-9"}, "namespace": "test-9", "name": "test-pvcviewer", "reconcileID": "0d3ed72e-7f25-4e6d-b47e-ad6be1c725e7"}
> >     1.6951520120819845e+09	INFO	Updating status	{"controller": "pvcviewer", "controllerGroup": "kubeflow.org", "controllerKind": "PVCViewer", "PVCViewer": {"name":"test-pvcviewer","namespace":"test-9"}, "namespace": "test-9", "name": "test-pvcviewer", "reconcileID": "0d3ed72e-7f25-4e6d-b47e-ad6be1c725e7"}
> > ...
> >     1.695152012089806e+09	ERROR	Reconciler error	{"controller": "pvcviewer", "controllerGroup": "kubeflow.org", "controllerKind": "PVCViewer", "PVCViewer": {"name":"test-pvcviewer","namespace":"test-9"}, "namespace": "test-9", "name": "test-pvcviewer", "reconcileID": "e0663be8-fa85-45ae-84e6-a552e2d3c4b5", "error": "PVCViewer.kubeflow.org \"test-pvcviewer\" not found"}
> >     sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).reconcileHandler
> >     	/home/runner/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.13.1/pkg/internal/controller/controller.go:326
> >     sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem
> >     	/home/runner/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.13.1/pkg/internal/controller/controller.go:273
> >     sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func2.2
> >     	/home/runner/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.13.1/pkg/internal/controller/controller.go:234
> >   << End Captured GinkgoWriter Output
> > ```
> 
> Not sure why this test starts failing now and without changes. I've only been able to reproduce the error about twice by running a few hundred times and have yet to see it in production. Judging by [this issue](https://github.com/kubernetes-sigs/controller-runtime/issues/1881) and [this one](https://github.com/kubernetes/kubernetes/issues/82130), we're not alone with this issue and I'd assume its related to a race condition in our testing environment. Could you please re-trigger the pipeline? If it continues to fail, I'd suggest we ignore this test for now and wait for an upstream fix.

Seems like it happened again [see latest run](https://github.com/kubeflow/kubeflow/actions/runs/6240088952/job/16968463772?pr=7286). I will let @kimwnasptd consider the next steps.

**Comment by TobiasGoerke** [comment]
> > > @TobiasGoerke could you help us debug the failing unit tests for the PVCViewer Controller?
> > > I see the following relevant logs, that come from the following line in the code https://github.com/kubeflow/kubeflow/blob/08eaaba1095455b3b44485e697bae8324ad8eaf8/components/pvcviewer-controller/controllers/pvcviewer_controller_test.go#L387C1-L387C7
> > > ```
> > > • [FAILED] [0.027 seconds]
> > > PVCViewer controller
> > > /home/runner/work/kubeflow/kubeflow/components/pvcviewer-controller/controllers/pvcviewer_controller_test.go:30
> > >   When RWO Scheduling is used
> > >   /home/runner/work/kubeflow/kubeflow/components/pvcviewer-controller/controllers/pvcviewer_controller_test.go:370
> > >     [It] Does not generate affinities for RWX PVCs
> > >     /home/runner/work/kubeflow/kubeflow/components/pvcviewer-controller/controllers/pvcviewer_controller_test.go:371
> > > 
> > > Begin Captured GinkgoWriter Output >>
> > >     STEP: Creating a RWX PVC and mounting Pod 09/19/23 19:33:32.07
> > >     STEP: Creating a PVCViewer for the RWX PVC 09/19/23 19:33:32.074
> > >     1.6951520120758505e+09	DEBUG	controller-runtime.webhook.webhooks	received request	{"webhook": "/mutate-kubeflow-org-v1alpha1-pvcviewer", "UID": "3936385e-5bda-4b4a-9a48-17d3bee931af", "kind": "kubeflow.org/v1alpha1, Kind=PVCViewer", "resource": {"group":"kubeflow.org","version":"v1alpha1","resource":"pvcviewers"}}
> > >     1.6951520120759068e+09	INFO	pvcviewer-resource	default	{"name": "test-pvcviewer"}
> > >     1.6951520120759153e+09	INFO	pvcviewer-resource	Inferring default podSpec	{"name": "test-pvcviewer"}
> > >     1.6951520120760825e+09	DEBUG	controller-runtime.webhook.webhooks	wrote response	{"webhook": "/mutate-kubeflow-org-v1alpha1-pvcviewer", "code": 200, "reason": "", "UID": "3936385e-5bda-4b4a-9a48-17d3bee931af", "allowed": true}
> > >     1.6951520120772035e+09	DEBUG	controller-runtime.webhook.webhooks	received request	{"webhook": "/validate-kubeflow-org-v1alpha1-pvcviewer", "UID": "32162513-9212-4426-a50f-964ace887c19", "kind": "kubeflow.org/v1alpha1, Kind=PVCViewer", "resource": {"group":"kubeflow.org","version":"v1alpha1","resource":"pvcviewers"}}
> > >     1.6951520120772767e+09	INFO	pvcviewer-resource	validate create	{"name": "test-pvcviewer"}
> > >     1.6951520120772908e+09	DEBUG	controller-runtime.webhook.webhooks	wrote response	{"webhook": "/validate-kubeflow-org-v1alpha1-pvcviewer", "code": 200, "reason": "", "UID": "32162513-9212-4426-a50f-964ace887c19", "allowed": true}
> > >     1.6951520120787518e+09	INFO	Creating Deployment	{"controller": "pvcviewer", "controllerGroup": "kubeflow.org", "controllerKind": "PVCViewer", "PVCViewer": {"name":"test-pvcviewer","namespace":"test-9"}, "namespace": "test-9", "name": "test-pvcviewer", "reconcileID": "0d3ed72e-7f25-4e6d-b47e-ad6be1c725e7"}
> > >     1.6951520120819845e+09	INFO	Updating status	{"controller": "pvcviewer", "controllerGroup": "kubeflow.org", "controllerKind": "PVCViewer", "PVCViewer": {"name":"test-pvcviewer","namespace":"test-9"}, "namespace": "test-9", "name": "test-pvcviewer", "reconcileID": "0d3ed72e-7f25-4e6d-b47e-ad6be1c725e7"}
> > > ...
> > >     1.695152012089806e+09	ERROR	Reconciler error	{"controller": "pvcviewer", "controllerGroup": "kubeflow.org", "controllerKind": "PVCViewer", "PVCViewer": {"name":"test-pvcviewer","namespace":"test-9"}, "namespace": "test-9", "name": "test-pvcviewer", "reconcileID": "e0663be8-fa85-45ae-84e6-a552e2d3c4b5", "error": "PVCViewer.kubeflow.org \"test-pvcviewer\" not found"}
> > >     sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).reconcileHandler
> > >     	/home/runner/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.13.1/pkg/internal/controller/controller.go:326
> > >     sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem
> > >     	/home/runner/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.13.1/pkg/internal/controller/controller.go:273
> > >     sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func2.2
> > >     	/home/runner/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.13.1/pkg/internal/controller/controller.go:234
> > >   << End Captured GinkgoWriter Output
> > > ```
> > 
> > 
> > Not sure why this test starts failing now and without changes. I've only been able to reproduce the error about twice by running a few hundred times and have yet to see it in production. Judging by [this issue](https://github.com/kubernetes-sigs/controller-runtime/issues/1881) and [this one](https://github.com/kubernetes/kubernetes/issues/82130), we're not alone with this issue and I'd assume its related to a race condition in our testing environment. Could you please re-trigger the pipeline? If it continues to fail, I'd suggest we ignore this test for now and wait for an upstream fix.
> 
> Seems like it happened again [see latest run](https://github.com/kubeflow/kubeflow/actions/runs/6240088952/job/16968463772?pr=7286). I will let @kimwnasptd consider the next steps.

Well, now we're running into a new problem. The tests [download the latest istio CRD](https://github.com/kubeflow/kubeflow/blob/08eaaba1095455b3b44485e697bae8324ad8eaf8/components/pvcviewer-controller/controllers/test_setup_utils.go#L13) which is required for testing. However, that path just changed to `https://raw.githubusercontent.com/kubeflow/manifests/master/common/istio-1-17/istio-crds/base/crd.yaml`, which causes an invalid file to be downloaded, failing all tests. This is easy to fix. Also, we might be better off copying that file statically without downloading it manually, as this is bound to happen again.

For reference: I [forked your branch](https://github.com/TobiasGoerke/kubeflow/pull/2) and changed the path. You'll see that [the tests run successfully](https://github.com/TobiasGoerke/kubeflow/actions/runs/6251989639/job/16974252442?pr=2).

I'll create PRs against both master and your `dnplas-bump-version-1.8.0-rc.1` branch in the next step.

**Comment by kimwnasptd** [comment]
So nice to see everything green! Thank you both @DnPlas @TobiasGoerke!

/lgtm
/approve

**Comment by TobiasGoerke** [comment]
Nice! Great to be part of this release. Thanks for the support @DnPlas @kimwnasptd

**Pull request merged**
