### PR TITLE
Update image-releaser README

### PR DESCRIPTION
**Pull request by ankushagarwal**
Also use resource requests to ensure that build containers have
3 cpu and 6Gi memory

/assign @lluunn

---
This change is [Reviewable](https://reviewable.io/reviews/kubeflow/kubeflow/922)

### CODE REVIEW

**Comment by lluunn** [comment]
/lgtm
/approve

thanks!

**Comment by ankushagarwal** [comment]
@lluunn Can you LGTM again? I rebased.

**Pull request merged**
