### PR TITLE
Clarify the dependency build step

### PR DESCRIPTION
**Pull request by holdenk**
If someone follows the guide as is it will result in a bunch of errors about missing dependencies.

---
This change is [Reviewable](https://reviewable.io/reviews/kubeflow/kubeflow/3384)

### CODE REVIEW

**Comment by holdenk** [comment]
cc @kkasravi ?

**Comment by holdenk** [comment]
/retest
Test failure seems spurious given pure doc change

**Comment by holdenk** [comment]
@kkasravi  could you give this an ok-to-test? And or add me to the approved testing group?

**Comment by holdenk** [comment]
This is literally a doc change, how is it failing presubmits so consistently? :(
/retest

**Comment by holdenk** [comment]
TF serving clearly unrelated
/retest

**Comment by holdenk** [comment]
Can we merge @kkasravi  or @jlewi the tfserving should be unrelated.

**Comment by rawkintrevo** [comment]
a doc change is causing mnist-cpu and mnist-gpu tests to fail... 

these seem like flaky tests, my .02. 

The doc/updates are useful.

**Comment by holdenk** [comment]
Failure is a 404 fetching an unrelated file from github (`INFO|2019-07-24T17:41:31|/src/kubeflow/testing/py/kubeflow/testing/util.py|71| level=error msg="find objects: Received status code '404' when trying to retrieve OpenAPI schema for cluster version 'v0.3.1' from URL 'https://raw.githubusercontent.com/kubernetes/kubernetes/v0.3.1/api/openapi-spec/swagger.json'"
`)
/retest

**Pull request merged**
