### PR TITLE
Fix profile-controller CRD pruning issue

### PR DESCRIPTION
**Pull request by yanniszark**
Closes https://github.com/kubeflow/kubeflow/issues/5813

@Bobgy @zijianjoy I took a look at the controller-gen and kubebuilder docs for embedding resources.
I added the `// +kubebuilder:pruning:PreserveUnknownFields` marker accordingly and regenerated manifests.
Could you please test and tell me if it also works for you?

### CODE REVIEW

**Comment by Bobgy** [comment]
@yanniszark I think you need to regenerate the crd. Did I miss anything?

**Comment by yanniszark** [comment]
> @yanniszark I think you need to regenerate the crd. Did I miss anything?

I think you missed it 😛 
I may be mistaken, but this is what you mean right?
https://github.com/kubeflow/kubeflow/pull/5822/files#diff-4cceae2882a85453456ceab092e7c9cc138e55b2cc907437c88e7f2d96f25c48

**Comment by Bobgy** [comment]
Ohhh, you are right!
That's exactly what I wanted
/LGTM

**Comment by zijianjoy** [comment]
Thank you Yannis for the fix!

**Pull request merged**
