### PR TITLE
Add model status endpoint to http-proxy

### PR DESCRIPTION
**Pull request by mrkm4ntr**
Add model status endpoint to http-proxy. This endpoint will be used to support readiness probe of tf-serving.
BTW, I'm not quite sure where is image of http-proxy built. After new image will be built,  I will create a PR to add readiness probe to ksonnet template of http-proxy container like below.
```
readinessProbe: {
  httpGet: {
    path: "/model/" + $.params.modelName + ":status",
    port: 8000,
  },
  initialDelaySeconds: 30,
  periodSeconds: 30,
},
```

Related issue about readiness probe is here.
https://github.com/kubeflow/kubeflow/issues/368#issuecomment-429670371

---
This change is [Reviewable](https://reviewable.io/reviews/kubeflow/kubeflow/2987)

### CODE REVIEW

**Comment by lluunn** [comment]
Hi, thanks for the PR.
However, we are not using that http-proxy anymore because TF Serving has native http support.
https://www.tensorflow.org/tfx/serving/api_rest

**Comment by mrkm4ntr** [comment]
OK, I will send PR for supporting readiness probe using native REST API.

**Comment by mrkm4ntr** [comment]
@lluunn The REST endpoint of tf-serving can not be used for readiness probe because it returns always 200. We have to check response whether model status is available. I completely agree that http-proxy is not needed currently, but some sidecar proxy is needed for readiness probe. How do you think?

**Comment by mrkm4ntr** [comment]
I am talking about sidecar health server in the following article.
https://ahmet.im/blog/advanced-kubernetes-health-checks/

**Pull request closed without merging**
