### PR TITLE
JWT validation works with GCP IAP - remove outdated docs

### PR DESCRIPTION
**Pull request by ankushagarwal**
Closes https://github.com/kubeflow/kubeflow/issues/60

---
This change is [Reviewable](https://reviewable.io/reviews/kubeflow/kubeflow/406)

### CODE REVIEW

**Comment by jlewi** [comment]
Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion.

---

*[docs/gke/iap.md, line 3 at r1](https://reviewable.io:443/reviews/kubeflow/kubeflow/406#-L7BwihWWXIxXT1BQzyh:-L7BwihXl6ArYLq54cG7:bgm4bwc) ([raw file](https://github.com/kubeflow/kubeflow/blob/42a73f4b5ced8df613a43c55eaa14219ad633543/docs/gke/iap.md#L3)):*
> ```Markdown
> # Setting Up IAP on GKE
> 
> **Important** This doc is a work in progress. The instructions don't fully work yet because Envoy can't properly validate JWTs created
> ```

Delete these instructions.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/kubeflow/kubeflow/406)*

**Comment by ankushagarwal** [comment]
Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion.

---

*[docs/gke/iap.md, line 3 at r1](https://reviewable.io:443/reviews/kubeflow/kubeflow/406#-L7BwihWWXIxXT1BQzyh:-L7C2-rjz0cNQblF7kjH:b-896fix) ([raw file](https://github.com/kubeflow/kubeflow/blob/42a73f4b5ced8df613a43c55eaa14219ad633543/docs/gke/iap.md#L3)):*
<details><summary><i>Previously, jlewi (Jeremy Lewi) wrote…</i></summary><blockquote>

Delete these instructions.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/kubeflow/kubeflow/406)*

**Pull request merged**
