### PR TITLE
cleanup some codes in notebook controller

### PR DESCRIPTION
**Pull request by yeya24**
Signed-off-by: yeya24 <yb532204897@gmail.com>
Just cleanup some codes and names in notebook controller

---
This change is [Reviewable](https://reviewable.io/reviews/kubeflow/kubeflow/4098)

### CODE REVIEW

**Comment by yeya24** [comment]
@kunmingg  PTAl, we should use camel case in go.

**Comment by nrchakradhar** [comment]
Nit: I just noticed that there are annotations to ambassador. As its not longer needed, can you please remove the same. [notebook_controller.go#319](https://github.com/kubeflow/kubeflow/blob/011e1f5a11157c5e8916ac9c5657b395e76e34b4/components/notebook-controller/controllers/notebook_controller.go#L319)

**Comment by yeya24** [comment]
> Nit: I just noticed that there are annotations to ambassador. As its not longer needed, can you please remove the same. [notebook_controller.go#319](https://github.com/kubeflow/kubeflow/blob/011e1f5a11157c5e8916ac9c5657b395e76e34b4/components/notebook-controller/controllers/notebook_controller.go#L319)

Done.

**Comment by jlewi** [comment]
/assign @nrchakradhar 
/assign @kimwnasptd 

@nrchakradhar and @kimwnasptd can you please review this PR?

**Comment by lluunn** [comment]
/lgtm
/approve 
thanks

**Pull request merged**
