### PR TITLE
config update

### PR DESCRIPTION
**Pull request by kunmingg**
1. fix typo in cluster.jinja
2. update bootstrapper image
3. remove ```registries:``` from cluster-kubeflow.yaml since it's not needed with new image. 

---
This change is [Reviewable](https://reviewable.io/reviews/kubeflow/kubeflow/982)

### CODE REVIEW

**Comment by ankushagarwal** [comment]
Can you rebase? #984 fixes testing issue

**Comment by kunmingg** [comment]
nice

**Pull request merged**
