### PR TITLE
jwa: Remove all the Rok references

### PR DESCRIPTION
**Pull request by elenzio9**
This PR removes all the Rok references from JWA's code.

### CODE REVIEW

**Review by tasos-ale — CHANGES_REQUESTED** [review]
@elenzio9 I don't have any big change to suggest since we are only removing code. Shouldn't we also remove the `browse-in-rok-*.svg` images?

**Comment by elenzio9** [comment]
> Shouldn't we also remove the `browse-in-rok-*.svg` images?

Right! I just removed them.

**Review by tasos-ale — APPROVED** [review]

**Comment by tasos-ale** [comment]
@kimwnasptd I believe we can merge this PR.

**Pull request merged**
