### PR TITLE
Don't set dummy values for project, email, or hostname in kfctl_gcp iap.yaml

### PR DESCRIPTION
**Pull request by jlewi**
* Comment out lines setting default values and provide comments explaining how
  they should be set.

* We don't want to set values because the behavior in kfctl init/generate is
  to try to automatically set intelligent default values but only if no
  value is set. So explicitly setting default values inhibits that behavior.

---
This change is [Reviewable](https://reviewable.io/reviews/kubeflow/kubeflow/3912)

### CODE REVIEW

**Comment by lluunn** [comment]
do you want to do the same for basic_auth config?

**Comment by jlewi** [comment]
@lluunn good point done;

**Pull request merged**
