### PR TITLE
Add notebook-server-rstudio-tidyverse dockerfile and CI/CD

### PR DESCRIPTION
**Pull request by DavidSpek**
Part of #5575.

Initial images were built and pushed to test CI/CD:
public.ecr.aws/j1r0q0g6/notebooks/notebook-servers/rstudio-tidyverse:master-87b7d015

### CODE REVIEW

**Comment by thesuperzapper** [comment]
@googlebot I consent.

**Comment by DavidSpek** [comment]
@googlebot I consent

**Comment by DavidSpek** [comment]
@googlebot I consent.

**Comment by thesuperzapper** [comment]
@googlebot I consent.

**Comment by thesuperzapper** [comment]
Looks good!
/approve
/lgtm

**Pull request merged**
