### PR TITLE
Automated cherry pick of #5404: Remove metadata link from centraldashboard

### PR DESCRIPTION
**Pull request by Jeffwan**

### CODE REVIEW

**Comment by thesuperzapper** [comment]
@Jeffwan I cant approve this, because I am only in OWNERS on the `master` branch

**Comment by Jeffwan** [comment]
@thesuperzapper Got you. Let me ping other folks

**Comment by Jeffwan** [comment]
Can someone help approve this cherry-pick? 

@avdaredevil  @elikatsis @kimwnasptd @prodonjs @StefanoFioravanzo

**Pull request merged**
