### PR TITLE
Add AWS IAM Role for ServiceAccount support in profile controller

### PR DESCRIPTION
**Pull request by Jeffwan**
kubeflow/kubeflow#4403

Profile controller side changes

---
This change is [Reviewable](https://reviewable.io/reviews/kubeflow/kubeflow/4751)

### CODE REVIEW

**Comment by jlewi** [comment]
/assign @kunmingg 

@kunmingg How risky do you think this change is? If we cherry-pick it onto 1.0 are you concerned anything other than AWS would be impacted? The code looks pretty isolated so it looks low risk to me.

**Comment by kunmingg** [comment]
@Jeffwan 
Thanks for the new plugin! Really cool.
Can we 
* add new plugin at https://github.com/kubeflow/kubeflow/tree/master/components/profile-controller#plugins?
* add one profile sample with new plugin at: https://github.com/kubeflow/kubeflow/tree/master/components/profile-controller/config/samples?
* add 1 or 2 tests to verify plugin works as expected?

@jlewi 
Should be fine to cherry-pick, each plugin's logic should only apply when set.

**Comment by Jeffwan** [comment]
@kunmingg Thanks. I will update the PR.

**Comment by Jeffwan** [comment]
@kunmingg  Please have another look. doc and examples have been updated. UT and manual test pass as well.

**Comment by kunmingg** [comment]
/lgtm
Thanks!

How does user bind multiple aws role per profile?

**Comment by Jeffwan** [comment]
@kunmingg 
Thanks for helping review. Currently, only one role can be attached. To support multiple roles, we can either accept string list for `awsIamRole`, or propose group concept in profile controller and grant user the right group of permissions

**Pull request merged**
