### PR TITLE
Adds argo to ambassador and Central UI

### PR DESCRIPTION
**Pull request by swiftdiaries**
Addresses: https://github.com/kubeflow/kubeflow/issues/1310.

Adds small nits and addresses suggestions from: https://github.com/kubeflow/kubeflow/pull/1242.

---
This change is [Reviewable](https://reviewable.io/reviews/kubeflow/kubeflow/1376)

### CODE REVIEW

**Comment by pdmack** [comment]
@swiftdiaries, needs rebase.

**Comment by pdmack** [comment]
`argo.libsonnet:204:20-28: Unknown variable: namespace`

**Comment by swiftdiaries** [comment]
Thanks @pdmack

**Pull request merged**
