### PR TITLE
Troubleshooting section updates

### PR DESCRIPTION
**Pull request by pdmack**
- minikube resource constraints
- proper name casing
- improved Docker for Mac context advice

---
This change is [Reviewable](https://reviewable.io/reviews/kubeflow/kubeflow/393)

### CODE REVIEW

**Comment by jlewi** [comment]
@pdmack  I think you need to sync for the tests to pass.

/assign jlewi

**Comment by pdmack** [comment]
@jlewi ptal

**Comment by pdmack** [comment]
@jlewi lgtm label? looks like it needs both to merge?

**Pull request merged**
