### PR TITLE
Introduce workflows for building notebook-server images upon changes

### PR DESCRIPTION
**Pull request by apo-ger**
This PR resolves part of: https://github.com/kubeflow/kubeflow/issues/6766

Introduce GitHub Action workflows for testing that notebook server images can be built for each PR.

### CODE REVIEW

**Comment by kimwnasptd** [comment]
@apo-ger the changes look good. Only have one suggestion; should we also trigger these when the `releasing/version/VERSION` file changes? Right now IIUC these workflows won't run once we update the manifests for a new release https://github.com/kubeflow/kubeflow/pull/6975

**Comment by apo-ger** [comment]
@kimwnasptd Yes you are right, I updated the PR.

**Comment by apo-ger** [comment]
@kimwnasptd Yes, you are right! I updated the PR

**Comment by thesuperzapper** [comment]
This was fixed as part of https://github.com/kubeflow/kubeflow/pull/7357.

**Pull request closed without merging**
