### PR TITLE
Clarify that we pick up PROJECT, EMAIL, and ZONE from environment variables.

### PR DESCRIPTION
**Pull request by holdenk**
Closes https://github.com/kubeflow/kubeflow/issues/4240

---
This change is [Reviewable](https://reviewable.io/reviews/kubeflow/kubeflow/4246)

### CODE REVIEW

**Comment by swiftdiaries** [comment]
Thanks for the quick fix @holdenk !
/lgtm

**Comment by jlewi** [comment]
Is this correct? Shouldn't we be using gcloud to get the default values?

**Comment by jlewi** [comment]
This should be where we are getting email
https://github.com/kubeflow/kubeflow/blob/9592b48c95537ceec4c9aada83b73b7a738e48a8/bootstrap/pkg/kfapp/gcp/gcp.go#L230

**Comment by swiftdiaries** [comment]
I went off of the docs here: https://www.kubeflow.org/docs/gke/deploy/deploy-cli/
I'm not sure if that is updated

**Comment by swiftdiaries** [comment]
For some reason, the shelled out commands don't work for me when I run `kfctl`. 
So as a work around, I set the environment variables. 
Would it be better to check here if the Spec has a project/email set and if it's empty then pick it up from the environment variable?

**Comment by holdenk** [comment]
So we ignore the spec currently (I tried setting project and e-mail in my input). I think longer term reading the input spec and figuring out default values from the gcloud command sound lovely, but for right now the error message has no path to resolution for the user.

**Comment by swiftdiaries** [comment]
Would something like this work?
Since the `gcloud config get-value account` is run at the beginning and if the `KfDef` is edited manually, at this point we should have these set.
In the event they aren't, we can set them from the environment variables.
Regarding raising an error, Apply should throw the appropriate error if something's not right. 

```
	if gcp.kfDef.Spec.Project == "" {
	    gcp.kfDef.Spec.Project = os.Getenv("PROJECT")
	}
	
	if gcp.kfDef.Spec.Email == "" {
            gcp.kfDef.Spec.Email = os.Getenv("EMAIL")
	}

	if gcp.kfDef.Spec.Zone == "" {
            gcp.kfDef.Spec.Zone = os.Getenv("ZONE")
	}
```

**Comment by jlewi** [comment]
@holdenk The resolution should be to set project explicitly in your KFDef file. That's what the E2E test is doing so I'd be suprised if setting project, email, and zone explicitly in your KFDef file doesn't work.
https://github.com/kubeflow/kubeflow/blob/9592b48c95537ceec4c9aada83b73b7a738e48a8/py/kubeflow/kubeflow/ci/kfctl_go_test_utils.py#L148

Can you provide the steps to reproduce?

**Comment by swiftdiaries** [comment]
I modified the E2E test to pick it up from the environment variable here:
https://github.com/kubeflow/kubeflow/blob/9592b48c95537ceec4c9aada83b73b7a738e48a8/py/kubeflow/kubeflow/ci/kfctl_go_test_utils.py#L211
So I guess it ignores the one in the KFDef file.

**Comment by jlewi** [comment]
@swiftdiaries that's a bug. We should not be reading PROJECT and ZONE from environment variables.

Where is the logic to fetch those values from environment variables? 


/assign @gabrielwen

**Comment by holdenk** [comment]
That makes sense then @swiftdiaries 
The repro steps are `mkdir gcp07b && cd gcp07b && kfctl build --file=../gcp07b.yaml` with https://pastebin.com/fbSfaRpz
I can update this to check if the spec values are empty and change the error message to say set env var or in the input spec.

Does that sound good @jlewi & @swiftdiaries ?

**Comment by jlewi** [comment]
@swiftdiaries @holdenk I'm still trying to figure out why using environment variables work. To my knowledge getting PROJECT and ZONE from environment variables was nothing we ever supported and I can't find code explicitly getting those values from environment variables.

My conjecture is that there might be some form of viper magic going on where options can automatically be set via command line or environment variable.

In the past the supported way of setting project and zone were

1. Setting it in KFDef
1. Setting explicitly via command line option

Using environment variables doesn't really make sense because its redundant with gcloud config. So i don't think we want to update the error message to start telling people to use environment variable.

If the code isn't respecting the value in KFDef then that's a huge bug that we need to fix.

**Comment by swiftdiaries** [comment]
Removing the error here should fix it.
While I was testing locally, the shelled out commands from `gcp.go` didn't execute.
I'll file a separate bug for this.

**Comment by jlewi** [comment]
@swiftdiaries the code should not be calling os.Getenv to get PROJECT, ZONE, or email. Those lines are also causing the bug since they are not checking if PROJECT, zone and email are already set.

**Comment by swiftdiaries** [comment]
I'll get a fix out in a PR and link it here.

**Comment by jlewi** [comment]
Thanks @swiftdiaries lets update the test as well please to not set the environment variables.

**Comment by swiftdiaries** [comment]
Got it !

**Comment by swiftdiaries** [comment]
Before we call `gcp.generateDMConfigs()` here:
https://github.com/kubeflow/kubeflow/blob/9592b48c95537ceec4c9aada83b73b7a738e48a8/bootstrap/pkg/kfapp/gcp/gcp.go#L1998

We need to have these set in the Spec. If they are empty, should we surface that out with a `log.Warnf()`?

**Comment by swiftdiaries** [comment]
PR: https://github.com/kubeflow/kubeflow/pull/4252

**Comment by gabrielwen** [comment]
> @swiftdiaries @holdenk I'm still trying to figure out why using environment variables work. To my knowledge getting PROJECT and ZONE from environment variables was nothing we ever supported and I can't find code explicitly getting those values from environment variables.
> 
> My conjecture is that there might be some form of viper magic going on where options can automatically be set via command line or environment variable.
> 
> In the past the supported way of setting project and zone were
> 
> 1. Setting it in KFDef
> 2. Setting explicitly via command line option
> 
> Using environment variables doesn't really make sense because its redundant with gcloud config. So i don't think we want to update the error message to start telling people to use environment variable.
> 
> If the code isn't respecting the value in KFDef then that's a huge bug that we need to fix.

@jlewi 
using env is supported since we started implementing kfctl go binary.  it is derived from the shell script version and back at that time we wanted to keep the same semantics.

**Comment by holdenk** [comment]
Should I close this then since https://github.com/kubeflow/kubeflow/pull/4252 ?

**Comment by swiftdiaries** [comment]
@holdenk sorry about that, could you please close?

**Pull request closed without merging**
