### PR TITLE
Profile controller and KFAM allow unauthenticated in-cluster traffic

### PR DESCRIPTION
**Pull request by johnhoman**
This is similar to this kerve issue https://github.com/kserve/kserve/issues/2197#issue-1248404440. Users can be impersonated without authentication by attaching the header `kubeflow-userid: ` with a valid profile contributor name to a request going to any namespace within the mesh.

```sh
(base) jovyan@tensorflow-0:~$ curl -sS -D - http://jupyter-scipy.kubeflow-user-example-com.svc.cluster.local/notebook/kubeflow-user-example-com/jupyter-scipy/api/sessions -o /dev/null
HTTP/1.1 403 Forbidden
content-length: 19
content-type: text/plain
date: Tue, 07 Mar 2023 04:02:17 GMT
server: envoy
x-envoy-upstream-service-time: 4

(base) jovyan@tensorflow-0:~$ curl -H "kubeflow-userid: user@example.com" -sS -D - http://jupyter-scipy.kubeflow-user-example-com.svc.cluster.local/notebook/kubeflow-user-example-com/jupyter-scipy/api/sessions -o /dev/null
HTTP/1.1 200 OK
server: envoy
content-type: application/json
date: Tue, 07 Mar 2023 04:03:22 GMT
x-content-type-options: nosniff
content-security-policy: frame-ancestors 'self'; report-uri /notebook/kubeflow-user-example-com/jupyter-scipy/api/security/csp-report; default-src 'none'
access-control-allow-origin: *
etag: "97d170e1550eee4afc0af065b78cda302a97674c"
content-length: 2
x-envoy-upstream-service-time: 106
```

Adding this change resolves that
```sh
kubectl patch deployment profiles-deployment -n kubeflow --type=json -p='[{"op": "replace", "path": "/spec/template/spec/containers/1/image", "value": "profile-controller:v1.7.0-rc.1-dirty"}]'
deployment.apps/profiles-deployment patched
```

```sh
➜  ~ kubectl get authorizationpolicies/ns-owner-access-istio -n kubeflow-user-example-com -o json | jq '.spec.rules[0]'

{
  "from": [
    {
      "source": {
        "principals": [
          "cluster.local/ns/istio-system/sa/istio-ingressgateway-service-account"
        ]
      }
    }
  ],
  "when": [
    {
      "key": "request.headers[kubeflow-userid]",
      "values": [
        "user@example.com"
      ]
    }
  ]
}
```

```sh
(base) jovyan@tensorflow-0:~$ curl -sS -D - http://jupyter-scipy.kubeflow-user-example-com.svc.cluster.local/notebook/kubeflow-user-example-com/jupyter-scipy/api/sessions -o /dev/null
HTTP/1.1 403 Forbidden
content-length: 19
content-type: text/plain
date: Tue, 07 Mar 2023 04:26:19 GMT
server: envoy
x-envoy-upstream-service-time: 32

(base) jovyan@tensorflow-0:~$ curl -H "kubeflow-userid: user@example.com" -sS -D - http://jupyter-scipy.kubeflow-user-example-com.svc.cluster.local/notebook/kubeflow-user-example-com/jupyter-scipy/api/sessions -o /dev/null
HTTP/1.1 403 Forbidden
content-length: 19
content-type: text/plain
date: Tue, 07 Mar 2023 04:26:22 GMT
server: envoy
x-envoy-upstream-service-time: 9
```

The authorization policy created by KFAM also has the same issue.
Screenshot 2023-03-06 at 11 39 47 PM

```sh
(base) jovyan@tensorflow-0:~$ curl -H "kubeflow-userid: jack@example.com" -sS -D - http://jupyter-scipy.kubeflow-user-example-com.svc.cluster.local/notebook/kubeflow-user-example-com/jupyter-scipy/api/sessions -o /dev/null | head -n 1
HTTP/1.1 200 OK
```

### CODE REVIEW

**Comment by juliusvonkohout** [comment]
are you using Kubeflow 1.7 ?

**Comment by TobiasGoerke** [comment]
Can confirm: spoofing the `kubeflow-userid` is easily done when there are no network policies in place.
grafik

I currently cannot test the PR but restricting the Authorization Policy to the istio SA looks promising.

Thanks!

**Comment by juliusvonkohout** [comment]
@johnhoman can you provide a public image for testing?

**Comment by johnhoman** [comment]
> @johnhoman can you provide a public image for testing?

Sorry, must have missed this. Here are public images rebuilt from this commit

`jackhoman/kubeflow-profile-controller:e205339e`
`jackhoman/kubeflow-kfam:e205339e`

**Comment by thesuperzapper** [comment]
@kimwnasptd I see that we have hard-coded the istio gateway's namespace as `istio-sytem` and its Pod ServiceAccount as `istio-ingressgateway-service-account`, this will make it impossible to use in many companies which don't use these.

Similar to how we allow configuring this with the `ISTIO_GATEWAY` env-var in the notebook controller.

**Comment by kimwnasptd** [comment]
@thesuperzapper indeed, let's have the same configuration everywhere for allowing different Istio handlings

**Comment by thesuperzapper** [comment]
@kimwnasptd we either need to revert this ASAP, because it will break Kubeflow as it currently stands.

Specifically, we need to:

1. __Allow users to specify the correct ServiceAccount for their Istio Gateway:__
     - These configs must be added to both controllers:
         - `ISTIO_GATEWAY_NAMESPACE`
         - `ISTIO_GATEWAY_SA`
     - These configs are used to set the `source.principals` of the rule: 
        - `cluster.local/ns/{ISTIO_GATEWAY_NAMESPACE}/sa/{ISTIO_GATEWAY_SA}`
2. Add a `source.principals` for the Kubeflow Pipelines UI:
      - (if we don't add this, KFP won't be able to access artifact)
      - `cluster.local/ns/kubeflow/sa/ml-pipeline-ui`

**Comment by thesuperzapper** [comment]
Also, another option is to use a single `ISTIO_GATEWAY_PRINCIPAL` config, rather than the two (`ISTIO_GATEWAY_NAMESPACE` and `ISTIO_GATEWAY_SA`)

Which would have a value like: `cluster.local/ns/{ISTIO_GATEWAY_NAMESPACE}/sa/{ISTIO_GATEWAY_SA}`

**Pull request merged**
