### PR TITLE
Katib 0.3 cherrypick

### PR DESCRIPTION
**Pull request by texasmichelle**
Cherrypick #1955

---
This change is [Reviewable](https://reviewable.io/reviews/kubeflow/kubeflow/2011)

### CODE REVIEW

**Comment by texasmichelle** [comment]
Do we need an LGTM from @YujiOshima?

**Comment by YujiOshima** [comment]
@texasmichelle Thank you! LGTM

**Comment by texasmichelle** [comment]
what's the command for removing the `cla:no` label?

**Comment by richardsliu** [comment]
@texasmichelle I removed the cla: no label manually.

**Comment by texasmichelle** [comment]
excellent - thanks!

**Pull request merged**
