### PR TITLE
Sync v0.6 to master head

### PR DESCRIPTION
**Pull request by kunmingg**
Pick up new changes around kfctl and more

---
This change is [Reviewable](https://reviewable.io/reviews/kubeflow/kubeflow/3678)

### CODE REVIEW

**Comment by kunmingg** [comment]
WIll merge once presubmit passed.

**Comment by jlewi** [comment]
Sync's v0.6-branch to
https://github.com/kubeflow/kubeflow/commit/f909404d667417c0c9fa7cd0d37ce06754fa31a7

/lgtm
/approve

**Pull request merged**
