### PR TITLE
Update images for RC 1

### PR DESCRIPTION
**Pull request by kimwnasptd**
Updates the `releaseing/version/VERSION` file with the latest tag and updates the images to use it.
The post-submit job should build/push these images.

/cc @elikatsis 
/assign @kimwnasptd

### CODE REVIEW

**Comment by kimwnasptd** [comment]
@DavidSpek @thesuperzapper the Notebook images are failing with:
> gpg: no valid OpenPGP data found.

Can you look into this? This is needed to cut the latest RC
https://argo.kubeflow-testing.com/workflows/kubeflow-test-infra/kubeflow-kubeflow-presubmit-nb-base-6137-098e9a7-6704-6fab?tab=workflow&nodeId=kubeflow-kubeflow-presubmit-nb-base-6137-098e9a7-6704-6fab-611371480&sidePanel=logs%3Akubeflow-kubeflow-presubmit-nb-base-6137-098e9a7-6704-6fab-611371480%3Amain

**Comment by DavidSpek** [comment]
@kimwnasptd Solved in https://github.com/kubeflow/kubeflow/pull/6138.

**Comment by kimwnasptd** [comment]
@elikatsis this should be ready to merge

**Pull request merged**
