### PR TITLE
Use iam-policy value for EMAIL if case-sensitive.

### LINKED ISSUE #1936: Use iam-policy value for EMAIL if case-sensitive
GCP identity in the iam-policy case-sensitive while the value returned by `$(gcloud config get-value account)` is not. If a user has capital letters their email address,  `kftl.sh apply platform` will result in an incorrect rbac `--user` assignment. 

To ensure that Kubeflow uses the correct `EMAIL` value for RBAC and IAM bindings, I recommend using the iam-policy value for `EMAIL` when it it contains capital letters. 

Pull request forthcoming.

### PR DESCRIPTION
**Pull request by IMBurbank**
Fixes #1936  

Modify `kfctl.createEnv` to check for a case-mismatch between the `EMAIL` value provided by `$(gcloud config get-value account)` and the value in the iam-policy, and to use the iam-policy value in the case of a mismatch.

---
This change is [Reviewable](https://reviewable.io/reviews/kubeflow/kubeflow/1937)

### CODE REVIEW

**Comment by IMBurbank** [comment]
This PR passed presubmit checks a few days ago, but is beginning to go stale sitting unmerged. The first branch conflict just arose today.

Is there anything else I can do to help this PR through?

**Comment by abhi-g** [comment]
Sorry about the delay. 

/lgtm

**Comment by abhi-g** [comment]
@IMBurbank Can you please update by merging master.

**Comment by IMBurbank** [comment]
No problem, and thank you for the response. 

Another PR moved the `$EMAIL` assignment from the `createEnv` function to `parseArgs`. I moved this iam-policy check into `parseArgs` accordingly.

**Pull request merged**
