### PR TITLE
Update Makefile to not build with `-i`

### PR DESCRIPTION
**Pull request by saschagrunert**
The -i flag should not be needed and will cause issues  on read-only `$GOROOT` paths.

---
This change is [Reviewable](https://reviewable.io/reviews/kubeflow/kubeflow/3700)

### CODE REVIEW

**Comment by yanniszark** [comment]
/lgtm
/approve
/hold

@saschagrunert there seems to be conflicts with the master branch.
Can you rebase to resolve them so we can get this in?

**Comment by saschagrunert** [comment]
Rebased on top of the latest master branch.

**Comment by gabrielwen** [comment]
conflicts again..  could you resolve it again and ping back,  promise this time you don't need to wait :)

**Comment by saschagrunert** [comment]
> conflicts again.. could you resolve it again and ping back, promise this time you don't need to wait :)

Thanks, I rebased on top of the master and removed further `-i`s. :)

**Pull request merged**
