### PR TITLE
use tf serving image

### LINKED ISSUE #1299: Use tensorflow/serving images
https://hub.docker.com/r/tensorflow/serving/

We can retire some infra for building and releasing those images.

### PR DESCRIPTION
**Pull request by lluunn**
Fix #1299 

This change is [Reviewable](https://reviewable.io/reviews/kubeflow/kubeflow/1370)

### CODE REVIEW

**Comment by lluunn** [comment]
The error shows:
`2018-08-15 21:27:10.359292: I tensorflow_serving/model_servers/main.cc:157] Building single TensorFlow model file config: model_name: model model_base_path: /models/model`

**Comment by lluunn** [comment]
https://github.com/tensorflow/serving/blob/master/tensorflow_serving/tools/docker/Dockerfile#L39

It should be cause of /models/model and model

**Comment by lluunn** [comment]
Fixed the command, now gpu test passed, but cpu one failed.
`
Unavailable: Error executing an HTTP request: libcurl code 77 meaning 'Problem with the SSL CA cert (path? access rights?)', error details: error setting certificate verify locations:
CAfile: /etc/ssl/certs/ca-certificates.crt
CApath: none
when reading metadata of gs://kubeflow-examples-data/mnist
`

https://pantheon.corp.google.com/logs/viewer?project=kubeflow-ci&minLogLevel=0&expandAll=false&timestamp=2018-08-16T22:24:54.157000000Z&customFacets=&limitCustomFacetWidth=true&dateRangeStart=2018-08-16T21:26:21.311Z&dateRangeEnd=2018-08-16T22:26:21.311Z&interval=PT1H&resource=container%2Fcluster_name%2Fkubeflow-testing&scrollTimestamp=2018-08-16T22:03:20.000000000Z&advancedFilter=resource.type%3D%22container%22%0Aresource.labels.cluster_name%3D%22kubeflow-testing%22%0Aresource.labels.namespace_id%3D%22kubeflow-presubmit-tf-serving-image-1370-1226108-2992-25fc%22%0AlogName%3D%22projects%2Fkubeflow-ci%2Flogs%2Fmnist-cpu%22

**Comment by lluunn** [comment]
1.8 works. https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/pr-logs/pull/kubeflow_kubeflow/1370/kubeflow-presubmit/2993/

Trying 1.9.1

**Comment by lluunn** [comment]
1.9.1 has the same error:
```
E  2018-08-16 23:22:04.397044: I external/org_tensorflow/tensorflow/core/platform/cloud/retrying_utils.cc:77] The operation failed and will be automatically retried in 32.177 seconds (attempt 7 out of 10), caused by: Unavailable: Error executing an HTTP request: libcurl code 77 meaning 'Problem with the SSL CA cert (path? access rights?)', error details: error setting certificate verify locations:
 
E    CAfile: /etc/ssl/certs/ca-certificates.crt
 
E    CApath: none
 
E  	 when reading metadata of gs://kubeflow-examples-data/mnist
 ```

**Comment by activatedgeek** [comment]
Interesting! Thanks for going through the pain. Are we finalizing on 1.8 cpu and 1.10 for gpu?

**Comment by lluunn** [comment]
I filed the issue in tensorflow serving for 1.9.1 and 1.10.0.
We can use 1.9 or 1.10 later when that's resolved.

**Comment by activatedgeek** [comment]
Ok sounds good.

/lgtm
/approve

**Pull request merged**
