### PR TITLE
Changed default kubeflow repo version to v0.6.0

### PR DESCRIPTION
**Pull request by nihir27**
This change is [Reviewable](https://reviewable.io/reviews/kubeflow/kubeflow/3731)

### CODE REVIEW

**Comment by nihir27** [comment]
I signed it!

**Comment by kunmingg** [comment]
/hold
Next version we are going to release is `v0.6.1`
So default version should point to like `v0.6.1-rc`?

**Comment by kunmingg** [comment]
@zhenghuiwang 
We might need to update version to `v0.6.1-rcX` before v0.6.1 cut.

**Comment by zhenghuiwang** [comment]
/hold
Let me create the v0.6.1-rc.0 tag, which you can point to.

**Comment by zhenghuiwang** [comment]
/hold cancel

Can you change the version to [v0.6.1-rc.0](https://github.com/kubeflow/kubeflow/releases/tag/v0.6.1-rc.0)?

**Pull request closed without merging**
