### PR TITLE
bootstrapper release workflow

### PR DESCRIPTION
**Pull request by kunmingg**
For https://github.com/kubeflow/kubeflow/issues/781.
Done with prototype in https://github.com/kubeflow/kubeflow/pull/948

---
This change is [Reviewable](https://reviewable.io/reviews/kubeflow/kubeflow/960)

### CODE REVIEW

**Comment by kunmingg** [comment]
/hold
Wait https://github.com/kubeflow/kubeflow/pull/951, which format build_image.sh.

**Comment by johnugeorge** [comment]
@kunmingg How do we specify build_image.sh location to the automation workflow?  https://github.com/kubeflow/kubeflow/blob/master/kubeflow/automation/release.libsonnet#L78 fixes the imageDir to be /kubeflow/kubeflow/components/k8s-model-server/images.  Doesn't it point to the build_image.sh of the bootstrapper?

**Comment by kunmingg** [comment]
@johnugeorge Thanks for reviewing my code! Will fix this bug asap.

**Comment by jlewi** [comment]
@kunmingg Ping?

**Comment by kunmingg** [comment]
@jlewi Will resume regular release once we had necessary backend server logics available.

**Comment by jlewi** [comment]
@kunmingg Is this PR still relevant? If it is it probably needs to be refactored as we've overhauled our release image process to allow pushing the images on postsubmit see
https://github.com/kubeflow/kubeflow/blob/master/docs_dev/releasing.md#image-auto-release

**Comment by kunmingg** [comment]
@jlewi 
Yeah seems this one is out of date by a lot, will adapt to new rules.

**Comment by jlewi** [comment]
@kunmingg I'm going to ahead and close this on the assumption it is out of date.

**Pull request closed without merging**
