### PR TITLE
fixes 'add kustomize support to kfctl'

### PR DESCRIPTION
**Pull request by kkasravi**
fixes 
- [x] #2445 Add kustomize support to kfctl
- [x] #2561 Move ksonnet, kustomize implementations out of KfApps.Children
- [x] #2560 Add a show command
- [x] #2635 kfctl - provide option (default) to statically link ksonnet and kustomize into kfctl 
- [x] #2642 kfctl error in application component
- [x] #2646 kfctl allow the --version CLI to include PR's
- [x] #2670 kfctl could not generate kfApp no hostname

---
This change is [Reviewable](https://reviewable.io/reviews/kubeflow/kubeflow/2673)

### CODE REVIEW

**Comment by jlewi** [comment]
/lgtm
/approve
/hold
hold for @lluunn 
@llun does this look good to you?

**Comment by lluunn** [comment]
have some questions, see my previous comment

**Comment by lluunn** [comment]
/lgtm
/hold cancel
thanks

**Pull request merged**
