### PR TITLE
Update notebook server base images

### PR DESCRIPTION
**Pull request by DavidSpek**
Small update for the base images of each server type.

/cc @kubeflow/wg-notebooks-leads

### CODE REVIEW

**Comment by DavidSpek** [comment]
@kimwnasptd Can you quickly `lgtm` this so I can continue with the downsteam images?

**Comment by kimwnasptd** [comment]
Sure! We will also need to start discussing our long term plan for how to manage the base image tag.

@DavidSpek could you start and issue for this with some proposed next steps so we could start iterating on?

**Comment by DavidSpek** [comment]
@kimwnasptd I'll create an issue for this soon. What is actually blocking this effort is the fact that the ECR public gallery doesn't have a public API endpoint that lists the latest image tags, making it incompatible with basically any dependency automation tool. See: https://github.com/aws/containers-roadmap/issues/1262. I've contacted @rarkins from Renovate about this already, but I think we'd need to get in touch with somebody from AWS to fix this as well. Another option would be to not use ECR, which by default has the same type of user pull rate limiting as dockerhub. FYI, dockerhub has a process to remove the rate limiting for open-source projects (for clarity, the repo isn't limited but rather anonymous pulls, but this can be disabled).

**Comment by kimwnasptd** [comment]
Thanks for the update @DavidSpek! Lets iterate more on our options on your new issue then.

/lgtm
/approve

**Pull request merged**
