### PR TITLE
switch test zone to us-east1-c

### PR DESCRIPTION
**Pull request by kunmingg**
us-east1-d has VM shortage.

---
This change is [Reviewable](https://reviewable.io/reviews/kubeflow/kubeflow/2583)

### CODE REVIEW

**Comment by lluunn** [comment]
our testing cluster is still in east1-d, is that ok?

**Comment by jlewi** [comment]
/test all

It looks like it was TFJob on minikube test that failed.

**Comment by kunmingg** [comment]
Zone us-east1-d VM shortage seems recovered

**Comment by jlewi** [comment]
@kunmingg Should we close this then or merge it anyway?

**Comment by kunmingg** [comment]
@jlewi close it for now as the problem is gone.

**Pull request closed without merging**
