### PR TITLE
Create test_flake8.py

### PR DESCRIPTION
**Pull request by cclauss**
As @pdmack requested at https://github.com/kubeflow/kubeflow/pull/2240#issuecomment-452480317 this file is a flake8 check for pre-submits.

---
This change is [Reviewable](https://reviewable.io/reviews/kubeflow/kubeflow/2247)

### CODE REVIEW

**Comment by jlewi** [comment]
/assign @jlewi 

Could you add it to the Argo workflow for unittests so that it will run on presubmit and postsubmit?
https://github.com/kubeflow/kubeflow/blob/master/testing/workflows/components/unit_tests.jsonnet

**Comment by cclauss** [comment]
Unfortunately I have been unable to figure out how to add this test to the Argo workflow as requested.

**Comment by jlewi** [comment]
Thanks. Created #2388 with some pointers if you're interested.

/lgtm
/approve

**Comment by cclauss** [comment]
Bump on this one.

**Comment by jlewi** [comment]
@cclauss Can you sign the CLA please and the CLA check to pass by following the instructions posted by googlebot?

**Comment by cclauss** [comment]
[__googlebot__](/googlebot) added the [cla: yes](/kubeflow/kubeflow/labels/cla%3A%20yes) label [on Jan 9](#event-2062176953)

**Comment by jlewi** [comment]
@cclauss you added new commits and the CLA check is no longer passing (this can happen if the author isn't set correctly on the latest commits).

I would suggest rebasing and squashing the commits.

/test all

**Pull request merged**
