### PR TITLE
Common code between the different python backends

### PR DESCRIPTION
**Pull request by kimwnasptd**
Right now JWA's backend is written in Python Flask. We also have the [Tensorboards web app](https://github.com/kubeflow/kubeflow/issues/3578) whose backend will also be written in Python and Flask. Lastly, the [Volumes web app](https://github.com/kubeflow/kubeflow/issues/4758), that we'd like to contribute, will be also written with the same technologies.

I think it would be a good next step to create a common python codebase/library that all these apps could use, at some extend. This common code will include:
* How we handle exceptions in the backend
* Common routes for serving static files and their cache control policy
* Authorization checks with SubjectAccessReview
* Authentication checks on the Kubeflow headers
* Common helper functions for dates, yaml parsing etc
* health/liveness probes

I have prepared this code while working on the Volumes web app and it's the first step towards pushing the backend code upstream. It would also help our running [GSoC project with Tensorboard](https://summerofcode.withgoogle.com/projects/#4660815581413376) as the backend could use a lot of this common code. The Jupyter web app should also gradually use this code.

I'm also adding @kandrio98 to the loop since this affects his GSoC project as well as to get him more exposed to our review process.

@jlewi if you have a better candidate in mind for reviewing this PR let me know

/cc @jlewi 
/assign @kimwnasptd

### CODE REVIEW

**Comment by jlewi** [comment]
@kimwnasptd Who else will be owning and maintaining this code? They should be the ones reviewing it.

What about @StefanoFioravanzo and what about @lalithvaka

**Comment by StefanoFioravanzo** [comment]
@jlewi I think you are suggesting creating an OWNERS file for the `py/` directory? It would definitely make sense since we have are going to rely heavily on this code for various applications. It's ok for me to be part of that file, @elikatsis as well is involved in the development of this common code. We could start with us + @kimwnasptd being part of the OWNERS

**Comment by jlewi** [comment]
What project or application is this code for? Please open up a separate PR creating an appropriate directory with an OWNERs file. The OWNERs should indicate who will be responsible for reviewing and maintaining this code. 

If this code is primarily for the jupyter web app, why not put it in
https://github.com/kubeflow/kubeflow/blob/master/components/jupyter-web-app/OWNERS

**Comment by kimwnasptd** [comment]
@jlewi this will be common backend code between the jupyter web app, tensorboards web app and the volumes web app.

The jupyter web app will start using the common code more gradually over time, but the tensorboards and volumes web apps will be using this common code out of the box.

**Comment by jlewi** [comment]
Can we structure the code so that all code lives under an appropriate project directory with a suitable OWNERs file that indicates who is responsible for this project.

All projects will need to find WG sponsorship or they will be archived. Ownership of the projects and boundaries should be clearly delineated by directory structure and OWNERs files.

**Comment by kimwnasptd** [comment]
@jlewi since this will be common code for different projects, what structure do you think would fit best here?

For the approvers/reviewers we could add @StefanoFioravanzo @elikatsis and I. Once we decide on where this code should be placed I'll create a new small PR just for adding the OWNERS file in the agreed place[s].

**Comment by jlewi** [comment]
@kimwnasptd I think my comment above applies.

> Can we structure the code so that all code lives under an appropriate project directory with a suitable OWNERs file that indicates who is responsible for this project.

So pick an appropriate directory to serve as the parent directory for all the web apps that you will be developing. Put an OWNERs file there to indicate clear ownership and then organize the code under that.

**Comment by kimwnasptd** [comment]
I updated the code to live under the `crud-web-apps` directory.

@elikatsis @StefanoFioravanzo take a look when when you have the time. I'll be on PTO for the next couple weeks so I won't be able to respond frequently during that time, but I'll try to answer any questions that might come up.

/cc @elikatsis 
/cc @StefanoFioravanzo 
/uncc @jlewi

**Pull request merged**
