### PR TITLE
make click-deploy-test upload junit artifacts

### PR DESCRIPTION
**Pull request by lluunn**
- The test was not producing any junit and thus not shown on testgrid.
- Also added some logging.
- Fix some bugs

https://github.com/kubeflow/testing/issues/301
https://github.com/kubeflow/kubeflow/issues/2364

/cc @kunmingg 
/cc @jlewi

---
This change is [Reviewable](https://reviewable.io/reviews/kubeflow/kubeflow/2437)

### CODE REVIEW

**Comment by lluunn** [comment]
/hold
testing

**Comment by kunmingg** [comment]
/lgtm
/approve
Thanks!

**Comment by lluunn** [comment]
test failure is out of disk quota

**Comment by lluunn** [comment]
https://github.com/kubeflow/kubeflow/issues/2401

**Pull request merged**
