### PR TITLE
Addresses issue while merging multiple PatchesJson6902 targets with same path file in MergeKustomization

### LINKED ISSUE #4247: Issue while merging PatchesJson6902 multiple targets with same path file in MergeKustomization
/kind bug

**What steps did you take and what happened:**
Issue is extension of #4136 
Added overlay to update multiple ClusterRoles(eg: argo and argo-ui) using PatchesJson6902 using same target.path file 
```
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
bases:
- ../../base
patchesJson6902:
- target:
    group: rbac.authorization.k8s.io
    version: v1beta1
    kind: ClusterRole
    name: argo
  path: patch.yaml
- target:
    group: rbac.authorization.k8s.io
    version: v1beta1
    kind: ClusterRole
    name: argo-ui
  path: patch.yaml
```
patch.yaml content is as below
```
- op: add
  path: /rules/0
  value:
    apiGroups:
      - extensions
    resourceNames:
      - privileged
    resources:
      - podsecuritypolicies
    verbs:
      - use
```

**What did you expect to happen:**
After kfctl generate I was expecting two patch files argo-ClusterRole.yaml & argo-ui-ClusterRole.yaml will get created with proper patch link in new kustomization.yaml(kustomize is patching two clusterroles with content from patch.yaml) where as kfctl is ignoring 2nd clusterrole

**Anything else you would like to add:**
I could see problem in these lines - **not  sure whether this was done intentionally!**
https://github.com/kubeflow/kubeflow/blob/2395c5fc0d384cf6dd4d7167bbe9010cd1315b54/bootstrap/pkg/kfapp/kustomize/kustomize.go#L851
```
		if _, ok := kustomizationMaps[patchesJson6902Map][patchJson.Path]; !ok {
			parent.PatchesJson6902 = append(parent.PatchesJson6902, *patchJson)
			kustomizationMaps[patchesJson6902Map][patchJson.Path] = true
		}
```

**Environment:**

- Kubeflow version: build version v0.6.2
- kfctl version: kfctl v0.6.2-0-g47a0e4c7
- Kubernetes platform: k8s cluster
- Kubernetes version: 
```
Client Version: version.Info{Major:"1", Minor:"14", GitVersion:"v1.14.3", GitCommit:"5e53fd6bc17c0dec8434817e69b04a25d8ae0ff0", GitTreeState:"clean", BuildDate:"2019-06-06T01:44:30Z", GoVersion:"go1.12.5", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"14", GitVersion:"v1.14.3", GitCommit:"5e53fd6bc17c0dec8434817e69b04a25d8ae0ff0", GitTreeState:"clean", BuildDate:"2019-06-06T01:36:19Z", GoVersion:"go1.12.5", Compiler:"gc", Platform:"linux/amd64"}
```
- OS :
```
NAME="CentOS Linux"
VERSION="7 (Core)"
ID="centos"
ID_LIKE="rhel fedora"
VERSION_ID="7"
PRETTY_NAME="CentOS Linux 7 (Core)"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:centos:centos:7"
HOME_URL="https://www.centos.org/"
BUG_REPORT_URL="https://bugs.centos.org/"

CENTOS_MANTISBT_PROJECT="CentOS-7"
CENTOS_MANTISBT_PROJECT_VERSION="7"
REDHAT_SUPPORT_PRODUCT="centos"
REDHAT_SUPPORT_PRODUCT_VERSION="7"
```

### PR DESCRIPTION
**Pull request by hemantha-kumara**
Resolves #4247 
Handled multiple PatchesJson6902 targets with same path file in kustomize

---
This change is [Reviewable](https://reviewable.io/reviews/kubeflow/kubeflow/4260)

### CODE REVIEW

**Comment by kkasravi** [comment]
@hemantha-kumara great work!

We also need to append each patch into the local patch file (beginning at line 956)
Could I ask you to add this change as well?

```
			for _, eachPatch := range values {
				patchPath := path.Join(compDir, eachPatch.Path)
				if _, err := os.Stat(patchPath); err == nil {
					data, err := ioutil.ReadFile(patchPath)
					if err != nil {
						return nil, err
					}
					f, patchErr := os.OpenFile(patchFile, os.O_APPEND|os.O_CREATE|os.O_WRONLY, 0644)
					if patchErr != nil {
						return nil, patchErr
					}
					if _, err := f.Write(data); err != nil {
						f.Close()
						return nil, err
					}
					if err := f.Close(); err != nil {
						return nil, err
					}
				}
			}
```

**Comment by hemantha-kumara** [comment]
> We also need to append each patch into the local patch file (beginning at line 956)
> Could I ask you to add this change as well?
> 
@kkasravi Sorry, I was away due to some personal work. Now I have repushed changes as suggested. Please do check and let me know if any other changes are required.

**Comment by kkasravi** [comment]
thanks @hemantha-kumara 
/lgtm
/approve

**Comment by kkasravi** [comment]
@htreemantha-kumara could I ask you to rebase from master?
I believe a recent change merged to master is causing the failure when checking if kfctl deployed successfully

git fetch upstream master
git rebase -i upstream/master
git commit -a -m "rebase from upstream/master"
git push

**Comment by hemantha-kumara** [comment]
> @hemantha-kumara could I ask you to rebase from master?
Yes, rebased and now presubmit job is passed.

**Comment by kkasravi** [comment]
@hemantha-kumara thank you for keeping after this
/lgtm

**Comment by kkasravi** [comment]
@hemantha-kumara merged!

**Pull request merged**
