### PR TITLE
Facilitate specifying seperate requests and limits

### PR DESCRIPTION
**Pull request by wmuizelaar**
When starting the jupyter notebook pods, it is good to also be able to
specify limits and not just only requests.

---
This change is [Reviewable](https://reviewable.io/reviews/kubeflow/kubeflow/1028)

### CODE REVIEW

**Comment by ankushagarwal** [comment]
Hi @wmuizelaar 

I am not sure if adding a limit to the UI is a very good idea. Firstly it adds the overhead of explaining to users what the difference b/w request and limit is - it is not very obvious for users who are not k8s experts. Even after that, for a compute and memory intensive pod like a jupyter notebook it is very hard for a user to estimate "after how much memory consumption should my pod be OOM killed".

**Comment by wmuizelaar** [comment]
@ankushagarwal yes - in the clusters we have running, we have a default limitrange set in place, with default request and limit values. 

If you then start a notebook with for example 4 CPU's as a request, but your default limit is set to 1 CPU, then the pod doesn't start, and you will get a nice red warning that the pod cannot be scheduled.

But I agree that it gives extra overhead in explaining. Maybe hide it behind a feature-flag?

**Comment by ankushagarwal** [comment]
Hiding behind a feature flag SGTM. 

1. Can you add a [tooltip](https://jqueryui.com/tooltip/) to the fields which explains what Limit and Request is
2. Can you update the logic so that when the Limit fields are empty, limits are not set for the Pods

**Comment by jlewi** [comment]
@wmuizelaar Any interest in updating the PR to address comments? If not we'll close it out.

**Comment by wmuizelaar** [comment]
Yes, I want to update the PR! Have been out of office for a bit, but please leave this open.

Thanks,
Wietse

Sent from my iPhone

On 27 Jul 2018, at 6:52 AM, Jeremy Lewi <notifications@github.com<mailto:notifications@github.com>> wrote:


@wmuizelaar<https://github.com/wmuizelaar> Any interest in updating the PR to address comments? If not we'll close it out.

**Comment by ankushagarwal** [comment]
Closing this because of lack of activity

**Pull request closed without merging**
