### PR TITLE
Add Kubebench releaser

### LINKED ISSUE #1510: Release process for kubebench
We needed some help with packaging Kubebench for releasing (related issue on Kubebench repo: issue https://github.com/kubeflow/kubebench/issues/88):

1. We are following the instructions at https://github.com/kubeflow/kubeflow/blob/master/docs_dev/releasing.md. Are these the correct instructions to follow?
2. We currently have 4 Dockerfiles for the Kubebench repo - 1 controller and 3 per benchmark (currently, just the tf-cnn benchmark exists). They can be found here: https://github.com/kubeflow/kubebench/tree/master/build/images. 
**MUST we have a single Dockerfile** that will be called via the build_image.sh file in the kubebench repo (we are yet to add that .sh file) or can we have multiple Dockerfiles?
3. How do we test the packaging code?

@xyhuang @johnugeorge

### PR DESCRIPTION
**Pull request by xyhuang**
This adds Kubebench to the auto releaser with 2 components:

- kubebench-controller: builds the image for the controller
- kubebench-examples: builds multiple images for all kubebench examples

Fix #1510 

---
This change is [Reviewable](https://reviewable.io/reviews/kubeflow/kubeflow/1538)

### CODE REVIEW

**Comment by kunmingg** [comment]
/lgtm
/approve

Please check after PR merge and see if images got released regularly.
Thanks!

**Comment by kunmingg** [comment]
@xyhuang Can you try rebase and update PR?

**Comment by xyhuang** [comment]
thanks @kunmingg rebased.

**Comment by kunmingg** [comment]
@xyhuang 
We had a update on release workflow:
https://github.com/kubeflow/kubeflow/pull/1565

**Comment by xyhuang** [comment]
closing this as the release process has been revamped and we have created releaser according to the new process.

**Pull request closed without merging**
