### PR TITLE
"argo" should be "Argo"

### PR DESCRIPTION
**Pull request by suigh**
"argo" should be "Argo"  in some messages.

---
This change is [Reviewable](https://reviewable.io/reviews/kubeflow/kubeflow/2099)

### CODE REVIEW

**Comment by pdmack** [comment]
You may want to try rebasing. I believe there have been some recent testing-related changes.

**Comment by suigh** [comment]
#2168 was logged to re-submit the change with newest change. Seems this build error is because the conflict with #2107.

**Comment by suigh** [comment]
Thanks for pdmack's reminder.

**Pull request closed without merging**
