### PR TITLE
Add thesuperzapper to notebook OWNERS

### PR DESCRIPTION
**Pull request by thesuperzapper**
Since I am one of the leads of the Notebook Working Group, it would be helpfully if I could approve PRs.

As an example, PR #5332 is blocked by me not being able to review it right now.

### CODE REVIEW

**Comment by thesuperzapper** [comment]
@kimwnasptd can you please review this PR?

**Comment by kimwnasptd** [comment]
@thesuperzapper happy deving :)

/lgtm
/approve

**Pull request merged**
