### PR TITLE
Kfctl switch packagemanagers

### LINKED ISSUE #2445: Add kustomize support to kfctl
Doc:
http://bit.ly/2RwMP8q

The immediate need is kfctl(go) needs to support installing ISTIO see #2052.
We currently install ISTIO using its YAML manifest. 
We could either add support to kfctl for installing YAML or we could just 

1. Add support for kustomize
1. Turn YAML manifests into kustomize packages by adding kustomize files 

To add support for kustomize we need to implement the KfApp interface for kustomize
https://github.com/kubeflow/kubeflow/tree/master/bootstrap/cmd/kfctl#kfapp-interface

See also #2351

### PR DESCRIPTION
**Pull request by kkasravi**
Implementation of kustomize. See [First Class Support for Kustomize Packages In Kubeflow](https://docs.google.com/document/d/156H79GiQ-gCAputHzcCdmD6gZZaMBLqC-kzwKqc2MIA/edit#heading=h.c4khqss4mjzp)

fixes #2445, #2566, #2568, #2599, #2629, #2911 

paired with [kubeflow/manifests/#13](https://github.com/kubeflow/manifests/pull/13)

The kustomize package manager will read its app.yaml and apply the packages, components and componentParams to kustomize in the following way:

- packages are always top-level directories under the manifests repo
- all components are also directories but may be a subdirectory in a package.
  - components may be a top-level directory if there is a base, overlay in that directory and the component name is equal to the package name. 
  - otherwise a component is a sub-directory whose name matches the component name in app.yaml.
- component parameters are applied to a component's params.env file which must contain an entry whose key matches the component parameter. The params.env file is used to generate a ConfigMap. Entries in params.env are resolved as kustomize vars or referenced in a deployment or statefulset env section.
- components are output as `<component>.yaml` under the kustomize subdirectory after `kfctl generate...`. 

---
This change is [Reviewable](https://reviewable.io/reviews/kubeflow/kubeflow/2971)

### CODE REVIEW

**Comment by kkasravi** [comment]
A few runtime errors remaining that I'll be able to correct by Monday

- ImagePullBackOff
  Deployment: centraldashboard
  Reason	
  Cannot pull image 'gcr.io/kubeflow-images-public/centraldashboard:0.5.0' from the registry.
- PodUnschedulable
Deployment: minio
Reason	
Cannot schedule pods: persistentvolumeclaim "minio-pvc" not found.
- PodUnschedulable
Deployment: mysql
Reason	
Cannot schedule pods: persistentvolumeclaim "mysql-pv-claim" not found.

**Comment by kkasravi** [comment]
@jlewi I think this is stable enough to go in. I'll open separate issues based on this for subsequent improvements.

**Comment by jlewi** [comment]
/lgtm
/approve

I think we should follow up on the dynamic creation of the Application resource; #3047

**Comment by jlewi** [comment]
PR to keep Argo test results longer should be merged so hopefully on next test run test failures won't be deleted.

/test all

Not sure why the CLA check is failing.

**Comment by jlewi** [comment]
Woo Hoo!
/lgtm
/approve

**Pull request merged**
