### PR TITLE
Fix notebook controller for virtual service

### LINKED ISSUE #3387: notebook-controller deployment fails with CrashLoopBackOff when --use_basic_auth --use_istio=false
notebook-controller assumes a virtualservice is available 
https://github.com/kubeflow/kubeflow/blob/master/components/notebook-controller/pkg/controller/notebook/notebook_controller.go#L97

and should take an environment variable setting to see if watching the VirtualService is needed

### PR DESCRIPTION
**Pull request by gabrielwen**
Fixes #3387

Skip watching and reconcile for virtual services if not using ISTIO.

---
This change is [Reviewable](https://reviewable.io/reviews/kubeflow/kubeflow/3393)

### CODE REVIEW

**Comment by lluunn** [comment]
thanks!
/lgtm
/approve

**Comment by kunmingg** [comment]
manual merge to unblock follow up PRs.
prow seems not responding.

**Comment by gabrielwen** [comment]
thanks for the help :)

**Pull request merged**
