### PR TITLE
Add prow config for new notebook servers

### PR DESCRIPTION
**Pull request by DavidSpek**
After realizing that @Bobgy would need to approve each of the PRs for the new notebook images due to the `prow_config.yaml` being edited, I thought it would be best to move those changes to a dedicated PR so @thesuperzapper and I can work more quickly when merging the notebook image PRs. 

@kimwnasptd can you also read over this quickly, as it is essential for being able to move fast with the other PRs and getting the images built.

### CODE REVIEW

**Comment by kimwnasptd** [comment]
@DavidSpek I was just thinking about the same think and was about to create an issue! I completely agree on this approach, as it will both help decouple the effort of merging the Dockerfiles and working on the tests.

I'll also be keeping an eye in the PRs and try to also bring up any points wrt the CI/CD here as well.

Thank you for opening the PR!

**Comment by Bobgy** [comment]
/approve
/hold
You can decide when to merge by yourselves.

Thank you for saving me efforts!

**Comment by DavidSpek** [comment]
@kimwnasptd Can this be merged? Then I can get started with rebasing and fixing Notebook PRs for this.

**Comment by kimwnasptd** [comment]
@DavidSpek just to make sure, will merging this PR now give us any trouble for merging the following notebook PRs?

My concern is about triggering tests for the Notebooks if the base would be modified. In that case, since the files for the other Notebooks would be missing we wouldn't be able to merge the first PR [ which is for the base Notebook image I assume? ]. But looking at the modified yaml the jobs for the other Notebooks don't run when the base is changes so we should be good.

**Comment by DavidSpek** [comment]
@kimwnasptd Indeed that should not be a problem. All the image builds are setup to only run when that image itself is changed (this method would tie in nicely with Renovate because of this). Merging this should not cause any problems. However, I am continuously monitoring the prow dashboard so if something unexpected happens I'll quickly create a PR to fix it.

**Comment by kimwnasptd** [comment]
Thanks for confirming. Lets move on with this PR and if something is different from our current best understanding we can come back and reiterate.

/lgtm
/approve

**Pull request merged**
