### PR TITLE
add support for azure auth provider

### LINKED ISSUE #3759: kfctl apply failes with No Auth Provider found for name "azure"
I'm trying to apply Kubeflow `v.0.6.0` in our cluster, and it failes with the following error:

```
$ kfctl apply all -V
INFO[0000] Downloading /home/user/workspace/kubeflow/app.yaml to /tmp/455975017/app.yaml  filename="v1alpha1/application_types.go:334"
INFO[0000] Writing stripped KfDef to /home/user/workspace/kubeflow/app.yaml  filename="v1alpha1/application_types.go:626"
INFO[0000] Downloading /home/user/workspace/kubeflow/app.yaml to /tmp/812831412/app.yaml  filename="v1alpha1/application_types.go:334"
INFO[0000] Initializing a default restConfig for Kubernetes  filename="kustomize/kustomize.go:248"
FATA[0000] Can not get kubernetes kfdef: No Auth Provider found for name "azure"  filename="apps/group.go:262"
```

We use Azure/AD to connect/login to the cluster, and if I create a user that authenticates with a token instead (of my regular user) it all works. 

I assume the problem is that `kfctl` is missing support for azure as an `oidc` flow. 

There has been a short disuccion on [slack](https://kubeflow.slack.com/archives/C7REE0EHK/p1564132253111500).

### PR DESCRIPTION
**Pull request by yeya24**
Signed-off-by: yeya24 <yb532204897@gmail.com>
fix #3759

---
This change is [Reviewable](https://reviewable.io/reviews/kubeflow/kubeflow/3881)

### CODE REVIEW

**Comment by gabrielwen** [comment]
/approve

will lgtm after you resolve the conflict.

**Comment by yeya24** [comment]
> /approve
> 
> will lgtm after you resolve the conflict.

Thanks! I updated it just now.

**Comment by yeya24** [comment]
@gabrielwen  Do you know how to fix ci? I believe this is unrelated.

**Comment by Kyrremann** [comment]
@yeya24 I tried to build the changes locally with `make build-kfctl` and got the following error:
```
...
pkg/utils/k8utils.go
# k8s.io/client-go/plugin/pkg/client/auth/azure
../../go/pkg/mod/k8s.io/client-go@v0.0.0-20190228174230-b40b2a5939e4/plugin/pkg/client/auth/azure/azure.go:247:4: cannot use json.Number(expiresIn) (type json.Number) as type string in field value
../../go/pkg/mod/k8s.io/client-go@v0.0.0-20190228174230-b40b2a5939e4/plugin/pkg/client/auth/azure/azure.go:248:4: cannot use json.Number(expiresOn) (type json.Number) as type string in field value
../../go/pkg/mod/k8s.io/client-go@v0.0.0-20190228174230-b40b2a5939e4/plugin/pkg/client/auth/azure/azure.go:249:4: cannot use json.Number(expiresOn) (type json.Number) as type string in field value
../../go/pkg/mod/k8s.io/client-go@v0.0.0-20190228174230-b40b2a5939e4/plugin/pkg/client/auth/azure/azure.go:301:25: cannot call non-function spt.Token (type adal.Token)
```
Have you seen something similar?

**Comment by yeya24** [comment]
@Kyrremann  Sorry about that, I will update the dependency in this PR

**Comment by yeya24** [comment]
@Kyrremann @lijo050 Can you test it againt? Thanks! I have tested in my local env with `make build-kfctl`

**Comment by Kyrremann** [comment]
@yeya24 I tried again, and it didn't work. First I had trouble with `GOROOT`, had to specify my version, or else I ended up with the following error:
```
$ make build-kfctl
/Users/kyrremann/workspace/nav/go/bin/deepcopy-gen -i github.com/kubeflow/kubeflow/bootstrap/v3/pkg/apis/apps/kfdef/... -O zz_generated.deepcopy && \
	mv /Users/kyrremann/workspace/nav/go/src/github.com/kubeflow/kubeflow/bootstrap/v3/pkg/apis/apps/kfdef/v1alpha1/zz_generated.deepcopy.go pkg/apis/apps/kfdef/v1alpha1/ && rm -rf v3
W0924 08:04:56.989314   65324 parse.go:223] Ignoring directory github.com/kubeflow/kubeflow/bootstrap/v3/pkg/apis/apps/kfdef: unable to import "github.com/kubeflow/kubeflow/bootstrap/v3/pkg/apis/apps/kfdef": go/build: importGo github.com/kubeflow/kubeflow/bootstrap/v3/pkg/apis/apps/kfdef: exit status 2
go: cannot find GOROOT directory: /usr/local/Cellar/go/1.12.4/libexec

panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x124c715]

goroutine 1 [running]:
k8s.io/gengo/parser.(*Builder).AddDirRecursive(0xc000013400, 0xc00001e140, 0x3d, 0x1, 0xc0000cdc88)
	/Users/kyrremann/workspace/nav/go/pkg/mod/k8s.io/gengo@v0.0.0-20180223161844-01a732e01d00/parser/parse.go:228 +0xb5
k8s.io/gengo/args.(*GeneratorArgs).NewBuilder(0xc0000b03c0, 0xc00005e580, 0x10, 0x28)
	/Users/kyrremann/workspace/nav/go/pkg/mod/k8s.io/gengo@v0.0.0-20180223161844-01a732e01d00/args/args.go:136 +0x229
k8s.io/gengo/args.(*GeneratorArgs).Execute(0xc0000b03c0, 0xc0000cde48, 0x13015e2, 0x6, 0x133c3c8, 0x0, 0x0)
	/Users/kyrremann/workspace/nav/go/pkg/mod/k8s.io/gengo@v0.0.0-20180223161844-01a732e01d00/args/args.go:182 +0x4d
main.main()
	/var/folders/rr/0x9q4tnj5cj4_fmr_2mr2hgw0000gn/T/tmp.pdY8q4Gw/cgen/cmd/deepcopy-gen/main.go:76 +0x410
make: *** [pkg/apis/apps/kfdef/v1alpha1/zz_generated.deepcopy.go] Error 2
```

After setting `GOROOT` it started building, but failed on finding a module:
```
$ make build-kfctl
/Users/kyrremann/workspace/nav/go/bin/deepcopy-gen -i github.com/kubeflow/kubeflow/bootstrap/v3/pkg/apis/apps/kfdef/... -O zz_generated.deepcopy && \
	mv /Users/kyrremann/workspace/nav/go/src/github.com/kubeflow/kubeflow/bootstrap/v3/pkg/apis/apps/kfdef/v1alpha1/zz_generated.deepcopy.go pkg/apis/apps/kfdef/v1alpha1/ && rm -rf v3
W0924 08:10:37.301088   65533 parse.go:238] Ignoring child directory github.com/kubeflow/kubeflow/bootstrap/v3/pkg/apis/apps/kfdef/testdata: unable to import "github.com/kubeflow/kubeflow/bootstrap/v3/pkg/apis/apps/kfdef/testdata": go/build: importGo github.com/kubeflow/kubeflow/bootstrap/v3/pkg/apis/apps/kfdef/testdata: exit status 1
go: finding github.com/kubeflow/kubeflow/bootstrap/v3/pkg/apis/apps/kfdef/testdata latest
go: finding github.com/kubeflow/kubeflow/bootstrap/v3/pkg/apis/apps/kfdef latest
go: finding github.com/kubeflow/kubeflow/bootstrap/v3/pkg/apis/apps latest
go: finding github.com/kubeflow/kubeflow/bootstrap/v3/pkg/apis latest
go: finding github.com/kubeflow/kubeflow/bootstrap/v3/pkg latest
go: finding github.com/kubeflow/kubeflow/bootstrap latest
go: finding github.com/kubeflow/kubeflow v0.6.2
go: downloading github.com/kubeflow/kubeflow v0.6.2
go: extracting github.com/kubeflow/kubeflow v0.6.2
can't load package: package github.com/kubeflow/kubeflow/bootstrap/v3/pkg/apis/apps/kfdef/testdata: unknown import path "github.com/kubeflow/kubeflow/bootstrap/v3/pkg/apis/apps/kfdef/testdata": cannot find module providing package github.com/kubeflow/kubeflow/bootstrap/v3/pkg/apis/apps/kfdef/testdata

F0924 08:10:37.473244   65533 deepcopy.go:126] Failed loading boilerplate: open /Users/kyrremann/workspace/nav/go/src/k8s.io/code-generator/hack/boilerplate.go.txt: no such file or directory
make: *** [pkg/apis/apps/kfdef/v1alpha1/zz_generated.deepcopy.go] Error 255
```

Are you building from `master`?

**Comment by yeya24** [comment]
> @yeya24 I tried again, and it didn't work. First I had trouble with `GOROOT`, had to specify my version, or else I ended up with the following error:
> 
> ```
> $ make build-kfctl
> /Users/kyrremann/workspace/nav/go/bin/deepcopy-gen -i github.com/kubeflow/kubeflow/bootstrap/v3/pkg/apis/apps/kfdef/... -O zz_generated.deepcopy && \
> 	mv /Users/kyrremann/workspace/nav/go/src/github.com/kubeflow/kubeflow/bootstrap/v3/pkg/apis/apps/kfdef/v1alpha1/zz_generated.deepcopy.go pkg/apis/apps/kfdef/v1alpha1/ && rm -rf v3
> W0924 08:04:56.989314   65324 parse.go:223] Ignoring directory github.com/kubeflow/kubeflow/bootstrap/v3/pkg/apis/apps/kfdef: unable to import "github.com/kubeflow/kubeflow/bootstrap/v3/pkg/apis/apps/kfdef": go/build: importGo github.com/kubeflow/kubeflow/bootstrap/v3/pkg/apis/apps/kfdef: exit status 2
> go: cannot find GOROOT directory: /usr/local/Cellar/go/1.12.4/libexec
> 
> panic: runtime error: invalid memory address or nil pointer dereference
> [signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x124c715]
> 
> goroutine 1 [running]:
> k8s.io/gengo/parser.(*Builder).AddDirRecursive(0xc000013400, 0xc00001e140, 0x3d, 0x1, 0xc0000cdc88)
> 	/Users/kyrremann/workspace/nav/go/pkg/mod/k8s.io/gengo@v0.0.0-20180223161844-01a732e01d00/parser/parse.go:228 +0xb5
> k8s.io/gengo/args.(*GeneratorArgs).NewBuilder(0xc0000b03c0, 0xc00005e580, 0x10, 0x28)
> 	/Users/kyrremann/workspace/nav/go/pkg/mod/k8s.io/gengo@v0.0.0-20180223161844-01a732e01d00/args/args.go:136 +0x229
> k8s.io/gengo/args.(*GeneratorArgs).Execute(0xc0000b03c0, 0xc0000cde48, 0x13015e2, 0x6, 0x133c3c8, 0x0, 0x0)
> 	/Users/kyrremann/workspace/nav/go/pkg/mod/k8s.io/gengo@v0.0.0-20180223161844-01a732e01d00/args/args.go:182 +0x4d
> main.main()
> 	/var/folders/rr/0x9q4tnj5cj4_fmr_2mr2hgw0000gn/T/tmp.pdY8q4Gw/cgen/cmd/deepcopy-gen/main.go:76 +0x410
> make: *** [pkg/apis/apps/kfdef/v1alpha1/zz_generated.deepcopy.go] Error 2
> ```
> 
> After setting `GOROOT` it started building, but failed on finding a module:
> 
> ```
> $ make build-kfctl
> /Users/kyrremann/workspace/nav/go/bin/deepcopy-gen -i github.com/kubeflow/kubeflow/bootstrap/v3/pkg/apis/apps/kfdef/... -O zz_generated.deepcopy && \
> 	mv /Users/kyrremann/workspace/nav/go/src/github.com/kubeflow/kubeflow/bootstrap/v3/pkg/apis/apps/kfdef/v1alpha1/zz_generated.deepcopy.go pkg/apis/apps/kfdef/v1alpha1/ && rm -rf v3
> W0924 08:10:37.301088   65533 parse.go:238] Ignoring child directory github.com/kubeflow/kubeflow/bootstrap/v3/pkg/apis/apps/kfdef/testdata: unable to import "github.com/kubeflow/kubeflow/bootstrap/v3/pkg/apis/apps/kfdef/testdata": go/build: importGo github.com/kubeflow/kubeflow/bootstrap/v3/pkg/apis/apps/kfdef/testdata: exit status 1
> go: finding github.com/kubeflow/kubeflow/bootstrap/v3/pkg/apis/apps/kfdef/testdata latest
> go: finding github.com/kubeflow/kubeflow/bootstrap/v3/pkg/apis/apps/kfdef latest
> go: finding github.com/kubeflow/kubeflow/bootstrap/v3/pkg/apis/apps latest
> go: finding github.com/kubeflow/kubeflow/bootstrap/v3/pkg/apis latest
> go: finding github.com/kubeflow/kubeflow/bootstrap/v3/pkg latest
> go: finding github.com/kubeflow/kubeflow/bootstrap latest
> go: finding github.com/kubeflow/kubeflow v0.6.2
> go: downloading github.com/kubeflow/kubeflow v0.6.2
> go: extracting github.com/kubeflow/kubeflow v0.6.2
> can't load package: package github.com/kubeflow/kubeflow/bootstrap/v3/pkg/apis/apps/kfdef/testdata: unknown import path "github.com/kubeflow/kubeflow/bootstrap/v3/pkg/apis/apps/kfdef/testdata": cannot find module providing package github.com/kubeflow/kubeflow/bootstrap/v3/pkg/apis/apps/kfdef/testdata
> 
> F0924 08:10:37.473244   65533 deepcopy.go:126] Failed loading boilerplate: open /Users/kyrremann/workspace/nav/go/src/k8s.io/code-generator/hack/boilerplate.go.txt: no such file or directory
> make: *** [pkg/apis/apps/kfdef/v1alpha1/zz_generated.deepcopy.go] Error 255
> ```
> 
> Are you building from `master`?

This is because the master branch updated the dependency and it conflicts with this PR. I resolved the conflicts and updated. PTAL.

**Comment by Lijo050** [comment]
> @Kyrremann @Lijo050 Can you test it again? Thanks! I have tested in my local env with `make build-kfctl`

It worked !!, many thanks @yeya24

**Comment by yeya24** [comment]
@gabrielwen  Can we move on this PR? Actually I notice there is another repo for kfctl. So what' s the main repo for kfctl? Do I need to open a PR at that repository?

**Comment by yeya24** [comment]
@jlewi Could you please help review this?

**Pull request merged**
