### PR TITLE
KFDef specs for gcp on v0.7-branch have a 0.7.0 suffix added.

### PR DESCRIPTION
**Pull request by jlewi**
* Related to kubeflow/testing#498

---
This change is [Reviewable](https://reviewable.io/reviews/kubeflow/kubeflow/4367)

### CODE REVIEW

**Comment by gabrielwen** [comment]
shouldn't this merge to v0.7-branch?

**Comment by jlewi** [comment]
@gabrielwen we haven't cut a v0.7-branch for kfctl yet.

**Comment by gabrielwen** [comment]
> @gabrielwen we haven't cut a v0.7-branch for kfctl yet.

ha, just noticed this..

**Pull request merged**
