### PR TITLE
Update katib components

### PR DESCRIPTION
**Pull request by richardsliu**
- Update katib components to support TFJob hyperparameter tuning
- Allow katib studyjobcontroller to delete pods
- Add ambassador annotation to katib-ui
- Fixed katib url in centraldashboard 
- Fixed bug in update_components script

---
This change is [Reviewable](https://reviewable.io/reviews/kubeflow/kubeflow/2064)

### CODE REVIEW

**Comment by YujiOshima** [comment]
@richardsliu Thanks! /lgtm

**Comment by YujiOshima** [comment]
@richardsliu Could you remove vizier-core NodePort? Related #1982.

**Comment by richardsliu** [comment]
@YujiOshima Done.

**Comment by YujiOshima** [comment]
Thanks! LGTM but I don't have lgtm, approve permission.

**Pull request merged**
