### PR TITLE
Use ambassador as a reverse proxy

### PR DESCRIPTION
**Pull request by jlewi**
* [Ambassdor](https://www.getambassador.io/) provides a reverse proxy that can be dynamically configured; we can mappings just by creating K8s services and anotating them with the prefix we want to serve the path on.

* Ambassador makes it really easy to configure our reverse proxy to direct traffic to an ephemeral service (e.g. a Tensorboard instance serving data for a particular job).

* This PR adds Ambassador and adds some default routes; e.g. we add a route to serve the K8s dashboard at /k8s/ui/

* In follow on PRs we can annotate other services (like the TFJobs UI) and TensorBoard deployments so that we can create mappings for those servers as well.

* Related to:
    #11 Secure Proxy 
    #60  IAP on GKE
   #154 Contour vs. Ambassador.

### CODE REVIEW

**Comment by jlewi** [comment]
@lluunn  Ping?

**Comment by lluunn** [comment]
will take a look later today or tomorrow morning.

**Comment by ddysher** [comment]
I come across this PR while searching for ambassador usage in kubeflow; before creating an issue, I feel like ask here first:

- is there any documentation on how we use ambassador?  ambassador is installed via core package by default, but there's no docs on why we need it and how to use it in kubeflow
- How do we dynamically direct traffic, considering that ephemeral services come and go?

**Comment by ddysher** [comment]
@jlewi 

/cc @gaocegege @codeflitting

**Comment by jlewi** [comment]
@ddysher 

The architecture is described in kubeflow/kubeflow#11

Routes can be added to ambassador by adding an annotation to the K8s service. A good example is the annotation that we add to add routes to specific tensorboard instances
https://github.com/kubeflow/kubeflow/blob/a50c2fb0e46cb3d9812be1ea1623749e13f63191/kubeflow/examples/prototypes/tensorboard.jsonnet#L23

**Comment by ddysher** [comment]
By we, you mean whoever deploy tensorboard, and via ksonnet?
> A good example is the annotation that we add to add routes to specific tensorboard instances

**Comment by jlewi** [comment]
Ksonnet is orthogonal. I meant how Kubeflow is using it. All you need to do
is add the appropriate annotaion to your K8s service. Tensorboard is an
example of that.  You can use whatever templating solution you want or just
specify the spec via YAML

**Comment by ddysher** [comment]
Thanks @jlewi.  Internally, we have components that manage this automatically (via ingress); i'll see if there is any integration point.

**Pull request merged**
