### PR TITLE
Adding kfserving to Kfctl config

### PR DESCRIPTION
**Pull request by johnugeorge**
KFServing and Knative(dependency) is added to config files

---
This change is [Reviewable](https://reviewable.io/reviews/kubeflow/kubeflow/3953)

### CODE REVIEW

**Comment by jlewi** [comment]
How about adding an E2E test to verify that knative and kfserving is actually deployed?

See:
https://github.com/kubeflow/kubeflow/blob/master/testing/kfctl/kf_is_ready_test.py

Do we also have issues tracking adding documentation on kubeflow.org about kfserving?

**Comment by johnugeorge** [comment]
Created issue for tracking docs on KFServing https://github.com/kubeflow/website/issues/1109

**Pull request merged**
