### PR TITLE
Add a check if hostname is too long for GCP endpoint

### PR DESCRIPTION
**Pull request by zhenghuiwang**
related to https://github.com/kubeflow/kubeflow/issues/4421

needs cherry-pick later.

---
This change is [Reviewable](https://reviewable.io/reviews/kubeflow/kubeflow/4436)

### CODE REVIEW

**Comment by kunmingg** [comment]
@jlewi 
Now the app name is folder name, seems user have to recreate folder?

**Comment by zhenghuiwang** [comment]
> @jlewi
> Now the app name is folder name, seems user have to recreate folder?

I don't think it is a problem.

Folder name is the default if name in spec is not set. User can still reset a shorter name in spec explicitly without recreating a folder.

**Pull request merged**
