### PR TITLE
Allow folks to have the kubeflow github repo over https + improve error message

### PR DESCRIPTION
**Pull request by holdenk**
Allow folks to have the kubeflow github repo over https + improve error message -- we don't actually need testing.git for the remote

---
This change is [Reviewable](https://reviewable.io/reviews/kubeflow/kubeflow/1626)

### CODE REVIEW

**Comment by holdenk** [comment]
cc @pdmack since you're the one who told me about the auto-formatter :)

**Comment by pdmack** [comment]
/approve
/lgtm

Thanks!

**Comment by pdmack** [comment]
Ironically, all.jsonnet needs formatting.

**Comment by holdenk** [comment]
hahahah. Ok i'll reformat :)

**Comment by holdenk** [comment]
Ran jsonnet format on all and it looks like it doesn't need any changes now, maybe master just was updated? /retest

**Comment by holdenk** [comment]
I'm not sure I understand the workflow failures... /retest?

**Comment by jlewi** [comment]
Test failures should be unrelated to this PR. So I'll just merge this manually.

Thanks for the fix.

**Comment by holdenk** [comment]
Thanks @jlewi :)

**Pull request merged**
