### PR TITLE
update the cuda base docker image version to 9.0 to align with tf-nightly-gpu

### PR DESCRIPTION
**Pull request by yongwen**
this is to fix https://github.com/kubeflow/kubeflow/issues/414

---
This change is [Reviewable](https://reviewable.io/reviews/kubeflow/kubeflow/427)

### CODE REVIEW

**Comment by yongwen** [comment]
I signed it!

**Comment by jlewi** [comment]
I'm not sure this is the right solution. 

I don't think we should be using the nightly build of TF (see #375). So we should pin TF in our notebook images to a specific version of TF.

Also the Makefile is no longer used to build our Docker images. We use the Argo workflow.

**Comment by jlewi** [comment]
I'm closing this PR because I think the issue is fixed by the fix to #375

**Comment by yongwen** [comment]
Thank you. Good to hear the better solution.

**Pull request closed without merging**
