### PR TITLE
Update aws parameters in serving and dashboard

### PR DESCRIPTION
**Pull request by Jeffwan**
1. Update tf serving aws prototype to use same pattern as gcp in order to reuse template. (Right now it's broken since k8s service was move out from tf-serving-template.libsonnet)
2. Remove useless parameters

Website are updated correspondingly. 
https://github.com/kubeflow/website/pull/362

---
This change is [Reviewable](https://reviewable.io/reviews/kubeflow/kubeflow/2097)

### CODE REVIEW

**Comment by jlewi** [comment]
Thanks @Jeffwan Can you open up follow on issues to add jsonnet unittests.

/lgtm
/approve

**Comment by Jeffwan** [comment]
@jlewi  Sure. I will use #2103 this issue to track future UT changes. you can assign to me.

**Comment by Jeffwan** [comment]
@jlewi Looks like it still need a /lgtm tag. Thanks for the help!

**Pull request merged**
