### PR TITLE
Fix admission webhook build issue

### PR DESCRIPTION
**Pull request by Jeffwan**
Address issue #4809

---
This change is [Reviewable](https://reviewable.io/reviews/kubeflow/kubeflow/4810)

### CODE REVIEW

**Comment by jlewi** [comment]
/lgtm
/approve

Do we want to run builds on presubmit e.g. by using Kaniko to ensure everything is working?
/hold

**Comment by Jeffwan** [comment]
@jlewi That will be better. There're a few components in kubeflow/kubeflow. It might be hard to build all of them. Otherwise, hook probably need to detect the project changes belong to and build that specific one.

**Comment by jlewi** [comment]
prow_config.yaml supports triggering certain workflows only when certain paths are modified. So we could have different workflows for the different applications and only trigger them when the corresponding source code is modified.

@gabrielwen is working on supporting Tekton in our E2E workflows. My hope is that will allow us to create reusable Tekton tasks for things like build a container, run unittests etc...

If you wanted to contribute to that I think you could try to define a Tekton Pipeline that we could run to build and test the admission hook. 

If you want to submit this as is just remove the hold.

**Comment by Jeffwan** [comment]
/hold cancel

Cool. Let me check Tekton tasks and see if I can build some CI for projects under kubeflow components.

**Pull request merged**
