### PR TITLE
Notebook backend throws 500 when status field is empty in the first query

### PR DESCRIPTION
**Pull request by midhun1998**
Fixs #7272

### CODE REVIEW

**Comment by annajung** [comment]
cc @kubeflow/release-team @DnPlas @kimwnasptd can we also get this in for 1.8 RC?

**Comment by midhun1998** [comment]
Friendly ping @kimwnasptd @DnPlas

**Comment by kimwnasptd** [comment]
Ah I missed this one, apologies @midhun1998. Could you confirm you no longer see this with https://github.com/kubeflow/kubeflow/pull/7335?

**Comment by midhun1998** [comment]
@kimwnasptd  Yup, In my tests it had resolved the issue. 
Any possible way to get quick reviews? I believe this PR was hanging for 2 weeks but the other one got reviewed in 2 days. 😅

**Comment by juliusvonkohout** [comment]
@midhun1998 we are short on maintainers and reviewers at the moment. You have to join the WG meetings to push stuff. https://www.kubeflow.org/docs/about/community/
We actively want to add more maintainers, maybe you are interested.

**Comment by midhun1998** [comment]
@juliusvonkohout Agree. Somehow the meeting invite expired for me. Will re subscribe to it. Thanks for information.

**Pull request closed without merging**
