### PR TITLE
Remove all unnecessary white spaces at the end of lines

### PR DESCRIPTION
**Pull request by ashahba**
Here are some of the commands to achieve this partially:
```
$ for file in $(git ls); do sed 's/[[:blank:]]*$//' ${file} > ${file}.new; cat ${file}.new > ${file}; rm -rf ${file}.new; done
```
Once done there would be a few files marked as untracked.
If all the files are truly untracked and not needed anywhere in the repo run this command:
```
$ git clean -f
```

---
This change is [Reviewable](https://reviewable.io/reviews/kubeflow/kubeflow/2371)

### CODE REVIEW

**Comment by ashahba** [comment]
Script to achieve this programmatically is on the way.

**Comment by ashahba** [comment]
I see a few things in the logs that concerns me:
```
TimeoutError: Timeout waiting for workflows kubeflow-presubmit-kfctl-2371-fdc06f5-5418-d5d1,kubeflow-presubmit-kfctl-beta-2371-fdc06f5-5418-91f8,kubeflow-presubmit-unittests-2371-fdc06f5-5418-9a46,kubeflow-presubmit-kubeflow-e2e-minikube-2371-fdc06f5-5418-5c57,kubeflow-presubmit-tf-serving-2371-fdc06f5-5418-237b,kubeflow-presubmit-dashboard-release-2371-fdc06f5-5418-ef05,kubeflow-presubmit-tf-notebook-release-2371-fdc06f5-5418-1652 in namespace kubeflow-test-infra to finish.
```
Also on the `argo` logs this is the read error:
```
INFO|2019-02-04T08:04:57|/mnt/test-data-volume/kubeflow-presubmit-kfctl-beta-2371-fdc06f5-5418-91f8/src/kubeflow/testing/py/kubeflow/testing/util.py|71| level=error msg="handle object: ca
n't update deployments kubeflow.workflow-controller: Operation cannot be fulfilled on deployments.extensions \"workflow-controller\": the object has been modified; please apply your chang
es to the latest version and try again"
INFO|2019-02-04T08:04:59|/mnt/test-data-volume/kubeflow-presubmit-kfctl-beta-2371-fdc06f5-5418-91f8/src/kubeflow/kubeflow/testing/test_deploy.py|326| Writing test results to /mnt/test-dat
a-volume/kubeflow-presubmit-kfctl-beta-2371-fdc06f5-5418-91f8/output/artifacts/junit_kubeflow-deploy-deploy-argo-test-argo-deploy.xml
INFO|2019-02-04T08:04:59|/mnt/test-data-volume/kubeflow-presubmit-kfctl-beta-2371-fdc06f5-5418-91f8/src/kubeflow/testing/py/kubeflow/testing/test_util.py|151| Creating /mnt/test-data-volu
me/kubeflow-presubmit-kfctl-beta-2371-fdc06f5-5418-91f8/output/artifacts/junit_kubeflow-deploy-deploy-argo-test-argo-deploy.xml
Traceback (most recent call last):
 File "/usr/lib/python2.7/runpy.py", line 174, in _run_module_as_main
   "__main__", fname, loader, pkg_name)
 File "/usr/lib/python2.7/runpy.py", line 72, in _run_code
   exec code in run_globals
 File "/mnt/test-data-volume/kubeflow-presubmit-kfctl-beta-2371-fdc06f5-5418-91f8/src/kubeflow/kubeflow/testing/test_deploy.py", line 739, in <module>
   main()
 File "/mnt/test-data-volume/kubeflow-presubmit-kfctl-beta-2371-fdc06f5-5418-91f8/src/kubeflow/kubeflow/testing/test_deploy.py", line 729, i
```

Which I'm not sure where it's coming from yet 🤔

**Comment by ashahba** [comment]
Looks like the previous failures were resolved after `GC` was triggered.
/assign @jlewi

**Comment by ashahba** [comment]
Fixes #2389

**Comment by jlewi** [comment]
Thank you so much for doing this.

/lgtm
/approve

**Pull request merged**
