### PR TITLE
Merge config for kftcl and click-to-deploy webapp

### PR DESCRIPTION
**Pull request by lluunn**
Both use config in scripts/gke/deployment_manager_configs.

/cc @kunmingg

---
This change is [Reviewable](https://reviewable.io/reviews/kubeflow/kubeflow/1594)

### CODE REVIEW

**Comment by kunmingg** [comment]
Can we have a path like ```deployment/gke/deployment_manager_configs``` for those configs?

**Comment by lluunn** [comment]
failure: #1620

**Comment by kunmingg** [comment]
/hold
Till deploy app e2e test merged, to save test effort.

**Comment by lluunn** [comment]
sounds good

**Comment by kunmingg** [comment]
/hold cancel
periodic test should be coming
@lluunn

**Pull request merged**
