### PR TITLE
 Notebook controller fixes

### PR DESCRIPTION
**Pull request by lluunn**
for #2456

- ~~Add field, useLab, and set jupyterlab environment var when it's true~~
- set containerPort only when it's not set
- add ambassador annotation
- make e2e test run on the new golang impl
- fix the Service clusterIP immutable problem

/cc @jlewi @vkoukis

also related: #2417

---
This change is [Reviewable](https://reviewable.io/reviews/kubeflow/kubeflow/2463)

### CODE REVIEW

**Comment by lluunn** [comment]
/hold
I will incorporate #2454 into this one so that we have e2e test running for go notebook controller

**Comment by kimwnasptd** [comment]
Hi @lluunn, there are two last changes that are demo critical in order for the Jupyter UI to work seamlessly. 
* While we were testing, we realized that Ambassador doesn't resolve the annotated Service's Endpoints. This means that if we put only the Service's name in the annotation it won't send the traffic to Port 8888 in the Pod but in Port 80

**Comment by kimwnasptd** [comment]
Hi @lluunn, there are two last changes that are demo critical in order for the Jupyter UI to work seamlessly.

* While we were testing, we realized that Ambassador doesn't resolve the annotated Service's Endpoints. This means that if we put only the Service's name in the annotation it won't map the traffic on Port 8888 in the Pod but in Port 80. I think we can solve this if we also specify the Port in the annotations, for ex. `service: <name>.<namespace>:<port>` (also the name should be prior to the namespace)
* We need to set the `securityContext` in the Pod. Specifically we need `fsGroup` to be 100 so that the volumes are owned from `users` GUID. This is needed for volumes to work properly on GKE

**Comment by kimwnasptd** [comment]
Hi @lluunn, I noticed in the commits that in the annotations the Notebook URL will be under `/notebook/<namespace>/<name>`. Previously the URLs for notebooks was just under `/<namespace>/<name>`. Was the `/notebook/` prefixed discussed somewhere and I missed it?
Could you have me in the loop similar changes?

**Comment by lluunn** [comment]
No I just added. I think other components might have service with same (namespace, name) pair, so it seems reasonable to me to have a prefix indicating it's a notebook.
WDYT?

**Comment by kimwnasptd** [comment]
Totally agree with it! I will update `connect(url)` function in the UI to redirect to the new URL for the Notebooks

**Comment by jlewi** [comment]
@lluunn just had 2 minor comments and then this is ready to go IMO.

**Comment by lluunn** [comment]
Update the comment, and put back main in pytest, thanks

**Comment by jlewi** [comment]
/lgtm
/approve
/hold
In case you want to move logging statements to top of module or into the test function so that logging works even if executed under pytest

**Comment by lluunn** [comment]
The logging is already at top of the module.
/hold cancel
thanks!

**Pull request merged**
