### PR TITLE
openmpi: master/workers sync mechanism is replaced with k8s api from redis

### PR DESCRIPTION
**Pull request by everpeace**
Currently, openmpi package uses redis to sync master/workers.  But I think it is overkilled a bit.  And we can watch master/workers status via k8s api.

In a pod, service account's token and kubernetes api server endpoint is embedded. So, we can see pods status just executing curl like this.

```
# I think --insecure is safe because this will be executed in a pod (inside of kubernetes cluster)
curl --insecure \
  --header "Authorization: Bearer $(cat /var/run/secrets/kubernetes.io/serviceaccount/token)" \
  https://$KUBERNETES_SERVICE_HOST:$KUBERNETES_SERVICE_PORT/api/v1/namespaces/$(cat /var/run/secrets/kubernetes.io/serviceaccount/namespace)/pods
```

So, I replaced master/workers sync mechanism with k8s api from redis.

What do you think??  I'm very happy if I could have some feedbacks.

---
This change is [Reviewable](https://reviewable.io/reviews/kubeflow/kubeflow/696)

### CODE REVIEW

**Comment by everpeace** [comment]
cc/ @jiezhang @pdmack would you mind reviewing this?

**Comment by everpeace** [comment]
@pdmack I'm so sorry. I force pushed my branch because I had typo...

**Comment by pdmack** [comment]
It's fine. Test is running. Stay tuned.

**Comment by pdmack** [comment]
/approve
/lgtm

Thanks @everpeace !

**Comment by jiezhang** [comment]
@everpeace @pdmack The worker reaches "running" state once init.sh starts running, but at that point the worker is not ready yet - it still has a bunch of initialization to finish.

**Comment by everpeace** [comment]
@jiezhang 

> - it still has a bunch of initialization to finish.

ah, you're write.  Then, master can wait until `ssh` to all workers succeeds.  What do you think? I'm very happy to fix it.

**Pull request merged**
