### PR TITLE
use broadwell

### LINKED ISSUE #1840: For GKE deployment, change default CPU to Broadwell
For the GKE deployment, change default CPU to Broadwell instead of Haswell (which is no longer as widely available).
https://cloud.google.com/compute/docs/regions-zones/

cc @jlewi

### PR DESCRIPTION
**Pull request by lluunn**
fix #1840

/cc @kunmingg 
/cc @jlewi

---
This change is [Reviewable](https://reviewable.io/reviews/kubeflow/kubeflow/1852)

### CODE REVIEW

**Comment by lluunn** [comment]
presubmit failure should be fixed by: https://github.com/kubeflow/kubeflow/pull/1851

**Comment by kunmingg** [comment]
Do you need to rebase?

**Pull request merged**
