### PR TITLE
install Ksonnet 0.8.0 in both CPU and GPU dockerfile.

### LINKED ISSUE #138: Add ksonnet to our Jupyter notebook Docker images
We should add ksonnet to our Jupyter notebook images so that we can run notebooks that show how to use Kubeflow.

### PR DESCRIPTION
**Pull request by fxue**
- to fix #138 
- added Ksonnet 0.8.0 install to both CPU and GPU dockerfile
- verified in docker CLI that jovyan is able to execute ks
```shell
jovyan@658114ba5b01:~$ ks

You can use the `ks` commands to write, share, and deploy your Kubernetes
application configuration to remote clusters.
```

### CODE REVIEW

**Comment by jlewi** [comment]
Thank you so much for this.

**Comment by fxue** [comment]
do we have workflow somewhere to push this to gcr?

**Comment by pineking** [comment]
@fxue it's better to push it docker hub. gcr.io is blocked.

**Comment by jlewi** [comment]
The release process for our Docker images is WIP. Right now it needs to happen manually and only a small set of folks have sufficient access.

There is also discussion about how to replicate images to GCR and DockerHub.

**Pull request merged**
