### PR TITLE
Release v1.8.0-rc.3

### PR DESCRIPTION
**Pull request by DnPlas**
Bump release version v1.8.0-rc.1 -> v1.8.0-rc.3

cc: @kimwnasptd

### CODE REVIEW

**Comment by thesuperzapper** [comment]
/hold

We need to wait for https://github.com/kubeflow/kubeflow/pull/7357

**Comment by thesuperzapper** [comment]
@kimwnasptd @DnPlas we are going to need to cut another release because this will have created the `1.8.0-rc.3` tag and https://github.com/kubeflow/kubeflow/pull/7357 was not merged.

**Comment by DnPlas** [comment]
@thesuperzapper that's the plan, as discussed in the Community Meeting, we are cutting two RCs in case we found an issue with the images in https://github.com/kubeflow/kubeflow/pull/7357 so we don't block the release anymore.

**Pull request merged**
