### PR TITLE
Disable test_jsonnet.py because it is failing blocking presubmits.

### PR DESCRIPTION
**Pull request by jlewi**
* See #4159

---
This change is [Reviewable](https://reviewable.io/reviews/kubeflow/kubeflow/4161)

### CODE REVIEW

**Comment by jlewi** [comment]
Preliminary results indicate test is skipped
http://testing-argo.kubeflow.org/workflows/kubeflow-test-infra/kubeflow-presubmit-unittests-4161-eee1a1b-9456-f531?tab=workflow&nodeId=kubeflow-presubmit-unittests-4161-eee1a1b-9456-f531-489357159&sidePanel=logs%3Akubeflow-presubmit-unittests-4161-eee1a1b-9456-f531-489357159%3Amain

The test_jsonnet.py file ran but no failed junit file appears

**Comment by yanniszark** [comment]
@jlewi I'm ok with disabling it temporarily to unblock other PRs.
However, we should find out why the test broke.
/lgtm

**Pull request merged**
