### PR TITLE
Update tf-job-operator.libsonnet

### PR DESCRIPTION
**Pull request by GarnettWang**
when tf-operator enable-gang-scheduler, tf-job-operator ClusterRole need the corresponding poddisruptionbudgets.policy, otherwise tf-operator will get/create pdb object failed.

---
This change is [Reviewable](https://reviewable.io/reviews/kubeflow/kubeflow/1216)

### CODE REVIEW

**Comment by pdmack** [comment]
@GarnettWang need to autoformat your libsonnet file

**Comment by GarnettWang** [comment]
@jlewi @pdmack 
Can you help me check the argo workflow's error, argo Logs: **/usr/bin/python: No module named py**
whether the gcr.io/kubeflow-ci/test-worker:latest images has some problem?

the argo worklow link: [kubeflow-presubmit-kubeflow-e2e-gke-1216-e805671-2606-e896](http://testing-argo.kubeflow.org/workflows/kubeflow-test-infra/kubeflow-presubmit-kubeflow-e2e-gke-1216-e805671-2606-e896?tab=workflow&nodeId=kubeflow-presubmit-kubeflow-e2e-gke-1216-e805671-2606-e896-1393658163)

**Comment by jlewi** [comment]
@GarnettWang Sorry I think that test failure was a problem with our test infrastructure that should be fixed.

Also sorry for the slow reply. If the assigned reviewers aren't being responsive you can ping them or else assign new reviewers with /assign

/assign jlewi

**Comment by pdmack** [comment]
Another one for rebase?

**Comment by jlewi** [comment]
@GarnettWang Could you please rebase of the latest changes? The tests were broken which is why this hasn't merged. If you rebase of master that should fix the tests and we can get this merged.

**Comment by jlewi** [comment]
@GarnettWang 

Closing this PR. tf-job-operator.libsonnet has now been refactored so additional changes will be needed to make the change work. Feel free to reopen with an updated PR if you want to continue working on this.

**Pull request closed without merging**
