### PR TITLE
Add MiniKF to the central dashboard

### PR DESCRIPTION
**Pull request by cspavlou**
Add MiniKF to the central dashboard, so that the latter is consistent with the Kubeflow docs.

---
This change is [Reviewable](https://reviewable.io/reviews/kubeflow/kubeflow/3211)

### CODE REVIEW

**Comment by prodonjs** [comment]
For ROADMAP.md approval...

/assign @texasmichelle

**Comment by cspavlou** [comment]
Thank you @prodonjs 

@texasmichelle what do you think?

**Comment by cspavlou** [comment]
Hi @texasmichelle @prodonjs any update on this? Thanks

**Comment by prodonjs** [comment]
It looks like the OWNERS file has changed. I'll ping a member of the team to take a look and approve the ROADMAP change.

/unassign @texasmichelle

**Comment by prodonjs** [comment]
For OWNERS approval for ROADMAP file change...

/cc @jlewi

**Pull request merged**
