### PR TITLE
Update E2E tests to pull GCP KFDef from kubeflow/manifests

### PR DESCRIPTION
**Pull request by jlewi**
* Related to kubeflow/manifests#241; move KFDef specs to kubeflow/manifests

* Update kfctl_go_test.py to support pulling the KFDef by a URI so we can
  just fetch the KFDef spec in kfctl_go_test.py

* Remove the GCP configs since they are now in kubeflow/manifests and
  the tests no longer use them

* Update bootstrap/README.md; delete a lot of obsolete information

---
This change is [Reviewable](https://reviewable.io/reviews/kubeflow/kubeflow/4129)

### CODE REVIEW

**Comment by jlewi** [comment]
The build of kfctl failed

```
util.py                     71 INFO     fatal: No tags can describe '0dbd2752ffe2c4ff17250688d85dddc83a630cec'.
util.py                     71 INFO     Try --always, or create some tags.
util.py                     71 INFO     go build -gcflags '-N -l' -ldflags "-X main.VERSION=" -o bin/kfctl cmd/kfctl/main.go
```

**Comment by jlewi** [comment]
I can repo locally by doing

```
git clone --depth=2 --no-single-branch https://github.com/kubeflow/kubeflow.git git_kubeflow
git describe --tags --long 
```
Looks cloning with depth=2 causes the problem. Adding --always should fix it.

**Comment by jlewi** [comment]
Most recent failure is 

```
    if u.scheme in ["http", "https"]:
       data = requests.get(config_path)
       return yaml.load(data.content)
     else:
>       with open(config_path, 'r') as f:
E       FileNotFoundError: [Errno 2] No such file or directory: '/mnt/test-data-volume/kubeflow-presubmit-kfctl-go-iap-istio-4129-dc634ba-4196-4792/src/k
ubeflow/kubeflow/https://raw.githubusercontent.com/kubeflow/manifests/master/kfdef/kfctl_gcp_iap.yaml'
```

So need to edit the workflow to not add the srcDir prefix.

**Comment by gabrielwen** [comment]
@jlewi my test is broken with message:
```
Error: couldn't generate KfApp:  (kubeflow.error): Code 500 with message: coordinator Generate failed for gcp:  (kubeflow.error): Code 400
with message: could not generate deployment manager configs under gcp_config Error:  (kubeflow.error): Code 400 with message: could not copy /mnt/test-data-volume/kubeflow-presubm
it-kfctl-go-iap-istio-4149-2ffff7f-9696-669d/kfctl-669d/.cache/kubeflow/kubeflow-master/deployment/gke/deployment_manager_configs/cluster.jinja to /mnt/test-data-volume/kubeflow-p
resubmit-kfctl-go-iap-istio-4149-2ffff7f-9696-669d/kfctl-669d/gcp_config/cluster.jinja using repo local path /mnt/test-data-volume/kubeflow-presubmit-kfctl-go-iap-istio-4149-2ffff
7f-9696-669d/kfctl-669d/.cache/kubeflow/kubeflow-master Error cannot open input for copying: open /mnt/test-data-volume/kubeflow-presubmit-kfctl-go-iap-istio-4149-2ffff7f-9696-669
d/kfctl-669d/.cache/kubeflow/kubeflow-master/deployment/gke/deployment_manager_configs/cluster.jinja: no such file or directory
```

Test is in #4149

**Comment by jlewi** [comment]
@gabrielwen Here is a recent postsubmit
https://prow.k8s.io/view/gcs/kubernetes-jenkins/logs/kubeflow_kubeflow/kubeflow-postsubmit/1174439779639496711

at 2f15d8dbe85f0081652c1e5363f6a8c547a3e5fc  which is the postsubmit run.

The workflow failed 
http://testing-argo.kubeflow.org/workflows/kubeflow-test-infra/kubeflow-postsubmit-kfctl-go-iap-endpoint-2f15d8d-6711-afb4?tab=workflow

But it looks like kubeflow was deployed but the endpoint never came up successfully.

So it got passed the deployment step which is where the file is failing.

I suspect the issue is related to your PR; i.e. you might need to rebase. It looks like your PR is still looking for the JINJA templates in the kubeflow/kubeflow repo when it should be looking in the kubeflow/manifests repo.

So I think you might be missing some of the changes in #4149.

**Comment by gabrielwen** [comment]
yea, you are right - it's missing this PR...  sorry for the false alarm.

**Pull request merged**
