### PR TITLE
Rebase for #3673

### PR DESCRIPTION
**Pull request by gabrielwen**
Rebase for #3673

---
This change is [Reviewable](https://reviewable.io/reviews/kubeflow/kubeflow/3676)

### CODE REVIEW

**Comment by jlewi** [comment]
CLA check was messed up because original commits are from @kkasravi ;
The PR needs to be rebased to make tests pass. @kkasravi is out so @gabrielwen is trying to resubmit on behalf of @kkasravi

**Comment by gabrielwen** [comment]
will amend commit author next time, thanks!

**Comment by kkasravi** [comment]
Thanks all

**Pull request merged**
