### PR TITLE
Make notebook controller docker image nonroot

### PR DESCRIPTION
**Pull request by naveensrinivasan**
This fix makes the notebook controller docker image nonroot.

### CODE REVIEW

**Comment by yanniszark** [comment]
/assign @yanniszark
Let's merge this after we have the test in https://github.com/kubeflow/kubeflow/pull/5400, in order to verify it! :)

**Comment by naveensrinivasan** [comment]
> /assign @yanniszark
> Let's merge this after we have the test in #5400, in order to verify it! :)

@yanniszark Thanks!

**Comment by DavidSpek** [comment]
This seems to be a duplicate of https://github.com/kubeflow/kubeflow/pull/5288

**Comment by DavidSpek** [comment]
@yanniszark Given that I tested https://github.com/kubeflow/kubeflow/pull/5288 manually which does the same thing as this PR. Should we merge this so it can be included in the 1.3 release? Then https://github.com/kubeflow/kubeflow/pull/5288 can be closed as well.

**Comment by DavidSpek** [comment]
@naveensrinivasan Would you be able to rebase this PR on the master branch? This way it picks up the new CI/CD.

**Comment by thesuperzapper** [comment]
/repoen

@kimwnasptd do we want to make the controllers run as non-root?

**Pull request closed without merging**
