### PR TITLE
add seldon to ks config; pre install all pkg

### PR DESCRIPTION
**Pull request by kunmingg**
To smooth user experience, including https://github.com/kubeflow/examples

---
This change is [Reviewable](https://reviewable.io/reviews/kubeflow/kubeflow/1098)

### CODE REVIEW

**Comment by ankushagarwal** [comment]
Does this mean that we no longer need to specify packages in the config file : https://github.com/kubeflow/kubeflow/blob/master/bootstrap/config/default.yaml#L5 ?

**Comment by kunmingg** [comment]
@ankushagarwal 
Yes
I didn't delete packages config in this commit to avoid backward compatibility problems.

**Pull request merged**
