### PR TITLE
Update to Ambassador 0.34.0

### PR DESCRIPTION
**Pull request by kflynn**
Update to Ambassador 0.34.0.

---
This change is [Reviewable](https://reviewable.io/reviews/kubeflow/kubeflow/888)

### CODE REVIEW

**Comment by pdmack** [comment]
```
HTTP response body: b'{"kind":"Status","apiVersion":"v1","metadata":{},"status":"Failure","message":"services is forbidden: User \\"system:serviceaccount:kubeflow-presubmit-kubeflow-e2e-gke-747-108440d-1365-340d:ambassador\\" cannot watch services in the namespace \\"kubeflow-presubmit-kubeflow-e2e-gke-747-108440d-1365-340d\\": Unknown user \\"system:serviceaccount:kubeflow-presubmit-kubeflow-e2e-gke-747-108440d-1365-340d:ambassador\\"","reason":"Forbidden","details":{"kind":"services"},"code":403}\n'
```
Hmmm, @kflynn this related to the UID changes?

**Comment by ankushagarwal** [comment]
@pdmack Where are you seeing this failure message?

**Comment by pdmack** [comment]
e.g., https://goo.gl/WswzWa

**Comment by kflynn** [comment]
@pdmack We actually haven't made any changes to anything UID-related in Ambassador since 0.30.1 (in fact, we've basically not changed anything about Ambassador's bootstrap). 

Looking at the test output again and noting that the failures seem to be minikube-related, can you (or @ankushagarwal?) tell me how minikube gets started?

**Comment by pdmack** [comment]
flake
Thanks @kflynn!

**Pull request merged**
