### PR TITLE
remove v2.zip, update references

### LINKED ISSUE #3368: kfctl: remove ksonnet, move to v2
We should remove all references to ksonnet and move to v2 for kfctl and bootstrap 

- [x] move kfctl code from under bootstrap to kubeflow/kfctl
- [x] kubeflow/kfctl/go.mod should now have module github.com/kubeflow/kubeflow/kfctl/v2
- [x] bootstrap go.mod should now have module github.com/kubeflow/kubeflow/bootstrap/v2
- [x] replace all references of github/kubeflow/kubeflow/bootstrap with either github/kubeflow/kubeflow/bootstrap/v2 or github/kubeflow/kubeflow/kfctl/v2
- [x] replace alls references to /tmp/v2 with kubernetes v1.13.4, client-go v10.0, kustomize v2.1.0 (#3497), controller-runtime v0.1.12 

background info:
there are  [2 alternatives](https://github.com/golang/go/wiki/Modules#releasing-modules-v2-or-higher) for v2 modules. We currently use ‘major subdirectory’ but will move to ‘major branch’. 

In order to load both ksonnet and kustomize in kfctl we implemented v2 modules for the following (v2.zip):
- k8s.io:
  - api@v1.13.4
  - apimachinery@v1.13.4
  - cli-runtime@v1.13.4
  - apiextensions-apiserver@v1.13.4
  - apiserver@v1.13.4
  - client-go@v10.0
- sigs.k8s.io
  - application@sha67ae7f915d4ea994e0805886928d9ec40e9526a2
  - controller-runtime@v0.1.12
  - kustomize@v2.0.3

Additional info is [here](https://research.swtch.com/vgo-module)

### PR DESCRIPTION
**Pull request by kkasravi**
fixes #3368

---
This change is [Reviewable](https://reviewable.io/reviews/kubeflow/kubeflow/3786)

### CODE REVIEW

**Comment by kkasravi** [comment]
assign @jlewi

**Comment by kkasravi** [comment]
assign @kunmingg

**Comment by kkasravi** [comment]
assign @yanniszark

**Comment by jlewi** [comment]
@kkasravi Can you provide a little more explanation of what this PR is doing?

Here's what I think is happening

* You moved all code in the v2/ subdirectory out of v2/ and merged it with the other directories
* You changed go.mod so all code under bootstrap/ is now imported as bootstrap/v2

  * Why make all imports "v2" e.g. "bootstrap/pkg" > "bootstrap/v2/pkg" as opposed to doing the reverse and change "bootstrap/v2/pkg" to "bootstrap/pkg"

  * If its a short term solution I think I'm ok with it. But can we get the import paths to match the directory path? I think that's what most developers expect

* Can you briefly describe your changes to cmd/bootstrap to get it to compile?

**Comment by jlewi** [comment]
Got it; That's a really long doc you linked to :) So I'm going to take you word for it.

/lgtm
/approve

**Comment by jlewi** [comment]
/lgtm
/approve

@kkasravi Were the most recent round of changes just to get the test to pass?

**Comment by kkasravi** [comment]
@jlewi yes and rebase from master

**Pull request merged**
