### PR TITLE
Automated cherry pick of #3760 upstream v0.6 branch

### PR DESCRIPTION
**Pull request by zhenghuiwang**
https://github.com/kubeflow/kubeflow/issues/3702

---
This change is [Reviewable](https://reviewable.io/reviews/kubeflow/kubeflow/3766)

### CODE REVIEW

**Comment by zhenghuiwang** [comment]
@yanniszark needs your reply `@googlebot I consent.`

**Comment by yanniszark** [comment]
@googlebot I consent

**Pull request merged**
