### PR TITLE
Remove unused bootstrap config

### PR DESCRIPTION
**Pull request by holdenk**
We now use https://github.com/kubeflow/manifests/tree/master/kfdef instead
cc @krishnadurai

---
This change is [Reviewable](https://reviewable.io/reviews/kubeflow/kubeflow/4211)

### CODE REVIEW

**Comment by krishnadurai** [comment]
@holdenk could you please rebase on master for this to pass tests?

**Comment by jlewi** [comment]
Thanks @holdenk I pulled your changes into a new PR #4490

**Pull request closed without merging**
