### PR TITLE
Issue#5496, to remove the f-strings in the Jupyter web app's backend.

### PR DESCRIPTION
**Pull request by nellaivijay**
Replaced the f'string with %s

### CODE REVIEW

**Comment by kimwnasptd** [comment]
@nellaivijay make sure to sign the CLA
https://www.kubeflow.org/docs/about/contributing/#sign-the-cla

/ok-to-test

**Comment by nellaivijay** [comment]
> @nellaivijay make sure to sign the CLA
> https://www.kubeflow.org/docs/about/contributing/#sign-the-cla
> 
> /ok-to-test

@kimwnasptd , Yes, I signed the CLA.

**Comment by kimwnasptd** [comment]
I think you've missed some cases. Try running
```grep -rnw jupyter/backend -e 'f' --exclude=\*.pyc``` to see all the instances.

> @kimwnasptd , Yes, I signed the CLA.
Try commenting again as the bot says https://github.com/kubeflow/kubeflow/pull/5500#issuecomment-754758919

**Comment by nellaivijay** [comment]
@googlebot I fixed it.

**Comment by nellaivijay** [comment]
> I think you've missed some cases. Try running
> `grep -rnw jupyter/backend -e 'f' --exclude=\*.pyc` to see all the instances.
> 
> > @kimwnasptd , Yes, I signed the CLA.
> 
> Try commenting again as the bot says [#5500 (comment)](https://github.com/kubeflow/kubeflow/pull/5500#issuecomment-754758919)

@kimwnasptd , I committed the changes, Please check

**Comment by thesuperzapper** [comment]
@nellaivijay why is this necessary?

**Comment by DavidSpek** [comment]
@thesuperzapper To quote @kimwnasptd "We need to remove any f"strings" from the backend of the Jupyter web app in order to be able to use lower versions from Python 3.6 to run it." https://github.com/kubeflow/kubeflow/issues/5496
Summary of https://github.com/kubeflow/kubeflow/issues/5494, to make it easier for developers to contribute.

**Comment by DavidSpek** [comment]
@nellaivijay It seems the CLA bot is getting hung up as the commits belong are made by `Ramdoss, Vijayakumar`, which does not seem to be associated with your GitHub account and thus the CLA bot cannot verify that the author of the commit has signed the CLA.

**Comment by thesuperzapper** [comment]
/hold

I believe this change is not needed, see my comment: https://github.com/kubeflow/kubeflow/issues/5496#issuecomment-759056472

**Comment by DavidSpek** [comment]
@thesuperzapper you probably want to hold https://github.com/kubeflow/kubeflow/pull/5495 as well in this case

**Comment by DavidSpek** [comment]
@kimwnasptd @thesuperzapper Given that https://github.com/kubeflow/kubeflow/pull/5495 was merged, this PR should probably also be merged.

**Comment by DavidSpek** [comment]
@nellaivijay Could you try committing the changes directly from your GitHub account?

**Comment by DavidSpek** [comment]
@kimwnasptd I'm closing this PR in favor of https://github.com/kubeflow/kubeflow/pull/5680 as the author has not responded or signed the CLA. 

/close

**Pull request closed without merging**
