### PR TITLE
add the centraldashboard Dockerfile for ppc64le

### PR DESCRIPTION
**Pull request by alongzhi**
This change is [Reviewable](https://reviewable.io/reviews/kubeflow/kubeflow/4257)

### CODE REVIEW

**Comment by prodonjs** [comment]
@alongzhi - How would you anticipate this being used in Kubeflow deployments? Currently, I don't think any other Docker images are built for ppc64le. I just want to make sure I understand what this will be used for since nothing else appears to be referencing it.

**Comment by jinchihe** [comment]
@prodonjs We are working on Kubeflow supporting POWER platform, and some Dockerfile has been updated. See the ticket for details https://github.com/kubeflow/kubeflow/issues/2633 .We now installed Kubeflow on POWER after rebuild some image for POWER platform, so contribute the Dockerfile. Thanks.

**Comment by alongzhi** [comment]
Hi @prodonjs , Thanks for your reviewing. 

I'm building such an image so that centraldashboard can be run on ppc64le platform. In the past several months, we have updated some components/images to support on ppc64le, centraldashboard will be one of the plan. @jinchihe , could you please share more background about this?

**Comment by jinchihe** [comment]
@alongzhi Seems you created new Dockerfile for POWER platform, is there have big diff with one that for x86_64?

**Comment by alongzhi** [comment]
@jinchihe Yes this Dockerfile for Power has a big difference with x86_64, the major reason is that the chromium-browser is not supported from source alpinelinux.org, so we have to find another one. And some other enhancement to make sure npm build/test pass, thanks.

**Comment by jinchihe** [comment]
@alongzhi OK, great.
/lgtm

**Comment by prodonjs** [comment]
Thanks @jinchihe and @alongzhi for the explanations. I'd like to get one of the project leads like @jlewi to weigh in on this as his comments on #2633 seem to indicate some concern about adding additional Dockerfiles to each component.

/cc @jlewi

**Comment by jlewi** [comment]
@prodonjs @alongzhi I think its fine to include non x86 Dockerfiles to support power PC builds.
My expectation is that it would be the folks supporting the powerpc deployments and not the application owners who would be responsible for maintaining these.

Placing a hold just to make sure we are all on the same page but if we are then I think @alongzhi you can remove this and we are good to go.

/approve
/hold

**Comment by xauthulei** [comment]
retest

**Comment by prodonjs** [comment]
@alongzhi - I would recommend rebasing this change over *master* and then pushing it again. Usually that resolves the failing presubmit tests.

**Pull request closed without merging**
