### PR TITLE
Add PVCViewer Frontend Integration

### PR DESCRIPTION
**Pull request by TobiasGoerke**
As discuseed in #6876, I've integrated the PVCViewer into the volumes UI.

You may test this by deploying the PVCViewer (make sure to merge/apply #7178 first) and the changed volumes UI.

### CODE REVIEW

**Comment by kimwnasptd** [comment]
@TobiasGoerke could you do one more rebase here as well to make sure all tests are running as expected?

**Comment by TobiasGoerke** [comment]
> @TobiasGoerke could you do one more rebase here as well to make sure all tests are running as expected?

Done. Looking good.
Btw, can you manually trigger the [backend docker pipeline](https://github.com/kubeflow/kubeflow/actions/workflows/pvcviewer_controller_docker_publish.yaml), now that it is fixed?

**Comment by kimwnasptd** [comment]
Looks good! Nice to see a dedicated button as well for stopping the viewer

/lgtm
/approe

**Pull request merged**
