### PR TITLE
Add CI format checks for the Jupyter web app

### LINKED ISSUE #5810: Extend CI tests to catch format errors on the web apps
/kind feature

**Why you need this feature:**
To ensure the code of our [crud-web-apps](https://github.com/kubeflow/kubeflow/tree/master/components/crud-web-apps) properly formatted.

**Describe the solution you'd like:**
Extend the existing CI python files to also run a task that will be checking the formatting of TypeScript as well as run `flake8` tests on the backends of the [crud-web-apps](https://github.com/kubeflow/kubeflow/tree/master/components/crud-web-apps).

/priority p1
/assign @kimwnasptd

### PR DESCRIPTION
**Pull request by kimwnasptd**
first step for #5810 

Fix format errors for the web apps and introduce new tasks that check the format of the code on each PR. I'll be using `prettier` for the frontend code and `flake8` for the Python backend.

I bumped into the following issues and included commits for them:
1. Kaniko was not properly using the dockerignore file in each app's repo. To migitage this I created a global dockerignore file for all the apps
2. The above issue with the dockerfile resulted in some erros when building the frontend. I think this was because kaniko would include the `node_modules` [no dockerignore] it would find, which were build from another task. I modified the docker file to not copy the node modules which seems to solve the issue, in conjunction with the updated dockerignore file
3. I fixed the formatting for the frontend and the backend in order for the updated CI tests to pass

As we can see now we have tasks that also check the formatting of the Jupyter web app's frontend and backend code. I'll also move forward with subsequent PRs to update the other web apps as well.

### CODE REVIEW

**Comment by DavidSpek** [comment]
Related to this PR, the repository currently contains both a `.pylintrc` and a `.flake8`. As far as I can tell `.flake8` is everywhere and not `.pylintrc`. Can the `.pylintrc` be removed so that IDEs pick up on the correct linter?

**Comment by thesuperzapper** [comment]
+1

**Comment by kimwnasptd** [comment]
> Related to this PR, the repository currently contains both a .pylintrc and a .flake8. As far as I can tell .flake8 is everywhere and not .pylintrc. Can the .pylintrc be removed so that IDEs pick up on the correct linter?

That's a good point. I'll remove the `.pylintcr` file in a subsequent PR

**Comment by kimwnasptd** [comment]
Also I'm mostly done with the code but I see that the `kaniko-build` test occasionally fails. I have a suspicion that this happens when the `kaniko-build` task is on the right of the `npm-modules-install` task, but I'll keep on rerunning the tests until I'm sure I know what's going on.

**Comment by kimwnasptd** [comment]
OK I can see a presubmit test succeeding as well with the `kaniko-build` task happening first so I believe we should be good to go. https://argo.kubeflow-testing.com/workflows/kubeflow-test-infra/kubeflow-kubeflow-presubmit-jwa-tests-5811-15e0c7e-7792-5830?tab=workflow&nodeId=kubeflow-kubeflow-presubmit-jwa-tests-5811-15e0c7e-7792-5830-497792503

I'll do a final refactor of the code and it should be ready for review.

**Comment by kimwnasptd** [comment]
@kubeflow/wg-notebooks-leads this should be ready for review. I also updated the description of the PR.

**Comment by kimwnasptd** [comment]
I force pushed the branch because I slightly changed the order of the commits to make it easier for the review.

**Comment by elikatsis** [comment]
Thanks @kimwnasptd !

/lgtm
/approve

**Pull request merged**
