### PR TITLE
centraldashboard: Add missing links ConfigMap

### PR DESCRIPTION
**Pull request by yanniszark**
/cc @StefanoFioravanzo @kimwnasptd 

For some reason, I missed this in the first PR.

### CODE REVIEW

**Comment by DavidSpek** [comment]
@yanniszark This file was deleted/renamed and updated in https://github.com/kubeflow/kubeflow/pull/5706, so I don't think this PR is correct.

**Comment by yanniszark** [comment]
@DavidSpek thanks for the heads-up. Here is what went wrong:
- PR https://github.com/kubeflow/kubeflow/pull/5706 introduced the new ConfigMap file, but didn't update kustomization.yaml. Thus, the kustomization was broken.

The extra things I fixed are:
- Name the ConfigMap `centraldashboard-links-config`, same as before.
- Fix a small JSON error inside the ConfigMap.

cc @StefanoFioravanzo plz take a look

**Comment by andreyvelich** [comment]
@yanniszark @StefanoFioravanzo As I can see, for Kubeflow 1.3 we moved Katib UI to the `Experiments/AutoML` sub-section.
Will it confuse the user ?

Maybe we should keep Katib in the Root dashboard access, like Pipelines and Notebooks ?
We haven't changed Katib UI yet to hide the menu part and we haven't discussed how we should manage the pages in the Katib UI.

As well, in the docs we introduce the old menu design: https://www.kubeflow.org/docs/components/central-dash/overview/.

Will it be easier for the user to see the Katib UI in the root menu section?

/cc @kimwnasptd @gaocegege @johnugeorge

**Comment by StefanoFioravanzo** [comment]
@yanniszark Note this https://github.com/kubeflow/kubeflow/blob/master/components/centraldashboard/app/k8s_service.ts#L5 
The default name is `centraldashboard-config`. Let's stick with it since the configmap is not just about links.

**Comment by StefanoFioravanzo** [comment]
@andreyvelich Not problem with me moving the Katib menu item one level up in the sidebar. If you confirm this and the others agree, then let's do it

**Comment by DavidSpek** [comment]
I don't really have an opinion on this, but removing Katib from that section would make it contain only one item. Kind of defeats it's purpose, but assuming other links will be added to it relatively soon it should be fine.

**Comment by yanniszark** [comment]
> @yanniszark Note this https://github.com/kubeflow/kubeflow/blob/master/components/centraldashboard/app/k8s_service.ts#L5
The default name is centraldashboard-config. Let's stick with it since the configmap is not just about links.

Got it, thanks! I kept the name as `centraldashboard-config` and edited the manifests accordingly.

**Comment by andreyvelich** [comment]
> @andreyvelich Not problem with me moving the Katib menu item one level up in the sidebar. If you confirm this and the others agree, then let's do it

Sure. What do you think @gaocegege @johnugeorge @kimwnasptd ?

> I don't really have an opinion on this, but removing Katib from that section would make it contain only one item. Kind of defeats it's purpose, but assuming other links will be added to it relatively soon it should be fine.

Yes, we have plans with @kimwnasptd to integrate various pages for the new Katib UI and directly add them to the Central Dashboard.
From my understanding, it makes more sense if Katib have independent section in the Central Dashboard with the different sub-sections in the future.

**Comment by StefanoFioravanzo** [comment]
Thanks @yanniszark ! 
/lgtm
/approve

**Comment by StefanoFioravanzo** [comment]
@andreyvelich let's discuss and address this tomorrow in another PR @kimwnasptd will open to add some other menu items to Centraldashboard

**Comment by yanniszark** [comment]
Thanks @StefanoFioravanzo!
@andreyvelich let's address the Katib links issue in a follow-up PR.

**Comment by andreyvelich** [comment]
Sure thank you @yanniszark @StefanoFioravanzo !

**Comment by yanniszark** [comment]
I'm taking the thumbs-up in Stefano's post to mean ok then :) 
/remove-hold

**Pull request merged**
