### PR TITLE
kfctl: OWNERS: add yanniszark

### PR DESCRIPTION
**Pull request by yanniszark**
This PR adds me (@yanniszark) to the OWNERS files of kfctl.

Signed-off-by: Yannis Zarkadas <yanniszark@arrikto.com>

---
This change is [Reviewable](https://reviewable.io/reviews/kubeflow/kubeflow/3506)

### CODE REVIEW

**Comment by yanniszark** [comment]
@kkasravi @jlewi @abhi-g can you please check and approve ?

**Comment by yanniszark** [comment]
@kkasravi @jlewi @abhi-g kind reminder on this

**Comment by jlewi** [comment]
Looks like
kubeflow-presubmit-kfctl-beta-3506-a26e6e7-5013-9cfa

I wonder if this is an old test and we should just delete?
I haven't noticed this test getting triggered on other PRs which is why I suspect that.
https://prow.k8s.io/view/gcs/kubernetes-jenkins/pr-logs/pull/kubeflow_kubeflow/3594/kubeflow-presubmit/1146135465074626560/

**Comment by yanniszark** [comment]
@jlewi it seems that it needed a rebase.
Should be good to go now!

**Pull request merged**
