### PR TITLE
[Windows] Windows Scripts for Setting up Kubeflow

### PR DESCRIPTION
**Pull request by avdaredevil**
## About
Our documentation setup does not have a section for windows. I have created a powershell script that can download and install the same dependencies on windows with multiple strategies:

#### Installation Strategies
- **Ksonnet**: Git
- **Kubectl**: GCloud, Chocolatey, PSGallery
- **Minikube**: Chocolatey, Github-Release (_scan latest version, download with git APIs_)

## Features
- Color Coded output
- Range for `cpu`,`ram`,`disk` is enforced using validation, and max can never be below the minimum (_current limitation in the bash script_)
- Likewise all inputs are validated (_and reprompted for user to fix_)
  - Numeric ranges are enforced
  - Virtualization enum values are checked
  - Filesystem paths are verified on input
- Fault detection and error handling
- Hyper-V Support with custom flow

#### Default Launch
image

#### Hyper-V Launch
image

---
This change is [Reviewable](https://reviewable.io/reviews/kubeflow/kubeflow/2650)

### CODE REVIEW

**Comment by prodonjs** [comment]
@avdaredevil This PR is pretty old at this point so probably needs to be rebased to pass presubmit and get merged.

**Comment by avdaredevil** [comment]
Rebased @prodonjs

**Pull request closed without merging**
