### PR TITLE
use Istio for JWT validation

### PR DESCRIPTION
**Pull request by lluunn**
Changes are in iap.libsonnet controlled by param: useIstio.
Major differences:
1. no envoy service and deployment, and thus no envoy-config
1. setup_backend.sh now creates policy for JWT validation (instead of sed envoy config)
1. update_backend.sh creates several routing rules (health check, ambassador)

/cc @jlewi

needs #2352 
related: #2261 

---
This change is [Reviewable](https://reviewable.io/reviews/kubeflow/kubeflow/2348)

### CODE REVIEW

**Comment by lluunn** [comment]
health check not working yet

**Comment by lluunn** [comment]
Ready for review.
/assign @jlewi 
/assign @kunmingg

**Comment by kunmingg** [comment]
If most changes happen around iap, can we have iap-istio component instead of whole new package?
Feels a bit confusing that both pkg contains same prototypes, as once user generate gcp components from pkg, later user can't tell which pkg they used unless check source code.

**Comment by jlewi** [comment]
I like @kunmingg 's suggestion? Perhaps we could just add a bool parameter "use_istio" and then conditionally install various components and configure them differently based on that parameter?

**Comment by lluunn** [comment]
make it a param now, PTAL

**Comment by lluunn** [comment]
/hold
testing

**Comment by lluunn** [comment]
/hold cancel
tested locally, will add e2e test

**Comment by jlewi** [comment]
/lgtm
/hold 
for @kunmingg

**Comment by kunmingg** [comment]
/hold cancel
lgtm
/approve

**Pull request merged**
