### PR TITLE
[kfctl] set default project and zone for GCP

### PR DESCRIPTION
**Pull request by zhenghuiwang**
fixes https://github.com/kubeflow/kubeflow/issues/3923

---
This change is [Reviewable](https://reviewable.io/reviews/kubeflow/kubeflow/4263)

### CODE REVIEW

**Comment by lluunn** [comment]
thanks
/lgtm
/approve

**Comment by swiftdiaries** [comment]
Hey @zhenghuiwang 
Could you please test this with the E2E?
I think [this](https://github.com/kubeflow/kubeflow/blob/master/py/kubeflow/kubeflow/ci/kfctl_go_test_utils.py#L149) is the part where we set the project in the config
By removing it, we should see the project automatically inferred.

**Comment by zhenghuiwang** [comment]
> Hey @zhenghuiwang
> Could you please test this with the E2E?
> I think [this](https://github.com/kubeflow/kubeflow/blob/master/py/kubeflow/kubeflow/ci/kfctl_go_test_utils.py#L149) is the part where we set the project in the config
> By removing it, we should see the project automatically inferred.

@swiftdiaries thanks for the suggestion, which makes a lot of sense to test it e2e if it is easy to do.

Looking at the pointed code, I find it is a util func not a test. Although the func is named `get_config_spec`, it actually sets the project name explicitly. Deleting that line may surprise the func caller when the default project name is not the same as the name passed in.

**Pull request merged**
