### PR TITLE
[openmpi] support non-root users run jobs (introducing `runAsUser`, `runAsGroup`, `supplementalGroups`)

### LINKED ISSUE #793: [openmpi] support to run a job with non-root users
Currently, openmpi package's `init.sh` assume to run only with `root` user.  However, users sometimes want to run with non-root users for some reasons.  So, I would like to support

- non-root users in `init.sh`
- `securityContext (RunAs, RunAsGroup)` to specify running user.
  - perhaps `supplementalGroups`

It is because, when interacting with NFS Volumes, administrator restricts root access even for containers because uid/gid would be propagated to the volumes.

/area openmpi
/priority p1

### PR DESCRIPTION
**Pull request by everpeace**
Fixes #793 

# Changes
- introduce `runAsUser`, `runAsGroup`, `supplementalGroups` parameters.
- If these parameters set, this package will put `securityContext` to the master/worker pods.
- changed `init.sh` to support non-root users can spawn sshd servers.
- changed openmpi-controller path from `/root` to `/openmpi-controller` so that non-root users can execute the controller
  - this bump version of openmpi-controller docker image.

# Note
__new openmpi-controller's docker image needs to be published before merging this__.

@jiezhang I need your assistance.  Could you build and publish `jiezhang/openmpi-controller:0.0.3` before this pr is approved 🙇  ??

---
This change is [Reviewable](https://reviewable.io/reviews/kubeflow/kubeflow/820)

### CODE REVIEW

**Comment by pdmack** [comment]
@everpeace, please [autoformat_jsonnet.sh](https://github.com/kubeflow/kubeflow/blob/master/scripts/autoformat_jsonnet.sh).

**Comment by jiezhang** [comment]
Review status: 0 of 7 files reviewed at latest revision, all discussions resolved, some commit checks failed.

---

*[components/openmpi-controller/Dockerfile, line 7 at r1](https://reviewable.io/reviews/kubeflow/kubeflow/820#-LCjTP0f6O_5wefkZX1D:-LCjTP0f6O_5wefkZX1E:b-c6cw7n) ([raw file](https://github.com/kubeflow/kubeflow/blob/1fa9a71ca1fbae05712c95645ff58f10eb0bece1/components/openmpi-controller/Dockerfile#L7)):*
> ```Dockerfile
> ENV HOME /root
> 
> RUN mkdir -p /openmpi-controller
> ```

Can you move it to /kubeflow/openmpi/openmpi-controller? Just be consistent with other artifacts (like assets) deployed by this package.

---

*[kubeflow/openmpi/assets/init.sh, line 61 at r1](https://reviewable.io/reviews/kubeflow/kubeflow/820#-LCjTssA32tqdGALPTli:-LCjTssA32tqdGALPTlj:b-mze5x7) ([raw file](https://github.com/kubeflow/kubeflow/blob/1fa9a71ca1fbae05712c95645ff58f10eb0bece1/kubeflow/openmpi/assets/init.sh#L61)):*
> ```Shell
> cp ${OPENMPI_DIR}/assets/ssh_config ${HOME}/.ssh/config
> 
> SSHD_CONFIG=${OPENMPI_DIR}/assets/sshd_config
> ```

nit: all constants declared at the top of the file.

---


*Comments from [Reviewable](https://reviewable.io/reviews/kubeflow/kubeflow/820)*

**Comment by everpeace** [comment]
@jiezhang I fixed my pr about your feedback and rebased it.  Would you mind reviewing it again?

> Sorry I'm unable to move the package to kubeflow due to #197. I'll publish new package once this is merged.

@jiezhang Ok. I understood the situation.  I'll wait for it.

> please autoformat_jsonnet.sh.

@pdmack apologies 🙇   I did it.

**Comment by jlewi** [comment]
/lgtm
/hold 

Putting a hold on this because I think someone more familiar with this should approve.

**Comment by jiezhang** [comment]
Review status: 0 of 7 files reviewed at latest revision, 4 unresolved discussions.

---

*[kubeflow/openmpi/util.libsonnet, line 16 at r2](https://reviewable.io/reviews/kubeflow/kubeflow/820#-LCpJIYV5YEsCcPJqspV:-LCpJIYV5YEsCcPJqspW:bla18zb) ([raw file](https://github.com/kubeflow/kubeflow/blob/cd2d3b66db643bb618c856eb330485ecbddefc71/kubeflow/openmpi/util.libsonnet#L16)):*
> ```
>       [std.splitLimit(keyValue, "=", 1)[0]]: std.splitLimit(keyValue, "=", 1)[1]
>       for keyValue in $.toArray(str)
>     } else {},
> ```

I just realized that resource limits are not set properly when customResources is null. Thanks for fixing this.

---


*Comments from [Reviewable](https://reviewable.io/reviews/kubeflow/kubeflow/820)*

**Comment by everpeace** [comment]
Review status: 0 of 7 files reviewed at latest revision, 5 unresolved discussions.

---

*[kubeflow/openmpi/util.libsonnet, line 16 at r2](https://reviewable.io/reviews/kubeflow/kubeflow/820#-LCpJIYV5YEsCcPJqspV:-LCpesEN9FU9rgitCiZ-:bvm4i42) ([raw file](https://github.com/kubeflow/kubeflow/blob/cd2d3b66db643bb618c856eb330485ecbddefc71/kubeflow/openmpi/util.libsonnet#L16)):*
<details><summary><i>Previously, jiezhang (Jie Zhang) wrote…</i></summary><blockquote>

I just realized that resource limits are not set properly when customResources is null. Thanks for fixing this.
</blockquote></details>

no worry.  sorry for fixing this without mentioning... 

---


*Comments from [Reviewable](https://reviewable.io/reviews/kubeflow/kubeflow/820)*

**Pull request merged**
