### PR TITLE
Refactor the workflow for TF Serving

### PR DESCRIPTION
**Pull request by jlewi**
* Use a script for the commands to build the image.

* Use the DAG functionality of Argo

* Autoformat the files.

* Rename the Dockerfiles so they are consistent i.e. ".cpu" and ".gpu"

* Refactor directories.
  * Move the Dockerfiles into the images directory. There's no reason
    to have them in a separate directory.

---
This change is [Reviewable](https://reviewable.io/reviews/kubeflow/kubeflow/347)

### CODE REVIEW

**Comment by lluunn** [comment]
Reviewed 8 of 10 files at r1.
Review status: 5 of 7 files reviewed at latest revision, 5 unresolved discussions.

---

*[components/k8s-model-server/images/Makefile, line 22 at r1](https://reviewable.io:443/reviews/kubeflow/kubeflow/347#-L6sMLrm7y4J64LN1h5G:-L6sMLrnkUNGgM4RhfwU:b64g3h1) ([raw file](https://github.com/kubeflow/kubeflow/blob/a0eec0200c7ad121cc6e97a8e84a7cfff6545b4c/components/k8s-model-server/images/Makefile#L22)):*
> ```Makefile
> 
> define build
> 	docker build --pull -t $(1)/model-server:${TF_VERSION} -f Dockerfile.cpu .
> ```

Change it to tf-model-server-cpu as in workflow?

---

*[components/k8s-model-server/images/releaser/components/workflows.libsonnet, line 140 at r1](https://reviewable.io:443/reviews/kubeflow/kubeflow/347#-L6sMaXTkLS3FOYQX1yx:-L6sMaXTkLS3FOYQX1yy:bn6g6rr) ([raw file](https://github.com/kubeflow/kubeflow/blob/a0eec0200c7ad121cc6e97a8e84a7cfff6545b4c/components/k8s-model-server/images/releaser/components/workflows.libsonnet#L140)):*
> ```
>                 // We need to explicitly specify bash because
>                 // build_image.sh is not in the container its a volume mounted file.
>                 "/bin/bash", "-c",                
> ```

trailing space

---

*[components/k8s-model-server/images/releaser/components/workflows.libsonnet, line 197 at r1](https://reviewable.io:443/reviews/kubeflow/kubeflow/347#-L6sNRmREO0BUx7r1MAB:-L6sNRmREO0BUx7r1MAC:b-oogauf) ([raw file](https://github.com/kubeflow/kubeflow/blob/a0eec0200c7ad121cc6e97a8e84a7cfff6545b4c/components/k8s-model-server/images/releaser/components/workflows.libsonnet#L197)):*
> ```
>             {
>               name: "e2e",
>                dag: {
> ```

Is this a new feature?

---

*[components/k8s-model-server/images/releaser/components/workflows.libsonnet, line 200 at r1](https://reviewable.io:443/reviews/kubeflow/kubeflow/347#-L6sNV579lpHJ1e8qHst:-L6sNV579lpHJ1e8qHsu:b-7jbqan) ([raw file](https://github.com/kubeflow/kubeflow/blob/a0eec0200c7ad121cc6e97a8e84a7cfff6545b4c/components/k8s-model-server/images/releaser/components/workflows.libsonnet#L200)):*
> ```
>                tasks: [
>                   {name: "checkout",
>                    template: "checkout",                
> ```

space

---

*[components/k8s-model-server/images/releaser/environments/prow/params.libsonnet, line 9 at r1](https://reviewable.io:443/reviews/kubeflow/kubeflow/347#-L6sN3S5eU4RJxH4BRNi:-L6sN3S6p6VO76u7a7il:b-z82wwq) ([raw file](https://github.com/kubeflow/kubeflow/blob/a0eec0200c7ad121cc6e97a8e84a7cfff6545b4c/components/k8s-model-server/images/releaser/environments/prow/params.libsonnet#L9)):*
> ```
>     //   replicas: params.global.replicas,
>     // },
>     workflows +: {
> ```

Do you need this change?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/kubeflow/kubeflow/347)*

**Comment by lluunn** [comment]
Some comments and questions. 
/lgtm

**Comment by jlewi** [comment]
Review status: 5 of 7 files reviewed at latest revision, 5 unresolved discussions.

---

*[components/k8s-model-server/images/Makefile, line 22 at r1](https://reviewable.io:443/reviews/kubeflow/kubeflow/347#-L6sMLrm7y4J64LN1h5G:-L6tL8pYMAfLSRlX1rng:b-896fix) ([raw file](https://github.com/kubeflow/kubeflow/blob/a0eec0200c7ad121cc6e97a8e84a7cfff6545b4c/components/k8s-model-server/images/Makefile#L22)):*
<details><summary><i>Previously, lluunn (Lun-Kai Hsu) wrote…</i></summary><blockquote>

Change it to tf-model-server-cpu as in workflow?
</blockquote></details>

Done.

---

*[components/k8s-model-server/images/releaser/components/workflows.libsonnet, line 140 at r1](https://reviewable.io:443/reviews/kubeflow/kubeflow/347#-L6sMaXTkLS3FOYQX1yx:-L6tLGa-BfGV17EtDCua:b-896fix) ([raw file](https://github.com/kubeflow/kubeflow/blob/a0eec0200c7ad121cc6e97a8e84a7cfff6545b4c/components/k8s-model-server/images/releaser/components/workflows.libsonnet#L140)):*
<details><summary><i>Previously, lluunn (Lun-Kai Hsu) wrote…</i></summary><blockquote>

trailing space
</blockquote></details>

Done.

---

*[components/k8s-model-server/images/releaser/components/workflows.libsonnet, line 197 at r1](https://reviewable.io:443/reviews/kubeflow/kubeflow/347#-L6sNRmREO0BUx7r1MAB:-L6tLHrdGHqxnEM_3_4z:bf8eu9v) ([raw file](https://github.com/kubeflow/kubeflow/blob/a0eec0200c7ad121cc6e97a8e84a7cfff6545b4c/components/k8s-model-server/images/releaser/components/workflows.libsonnet#L197)):*
<details><summary><i>Previously, lluunn (Lun-Kai Hsu) wrote…</i></summary><blockquote>

Is this a new feature?
</blockquote></details>

Its a new feature in Argo that allows you to specify arbitrary dags.

---

*[components/k8s-model-server/images/releaser/components/workflows.libsonnet, line 200 at r1](https://reviewable.io:443/reviews/kubeflow/kubeflow/347#-L6sNV579lpHJ1e8qHst:-L6tLOmfInXYER-CtZxk:b-896fix) ([raw file](https://github.com/kubeflow/kubeflow/blob/a0eec0200c7ad121cc6e97a8e84a7cfff6545b4c/components/k8s-model-server/images/releaser/components/workflows.libsonnet#L200)):*
<details><summary><i>Previously, lluunn (Lun-Kai Hsu) wrote…</i></summary><blockquote>

space
</blockquote></details>

Done.

---

*[components/k8s-model-server/images/releaser/environments/prow/params.libsonnet, line 9 at r1](https://reviewable.io:443/reviews/kubeflow/kubeflow/347#-L6sN3S5eU4RJxH4BRNi:-L6tLl4JNvOb8ynQSj6M:bm9q6dg) ([raw file](https://github.com/kubeflow/kubeflow/blob/a0eec0200c7ad121cc6e97a8e84a7cfff6545b4c/components/k8s-model-server/images/releaser/environments/prow/params.libsonnet#L9)):*
<details><summary><i>Previously, lluunn (Lun-Kai Hsu) wrote…</i></summary><blockquote>

Do you need this change?
</blockquote></details>

Technically no. But its more convenient if we just accept these changes rather than expecting that every PR zero out these changes.  

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/kubeflow/kubeflow/347)*

**Comment by jlewi** [comment]
@lluunn Thanks. PTAL.

**Comment by lluunn** [comment]
Reviewed 3 of 10 files at r1, 2 of 2 files at r2.
Review status: all files reviewed at latest revision, 5 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/kubeflow/kubeflow/347)*

**Pull request merged**
