### PR TITLE
update profile creation defaults to match documentation

### PR DESCRIPTION
**Pull request by surajkota**
[Documentation says](https://www.kubeflow.org/docs/components/multi-tenancy/getting-started/#automatic-creation-of-profiles) its enabled by default but in reality it is not.

### CODE REVIEW

**Comment by surajkota** [comment]
@thesuperzapper @kimwnasptd it will be great if we can merge in this quick change for 1.5

**Comment by thesuperzapper** [comment]
@surajkota [those docs](https://www.kubeflow.org/docs/components/multi-tenancy/getting-started/#automatic-creation-of-profiles) are out of date, the parameter name is not even `registration-flow` anymore, its not `CD_REGISTRATION_FLOW`.
But I do think the sensible default is to create profiles (which was the behavior for all previous releases until Kubeflow 1.4).

I will let @kimwnasptd do an `/lgtm`, as we will need to update the manifests repo if this is merged for 1.5.

/approve

**Comment by surajkota** [comment]
Good point. I can raise a PR for the docs once this gets merged

**Review by AlexandreBrown — APPROVED** [review]

**Comment by thesuperzapper** [comment]
@kimwnasptd can you chuck us an `/lgtm`?

**Comment by surajkota** [comment]
@kimwnasptd ping

**Comment by surajkota** [comment]
Closing in favour of https://github.com/kubeflow/website/pull/3023

**Pull request closed without merging**
