### PR TITLE
frontend update for v0.6

### PR DESCRIPTION
**Pull request by kunmingg**
- update request body based on user's selection
- refer to release branch head version

---
This change is [Reviewable](https://reviewable.io/reviews/kubeflow/kubeflow/3906)

### CODE REVIEW

**Comment by kunmingg** [comment]
@abhi-g 
As of now kfctl on GCP will always create PD.
Should we remove the option `Create Permanent Storage` from UI as well and always create PD?

**Comment by prodonjs** [comment]
/lgtm
/approve

Thanks for the making the change!

**Comment by kunmingg** [comment]
Thanks @prodonjs !

**Pull request merged**
