### PR TITLE
Update cofig file versions

### PR DESCRIPTION
**Pull request by gabrielwen**
- Update default version in kfctl go binary to v0.6.2 tag.
- Update config files to pin to commit for both kubeflow and manifest repos.

---
This change is [Reviewable](https://reviewable.io/reviews/kubeflow/kubeflow/3978)

### CODE REVIEW

**Comment by yanniszark** [comment]
@gabrielwen can you also please update the existing_arrikto config file?

I imagine this won't be merged until everything in https://github.com/kubeflow/kubeflow/issues/3860 is resolved?

**Comment by gabrielwen** [comment]
> @gabrielwen can you also please update the existing_arrikto config file?
> 
> I imagine this won't be merged until everything in #3860 is resolved?

right, that's the idea.  let me update that file you mentioned :)

**Comment by gabrielwen** [comment]
@yanniszark spoke to Jeremy, this config file change is not related to the release.  The release is mainly to release kfctl binary.  For the config file, we can always use raw content in branches.

**Pull request merged**
