### PR TITLE
rename kubeflow/core to kubeflow/common

### LINKED ISSUE #42: Split up core ksonnet package into separate packages
The core package consists of 

- JupyterHub
- TfJob CRD
- NFS Provisioner

These should probably each be their own package. The core component could then depend on these packages.

The reason we didn't do this in the initial PR #36 was because ksonnet doesn't yet support having packages depend on other packages see ksonnet/ksonnet#231

### PR DESCRIPTION
**Pull request by kkasravi**
fixes #42

---
This change is [Reviewable](https://reviewable.io/reviews/kubeflow/kubeflow/2107)

### CODE REVIEW

**Comment by jlewi** [comment]
/unassign @gaocegege 
/assign @kunmingg 

@kunmingg Do we need to make changes to the click to deploy app to use the renamed package?

**Comment by jlewi** [comment]
I don't think any click to deploy app changes are needed.

WebApp installs all the packages in the registry
https://github.com/kubeflow/kubeflow/blob/3693d5948700a8ecf80a19faecc13c67d602e921/bootstrap/cmd/bootstrap/app/ksServer.go#L586

So installing the packages doesn't need to change given the rename.

It looks like we do optionally install specific packages
https://github.com/kubeflow/kubeflow/blob/3693d5948700a8ecf80a19faecc13c67d602e921/bootstrap/cmd/bootstrap/app/ksServer.go#L621

But it doesn't look like we specify any packages (we just rely on installing all packages by name).

I also looked at our app config and it doesn't look like we specify package name for components.
https://github.com/kubeflow/kubeflow/blob/3693d5948700a8ecf80a19faecc13c67d602e921/bootstrap/cmd/bootstrap/app/server.go#L52

It looks like we rely on component names being unique.

**Comment by jlewi** [comment]
@kkasravi So I think this is good to go but you'll need to resolve the conflicts.

/lgtm
/approve

**Comment by jlewi** [comment]
GCP deployment failed because of static IP quota issues

```
W
+ '[' 0 -eq 0 ']'
+ echo kfctl-3e64 exists
+ gcloud deployment-manager --project=kubeflow-ci deployments update kfctl-3e64 --config=cluster-kubeflow.yaml
The fingerprint of the deployment is WV3L2UQKkQclPpYbfpVnBQ==
Waiting for update [operation-1545179005222-57d5505b87c70-97f0f54a-5df72764]...
.........failed.
ERROR: (gcloud.deployment-manager.deployments.update) Error in Operation [operation-1545179005222-57d5505b87c70-97f0f54a-5df72764]: errors:
- code: RESOURCE_ERROR
 location: /deployments/kfctl-3e64/resources/kfctl-3e64-ip
 message: "{\"ResourceType\":\"compute.v1.globalAddress\",\"ResourceErrorCode\":\"\
   403\",\"ResourceErrorMessage\":{\"code\":403,\"errors\":[{\"domain\":\"usageLimits\"\
   ,\"message\":\"Quota 'STATIC_ADDRESSES' exceeded. Limit: 15.0 globally.\",\"reason\"\
   :\"quotaExceeded\"}],\"message\":\"Quota 'STATIC_ADDRESSES' exceeded. Limit: 15.0\
   \ globally.\",\"statusMessage\":\"Forbidden\",\"requestPath\":\"https://www.googleapis.com/compute/v1/projects/kubeflow-ci/global/addresses\"\
   ,\"httpMethod\":\"POST\"}}"
- code: RESOURCE_ERROR
 location: /deployments/kfctl-3e64/resources/kfctl-3e64
 message: "{\"ResourceType\":\"container.v1.cluster\",\"ResourceErrorCode\":\"403\"\
   ,\"ResourceErrorMessage\":{\"code\":403,\"message\":\"Insufficient regional quota\
   \ to satisfy request: resource \\\"CPUS\\\": request requires '16.0' and is short\
   \ '4.0'. project has a quota of '320.0' with '12.0' available.\",\"status\":\"\
   PERMISSION_DENIED\",\"statusMessage\":\"Forbidden\",\"requestPath\":\"https://container.googleapis.com/v1/projects/kubeflow-ci/zones/us-east1-d/cluster
s\"\
   ,\"httpMethod\":\"POST\"}}"
Command failed: /mnt/test-data-volume/kubeflow-presubmit-kfctl-2107-c0dd930-4718-3e64/src/kubeflow/kubeflow/scripts/kfctl.sh apply platform
command didn't succeed
```

**Comment by jlewi** [comment]
Created #2146 for the test flake.

**Comment by kunmingg** [comment]
@jlewi 
"It looks like we do optionally install specific packages"
Only useful when people add package but didn't update registry config, so registry list won't show those anonymous pkgs. We do force install by specify pkg.

**Comment by oshev** [comment]
After this change everyone who had `ks pkg install kubeflow/core` in their scripts will wonder what happened becuase it'll fail with 404... Could it be done in some smoother way? I wonder because this kind of straightforward approach seem to threaten the stability of the projects depending on KubeFlow.

**Comment by oshev** [comment]
Also, all blog posts explaining how to work with KubeFlow won't work, e.g. https://ai.intel.com/lets-flow-within-kubeflow/

**Comment by oshev** [comment]
OK, I figured out. I guess I has to add @${KUBEFLOW_VERSION} to each `ks pkg install kubeflow...` command and fix the scripts to the latest specific stable version.

**Comment by jlewi** [comment]
@oshev I'm not sure I understood the question. Were you not using kfctl? The recommended way to install Kubeflow is using kfctl.sh. kfctl.sh is versioned and each version will install the correct set of packages for each version.

If you want to discuss more I'd suggest opening up a new issue.

**Comment by oshev** [comment]
Apologies, I didn't know about `kfctl`. I'm checking it now, not sure how I missed it. Thanks for pointing out!

**Pull request merged**
