### PR TITLE
WIP: Adds generalized webhook admission

### LINKED ISSUE #2844: Generalize the admission webhook to set environment variables and secrets based on config file
The admission webhook 
https://github.com/kubeflow/kubeflow/blob/master/components/gcp-admission-webhook/main.go

Right now hardcodes the environment variables and secrets to mount.
https://github.com/kubeflow/kubeflow/blob/c5977793d5615e4ff867d5f0853e26a1201deb13/components/gcp-admission-webhook/main.go#L51

Can we make this configurable? e.g. make it easy for users to provide a spec describing the environment variables and secrets to mount?

Can we do something like PodPreset?
https://kubernetes.io/docs/tasks/inject-data-application/podpreset/

A simple thing would be to make the web-hook configurable via a YAML file provided via config map.

/cc @eLco @lluunn

### PR DESCRIPTION
**Pull request by zabbasi**
- integrated the existing gcp-admission-webhook with an implementation of [podpreset](https://github.com/jpeeler/podpreset-crd)
- tested for jupyter notebooks
- resolves #2844
- currently integrated with jupyter-web-app to add all available podpresets to notebook resources. This needs to be improved according to #2992 
- related to https://github.com/kubeflow/manifests/pull/33
- please [read here](https://github.com/zabbasi/kubeflow/blob/webhook11/components/admission-webhook/README.md) to see how it works.

/cc @lluunn @kimwnasptd @jlewi

---
This change is [Reviewable](https://reviewable.io/reviews/kubeflow/kubeflow/3186)

### CODE REVIEW

**Comment by jlewi** [comment]
Would it make sense to split this into 2 PRs one updating the Jupyter web app and one updating the general admission hook?

**Comment by zabbasi** [comment]
> Would it make sense to split this into 2 PRs one updating the Jupyter web app and one updating the general admission hook?

Good idea. Will split it to two PRs (1 generalized webhook, and 2) updating notebook controller and jupyter-web-app

**Comment by lluunn** [comment]
thanks, let me know when it's ready for review

**Comment by zabbasi** [comment]
split this to two prs: 1- #3202  which adds generalized webhook without modifying jupyter-web-app and notebook controller, 2) another pr will be generated after #3202 is merged to update jupyter-web-app and notebook controller.

**Pull request closed without merging**
