### PR TITLE
cherry pick missing commits into v1.3-branch

### PR DESCRIPTION
**Pull request by thesuperzapper**
This PR cherry picks commits from master into `v1.3-branch`

When we tag Kubeflow 1.3-RC1 we need to change the kustomization image tags to RC1 (as this changes them to the master ones for now)

### CODE REVIEW

**Comment by thesuperzapper** [comment]
@yanniszark if you are a writer on the repo, you could directly push these commits (to prevent the googlebot consent issue).

Otherwise @kimwnasptd @DavidSpek and @yanniszark can just reply `@googlebot I consent.`

**Comment by DavidSpek** [comment]
@googlebot I consent.

**Comment by kimwnasptd** [comment]
@googlebot I consent.

**Comment by yanniszark** [comment]
@googlebot I consent.

**Pull request merged**
