### PR TITLE
Secure access to KFAM

### PR DESCRIPTION
**Pull request by DavidSpek**
Solves: https://github.com/kubeflow/kubeflow/issues/6228

This PR secures access to KFAM so it is not accessible to users.

/cc @thesuperzapper

### CODE REVIEW

**Comment by DavidSpek** [comment]
/freeze

@kubeflow/wg-notebooks-leads Not sure if you guys realize this, but without securing the KFAM API any user can take ownership of any namespace in the cluster. This includes the `kube-system` namespace, allowing a user to effectively take ownership of the entire cluster. It would have been nice to have this solved without exposing the vulnerability publicly, but given the lack of responsiveness I guess this is the only way forward.

It's probably a good idea to put out a CVE advisory related to this issue.

**Comment by soleares** [comment]
I can confirm that during security testing we were able to fully take over a cluster from an uploaded pipeline step container/pod due to this issue. This fix remediates the issue.

**Comment by thesuperzapper** [comment]
I am pretty sure this will not fully address the issue, as [`STRICT` MTLS mode](https://istio.io/latest/docs/concepts/security/#peer-authentication) will also be required to be enabled in the istio cluster/namespace to prevent non-istio access.

**Comment by soleares** [comment]
@thesuperzapper This fix does block access to the kfam service from non istio pipeline step pods in user profile namespaces. Was there something additional you were thinking of?

**Comment by kimwnasptd** [comment]
Regarding the `PERMISSIVE` mode for mTLS, AFAIK it's an orthogonal discussion. The mTLS setting is for deciding if traffic should be allowed between pods without a sidecar. 

But in this case's AuthorizationPolicy, Istio will only allow traffic to reach KFAM if the requests come from the CentralDashboard and this identity is deduced from sidecars. If a Pod without a sidecar tries to talk to KFAM then from an mTLS point of view it should be able to, in PERMISSIVE mode, but the AuthorizationPolicy would block the request since Istio can't deduce the workload id of that request [no sidecar].

Either way we need these AuthorizationPolicies, so I'm moving forward with the PR.

Thank you for your work @DavidSpek, and apologies for the too delayed review on this

/lgtm
/approve

**Pull request merged**
