### PR TITLE
Initialize the Jupyter web app frontend in crud-web-apps

### PR DESCRIPTION
**Pull request by kimwnasptd**
This is the last part for #5310 and follow up of #5316

In this PR I introduce the bulk of the frontend. I've made some small backend changed to accommodate some of the UI's new features. 

This UI should be on par with the current one under `components/jupyter-web-app` with only exclusion being the functionality of  #5086. But since I want to unblock @thesuperzapper and work on integrating the features from #5280 let's move forward with this PR and I'll also by working on added this functionality.

Some new features:
**Start/Stop Notebooks** @thesuperzapper has also implemented an iteration on this on #5280 which we could also use
nb-start-stop

**Advanced options** for allowing the users to specify the image pull policy of the Notebook's image
advanced-options

**Don't allow selecting GPUs that are not installed**
gpus

As with #5316 we (Arrikto) are deploying this jupyter web app on MiniKF and have extensively tested it. So @elikatsis @yanniszark and @StefanoFioravanzo will most probably not have something big to propose in the review.

cc @thesuperzapper

### CODE REVIEW

**Comment by thesuperzapper** [comment]
@kimwnasptd We need to get this merged soon if we want to make the Kubeflow 1.2 cut (which is realistically in a few days).

To get these changes ready for release (after this PR is merged), we need to:
* update the manifests repo to replace the `jupyter-web-app` YAML
* implement the other features from #5280

Alternatively, we could:
* update #5280 with a few small changes (e.g. re-add the CPU/RAM columns to the Notebook screen)
* merge #5280 
* bump this rewrite to Kubeflow 1.3

**Comment by thesuperzapper** [comment]
@kimwnasptd I would review this, but I need to be in the OWNERS to approve it, should I raise a PR for that?

**Comment by kimwnasptd** [comment]
Didn't have a lot of cycles the past days, but I'm not ready to keep on pushing on this.

@thesuperzapper sure, adding you as an approver will allow us to coordinate and develop faster. I'll comment also in the corresponding PR.

In the mean time @elikatsis and @StefanoFioravanzo you can move forward with merging this PR so we can start adding new features.

**Pull request merged**
