### PR TITLE
Tag and update v0.3.0 release for chainer-operator

### PR DESCRIPTION
**Pull request by everpeace**
- updated `releasing/image_tags.yaml` for tagging `v0.3.0`  on `gcr.io/kubeflow-images-public/chainer-operator:e63dee1`
- updated default chainer-operator image in `chainer-operator` prototype with `gcr.io/kubeflow-images-public/chainer-operator:v0.3.0`
- delete chainer-operator from releaser because chainer-operator docker image is now built on postsubmit job in prow on chainer-operator repo (kubeflow/chainer-operator#26)

ref: https://github.com/kubeflow/chainer-operator/issues/25

---
This change is [Reviewable](https://reviewable.io/reviews/kubeflow/kubeflow/1552)

### CODE REVIEW

**Comment by jlewi** [comment]
I don't think we should submit this until the new image is built and tagged.
How is the new image going to be built and tagged?
Do we need to wait for the releaser to create a new image and then tag it with the 0.3 tag?

**Comment by everpeace** [comment]
@jlewi sorry for rush.    Would you mind giving me some instruction because I'm not familiar with kubeflow release process?? Thanks in advance 🙇 

If I correctly understood how other operator images will be release/tagged and default images in prototypes will be bumped, I will see what my next step is.

**Comment by abhi-g** [comment]
@everpeace Please see if this helps: https://github.com/kubeflow/kubeflow/blob/master/docs_dev/releasing.md

**Comment by jlewi** [comment]
I think in a different PR you submitted a change to automatically build a chainer image as part of our nightly builds.

If that's working at some point that should publish a Docker image for chainer. The tag won't be "0.3.0". So your options at that point would be to add someone with appropriate GCR permissions to manually add the tag to that image; or else just go with whatever tag that image used (a datastamp and git hash)

**Comment by everpeace** [comment]
Thank you @aghi-g and @jlewi for information and advise 🙇 

> or else just go with whatever tag that image used (a datastamp and git hash)

I would like to go with this plan.  Where can I find nightly build job log/status??
Once new official chainer image was built, I will update the prototype's default image with it.

**Comment by jlewi** [comment]
You can check http://gcr.io/kubeflow-images-public/chainer to see the images that are currently built.

It looks like the release for chainer release workflow isn't running successfully because it can't find the build_image.sh script that the release workflow is added. Did you create a build_image.sh file as described here
https://github.com/kubeflow/kubeflow/blob/master/docs_dev/releasing.md#create-release-workflow

I suggest we move the conversation into slack #release for faster coordination.

Note the cron job to run the release workflows is also broken and I'm working on fixing that  kubeflow/kubeflow#1563

**Comment by everpeace** [comment]
> Did you create a build_image.sh file as described here

Oh, I forgot adding the script. I will.

> I suggest we move the conversation into slack #release for faster coordination.

sure.  I will.

> Note the cron job to run the release workflows is also broken and I'm working on fixing that 

Thank you so much!

**Comment by jlewi** [comment]
Please ping the PR when the image exists and this is ready to be committed.

**Comment by everpeace** [comment]
@jlewi Finally, I think this pr is now ready.

Could you do me a favor?  I updated `releasing/image_tags.yaml` for tagging `chainer-operator:v0.3.0`.  Because I don't have permission, could you execute `run_apply_image_tags.sh` ??

**Comment by jlewi** [comment]
I applied the image tag. Looks like you need to resolve some merge conflicts though.

**Pull request merged**
