### PR TITLE
release workflow bug fixes and doc update

### PR DESCRIPTION
**Pull request by kunmingg**
support https://github.com/kubeflow/kubeflow/issues/1020.
First user of auto-release prototype.

---
This change is [Reviewable](https://reviewable.io/reviews/kubeflow/kubeflow/1032)

### CODE REVIEW

**Comment by jlewi** [comment]
Review status: 0 of 10 files reviewed, 1 unresolved discussion (waiting on @kunmingg, @johnugeorge, and @jlewi)

---

*[docs_dev/releasing.md, line 30 at r1](https://reviewable.io/reviews/kubeflow/kubeflow/1032#-LFPSX1W78SN_7cgkJHb:-LFPSX1W78SN_7cgkJHc:b-4giar3) ([raw file](https://github.com/kubeflow/kubeflow/blob/b5c7108a9256b3c25f6e4bf08694f005df6f3e85/docs_dev/releasing.md#L30)):*
> ```
> executable
> ```
suggest changing the text to

which contains a script, build_image.sh which has the executable bit set.

---


*Comments from [Reviewable](https://reviewable.io/reviews/kubeflow/kubeflow/1032)*

**Comment by johnugeorge** [comment]
@kunmingg Why do we need vendor code in the app?

**Comment by jlewi** [comment]
@johnugeorge These are ksonnet vendor'd dependencies. If we don't check in vendor then anyone who checks it out will find its broken. And to my knowledge ksonnet doesn't provide a tool to easily reconstruct vendor.

**Pull request merged**
