### PR TITLE
Use empty list when OIDC not being used

### PR DESCRIPTION
**Pull request by hgrsd**
See comment by @Jeffwan on https://github.com/kubeflow/kubeflow/pull/3272

---
This change is [Reviewable](https://reviewable.io/reviews/kubeflow/kubeflow/3302)

### CODE REVIEW

**Comment by Jeffwan** [comment]
@hgrsd Thanks for your first contribution!
1. Could you change the title to more meaningful one like "Use empty list when OIDC not being used" ?
2. Kubeflow require contributors to sign CLA.  Please visit https://cla.developers.google.com/ to sign.

**Comment by hgrsd** [comment]
> @hgrsd Thanks for your first contribution!
> 
>     1. Could you change the title to more meaningful one like "Use empty list when OIDC not being used" ?
> 
>     2. Kubeflow require contributors to sign CLA.  Please visit https://cla.developers.google.com/ to sign.

Thank you -- both done.

**Pull request merged**
