### PR TITLE
Ignore Deleted Notebook cr in notebook controller

### PR DESCRIPTION
**Pull request by mofanke**
fix issue https://github.com/kubeflow/kubeflow/issues/5982

### CODE REVIEW

**Comment by mofanke** [comment]
> @googlebot I signed it!

@googlebot I signed it!

**Review by mofanke — COMMENTED** [review]
fix https://github.com/kubeflow/kubeflow/issues/6043

**Comment by MartinForReal** [comment]
Thanks for your contribution! 
I think "Ignore Deleted Notebook cr in notebook controller" adds more context to pr description. How do you think? @mofanke

**Comment by mofanke** [comment]
> Thanks for your contribution!
> I think "Ignore Deleted Notebook cr in notebook controller" adds more context to pr description. How do you think? @mofanke
thanks for the advice

**Comment by MartinForReal** [comment]
Could you please merge the commits as requested by https://github.com/kubernetes/community/blob/master/contributors/guide/contributor-cheatsheet/README-zh.md#%E5%8E%8B%E7%BC%A9%E6%8F%90%E4%BA%A4

**Comment by mofanke** [comment]
> Could you please merge the commits as requested by https://github.com/kubernetes/community/blob/master/contributors/guide/contributor-cheatsheet/README-zh.md#%E5%8E%8B%E7%BC%A9%E6%8F%90%E4%BA%A4

sorry, i don't know why this pr was closed.

**Comment by mofanke** [comment]
> Could you please merge the commits as requested by https://github.com/kubernetes/community/blob/master/contributors/guide/contributor-cheatsheet/README-zh.md#%E5%8E%8B%E7%BC%A9%E6%8F%90%E4%BA%A4

@MartinForReal sorry, i don't know why this pr closed

**Comment by mofanke** [comment]
@googlebot I fixed it..

**Comment by mofanke** [comment]
reopen

**Comment by mofanke** [comment]
> Could you please merge the commits as requested by https://github.com/kubernetes/community/blob/master/contributors/guide/contributor-cheatsheet/README-zh.md#%E5%8E%8B%E7%BC%A9%E6%8F%90%E4%BA%A4

ok

**Comment by MartinForReal** [comment]
@kimwnasptd @StefanoFioravanzo Any ideas? :)

**Pull request closed without merging**
