### PR TITLE
Add seldon to kfctl

### PR DESCRIPTION
**Pull request by cliveseldon**
This change is [Reviewable](https://reviewable.io/reviews/kubeflow/kubeflow/3527)

### CODE REVIEW

**Comment by cliveseldon** [comment]
Will this make it to 0.6 @jlewi ?

**Comment by yanniszark** [comment]
Hi @cliveseldon !
`kfctl` is moving towards the direction of specifying static config files that contain all packages.
For example:
* [Config file for existing clusters by Arrikto](https://github.com/kubeflow/kubeflow/blob/ea8868a77c498c68a36b0d15a03755a5ca726551/bootstrap/config/kfctl_existing_arrikto.0.6.yaml)
* [Config file for IAP GCP](https://github.com/kubeflow/kubeflow/blob/master/bootstrap/config/kfctl_gcp_iap.0.6.yaml)

Because of this, it would be better to add Seldon to those files, as they are the ones that kfctl will use.
I would love to test Seldon on an existing cluster and try to have it in v0.6 :smile:

**Comment by cliveseldon** [comment]
@yanniszark OK Thanks.  I have submitted a PR to the manifest https://github.com/kubeflow/manifests/pull/36 which has been merged. Are you saying I need to copy those manifest to this repo?

**Comment by yanniszark** [comment]
@cliveseldon that's not necessary.
Just add the new component and componentParam to the files I mentioned, since they're the ones that kfctl will use in the future.

**Comment by cliveseldon** [comment]
I will close. If we could continue the conversation in #3608 @yanniszark

**Pull request closed without merging**
