### PR TITLE
Notebooks: Rename "Notebook" to "Workbench" in the WEB GUI

### PR DESCRIPTION
**Pull request by tzstoyanov**
Kubeflow notebooks were initially created from JupyterLab Notebook. That functionality evolved, now other web-based development environments can be used as well - VSCode, RStudio and others can be added in future. The term "notebook" is a bit misleading and does not reflect all recent changes and enhancements. That's why a proposal was made to replace it with the term "workbench" - issue 6981.
This patch renames "notebook" to "workbench" in the Kubeflow WEB GUI.

issue: https://github.com/kubeflow/kubeflow/issues/6981

### CODE REVIEW

**Comment by thesuperzapper** [comment]
@juliusvonkohout @tzstoyanov I strongly believe that we should NOT do a rename unless there is a technical change, as that would just be confusing to users who already know about "Kubeflow Notebooks", which is effectively a brand at this point rather than a description.

**Comment by thesuperzapper** [comment]
@juliusvonkohout @tzstoyanov I strongly believe that we should NOT do a rename unless there is a technical change, as that would just be confusing to users who already know about "Kubeflow Notebooks", which is effectively a brand at this point rather than a description.

/hold

**Comment by juliusvonkohout** [comment]
> @juliusvonkohout @tzstoyanov I strongly believe that we should NOT do a rename unless there is a technical change, as that would just be confusing to users who already know about "Kubeflow Notebooks", which is effectively a brand at this point rather than a description.
> 
> /hold

We discussed this for almost one year in the meetings ;-) it was planned for 1.6 already. We even had community polls regarding the name.

The name is really just technically wrong and should not manifest as a brand. The longer it stays the longer it will be wrong.

Let us rather focus on what you want to achieve on the technical level afterwards.

**Pull request closed without merging**
