### PR TITLE
add profile and kfam API to kfctl default component

### PR DESCRIPTION
**Pull request by kunmingg**
With this one, kfctl will deploy profile and kfam API by default.

---
This change is [Reviewable](https://reviewable.io/reviews/kubeflow/kubeflow/3473)

### CODE REVIEW

**Comment by abhi-g** [comment]
/lgtm
/approve 

woohooo!

**Comment by kunmingg** [comment]
Also roll back notebook controller until https://github.com/kubeflow/kubeflow/issues/3425 fixed.

**Pull request merged**
