### PR TITLE
Update fairing to bd8313

### PR DESCRIPTION
**Pull request by r2d4**
This change is [Reviewable](https://reviewable.io/reviews/kubeflow/kubeflow/2918)

### CODE REVIEW

**Comment by r2d4** [comment]
needs cherry-pick @lluunn

**Comment by lluunn** [comment]
Do we have to rebuild all notebook images?

**Comment by r2d4** [comment]
We could just retag the ones that get built as v0.5.0 and avoid the cherry-pick

**Comment by lluunn** [comment]
will be image be rebuilt automatically? 
cc @zabbasi

**Pull request merged**
