### PR TITLE
fixes 'kfctl needs to support passing swagger spec to ks init from file'

### LINKED ISSUE #2706: kfctl tries to call ks init even on ks generate platform
I'm using #2705 which has  a WIP E2E test for kfctl.

It looks like when I call `kfctl generate platform` it ends up calling `ks init` which fails because there is no cluster to connect to.

Here are the logs.

```
util.py                     45 INFO     Running: /home/jlewi/git_kubeflow/bootstrap/bin/kfctl generate -V platform 
cwd=/tmp/kfctl-2145-4086
util.py                     60 INFO     Subprocess output:

util.py                     71 INFO     time="2019-03-14T21:47:01-07:00" level=info msg="reading from /tmp/kfctl-2145-4086/app.yaml"
util.py                     71 INFO     time="2019-03-14T21:47:01-07:00" level=info msg="Setting acmeEmail to "
util.py                     71 INFO     time="2019-03-14T21:47:01-07:00" level=info msg="Setting ipName to kfctl-2145-4086-ip"
util.py                     71 INFO     time="2019-03-14T21:47:01-07:00" level=info msg="Setting hostname to kfctl-2145-4086.endpoints.kubeflow-ci-deployment.cloud.goog"
util.py                     71 INFO     time="2019-03-14T21:47:01-07:00" level=info msg="Setting mysqlPd to kfctl-2145-4086-storage-metadata-store"
util.py                     71 INFO     time="2019-03-14T21:47:01-07:00" level=info msg="Setting minioPd to kfctl-2145-4086-storage-artifact-store"
util.py                     71 INFO     time="2019-03-14T21:47:01-07:00" level=info msg="Ksonnet.Generate Name kfctl-2145-4086 AppDir /tmp/kfctl-2145-4086 Platform gcp"
util.py                     71 INFO     time="2019-03-14T21:47:16-07:00" level=fatal msg="couldn't get server version info. Error: Get https://35.229.112.22/version: dial tcp 35.229.112.22:443: connect: connection timed out"
```

It looks to me like the bug is in `kfctl generate`
https://github.com/kubeflow/kubeflow/blob/b42734af7845087b6bd42e36d01422cb34ec8aa0/bootstrap/pkg/client/coordinator/coordinator.go#L386

It looks like the switch statement is always falling through and calling generate on the platform.

### LINKED ISSUE #2709: kfctl needs to support passing swagger spec to ks init from file
By default ksonnet tries to contact the internet in order to download the swagger spec for the K8s API version being used and generate the K8s libsonnet file for it.

This causes problems for on prem situations in which there is no internet access (see #1615).  ksonnet supports passing the swagger spec from a file on `ks init`. kfctl should expose a suitable command line option to `ks generate k8s` and pass it to `ks init`.
https://github.com/kubeflow/kubeflow/blob/b42734af7845087b6bd42e36d01422cb34ec8aa0/bootstrap/pkg/client/ksonnet/ksonnet.go#L491

See also: #2706

### PR DESCRIPTION
**Pull request by kkasravi**
fixes #2706, #2709 

---
This change is [Reviewable](https://reviewable.io/reviews/kubeflow/kubeflow/2719)

### CODE REVIEW

**Comment by jlewi** [comment]
Marking this WIP until blocking PRs are merged.

**Comment by kkasravi** [comment]
@kunmingg @lluunn this is ready to merge

**Pull request merged**
