### PR TITLE
JWA: Fix UI handling of default StorageClass

### LINKED ISSUE #4906: Notebook provisioner UI ignores specified StorageClass
/kind bug

**What steps did you take and what happened:**
[A clear and concise description of what the bug is.]

We have deployed Kubeflow at `v1.0.1` into our cluster.  Our cluster does not have a default StorageClass, and when attempting to provision a notebook from the `New Server` button, the `New` dropdown option for `workspaceVolume` does not appear (regardless of whether we set the `workspaceVolume` class to an existing StorageClass in the cluster).
image

**What did you expect to happen:**

If the config has value `{none}` and no default storage class is set then the UI should have the `New` option disabled. It should also show a tooltip as to why it is disabled.

If the config has an existing StorageClass specified, the `New` option should work as expected with that StorageClass.

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Environment:**

- Kubeflow version: (version number can be found at the bottom left corner of the Kubeflow dashboard): `1.0.1`
- kfctl version: (use `kfctl version`): `v1.0.1-0-gf3edb9b`
- Kubernetes platform: (e.g. `minikube`) Custom AWS Cluster
- Kubernetes version: (use `kubectl version`): `v1.14.8`
- OS (e.g. from `/etc/os-release`): `Ubuntu 18.04`

### PR DESCRIPTION
**Pull request by kimwnasptd**
closes #4906 

Right now the UI will completely ignore the `class` field of a volume in
the config received from the backend.

We want the UI to:
* Respect that field from the config
* Disable the `New` option in the volume type if
  a. The volume class is `{none}` (default SC) and
  b. No default storage class is set in the cluster

Else the UI should allow the user to create a new volume and the UI will
use the storage class received from the config.

/cc @avdaredevil 
/cc @kunmingg 
/assign @kimwnasptd

### CODE REVIEW

**Comment by kimwnasptd** [comment]
@googlebot I fixed it

**Comment by kimwnasptd** [comment]
@avdaredevil I tried to make a quick commit of your proposed changes via GitHub's gui. 
The commit was co-authored with your email, which was the gmail. It showed an invalid cla, maybe you are not using this email for the PRs? Either way, I force pushed a new commit with the changes.

if you are ok give it an lgtm

**Comment by jbottum** [comment]
@avdaredevil @kimwnasptd Hey Apporv - we have a user (Capital One) asking about the status of this improvement.   Kubeflow 1.1 is closing soon, can we get this into 1.1?

**Comment by avdaredevil** [comment]
/lgtm
/approve

Sorry @kimwnasptd I lost track of this PR. Approved and LGTM'ed

**Pull request merged**
