### PR TITLE
Update link in README

### PR DESCRIPTION
**Pull request by kunmingg**
This change is [Reviewable](https://reviewable.io/reviews/kubeflow/kubeflow/1640)

### CODE REVIEW

**Comment by kunmingg** [comment]
I signed it!

**Comment by jlewi** [comment]
The CLA failure is very weird.

**Comment by jlewi** [comment]
I'll merge this manually since its just a README change we know its not related to the presubmit failures. and @kunmingg has already signed hte CLA.

**Comment by kunmingg** [comment]
Thanks! github bug.

**Pull request merged**
