### PR TITLE
[WIP] Test optional-test-infra

### PR DESCRIPTION
**Pull request by PatrickXYS**
**DO NOT MERGE!**

This PR is used to test against kubeflow/kubeflow configurations on optional-test-infra

/hold

### CODE REVIEW

**Comment by PatrickXYS** [comment]
In this PR, it's correctly triggered and try to use python generated argo workflow

```
INFO|2021-02-26T19:58:10|/src/kubeflow/testing/py/kubeflow/testing/util.py|73| INFO|2021-02-26T19:58:10|/src/kubeflow/testing/py/kubeflow/testing/run_e2e_workflow.py|107| Importing path kubeflow.kubeflow.ci.shared_ui_tests
```

Though tests failed, but we can confirm it works on triggering.

**Comment by kimwnasptd** [comment]
@PatrickXYS thanks for the test PR. Looking at the logs I see
```
[metadata.name: Invalid value: \"kubeflow-kubeflow-presubmit-shared_ui_tests-5642-637f607-9360-0b98\": a DNS-1123 subdomain must consist of lower case alphanumeric characters, '-' or '.', and must start and end with an alphanumeric character
```

So I should change the name from `shared_ui_tests` to `shared-ui-tests`, somewhere. I have a suspicion that this name was generated from the `run_e2e_workflow.py` file and it used the filename to create it. In any case we know the problem is the `_` characters.

I'll take a more extensive look at this on Monday

**Comment by PatrickXYS** [comment]
/retest

Retest to remove logging in environment variable

**Comment by PatrickXYS** [comment]
Yeah the env var logs are gone now

**Review by PatrickXYS — COMMENTED** [review]
/close 

Close in favor of test passed

**Pull request closed without merging**
