### PR TITLE
Add katib's hyperband/bayesianoptimization suggestion images (#1464)

### PR DESCRIPTION
**Pull request by leoncamel**
Add missing hyperband/bayesianoptimization suggestion images.

---
This change is [Reviewable](https://reviewable.io/reviews/kubeflow/kubeflow/1727)

### CODE REVIEW

**Comment by leoncamel** [comment]
@YujiOshima Since the release process is quite hard for local testing, could you please review this patch?

**Comment by YujiOshima** [comment]
@leoncamel Great! Thank you for the contribution. LGTM
@richardsliu Could you review it?

**Comment by jlewi** [comment]
/ok-to-test

What was the reason you changed double quotes to single quotes? I think that will cause our lint checker to fail.

You can use this script to autoformat the jsonnet files
https://github.com/kubeflow/kubeflow/blob/master/scripts/autoformat_jsonnet.sh

Once this PR is merged; you will need to cherry pick it on to the v0.3-branch to be included in the next release.

**Comment by jlewi** [comment]
There are two test failures

1. jsonnet formatting if you use the script I mentioned previously that should fix the formatting

2. The GKE version used by the E2E test is out of date; this should be fixed on master so I think you just need to rebase off the latest changes.

**Comment by jlewi** [comment]
/lgtm
/approve

Can you cherry pick this onto the v0.3-branch?

Do we need to build Docker images for these other algorithms?

**Comment by leoncamel** [comment]
@jlewi OK.

**Comment by leoncamel** [comment]
@jlewi 

> 
> Can you cherry pick this onto the v0.3-branch?

I have created [new PR](https://github.com/kubeflow/kubeflow/pull/1777) for cherry-picking.

> 
> Do we need to build Docker images for these other algorithms?

The image is provided along with other images. But, it seems bayesianoptimization's image has some bug, and katib team is fixing it. And [the patch](https://github.com/kubeflow/katib/pull/188) is merged.

Anyway, let merge this PR and push things going forward.

**Pull request merged**
