### PR TITLE
generate license for profile controller image

### PR DESCRIPTION
**Pull request by kunmingg**
add third party dependency license for profile controller image following:
https://github.com/kubeflow/metadata/tree/master/third_party_licenses

fix https://github.com/kubeflow/kubeflow/issues/4619

---
This change is [Reviewable](https://reviewable.io/reviews/kubeflow/kubeflow/4622)

### CODE REVIEW

**Comment by kunmingg** [comment]
@zhenghuiwang 
Any requirement for license file format or location in our image?

**Comment by abhi-g** [comment]
Generally License file goes in the top directory, for eg. where README.md
might be. Also, common practice is to name is LICENSE.TXT

**Comment by zhenghuiwang** [comment]
/lgtm

I don't think there are requirements on where to put all dependency licenses, but I see others usually put them into `third_party/licenses.txt` as you do.

**Pull request merged**
