### PR TITLE
To use the latest fairing version.

### PR DESCRIPTION
**Pull request by xauthulei**
This change is [Reviewable](https://reviewable.io/reviews/kubeflow/kubeflow/4018)

### CODE REVIEW

**Comment by jinchihe** [comment]
@xauthulei Could you please update the last PR in fairing:
From 
```
git+https://github.com/kubeflow/fairing@a9bb9d5cc1c9f1d75efa31198ddbdccfe176b7bf
```
To
```
git+https://github.com/kubeflow/fairing@11a4c0f25140054d5d1cda7ca981001827ff972b
```

**Comment by xauthulei** [comment]
@jinchihe , I have refreshed it, please review the latest changes. Many thanks

**Comment by jinchihe** [comment]
@xauthulei Thanks.

/lgtm

/assign @jlewi Could you please review and approve? Thanks a lot!

**Pull request closed without merging**
