### PR TITLE
Automated cherry pick of #5074: added gpu details to the notebook server table #5086: show all existing PVCs as dropdown under volumes while Cherry pick of #5074 #5086 on v1.1-branch. #5074: added gpu details to the notebook server table #5086: show all existing PVCs as dropdown under volumes while

### PR DESCRIPTION
**Pull request by lalithvaka**

### CODE REVIEW

**Comment by jlewi** [comment]
@lalithvaka Should this be the last cherry-picking of anything which isn't a critical bug fix? Perhaps we should start thinking about 1.2?

As is this cherry-pick will likely not be included in 1.1 because it arrived after 1.1-RC.2 which is the one we are pushing.

**Comment by lalithvaka** [comment]
@jlewi this is the last one am tracking besides the documentation [PR]() https://github.com/kubeflow/website/pull/2032 for some of these changes.

**Pull request merged**
