### PR TITLE
[Hotfix] Usage reporting Link

### PR DESCRIPTION
**Pull request by avdaredevil**
## Info:
- **Update for #2921** 
- **Hotfix for #2922** 

/area front-end
/area centraldashboard
/priority p1

/assign @avdaredevil 
/review @prodonjs @rileyjbauer

---
This change is [Reviewable](https://reviewable.io/reviews/kubeflow/kubeflow/2942)

### CODE REVIEW

**Comment by tmc** [comment]
FWIW this link is broken.

**Comment by prodonjs** [comment]
Can you elaborate on what behavior you're seeing? Is the link to the docs page not resolving?

**Pull request merged**
