### PR TITLE
[gcp-click-to-deploy] cleanup: remove ks and kubectl from Dockerfile

### PR DESCRIPTION
**Pull request by stpabhi**
Signed-off-by: Abhilash Pallerlamudi <stp.abhi@gmail.com>

---
This change is [Reviewable](https://reviewable.io/reviews/kubeflow/kubeflow/2164)

### CODE REVIEW

**Comment by kunmingg** [comment]
/ok-to-test

Thanks!

**Comment by kunmingg** [comment]
@stpabhi 
You might need to resolve conflict.

**Comment by stpabhi** [comment]
@kunmingg rebase done.

**Pull request merged**
