### PR TITLE
web-apps(front): Update the common frontend library

### PR DESCRIPTION
**Pull request by kimwnasptd**
This is a prerequisite for #4758 

This PR updates the common code and introduces the following features:
* Introduce new reusable components 
* Improve the way we use the common table component in all the crud-web-apps
* Adds frontend CSRF protection in the common frontend library #5461
* Adds unit tests to the common frontend library #5462

Also cc @DavidSpek, after we merge this I'll be able to push the frontend PR for the Volumes UI

We (Arrikto) are already using this code from the web apps in MiniKF and we've tested it extensively. 

/cc @StefanoFioravanzo 
/cc @elikatsis 
/cc @thesuperzapper 
/assign @kimwnasptd

### CODE REVIEW

**Comment by kimwnasptd** [comment]
/approve cancel
Why was this approved out of the box? The bot mentions that

> [APPROVALNOTIFIER] This PR is **APPROVED**
> 
> This pull-request has been approved by: kimwnasptd

**Comment by PatrickXYS** [comment]
>Why was this approved out of the box? The bot mentions that

This is expected behavior, PR made by author will be automatically approved by author themselves. 

Ref: https://github.com/kubernetes/test-infra/blob/master/prow/plugins/approve/approvers/README.md#step-1

**Comment by StefanoFioravanzo** [comment]
@kimwnasptd looks goo to me! This is awesome. I have run the unit tests and everything seems to be in order

**Pull request merged**
