### PR TITLE
Change default view to lab

### PR DESCRIPTION
**Pull request by DavidSpek**
Closes: https://github.com/kubeflow/kubeflow/issues/4838.

### CODE REVIEW

**Comment by kimwnasptd** [comment]
@DavidSpek  from what I remember this shouldn't work since JupyterLab was had different cmd arguments. The `--NotebookApp.ip` argument for example should be `--LabApp.ip`. At least that was the case a [couple of years back](https://github.com/kubeflow/kubeflow/pull/2349/files#diff-f3f0008fed2b80d1da069d653213382a430869c171abf1447c1529af87aa50a8R19), but I'm not sure if they've changed it.

Have you tried building a docker image of a Notebook and test it?

**Comment by DavidSpek** [comment]
@kimwnasptd I've been using this CMD string for months with my personal images that are all using the jupyter-stack as a base. Also, `--NotebookApp.ip` doesn't currently exist `--NotebookApp.token=''` `--NotebookApp.password=''` `--NotebookApp.allow_origin='*'` `--NotebookApp.base_url` are all fine from my experience. I can double check the documentation if you'd like though.

**Comment by DavidSpek** [comment]
@kimwnasptd Found it quickly, there are no `--LabApp.xx` arguments. https://jupyter-notebook.readthedocs.io/en/stable/config.html

**Comment by kimwnasptd** [comment]
Aren't the docs for Notebooks different for labs?
https://jupyter-notebook.readthedocs.io/en/stable/config.html
https://jupyterlab.readthedocs.io/en/stable/

The only references to `LabApp` I can find are in the [Advanced Usage](https://jupyterlab.readthedocs.io/en/stable/user/directories.html?highlight=labapp#disabling-rebuild-checks) section where they mention the `LabConfig`. I can't seem to find any more references to `--LabApp` so maybe indeed these are remnants from the past.

I'll try out the command with a "latest" Notebook docker image and will resume the review of this.

**Comment by DavidSpek** [comment]
@kimwnasptd Given https://github.com/kubeflow/kubeflow/issues/5516 I'd say this PR has been tested at this point.

**Comment by DavidSpek** [comment]
@kimwnasptd I think this can be merged.

**Comment by kimwnasptd** [comment]
I tested the above change be editing the `args` field of the pod template spec inside a notebook and the change works as expected. So it seems that the `--LabApp.*` args are no longer used.

LGTM from my end, but I'll wait for @StefanoFioravanzo to take a look and merge this, since he has more experience wrt the actual Notebook environments.

/lgtm

**Comment by DavidSpek** [comment]
@kimwnasptd The Kale Dockerfiles seem to use the `--LabApp` annotation. So just to be sure I hadn't missed something looked it up again and I see lots of references to `--LabApp` usage on Google, but I can't find it in the docs myself. Either way, it seems like both `--LabApp` and `--NotebookApp` work regardless. Maybe @StefanoFioravanzo knows what the difference is.

**Comment by StefanoFioravanzo** [comment]
@kimwnasptd @DavidSpek These `--LabApp` and `--NotebookApp` arguments correspond to the keys used in the Jupyter config file that one can generate with `jupyter {notebook,lab} --generate-config`.

By looking at the two configs, the `lab` version still uses `NotebookApp` as prefix, apart from a few of them that use the `LabApp` one.

All the CLI overrides we provide in the Dockerfile entrypoint are listed as `NotebookApp` fields even in the `lab` config. So I am good with it.

(Since we can't find any Lab-specific documentation on this, I believe they indeed support both version, but let's just stick with what the default configuration file generates.)

**Pull request merged**
