### PR TITLE
Update Pipelines to version 0.1.16 (#2955) {Cherry-pick to pipelines}

### PR DESCRIPTION
**Pull request by Ark-kun**
This change is [Reviewable](https://reviewable.io/reviews/kubeflow/kubeflow/2956)

### CODE REVIEW

**Comment by Ark-kun** [comment]
`kubeflow.testing.util.TimeoutError: Timeout waiting for deployment jupyter-web-app in namespace kubeflow`

Is this test supposed to be working in the pipelines branch?

**Comment by jlewi** [comment]
Meged at request of @Ark-kun

**Pull request merged**
