### PR TITLE
Update image pull policy for pipeline

### PR DESCRIPTION
**Pull request by jinchihe**
fixes: #2249

---
This change is [Reviewable](https://reviewable.io/reviews/kubeflow/kubeflow/2251)

### CODE REVIEW

**Comment by jlewi** [comment]
/assign @IronPan 

@jinchihe Sorry for the slow review. Feel free to ping people on kubeflow.slack.com if they aren't being responsive.

Looks like the PR got out of date; would you mind sync'ing and updating it?

**Comment by IronPan** [comment]
thanks for the change

**Pull request merged**
