### PR TITLE
update github oauth setup for Jupyterhub

### PR DESCRIPTION
**Pull request by ogre0403**
Update document for Jupyterhub gitthub oauth setup

---
This change is [Reviewable](https://reviewable.io/reviews/kubeflow/kubeflow/660)

### CODE REVIEW

**Comment by ogre0403** [comment]
I signed it!

**Comment by jlewi** [comment]
/lgtm
/approve

Please sign the CLA

**Comment by jlewi** [comment]
@ogre0403 Can you sign the CLA please?

**Comment by ogre0403** [comment]
I signed it!

**Pull request closed without merging**
