### PR TITLE
Update container image to 1.12.0

### PR DESCRIPTION
**Pull request by Youki**
- Update container image to 1.12.0
- Add option to tensorflow_model_server to enable Rest API

---
This change is [Reviewable](https://reviewable.io/reviews/kubeflow/kubeflow/2248)

### CODE REVIEW

**Comment by lluunn** [comment]
Actually, we are moving to this libsonnet:
https://github.com/kubeflow/kubeflow/blob/master/kubeflow/tf-serving/tf-serving-template.libsonnet

The newer features (e.g. Istio) are only added there, and I was planning to remove tf_serving.libsonnet.
Does tf_serving_template.libsonnet meet your need?

**Comment by Youki** [comment]
[kubeflow-presubmit](http://testing-argo.kubeflow.org/workflows/kubeflow-test-infra/kubeflow-presubmit-unittests-2248-381b326-5000-8764?tab=workflow&nodeId=kubeflow-presubmit-unittests-2248-381b326-5000-8764-1967743505) failed because of following error.

> INFO|2019-01-11T00:07:23|test_jsonnet_formatting.py:51| Running test_jsonnet_formatting
usage: test_jsonnet_formatting.py [-h] [--src_dir SRC_DIR]
                                 [--exclude_dirs EXCLUDE_DIRS]
test_jsonnet_formatting.py: error: unrecognized arguments: --project=kubeflow-ci --artifacts_dir=/mnt/test-data-volume/kubeflow-presubmit
-unittests-2248-381b326-5000-8764/output/artifacts
INFO|2019-01-11T00:07:23|test_helper.py:62| Writing file: /mnt/test-data-volume/kubeflow-presubmit-unittests-2248-381b326-5000-8764/outpu
t/artifacts/junit_test-jsonnet-formatting.xml

I will re-run the test to check if this happens again.

**Comment by Youki** [comment]
@lluunn 
Thanks for the information.
Found that this PR is covered by tf-serving-template.libsonnet :D.
Do you mean you will replace current tf-serving.libsonnet with tf-serving-template.libsonnet?

If so, I want to reflect my past PR #2231 to tf-serving-template.libsonnet so that pod can be auto-scaled based on monitoring metrics (e.g. CPU Utilization, GPU Utilization and so on).

**Comment by Youki** [comment]
@lluunn 
Is there any reason you don't replace current tf-serving.libsonnet immediately?

**Comment by lluunn** [comment]
We didn't remove it immediately because the new one was still WIP. I think we can remove tf-serving.libsonnet now.

**Comment by Youki** [comment]
@lluunn Got it. I close this PR since it doesn't make sense to update tf-serving.libsonnet if you are removing it. BTW, tf-serving.libsonnet is being used by one of examples here: https://github.com/kubeflow/examples/tree/master/object_detection

**Comment by lluunn** [comment]
thanks, will update that

**Pull request closed without merging**
