### PR TITLE
Automated cherry pick of #3695 upstream v0.6 branch

### PR DESCRIPTION
**Pull request by zhenghuiwang**
https://github.com/kubeflow/kubeflow/issues/3702

---
This change is [Reviewable](https://reviewable.io/reviews/kubeflow/kubeflow/3763)

### CODE REVIEW

**Comment by zhenghuiwang** [comment]
@Jeffwan can you type `@googlebot I consent.` ?


> All (the pull request submitter and all commit authors) CLAs are signed, **but** one or more commits were authored or co-authored by someone other than the pull request submitter.
> 
> We need to confirm that all authors are ok with their commits being contributed to this project. Please have them confirm that by leaving a comment that contains only `@googlebot I consent.` in this pull request.
> 
> _Note to project maintainer:_ There may be cases where the author cannot leave a comment, or the comment is not properly detected as consent. In those cases, you can manually confirm consent of the commit author(s), and set the `cla` label to `yes` (if enabled on your project).
> 
>  **Googlers: [Go here](https://goto.google.com/prinfo/https%3A%2F%2Fgithub.com%2Fkubeflow%2Fkubeflow%2Fpull%2F3763) for more info**.

**Comment by Jeffwan** [comment]
@googlebot I consent

**Comment by Jeffwan** [comment]
@googlebot I consent.

**Pull request merged**
