### PR TITLE
fixes 'add a jobs component'

### LINKED ISSUE #2058: add a jobs component
The component kubeflow/jobs will include different prototypes to run common types of jobs. The single-job prototype takes a jobImage, jobName, jobCommand and jobArgs.

Other types of jobs will be added, like a job sequence

### PR DESCRIPTION
**Pull request by kkasravi**
fixes #2058

---
This change is [Reviewable](https://reviewable.io/reviews/kubeflow/kubeflow/2059)

### CODE REVIEW

**Comment by kkasravi** [comment]
@jlewi this is being used to run a mnist training job using tensorflow with ngraph enabled that then shows the output in tensorboard. see [#412](https://github.com/kubeflow/examples/issues/412)

Although I can conceive of other types of prototypes in addition `single-job` like parallel jobs serial jobs, etc. I think these could be added over time.

**Comment by jlewi** [comment]
@kkasravi So why not just make this part of the example in #421? Why create a reusable Jobs package?

Complex examples (e.g. code search) will often need to create a bunch of K8s resources. So we can just create manifests suitable for the example and parameterize them as needed to make it easier for people to run the example.

**Comment by kkasravi** [comment]
@jlewi - yes I'll move this into the example and close this request

**Pull request closed without merging**
