### PR TITLE
[WIP] Allow bootstrapper to use disk-based registry

### PR DESCRIPTION
**Pull request by inc0**
This approach will allow to skip whole GITHUB_TOKEN issue, but is
blocked on this https://github.com/ksonnet/ksonnet/issues/480

---
This change is [Reviewable](https://reviewable.io/reviews/kubeflow/kubeflow/720)

### CODE REVIEW

**Comment by pdmack** [comment]
Could we please change references of "bootstraper" to "bootstrapper"?
/cc @jlewi

**Comment by jlewi** [comment]
@pdmack SGTM. 
/assign @kunmingg

**Comment by kunmingg** [comment]
@inc0 created a PR to enable ks disk-based registry in docker:
https://github.com/kubeflow/kubeflow/pull/725

**Comment by inc0** [comment]
After your update ks works, but bootstrapper still fails with same issue.
```
root@74e18df52e17:/# /opt/kubeflow/bootstrapper --registry-dir /opt/kubeflow/kubeflow/ --app-dir=/kubeflow
{"filename":"app/server.go:109","level":"info","msg":"Reading config from file: /root/.kube/config","time":"2018-04-26T10:02:47Z"}
{"filename":"app/server.go:186","level":"info","msg":"Using existing namespace: kubeflow","time":"2018-04-26T10:02:49Z"}
{"filename":"app/server.go:153","level":"info","msg":"Cluster platform: linux/amd64","time":"2018-04-26T10:02:49Z"}
{"filename":"app/server.go:253","level":"info","msg":"Cluster version: v1.9.5","time":"2018-04-26T10:02:49Z"}
{"filename":"app/server.go:160","level":"info","msg":"Storage class: rook-block","time":"2018-04-26T10:02:49Z"}
{"filename":"app/server.go:162","level":"info","msg":"Storage class rook-block doesn't have annotation storageclass.beta.kubernetes.io/is-default-class","time":"2018-04-26T10:02:49Z"}
{"filename":"app/server.go:268","level":"info","msg":"Using K8s host https://8.44.40.57:35000","time":"2018-04-26T10:02:49Z"}
{"filename":"env/create.go:78","level":"info","msg":"Creating environment \"default\" with namespace \"kubeflow\", pointing to cluster at address \"https://8.44.40.57:35000\"","time":"2018-04-26T10:02:49Z"}
{"filename":"lib/lib.go:129","level":"info","msg":"Generating ksonnet-lib data at path '/kubeflow/lib/v1.7.0'","time":"2018-04-26T10:02:50Z"}
{"filename":"app/server.go:292","level":"info","msg":"Successfully initialized the app /kubeflow.","time":"2018-04-26T10:02:50Z"}
{"filename":"app/server.go:350","level":"info","msg":"Installing package kubeflow/core","time":"2018-04-26T10:02:50Z"}
{"filename":"registry/cache.go:83","level":"info","msg":"Retrieved 29 files","time":"2018-04-26T10:02:50Z"}
{"filename":"app/server.go:350","level":"info","msg":"Installing package kubeflow/tf-serving","time":"2018-04-26T10:02:50Z"}
{"filename":"registry/cache.go:83","level":"info","msg":"Retrieved 5 files","time":"2018-04-26T10:02:50Z"}
{"filename":"app/server.go:350","level":"info","msg":"Installing package kubeflow/tf-job","time":"2018-04-26T10:02:50Z"}
{"filename":"registry/cache.go:83","level":"info","msg":"Retrieved 5 files","time":"2018-04-26T10:02:50Z"}
{"filename":"app/server.go:388","level":"fatal","msg":"There was a problem creating protoype package kubeflow-core; error no prototype names matched 'kubeflow-core'","time":"2018-04-26T10:02:50Z"}
```

**Comment by kunmingg** [comment]
@inc0 I think we need to update ks version inside vendor as well.
Created issue for it: https://github.com/kubeflow/kubeflow/issues/727.
Will update it soon.

**Comment by jlewi** [comment]
@inc0 @kunmingg Can we close this issue because @kunmingg created #766?

**Pull request closed without merging**
