### PR TITLE
Fix the bug of ResourceQuota removal

### LINKED ISSUE #6187: ResourceQuota still exists after removed from profile
/kind bug

**What steps did you take and what happened:**

1. Add resourceQuotaSpec for kubeflow-user-example-com profile as follows:
```
apiVersion: kubeflow.org/v1
kind: Profile
metadata:
  name: kubeflow-user-example-com
spec:
  owner:
    kind: User
    name: user@example.com
  resourceQuotaSpec:
    hard:
      cpu: "4"
      memory: 4Gi
```
We can get the kf-resource-quota resource and it works as expected.
```
$ kubectl get resourcequotas -n kubeflow-user-example-com
NAME                AGE   REQUEST                            LIMIT
kf-resource-quota   74s   cpu: 2090m/4, memory: 4486Mi/4Gi
```

2.  Remove the resourceQuotaSpec for kubeflow-user-example-com profile as follows: 
```
apiVersion: kubeflow.org/v1
kind: Profile
metadata:
  name: kubeflow-user-example-com
spec:
  owner:
    kind: User
    name: user@example.com
```
It can be found that kf-resource-quota has not been deleted.
```
$ kubectl get resourcequotas -n kubeflow-user-example-com
NAME                AGE     REQUEST                            LIMIT
kf-resource-quota   6m24s   cpu: 2090m/4, memory: 4486Mi/4Gi
```

**What did you expect to happen:**

Delete the kf-resource-quota resource after remove resourceQuotaSpec from the profile.

**Environment:**

- Kubeflow version: : 1.4
- Kubernetes platform: kind
- Kubernetes version: v1.21.1

### PR DESCRIPTION
**Pull request by sunzhaochang**
Fix #6187

### CODE REVIEW

**Comment by sunzhaochang** [comment]
@kimwnasptd Could you please take a look at this PR ? Thanks.

**Comment by sergeyshevch** [comment]
@kimwnasptd @StefanoFioravanzo Can someone look at this? It's a really little fix that can be easily reviewed. I also faced with the bug that will be fixed by this PR

**Comment by kimwnasptd** [comment]
This got completely out of my radar, thanks for the ping @sergeyshevch.

The changes look good. This is also a small fix that we could include in the next KF 1.7 RC cc @DomFleischmann 

/lgtm
/approve

**Pull request merged**
