### PR TITLE
fix click_to_deploy test

### PR DESCRIPTION
**Pull request by lluunn**
- make `copy-artifacts` not depend on `deploy-delete` so that even delete failed we still have artifacts. @kunmingg Is this ok?
- when GetDeploymentStatus failed, retry
- update go version, and print out go version

for https://github.com/kubeflow/kubeflow/issues/2364

---
This change is [Reviewable](https://reviewable.io/reviews/kubeflow/kubeflow/2431)

### CODE REVIEW

**Comment by lluunn** [comment]
ready for review
/assign @kunmingg 
/assign @jlewi

**Comment by jlewi** [comment]
@lluunn Does delete_deploy emit a junit test file to report the results in test grid?

If its not reporting a junit file then its probably ok to run copy-artifacts in parallel as delete-deploy won't emit any results anyway to upload to GCS.

If it does then it might be better to have deploy emit a junit that indicates failure but still exit with code 0. This way the next step copy-artifacts would still run.

**Comment by lluunn** [comment]
it's won't.
it's doing https://github.com/kubeflow/kubeflow/blob/master/bootstrap/test_delete.sh

**Pull request merged**
