### PR TITLE
static-config-server

### PR DESCRIPTION
**Pull request by kunmingg**
Tiny server that serve static config contents within k8s cluster.

---
This change is [Reviewable](https://reviewable.io/reviews/kubeflow/kubeflow/4853)

### CODE REVIEW

**Comment by yanniszark** [comment]
@kunmingg can you share details on why this is needed?
Is there an open issue?

**Comment by kunmingg** [comment]
@yanniszark 
Our current use case is hosting jwt public key in private cluster.
Related: 
https://github.com/kubeflow/manifests/pull/999

**Comment by yanniszark** [comment]
@kunmingg thanks for the explanation :)

**Pull request merged**
