### PR TITLE
Update docs so that namespace is only set at ks env level

### PR DESCRIPTION
**Pull request by ankushagarwal**
Now that https://github.com/kubeflow/kubeflow/pull/426 is merged, we do
not need to set namespace at the component level. namespace will be
automatically inherited by the component from env.

---
This change is [Reviewable](https://reviewable.io/reviews/kubeflow/kubeflow/463)

### CODE REVIEW

**Comment by jlewi** [comment]
Can you update the Requirements section to reflect the version of ksonnet required?
https://github.com/kubeflow/kubeflow#requirements

**Comment by ankushagarwal** [comment]
Done.

**Pull request merged**
