### PR TITLE
parameterize mysql and minio image

### PR DESCRIPTION
**Pull request by IronPan**
This would be useful if I want to override the images when creating private cluster 

This change is [Reviewable](https://reviewable.io/reviews/kubeflow/kubeflow/2109)

### CODE REVIEW

**Comment by IronPan** [comment]
/test kubeflow-presubmit
--

**Comment by jlewi** [comment]
Test failure looks like we exceeded maximum number of service accounts.
https://github.com/kubeflow/testing/issues/250

**Comment by jlewi** [comment]
I cleaned up the service accounts.

/test all

**Comment by jlewi** [comment]
Looks like the test failure is legit.

```
level=error msg="find objects: RUNTIME ERROR: function expected 1 positional argument(s), but got 2\n\t/mnt/test-data-volume/kubeflow-presubmit-kfctl-2109
-777b03b-4785-cbae/kfctl-cbae/ks_app/vendor/kubeflow/pipeline/all.libsonnet:20:11-45\tobject <anonymous>\n\t/mnt/test-data-volume/kubeflow-presubmit-kfctl
-2109-777b03b-4785-cbae/kfctl-cbae/ks_app/vendor/kubeflow/pipeline/all.libsonnet:(20:11)-(21:49)\tobject <anonymous>\n\t/mnt/test-data-volume/kubeflow-pre
submit-kfctl-2109-777b03b-4785-cbae/kfctl-cbae/ks_app/vendor/kubeflow/pipeline/all.libsonnet:(20:11)-(22:54)\tobject <anonymous>\n\t/mnt/test-data-volume/
kubeflow-presubmit-kfctl-2109-777b03b-4785-cbae/kfctl-cbae/ks_app/vendor/kubeflow/pipeline/all.libsonnet:(20:11)-(23:76)\tobject <anonymous>\n\t/mnt/test-
data-volume/kubeflow-presubmit-kfctl-2109-777b03b-4785-cbae/kfctl-cbae/ks_app/vendor/kubeflow/pipeline/all.libsonnet:(20:11)-(24:74)\tobject <anonymous>\n
\t/mnt/test-data-volume/kubeflow-presubmit-kfctl-2109-777b03b-4785-cbae/kfctl-cbae/ks_app/vendor/kubeflow/pipeline/all.libsonnet:(20:11)-(25:46)\tobject <
anonymous>\n\t<extvar:__ksonnet/components>:94:34-60\tthunk from <thunk from <object <anonymous>>>\n\t/mnt/test-data-volume/kubeflow-presubmit-kfctl-2109-
777b03b-4785-cbae/kfctl-cbae/ks_app/lib/v1.11.5/k.libsonnet:96:24-29\tthunk from <function <anonymous>>\n\t/mnt/test-data-volume/kubeflow-presubmit-kfctl-
2109-777b03b-4785-cbae/kfctl-cbae/ks_app/lib/v1.11.5/k.libsonnet:97:36-41\tthunk from <function <anonymous>>\n\t<builtin>\tbuiltin function <type>\n\t<std
>:1165:25-26\tthunk from <thunk <ta> from <function <anonymous>>>\n\t<builtin>\tbuiltin function <type>\n\t<std>:1167:29-31\tthunk from <function <anonymo
us>>\n\t<builtin>\tbuiltin function <primitiveEquals>\n\t<std>:1167:8-36\tfunction <anonymous>\n\t\t\n\t/mnt/test-data-volume/kubeflow-presubmit-kfctl-210
9-777b03b-4785-cbae/kfctl-cbae/ks_app/lib/v1.11.5/k.libsonnet:96:13-30\tfunction <anonymous>\n\t/mnt/test-data-volume/kubeflow-presubmit-kfctl-2109-777b03
b-4785-cbae/kfctl-cbae/ks_app/lib/v1.11.5/k.libsonnet:(92:22)-(96:30)\tfunction <anonymous>\n\t<extvar:__ksonnet/components>:94:15-61\tthunk from <object
<anonymous>>\n\t<std>:1216:24-25\tthunk from <thunk <t> from <function <anonymous>>>\n\t...\n\t<std>:793:34-35\tfunction <anonymous>\n\t<std>:793:30-35\tf
unction <anonymous>\n\t<std>:740:24-47\tthunk from <function <aux>>\n\t<std>:740:9-57\tfunction <aux>\n\t<std>:741:5-28\tfunction <anonymous>\n\t<std>:793
:5-46\tfunction <anonymous>\n\t/mnt/test-data-volume/kubeflow-presubmit-kfctl-2109-777b03b-4785-cbae/kfctl-cbae/ks_app/vendor/kubeflow/application/applica
tion.libsonnet:249:20-75\tobject <anonymous>\n\t/mnt/test-data-volume/kubeflow-presubmit-kfctl-2109-777b03b-4785-cbae/kfctl-cbae/ks_app/vendor/kubeflow/ap
plication/application.libsonnet:148:43-49\tthunk from <object <anonymous>>\n\t<std>:210:22-25\tthunk from <function <anonymous>>\n\t<builtin>\tbuiltin fun
ction <type>\n\t<std>:1165:25-26\tthunk from <thunk <ta> from <function <anonymous>>>\n\t<builtin>\tbuiltin function <type>\n\t<std>:1167:29-31\tthunk fro
m <function <anonymous>>\n\t<builtin>\tbuiltin function <primitiveEquals>\n\t<std>:1167:8-36\tfunction <anonymous>\n\t\t\n\t\t\n\t<std>:210:13-66\tfunctio
n <anonymous>\n\t/mnt/test-data-volume/kubeflow-presubmit-kfctl-2109-777b03b-4785-cbae/kfctl-cbae/ks_app/vendor/kubeflow/application/application.libsonnet
:148:22-50\tobject <anonymous>\n\tDuring manifestation\t\n"
```

**Comment by jlewi** [comment]
@IronPan If this should be in 0.4 please submit a cherry-pick to the 0.4 release branch.

**Pull request merged**
