### PR TITLE
Support custom image names for kubeflow components

### LINKED ISSUE #3210: Python/Go binary to bulk replace images in kustomization.yaml files  (was Port use_gcr_for_all_images.sh to work with kustomize)
Port https://github.com/kubeflow/kubeflow/blob/master/scripts/gke/use_gcr_for_all_images.sh
to kustomize.

This script is used for switching the images to a private registry. We will need to update the script
to work with the new kustomize manifests.

### PR DESCRIPTION
**Pull request by xaniasd**
Related to #3210 

added set-image-name command
added unit tests
added documentation

---
This change is [Reviewable](https://reviewable.io/reviews/kubeflow/kubeflow/4222)

### CODE REVIEW

**Comment by yanniszark** [comment]
Code looks good and the functionality works great with local testing.
/lgtm
/approve
/hold

For @jlewi to take a look.

**Comment by jlewi** [comment]
Thanks @xaniasd !

Before we close #3210 lets add documentation to the website.

/hold cancel

**Pull request merged**
