### PR TITLE
Setting the base_url flag of Jupyter images

### PR DESCRIPTION
**Pull request by zabbasi**
Addressing [this issue](https://github.com/kubeflow/kubeflow/issues/2595). Tested an image locally.

---
This change is [Reviewable](https://reviewable.io/reviews/kubeflow/kubeflow/2627)

### CODE REVIEW

**Comment by kimwnasptd** [comment]
@zabbasi in the end, we set the NB_PREFIX environment variable from the [notebook controller](https://github.com/kubeflow/kubeflow/pull/2620/files). 

Sorry for not making that clear enough

**Comment by zabbasi** [comment]
retest

**Pull request merged**
