### PR TITLE
cron job & workflow config for image release

### PR DESCRIPTION
**Pull request by kunmingg**
Anoother part for https://github.com/kubeflow/kubeflow/issues/666.
1. cron_job_release.yaml: 
    Define cron job for daily release images
2. prow_config_release.yaml:
    Workflows of images that need to be released.

For https://github.com/kubeflow/kubeflow/issues/666

---
This change is [Reviewable](https://reviewable.io/reviews/kubeflow/kubeflow/825)

### CODE REVIEW

**Comment by ankushagarwal** [comment]
Shouldn't the cron_job_release.yaml be a component in the ksonnet app here : `releasing/releaser/components`

**Comment by kunmingg** [comment]
@ankushagarwal 
cron_job_release.yaml wakes up all release workflows, releasing/releaser/components is only one of them. (repo struct is a bit strange)

**Pull request merged**
