### PR TITLE
Move the CD scripts and Tekton pipelines into kubeflow/testing

### PR DESCRIPTION
**Pull request by jlewi**
* Delete all the Tekton pipelines and scripts for continuous delivery
  of Kubeflow applications because they are moving into kubeflow/testing

* kubeflow/testing#551 is the PR moving the code into kubeflow/testing

Related to: kubeflow/testing#544 redo how we use kustomize and Tekton
            to parameterize the pipelines

---
This change is [Reviewable](https://reviewable.io/reviews/kubeflow/kubeflow/4593)

### CODE REVIEW

**Comment by gabrielwen** [comment]
will wait for kubeflow/testing#551 to be merged

**Comment by jlewi** [comment]
Thanks @gabrielwen looks like it got merged.

**Pull request merged**
