### PR TITLE
Add pipeline to centaldashboard

### PR DESCRIPTION
**Pull request by yupbank**
This change is [Reviewable](https://reviewable.io/reviews/kubeflow/kubeflow/1951)

### CODE REVIEW

**Comment by abhi-g** [comment]
FYI /cc @yebrahim @IronPan

**Comment by yebrahim** [comment]
Are we ready to do this yet? Should we wait until Pipelines is deployed with Kubeflow by default?

**Comment by abhi-g** [comment]
It shouldn't hurt and might be helpful if someone has deployed pipelines
into their KF cluster.

**Pull request merged**
