### PR TITLE
Fix for #432 Provide basic tests for every ksonnet prototype. It will…

### PR DESCRIPTION
**Pull request by kkasravi**
… need to be run with the jsonnect --jpath set to /kubeflow

---
This change is [Reviewable](https://reviewable.io/reviews/kubeflow/kubeflow/450)

### CODE REVIEW

**Comment by kkasravi** [comment]
This should also apply to #349

**Comment by ankushagarwal** [comment]
@kkasravi You need to merge master to pull in changes from #456

**Comment by kkasravi** [comment]
@ankushagarwal thanks! - will do now.

**Comment by kkasravi** [comment]
@ankushagarwal looks like tests pass

**Comment by ankushagarwal** [comment]
Thanks a lot - this will be very useful!
/lgtm
/approve

**Pull request merged**
