### PR TITLE
Add storage read scope to VM scopes; v0.2-branch (#1466)

### PR DESCRIPTION
**Pull request by jlewi**
* This is needed to pull images from private GCR.

* Cherry pick the fix into the v0.2-branch

* Related to #1432

---
This change is [Reviewable](https://reviewable.io/reviews/kubeflow/kubeflow/1468)

### CODE REVIEW

**Comment by abhi-g** [comment]
Makes sense. I agree that we'd have to ensure that tests on PRs to a
release branch should run from that branch.

**Comment by jlewi** [comment]
Tests are failing on the release branch because they haven't been updated to match changes in kubeflow/testing

```
W
Traceback (most recent call last):
 File "/usr/lib/python2.7/runpy.py", line 174, in _run_module_as_main
   "__main__", fname, loader, pkg_name)
 File "/usr/lib/python2.7/runpy.py", line 72, in _run_code
   exec code in run_globals
 File "/mnt/test-data-volume/kubeflow-presubmit-kubeflow-e2e-gke-1468-e71b3de-3209-4855/src/kubeflow/kubeflow/testing/wait_for_deployment.py", line 87, in <module>
   name="", test_cases=[test_case])
 File "/mnt/test-data-volume/kubeflow-presubmit-kubeflow-e2e-gke-1468-e71b3de-3209-4855/src/kubeflow/testing/py/kubeflow/testing/test_helper.py", line 182, in init
   test_cases=test_cases)
 File "/mnt/test-data-volume/kubeflow-presubmit-kubeflow-e2e-gke-1468-e71b3de-3209-4855/src/kubeflow/testing/py/kubeflow/testing/test_helper.py", line 43, in __init__
   raise ValueError("name must be set.")
ValueError: name must be set.
```

Filed #1474 to track tests for 0.2-branch

**Comment by jlewi** [comment]
Going to go ahead and merge this since test failures should be unrelated.

**Pull request merged**
