### PR TITLE
kfctl (golang) add bash/zsh completion

### LINKED ISSUE #2543: kfctl (golang) add bash/zsh completion
kfctl should have command completion provided by golang

### PR DESCRIPTION
**Pull request by kkasravi**
fixes #2543

---
This change is [Reviewable](https://reviewable.io/reviews/kubeflow/kubeflow/3067)

### CODE REVIEW

**Comment by kkasravi** [comment]
@jlewi @gabrielwen it would be nice to get this in. I rebased with master

**Comment by jlewi** [comment]
sorry @kkasravi 
/lgtm
/approve

**Pull request merged**
