### PR TITLE
store azure secrets to cluster during setup

### LINKED ISSUE #2675: Store Azure Secrets during setup
kfctl.sh curently stores secrets for GCP and these are later used by Kubeflow Pipelines to authenticate steps. kfctl.sh has been recently updated to support Azure (#2557), however setup doesnt save the secrets t othe cluster... (and it should) @ritazh @aronchick

### PR DESCRIPTION
**Pull request by rakelkar**
resolves #2675 by storing azure creds into a secret during setup

---
This change is [Reviewable](https://reviewable.io/reviews/kubeflow/kubeflow/2676)

### CODE REVIEW

**Comment by rakelkar** [comment]
I signed it!

**Comment by rakelkar** [comment]
I signed it

**Comment by jlewi** [comment]
Looks like test failures are #2693

**Pull request merged**
