### PR TITLE
images: Add the link

### PR DESCRIPTION
**Pull request by gaocegege**
/cc @jlewi

---
This change is [Reviewable](https://reviewable.io/reviews/kubeflow/kubeflow/614)

### CODE REVIEW

**Comment by gaocegege** [comment]
It seems that the CI failed in master, IMO.

**Comment by jlewi** [comment]
There was a problem creating the VM for the test on minikube. The logs aren't that helpful

```
 File "/usr/lib/python2.7/runpy.py", line 174, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/mnt/test-data-volume/kubeflow-presubmit-kubeflow-e2e-minikube-614-0340221-1073-e21d/src/kubeflow/kubeflow/testing/test_deploy.py", line 657, in <module>
    main()
  File "/mnt/test-data-volume/kubeflow-presubmit-kubeflow-e2e-minikube-614-0340221-1073-e21d/src/kubeflow/kubeflow/testing/test_deploy.py", line 647, in main
    wrap_test(args)
  File "/mnt/test-data-volume/kubeflow-presubmit-kubeflow-e2e-minikube-614-0340221-1073-e21d/src/kubeflow/kubeflow/testing/test_deploy.py", line 307, in wrap_test
    test_util.wrap_test(run, test_case)
  File "/mnt/test-data-volume/kubeflow-presubmit-kubeflow-e2e-minikube-614-0340221-1073-e21d/src/kubeflow/testing/py/kubeflow/testing/test_util.py", line 82, in wrap_test
    test_func()
  File "/mnt/test-data-volume/kubeflow-presubmit-kubeflow-e2e-minikube-614-0340221-1073-e21d/src/kubeflow/kubeflow/testing/test_deploy.py", line 305, in run
    args.func(args)
  File "/mnt/test-data-volume/kubeflow-presubmit-kubeflow-e2e-minikube-614-0340221-1073-e21d/src/kubeflow/kubeflow/testing/test_deploy.py", line 445, in deploy_minikube
    vm_util.wait_for_vm(args.project, args.zone, args.vm_name)
  File "/mnt/test-data-volume/kubeflow-presubmit-kubeflow-e2e-minikube-614-0340221-1073-e21d/src/kubeflow/kubeflow/testing/vm_util.py", line 37, in wait_for_vm
    "Timed out waiting for op: {0} to complete.".format(op_id))
NameError: global name 'op_id' is not defined
```
The NameError looks like a typo in the exception handling and not the actual error.

**Pull request merged**
