### PR TITLE
add prow_config.yaml

### PR DESCRIPTION
**Pull request by lluunn**
prow_config.yaml contains the workflows that we want to run by prow.

By using prow_config.yaml, we can use the same testing image for different kubeflow repos.

Related to #276 

---
This change is [Reviewable](https://reviewable.io/reviews/kubeflow/kubeflow/271)

### CODE REVIEW

**Comment by jlewi** [comment]
The test didn't succeed.
Also it looks like the test is only running a single workflow; should it be running two workflows?

**Comment by jlewi** [comment]
You can ignore the test failure that should be fixed #274 if you sync.

**Comment by jlewi** [comment]
Looks like a timeout. Maybe you need to increase it?

**Comment by lluunn** [comment]
Something is wrong. It stuck at checkout for >11hrs.
http://testing-argo.kubeflow.io/timeline/kubeflow-test-infra/kubeflow-presubmit-tf-serving-image-271-152c3d9-294-a16f;tab=workflow

**Comment by lluunn** [comment]
@jlewi The test passed with just one workflow.
I think the TF serving image workflow needs some fix to integrate with prow. I will do that in another PR.
PTAL, thanks

**Pull request merged**
