### PR TITLE
Release v1.8.0-rc.2

### PR DESCRIPTION
**Pull request by DnPlas**
Bump release version v1.8.0-rc.1 -> v1.8.0-rc.2

cc: @kimwnasptd

### CODE REVIEW

**Comment by kimwnasptd** [comment]
Looks like the Notebook Controller is failing for the same reason like
* https://github.com/kubeflow/kubeflow/pull/7310/files
* https://github.com/kubeflow/kubeflow/pull/7338

@DnPlas could you send a small PR to only update the golang version used to run the unit tests to 1.20?
https://github.com/kubeflow/kubeflow/blob/master/.github/workflows/notebook_controller_unit_test.yaml#L17

**Comment by DnPlas** [comment]
@kimwnasptd sent a patch in #7348 , thanks!

**Comment by kimwnasptd** [comment]
Thank you @DnPlas for the help!

/lgtm
/approve

**Comment by kimwnasptd** [comment]
Looks like only the workflow for the CentralDashboard in Angular failed
https://github.com/kubeflow/kubeflow/actions/runs/6531881039/job/17733960649

I think we should drop this automation, until the effort will get back some traction

**Pull request merged**
