### PR TITLE
fix Profile Plugins functionality

### PR DESCRIPTION
**Pull request by surajkota**
Resolves: #6618

Description of changes:
- As described in https://github.com/kubeflow/kubeflow/issues/6618#issuecomment-1223404464, profile plugins functionality broke when the yaml package was changed as part of #6491. Since the structs have JSON tags, we can safely serialize and deserialize the structs using Go's JSON library.
- Added unit tests to prevent this from happening in future.
- Added a validation in the plugin to error out if the role value is missing because golang json library will create the struct even if the value is missing. Since the struct is small at this point, I have added a simple validation but this solution is not great if the struct is complex.
- Added samples which were deleted.

Testing:
- Ran unit tests
- Tested with and without the AWS plugin by running the controller locally
- Tested that GCP plugin struct as well to ensure it is loaded but have not run a real e2e test. Someone using GCP will need to confirm

### CODE REVIEW

**Comment by surajkota** [comment]
@kimwnasptd

**Comment by kimwnasptd** [comment]
Thanks for the prompt PR @surajkota!

The changes LGTM. Could you also add a simple gh action for running the `make test` rule to ensure we keep testing this functionality on each PR?

You can create a `prof_controller_unit_test.yaml` under https://github.com/kubeflow/kubeflow/blob/master/.github/workflows/ for this that just runs `make test`. We can use the https://github.com/actions/setup-go action for setting up the Go env

**Comment by surajkota** [comment]
@kimwnasptd thats a good idea. Added it

I also opened https://github.com/kubeflow/kubeflow/pull/6627 for KServe, can you please take a look

**Comment by kimwnasptd** [comment]
Thanks @surajkota! Will take a look to the KServe one as well.

/lgtm
/approve

**Pull request merged**
