### PR TITLE
Use manifest master for tests.

### PR DESCRIPTION
**Pull request by zhenghuiwang**
Update the pinned version in kfctl go tests to [7cf5587dd9e2ec523bbdc99642d530f42fec4361](https://github.com/kubeflow/manifests/commit/7cf5587dd9e2ec523bbdc99642d530f42fec4361)

---
This change is [Reviewable](https://reviewable.io/reviews/kubeflow/kubeflow/3600)

### CODE REVIEW

**Comment by yanniszark** [comment]
Hi @zhenghuiwang !
This seems to be a feature, not a bug (https://github.com/kubeflow/kubeflow/pull/3493/files).
We pin to a known good version so that changes in manifests don't break our E2E tests.
cc @jlewi

**Comment by zhenghuiwang** [comment]
> This seems to be a feature, not a bug (#3493).

Hi @yanniszark How do we make sure kubeflow@master & manifests@master can work together?

Also, https://github.com/kubeflow/kubeflow/pull/3590 failed because this pinned version doesn't have valid config.

**Comment by zhenghuiwang** [comment]
maybe I can pin it to the master commit for now.

**Comment by swiftdiaries** [comment]
We've added a E2E test for kfctl in manifests as well. So it should be fine to pin to master.

**Comment by zhenghuiwang** [comment]
> We've added a E2E test for kfctl in manifests as well. So it should be fine to pin to master.

@yanniszark @swiftdiaries @jlewi @pdmack  Is it safe to merge this PR then?

**Comment by zhenghuiwang** [comment]
Updated the pinned version, which should be safe to be merged.

**Comment by swiftdiaries** [comment]
LGTM.
I don't have owners access, so I'm not able to approve

**Pull request merged**
