### PR TITLE
Fix iap libsonnet: avoid empty object

### LINKED ISSUE #2642: Error in application component
#2608
#2622

Both issues have error when trying to apply (or show) application component generated from kfctl.

cc @kkasravi

### PR DESCRIPTION
**Pull request by lluunn**
fix #2642 

See https://github.com/kubeflow/kubeflow/issues/2642#issuecomment-470672714

/cc @kunmingg @richardsliu

---
This change is [Reviewable](https://reviewable.io/reviews/kubeflow/kubeflow/2654)

### CODE REVIEW

**Comment by lluunn** [comment]
test failure is argo deploy
/retest

**Comment by kkasravi** [comment]
@lluunn there is a iap_test.jsonnet that might need to be updated...

**Comment by lluunn** [comment]
The test passed.
I think it's expected because this change is essentially trimming the empty object.

**Pull request merged**
