### PR TITLE
Reword reference to Python 3.6 (#3391)

### LINKED ISSUE #3391: Python 3.7 is now supported by Tensorflow
This is now out of date as Tensorflow now supports 3.7 (see https://github.com/tensorflow/tensorflow/issues/20517):
https://github.com/kubeflow/kubeflow/blob/1f8d0008c02b7582a45d4bce0d7d34ae97c081ce/components/tensorflow-notebook-image/Dockerfile#L97

### PR DESCRIPTION
**Pull request by scottilee**
Fixes #3391. In case the user wants to continue using 3.6 I left the blurb about what line to add.

---
This change is [Reviewable](https://reviewable.io/reviews/kubeflow/kubeflow/3397)

### CODE REVIEW

**Comment by scottilee** [comment]
Signed CLA.

**Comment by scottilee** [comment]
Look like a timeout? Can someone rerun the test?

**Comment by scottilee** [comment]
Not sure what this error has to do with my change... @jlewi can you advise?

Screen Shot 2019-08-17 at 11 56 10 PM

**Comment by jlewi** [comment]
I think this is obsolete because we are no longer using conda.

**Pull request closed without merging**
