### PR TITLE
fixes 'metacontroller's compositecontrollers and decoratorcontrollers need to be at Cluster scope'

### LINKED ISSUE #1833: metacontroller's compositecontrollers and decoratorcontrollers need to be at Cluster scope
See metacontroller's [yaml](https://raw.githubusercontent.com/GoogleCloudPlatform/metacontroller/master/manifests/metacontroller.yaml)

### PR DESCRIPTION
**Pull request by kkasravi**
fixes #1833

---
This change is [Reviewable](https://reviewable.io/reviews/kubeflow/kubeflow/1834)

### CODE REVIEW

**Comment by jlewi** [comment]
So metacontroller is a cluster scoped resource? 

It looks like this PR is installing metacontroller by default. Do we already have a component that depends on metacontroller or is this in preparation for the new Jupyter CRD?

**Comment by jlewi** [comment]
So metacontroller is cluster scoped?

It looks like you are installing metacontroller by default now with kfctl.sh. Do we already have something that is using metacontroller by default? Or is this in preparation for the Jupyter CRD.

**Comment by kkasravi** [comment]
Yes, metacontroller in 0.2 is cluster scoped. 

We could wait until jupyter CRD is ready. Also we need to upgrade cloud-endpoints.

**Comment by kkasravi** [comment]
Since this is in preparation for jupyterhub replacement which i'll open a PR this week and it doesn't conflict with cloud-endpoints (which isn't using any of metacontroller's 0.2 crds), I think this could go in now.

**Pull request merged**
