### PR TITLE
Make bootstrapper support multi ks registry, including private ones

### PR DESCRIPTION
**Pull request by kunmingg**
For https://github.com/kubeflow/kubeflow/issues/880
Bootstrapper now can apply and update ksonnet apps from multi repos.
Users now can one-command-deploy any custom ksonnet apps set through bootstrapper. 

---
This change is [Reviewable](https://reviewable.io/reviews/kubeflow/kubeflow/900)

### CODE REVIEW

**Comment by jlewi** [comment]
/assign @ironpan 

@ironpan will this work for you?

**Comment by IronPan** [comment]
I guess it would work. Based on my understanding adding a new private ksonnet registry would 
1.update config/default.yaml
2.update config/gcp_prototype.yaml 
3. build new private bootstrapper docker image then deploy

**Pull request merged**
