### PR TITLE
Cherry pick minor fixes on master

### PR DESCRIPTION
**Pull request by kunmingg**
Include fix for [re-apply](https://github.com/kubeflow/kubeflow/issues/4397) and allow deleting application from config.

cherry pick:
#4391
#4385
#4380 
#4398

Related to: #4397

---
This change is [Reviewable](https://reviewable.io/reviews/kubeflow/kubeflow/4435)

### CODE REVIEW

**Comment by lluunn** [comment]
close for https://github.com/kubeflow/kubeflow/pull/4432

**Comment by lluunn** [comment]
sorry comment on wrong pr

**Comment by lluunn** [comment]
/lgtm
/approve
Test failure is https://github.com/kubeflow/testing/issues/508

**Comment by jlewi** [comment]
test-worker image has been rolled back.
/test all

**Pull request merged**
