### PR TITLE
Small fix to katib deploy

### PR DESCRIPTION
**Pull request by inc0**
Katib vizier-core fails without it

---
This change is [Reviewable](https://reviewable.io/reviews/kubeflow/kubeflow/999)

### CODE REVIEW

**Comment by pdmack** [comment]
/assign @lluunn 
We were just talking about that change yesterday on Slack.

**Comment by pdmack** [comment]
```
Containers:
  vizier-core:
    Container ID:  docker://bb4ea768bbb1db6b6c4e3a71fddc3c696b5d7fa1a3ace71b705f85865ee59d08
    Image:         katib/vizier-core
    Image ID:      docker-pullable://katib/vizier-core@sha256:7e7160d785ab4eaa30c21424d903f5a762248f843d40896964ec0fae39a2fee4
    Port:          6789/TCP
    Args:
      ./vizier-manager
      -w
      kubernetes
      -i
      k-cluster.example.net
```

I think @lluunn already fixed it.

**Comment by lluunn** [comment]
https://github.com/kubeflow/kubeflow/blob/master/kubeflow/katib/vizier.libsonnet#L69

It's fixed. I guess you didn't sync?

**Comment by inc0** [comment]
yeah, my bad, closing this one

**Pull request closed without merging**
