### PR TITLE
Remove sync_images.py

### PR DESCRIPTION
**Pull request by marload**
The existing late return has been changed to an early return.

Thank You!

### CODE REVIEW

**Comment by jlewi** [comment]
This script is no longer used. Do you want to just delete it?

kfctl now has a subcommand "mirror" which outputs either Cloud Build or Tekton workflows to mirror your images to a different registry.

**Comment by marload** [comment]
@jlewi 
Are you just saying to delete file `sync_image.py`?

**Comment by jlewi** [comment]
Yes

**Pull request merged**
