### PR TITLE
python prediction server

### PR DESCRIPTION
**Pull request by lluunn**
An implementation of Google Cloud Machine Learning Engine (CMLE) [Prediction API](https://cloud.google.com/ml-engine/docs/v1/predict-request).

The PR contains the Dockerfile that can run a python prediction server that provides the prediction service for a trained ML model. It supports tensorflow, scikit-learn, and xgboost. See [README](https://github.com/lluunn/kubeflow/blob/pred_server/components/prediction_server/README.md).

### CODE REVIEW

**Comment by lluunn** [comment]
related to this [issue](https://github.com/google/kubeflow/issues/15)

**Comment by jlewi** [comment]
Can you update the comment to explain what this PR is about?

What functionality is this Python Server provide? What does the API look like? Which frameworks does it support?

**Comment by jlewi** [comment]
Also you might want to take a look at #15 and chime in about how this PR relates to that issue.

**Comment by lluunn** [comment]
Updated the description, and added an OpenAPI spec. PTAL, thanks!

**Comment by jlewi** [comment]
Thanks can you explain the architecture? 

For the model server? 
Does the server support HTTP and Rest? Is their common request handling infrastructure?
What is the interface between the model server and specific model types/framework?

What server infrastructure does the model use?

The Seldon API also provides a one off that allows sending data with more structure

```
message DefaultData {
  repeated string names = 1;
  oneof data_oneof {
    Tensor tensor = 2;
    google.protobuf.ListValue ndarray = 3;
  }
}

message Tensor {
  repeated int32 shape = 1 [packed=true];
  repeated double values = 2 [packed=true];
}
```

**Comment by lluunn** [comment]
It's a python HTTP server (no gRPC support yet), using [paste](https://pypi.python.org/pypi/Paste)

For either TF, scikit, or xgboost, the request should have the same format as {"instances": [instance1, instance2, ...]} as described in [spec](https://gist.github.com/lluunn/22fe1f2eaf0859f7aee8c54a1aeb3275), and handled by the handler [here](https://github.com/lluunn/kubeflow/blob/pred_server/components/prediction_server/server/prediction_server_lib.py#L302).

In the case of TF, the TF ModelServer is running as a [subprocess](https://github.com/lluunn/kubeflow/blob/pred_server/components/prediction_server/server/frameworks/tf_prediction_server_lib.py#L151). We may want to make ModelServer to run as its own container later.

**Comment by jlewi** [comment]
I don't think running the TF ModelServer as a subprocess is the right pattern for K8s. The more common pattern for K8s would be to have 2 containers in the pod one for the Python HTTP server and one for TF Serving.

So in the case of TF, is the primary purpose of this server to proxy HTTP to gRPC? Does it do anything else like transform the request to ExampleProto?

**Comment by jlewi** [comment]
How does this compare to the Seldon [model server](https://github.com/SeldonIO/seldon-core/tree/master/wrappers/python)?

**Comment by jlewi** [comment]
Would it make sense to turn this into a CMLE to TF Proxy? So a simple binary that converts the incoming request to a request that can be sent to TF serving? With the expectation that this would run as a sidecar in a pod running TF Serving.

**Comment by yupbank** [comment]
hey... how is the status of this? i am interested in the feature.. 
if no one is picking up, i can help a bit..

**Comment by lluunn** [comment]
Scope it down to a proxy from CMLE to TF serving sounds good. I will split the PR and start with that.

**Comment by jlewi** [comment]
#183 was just submitted. Do we still need this PR?

**Comment by lluunn** [comment]
I will close it for now. We will add more functionalities to the http server in another PR.

**Pull request closed without merging**
