### PR TITLE
Manage multiple profiles from centraldashboard UI

### PR DESCRIPTION
**Pull request by Jason-CKY**
#4569
#4924
#6575

This is a PR to fix these issues. I just extracted out the commits from @StatCan:
* https://github.com/StatCan/kubeflow/commit/01a17e6b4ac2520327d95eea6a414a234f11db5e#diff-7b12be43febc6e18259dd77c004315b4143d570234e0f15acf5f9d7b79c371b5
* https://github.com/StatCan/kubeflow/commit/1fa21268306f8be26d21efe905d0f13e558169ed

### CODE REVIEW

**Comment by maganaluis** [comment]
Any chance this could get merged before the 1.8 release?

**Comment by kimwnasptd** [comment]
Have this in my radar and will take a look by EOW, thanks for the work @Jason-CKY!

**Comment by thesuperzapper** [comment]
@kimwnasptd I also think there is some kind of bug after adding the "all namespaces" feature from https://github.com/kubeflow/kubeflow/pull/6778, give that this person raised an issue https://github.com/kubeflow/kubeflow/issues/7188

But I am not sure if its just a visual bug.

**Comment by maganaluis** [comment]
Is there any way to cherry pick this into a patch for 1.8 if not add it to 1.9? This feature comes up from time to time as people shift from team to team is often better to have more than one owner. Programatic access works, but creates unnecessary ops work.

**Comment by juliusvonkohout** [comment]
@maganaluis can you create a new PR without merge conflicts and join the working group meeting?

**Comment by maganaluis** [comment]
Sure, I'll create a PR in the next two weeks. Which working group is responsible for this service?

**Comment by juliusvonkohout** [comment]
> Sure, I'll create a PR in the next two weeks. Which working group is responsible for this service?

Currently "notebooks", but it will probably renamed in the future to workspaces or workbenches

**Comment by maganaluis** [comment]
@juliusvonkohout I started working on this, but I noticed the image is using nodejs 14 which is past End of Life. 

I'm actually getting `33.11 npm ERR! code ELIFECYCLE` on the PR tests, as well as locally. I'll look into upgrading to 20 but I might do the upgrade to 20 on a sep PR. 

https://github.com/kubeflow/kubeflow/pull/7435

**Comment by thesuperzapper** [comment]
Closing as is duplicate of https://github.com/kubeflow/kubeflow/pull/7435, lets continue the discussion on that PR.

**Pull request closed without merging**
