### PR TITLE
Updated Jupyter image paths for using in notebook controller

### PR DESCRIPTION
**Pull request by zabbasi**
This change is [Reviewable](https://reviewable.io/reviews/kubeflow/kubeflow/2552)

### CODE REVIEW

**Comment by zabbasi** [comment]
Tested all cpu tagged images locally (and run some test on a Kubernete cluster) all could successfully launch the notebook and import tensorflow.

**Comment by jlewi** [comment]
Thanks.

@zabbasi How come there's no 1.4 image?

**Comment by zabbasi** [comment]
> Thanks.
> 
> @zabbasi How come there's no 1.4 image?

tensorflow could not be properly  imported in 1.4.1 . removed it per @lluunn suggestion as it is barely used.

**Comment by lluunn** [comment]
@zabbasi I think you mentioned 1.4 has error? I think in that case we can just remove that.
I don't think we need to keep that many versions anyway.

**Pull request merged**
