### PR TITLE
notebooks: Don't reconcile on Events deletion

### PR DESCRIPTION
**Pull request by kimwnasptd**
Refs https://github.com/kubeflow/kubeflow/issues/6382

The PR updates the controller to never trigger the `Reconcile()` function when any K8s Event gets deleted, whether it belonged to a Notebook or not.

This should resolve logs we saw in #6382 like:
```
2022-03-01T14:08:50.378Z	ERROR	controllers.Notebook	unable to fetch Notebook	{"notebook": "kube-system/istio-cni-node-854fq.16d83d225eab3a57", "error": "Notebook.kubeflow.org \"istio-cni-node-854fq.16d83d225eab3a57\" not found"}
github.com/go-logr/zapr.(*zapLogger).Error
	/go/pkg/mod/github.com/go-logr/zapr@v0.1.0/zapr.go:128
github.com/kubeflow/kubeflow/components/notebook-controller/controllers.(*NotebookReconciler).Reconcile
	/workspace/notebook-controller/controllers/notebook_controller.go:125
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).reconcileHandler
	/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.2.0/pkg/internal/controller/controller.go:216
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem
	/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.2.0/pkg/internal/controller/controller.go:192
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).worker
	/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.2.0/pkg/internal/controller/controller.go:171
k8s.io/apimachinery/pkg/util/wait.JitterUntil.func1
	/go/pkg/mod/k8s.io/apimachinery@v0.0.0-20190404173353-6a84e37a896d/pkg/util/wait/wait.go:152
k8s.io/apimachinery/pkg/util/wait.JitterUntil
	/go/pkg/mod/k8s.io/apimachinery@v0.0.0-20190404173353-6a84e37a896d/pkg/util/wait/wait.go:153
k8s.io/apimachinery/pkg/util/wait.Until
	/go/pkg/mod/k8s.io/apimachinery@v0.0.0-20190404173353-6a84e37a896d/pkg/util/wait/wait.go:88
```

This means that the Controller won't be doing anything to the mirrored/emitted Notebook events, if one of the underlying Pod Events gets deleted. But this is already the case, so we are not changing any functionality.

I've also built an image for this code, for trying it out `gcr.io/arrikto/notebook-controller:v1.5.0-rc.0-13-g459c3bdaf`

/cc @juliusvonkohout @elikatsis

### CODE REVIEW

**Comment by juliusvonkohout** [comment]
There are still some rare errors, but i think they were also there in 1.4. The error spam is gone.

```
2022-03-03T14:50:33.743Z	ERROR	controllers.Notebook	unable to update Statefulset	{"notebook": "julius-vonkohout/julius-1", "error": "Operation cannot be fulfilled on statefulsets.apps \"julius-1\": the object has been modified; please apply your changes to the latest version and try again"}
github.com/go-logr/zapr.(*zapLogger).Error
	/go/pkg/mod/github.com/go-logr/zapr@v0.1.0/zapr.go:128
github.com/kubeflow/kubeflow/components/notebook-controller/controllers.(*NotebookReconciler).Reconcile
	/workspace/notebook-controller/controllers/notebook_controller.go:157
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).reconcileHandler
	/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.2.0/pkg/internal/controller/controller.go:216
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem
	/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.2.0/pkg/internal/controller/controller.go:192
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).worker
	/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.2.0/pkg/internal/controller/controller.go:171
k8s.io/apimachinery/pkg/util/wait.JitterUntil.func1
	/go/pkg/mod/k8s.io/apimachinery@v0.0.0-20190404173353-6a84e37a896d/pkg/util/wait/wait.go:152
k8s.io/apimachinery/pkg/util/wait.JitterUntil
	/go/pkg/mod/k8s.io/apimachinery@v0.0.0-20190404173353-6a84e37a896d/pkg/util/wait/wait.go:153
k8s.io/apimachinery/pkg/util/wait.Until
	/go/pkg/mod/k8s.io/apimachinery@v0.0.0-20190404173353-6a84e37a896d/pkg/util/wait/wait.go:88
```

[notebook-controller-deployment-74465f77b4-n7k86-manager.log](https://github.com/kubeflow/kubeflow/files/8178807/notebook-controller-deployment-74465f77b4-n7k86-manager.log)

The gpu unavailability is a problem of my cluster, not your implementation.

So i 
/approve

**Comment by kimwnasptd** [comment]
Thank you for the quick review @juliusvonkohout!

Regarding the `the object has been modified; please apply your changes to the latest version and try again` logs, AFAIK this is considered a benign error https://github.com/kubernetes/kubernetes/issues/28149 https://github.com/kubernetes/kubernetes/issues/84430.

But ofc we should ideally be able to remove these logs altogether and figure out the codepath that triggers them. But for the KF 1.5 I also believe we are OK with them for now.

cc @kubeflow/wg-notebooks-leads for helping merge the PR

**Comment by juliusvonkohout** [comment]
> Thank you for the quick review @juliusvonkohout!
> 
> Regarding the `the object has been modified; please apply your changes to the latest version and try again` logs, AFAIK this is considered a benign error [kubernetes/kubernetes#28149](https://github.com/kubernetes/kubernetes/issues/28149) [kubernetes/kubernetes#84430](https://github.com/kubernetes/kubernetes/issues/84430).
> 
> But ofc we should ideally be able to remove these logs altogether and figure out the codepath that triggers them. But for the KF 1.5 I also believe we are OK with them for now.
> 
> cc @kubeflow/wg-notebooks-leads for helping merge the PR

i do not need to because the jupyterlabs are working even with GPUs. After 1.5 we can get rid of the remaining benign errors. We can merge this pull request now.

**Comment by juliusvonkohout** [comment]
> But for the KF 1.5 I also believe we are OK with them for now.

Yes, please merge.

**Pull request merged**
