### PR TITLE
Update Central Dashboard npm packages, change Dockerfile to use Distroless

### PR DESCRIPTION
**Pull request by jtfogarty**
This is part of an effort to reduce critical vulnerabilities. 

Reference issue is [Convert Container image to distroless #4590](https://github.com/kubeflow/kubeflow/issues/4590)

### CODE REVIEW

**Comment by jtfogarty** [comment]
I'm still in the process of testing this.  We need to put a hold on this PR

**Comment by jtfogarty** [comment]
I'm getting the below errors when I deploy;
```
Warning  Failed     25s (x4 over 65s)  kubelet, gke-kf-mar-25-kf-mar-25-cpu-pool-v1-3d7367ab-vfqc  Error: failed to start container "centraldashboard": Error response from daemon: OCI runtime create failed: container_linux.go:345: starting container process caused "exec: \"npm\": executable file not found in $PATH": unknown
 ```

**Comment by jlewi** [comment]
@jtfogarty Any update on this? Do you think we can get this in for 1.1?

It looks like your docker image doesn't have npm in it?

**Comment by jtfogarty** [comment]
@jlewi @krishnadurai is working with some google people on [this issue #498](https://github.com/GoogleContainerTools/distroless/issues/498) @krishnadurai can you please provide an update so we know what is going on?

**Comment by jlewi** [comment]
@jtfogarty @yanniszark @kimwnasptd  Is this something we wanted to try to push over the hump for the next release?

**Comment by jtfogarty** [comment]
My plan was to push this to a working group.

**Comment by DavidSpek** [comment]
@thesuperzapper This seems like something that should be merged before 1.3.

**Comment by DavidSpek** [comment]
@jtfogarty There is a conflict with the Dockerfile as the node version has since been update. Could you rebase on master to solve this issue?

**Comment by jtfogarty** [comment]
@DavidSpek This PR should have been closed.  We attempted to change the base image to distroless but with lots of issues.  The goal was to eliminate CVs but distorless images also have CVs.  Each working group should mitigate their image CVs.

**Pull request closed without merging**
