### PR TITLE
Replace azure env by aks || acs-engine

### PR DESCRIPTION
**Pull request by wbuchwalter**
In azure there is two main ways to create a kubernetes cluster:
* acs-engine
* AKS

`acs-engine` is the open source project used behing the scene by AKS. acs-engine receives features first and then they make their way to AKS.
The NVIDIA driver installation was recently updated in acs-engine to make it simpler, and so the mount point are now different between the two platform.
acs-engine will also soon received the update to use NVIDIA device-plugin, so the two platform will use different configuration for a few months.

Consequently I replaced the `azure` cloud by `aks`or `acsengine` to avoid issues like this one: https://github.com/kubeflow/kubeflow/issues/414#issuecomment-372502012

Once the move to device-plugin is complete in AKS we will probably be able to entirely remove the cloud param since it won't be used anymore.

---
This change is [Reviewable](https://reviewable.io/reviews/kubeflow/kubeflow/415)

### CODE REVIEW

**Comment by jlewi** [comment]
/lgtm
/approve

Might be a good idea to open issues to add
1. ksonnet unittests for the Azure configs
2. E2E testing on Azure.

**Comment by wbuchwalter** [comment]
@jlewi Can you re /lgtm? Had to pull master to fix issues with the presubmit hook. Thanks.

**Pull request merged**
