### PR TITLE
Fix finalizer rbac error and use nonroot account as default account in docker image

### PR DESCRIPTION
**Pull request by MartinForReal**
Fix: #5250
add rbac rules for finalizer in order to support kubernetes 1.18+
use nonroot account as default account
update cert-manager related configuration to support cert-manager 0.16
Signed-off-by: Fan Shang Xiang <fanshangxiang@gmail.com>

### CODE REVIEW

**Comment by jlewi** [comment]
Looks like we need to identify proper owners for the notebook controller

kubeflow/kubeflow#5200

/assign @kimwnasptd 
/assign @StefanoFioravanzo 
/assign @yanniszark

**Comment by MartinForReal** [comment]
I would like to join kubeflow org if I could. @jlewi

**Comment by Jeffwan** [comment]
It would be better to mention it's controller runtime 0.6.2.

**Comment by jlewi** [comment]
@MartinForReal 
https://www.kubeflow.org/docs/about/contributing/#joining-the-community

**Comment by MartinForReal** [comment]
> It would be better to mention it's controller runtime 0.6.2.

I did. Please refer to the first comment.

> update controller runtime to 0.6.2
> add rbac rules for finalizer in order to support kubernetes 1.18+
> use nonroot account as default account
> upgrade go to 1.14
> Signed-off-by: Fan Shang Xiang fanshangxiang@gmail.com

**Comment by jlewi** [comment]
@StefanoFioravanzo, @kimwnasptd, @yanniszark ping?

**Comment by kimwnasptd** [comment]
@MartinForReal could you give a brief explanation of why you made these changes?

Does this PR close an already existing issue?

**Comment by MartinForReal** [comment]
@kimwnasptd Kubebuilder v2 provides an excellent user experience in developing controller logic, such as generating RBAC configuration, Adding webhook configuration, Setting owner reference and etc. And I tried to adopt kubebuilder and found that we might need to update a few scripts and configurations.  After we adopt kubebuilder, we can fix a few RBAC issues on k8s 1.16+ cluster and it is much easier if we need to add webhook and other logic.  If these commits should be a part of other implementation, I can also refactor the code and submit a pr.

**Comment by MartinForReal** [comment]
related issue: https://github.com/kubeflow/kubeflow/issues/5214

**Pull request closed without merging**
