### PR TITLE
crud-web-apps: Apply ng lint

### PR DESCRIPTION
**Pull request by haoxins**
#6464 

The `1/2` process of applying `ng lint` or `eslint`

### CODE REVIEW

**Comment by kimwnasptd** [comment]
Thanks @haoxins! Let's also add a commit to introduce a `frontend_lint.yaml` that:
1. Will be triggered if either of the frontend of the three web apps or the common frontend code changes
2. Will run the `npm run lint` command of these 4 frontend projects

It's OK to not create a workflow for each project. We can just have one action that tests all frontends at the same time, all the time

**Comment by haoxins** [comment]
> Let's also add a commit to introduce a frontend_lint.yaml that:

We can do this at another PR I will submit after this been merged.
Still need to fix some lint error that can't fix by `--fix`
And maybe or not break something, that's why I split into two PRs.

**Comment by thesuperzapper** [comment]
> Thanks @haoxins! Let's also add a commit to introduce a `frontend_lint.yaml` that:
> 
> 1. Will be triggered if either of the frontend of the three web apps or the common frontend code changes
> 2. Will run the `npm run lint` command of these 4 frontend projects
> 
> It's OK to not create a workflow for each project. We can just have one action that tests all frontends at the same time, all the time

@kimwnasptd I assume you mean we add a PR check that fails if linting would change the code?

**Comment by haoxins** [comment]
https://github.com/kubeflow/kubeflow/pull/6586
I think all the lint rules are pass now~

**Pull request merged**
