### PR TITLE
adding kfctl to a container, Makefile related changes, developer_guide updated

### LINKED ISSUE #2832: kfctl Makefile updates, developer_guide updates
- [ ] add kfctl as a target in the Dockerfile (build kfctl in a container)
- [ ] fix TAG in Makefile so `make push-*` works correctly
- [ ] update developer_guide to include new make targets

### PR DESCRIPTION
**Pull request by kkasravi**
fixes #2832

- [x] add kfctl as a target in the Dockerfile (build kfctl in a container)
- [x] fix TAG in Makefile so `make push-*` works correctly
- [x] update developer_guide to include new make targets

---
This change is [Reviewable](https://reviewable.io/reviews/kubeflow/kubeflow/2833)

### CODE REVIEW

**Comment by jlewi** [comment]
This is to support reproducible builds as part of releases?

**Comment by kkasravi** [comment]
@jlewi good to go. See my comments.

**Pull request merged**
