### PR TITLE
fixes 'ksonnet package for Jupyter/JupyterHub'

### LINKED ISSUE #1886: ksonnet package for Jupyter/JupyterHub
See #42  - Split up core ksonnet package

Right now JupyterHub is in the "core" package. We should probably move it into its own ksonnet package.

@pdmack @kkasravi WDYT?

### PR DESCRIPTION
**Pull request by kkasravi**
fixes #1886

---
This change is [Reviewable](https://reviewable.io/reviews/kubeflow/kubeflow/1917)

### CODE REVIEW

**Comment by kkasravi** [comment]
@jlewi I moved the jupyterhub component to kubeflow/jupyterhub. However the documentation for ks-0.12 says that as a [dependency](https://github.com/ksonnet/ksonnet/blob/master/docs/cli-reference/ks_pkg_install.md) I should put it under kubeflow/core/jupyterhub/.  Thoughts?

**Comment by jlewi** [comment]
Thanks @kkasravi 

nit: How about just calling the package Jupyter? This way we won't need to refactor it if we move away from JupyterHub.

**Comment by kkasravi** [comment]
@jlewi @pdmack should be good to merge

**Comment by vkoukis** [comment]
@jlewi 
> I think @ioandr and @vkoukis have some follow up PRs making additional changes to Jupyter/JupyterHub. So how should we plan on sequencing those PRs?

We have coordinated with @kkasravi on this, we will incorporate his feedback and rebase our work (#1918) on this PR.

**Comment by kkasravi** [comment]
I'll rebase this evening / tomorrow morning

**Pull request merged**
