### PR TITLE
Add mxnet operator (https://github.com/kubeflow/community/issues/136)

### PR DESCRIPTION
**Pull request by suleisl2000**
Add MXNet operator into kubeflow repo

---
This change is [Reviewable](https://reviewable.io/reviews/kubeflow/kubeflow/1392)

### CODE REVIEW

**Comment by pdmack** [comment]
`mxnet-operator.libsonnet is not formatted`

@suleisl2000 can you please run scripts/autoformat_jsonnet.sh on your code?

**Comment by jzp1025** [comment]
@pdmack Any suggestion about this ? thank you !

**Comment by pdmack** [comment]
`prototypes/mxnet-job.jsonnet is not formatted`

You run scripts/autoformat_jsonnet.sh in your branch and it will format the new libsonnet and jsonnet files you are adding. Then you just commit those changed files to your PR.

**Comment by jzp1025** [comment]
@pdmack thanks for your reply 
actually we have correct the format , now we are facing the following failed-test:

> Test failed; Failed to run argo workflow

the log shows 

> /src/kubeflow/testing/py/kubeflow/testing/run_e2e_workflow.py|242| Workflow kubeflow-test-infra/kubeflow-presubmit-kfctl-1392-40d3a42-3060-25d4 finished phase: Failed

so i'm thinking if this is due to the 'scripts/kfctl.sh' or other files i haven't changed ?

thanks again

**Comment by richardsliu** [comment]
@jzp1025 The argo test failure was a flake. It is passing now. But looks like you still have some jsonnet formatting issues, please run the latest autoformat script and commit the fixes.

**Comment by jzp1025** [comment]
@pdmack 
Hi ! We are facing the following failed tests:

> smoke-tfjob-gke 9.02s
    go run hack/e2e.go -v --test --test_args='--ginkgo.focus=smoke\-tfjob\-gke$'

and we got error log like this 

> Exception occured; type <type 'exceptions.TypeError'> message Got an unexpected keyword argument 'async' to method get_namespaced_custom_object

I don't think this is related to our code , looking for some help here !

Thanks for your attention !

**Comment by jlewi** [comment]
This should be fixed by kubeflow/tf-operator#790

**Pull request merged**
