### PR TITLE
[WIP] Remove ksonnet. Move kfctl, bootstrap to v2

### PR DESCRIPTION
**Pull request by kkasravi**
Resolves the following issues:

- [x] bootstrap: replace ksonnet with kustomize, move to v2 #3371 
- [x] kfctl: remove ksonnet, move to v2 #3368
- [x] upgrade to use kustomize v2.1.0 #3497
- [x] Problem building kfctl - /tmp/v2 not properly created #2790
- [x] Provide a build option that will create a versioned package for k8 libraries #2636
- [x] upgrade to use kustomize v2.1.0 #3497
- [x] [Discussion] Where should kfctl go code live? New repository? #2812

---
This change is [Reviewable](https://reviewable.io/reviews/kubeflow/kubeflow/3528)

### CODE REVIEW

**Comment by jlewi** [comment]
@kkasravi I think moving kfctl should be its own PR and I still have some questions about when exactly.

Moving the code is a risk of breaking a lot of things. There are lots of places that build the code and lots of outstanding PRs that will have merge conflicts when we do a massive move.

I actually think it makes sense to put kfctl into its own repository. So I think I lean towards leaving the code where it is now and then eventually moving development into its own repository kubeflow/kfctl.

**Comment by jlewi** [comment]
Do the other changes like removing ksonnet, upgrading kustomize etc..., do these all need to go into one massive PR? 

I think it would really help if we can break these up to individual PRs.

**Comment by jlewi** [comment]
Thanks @kkasravi 

In general, I think its really helpful if we break things down into small, focused PRs. This is less likely to create merge conflicts for other folks working on the code base. It also makes it easier to rollback in the event of a breakage.

Large scale refactorings that touch a lot of files (e.g. moving kfctl) or changing package imports should be handled with care because 1) they are likely to cause merge conflicts and 2) difficult to rollback.

w.r.t to kfctl; I think moving to its own repo makes sense long term but that's more work and I don't think we can do it before 0.6.

If we were going to stick with kfctl in repo kubeflow then I think it might make sense to do the move before 0.6. That would make it easier to cherry-pick fixes on the 0.6 branch. But if we decide to move to its own repo then I think we should just keep it in its own repo.

> It's slightly tricky to remove v2.zip and move bootstrap and kfctl to v2.

What's the connection between the move and removing v2.zip? I thought v2.zip was some hack for go modules because we have two different versions of K8s client that we pull in because of ksonnet. 

Can we remove that hack and always use a single version of our dependencies while still leaving all of our .go files at their current location?

Regardless, I would guess a prerequisite would be a PR just deleting the ksonnet code like
https://github.com/kubeflow/kubeflow/tree/master/bootstrap/pkg/kfapp/ksonnet

Also regarding the kustomize upgrade; should this be split into two PRs

1. Upgrade kustomize dependency to the new version
1. Remove/update any code that was used to work around limitations in the previous versions of kustomize that are now fixed.

**Comment by kkasravi** [comment]
>If we were going to stick with kfctl in repo kubeflow then I think it might make sense to do the move before 0.6. That would make it easier to cherry-pick fixes on the 0.6 branch. But if we decide to move to its own repo then I think we should just keep it in its own repo.

Moving kfctl to kubeflow/kubeflow/kfctl before 0.6 would be a big help. Moving to its own repo after 0.6 would be changing kubeflow/kubeflow/kfctl to kubeflow/kfctl for imports, etc and should be straightforward.

> Can we remove that hack and always use a single version of our dependencies while still leaving all of our .go files at their current location?

we could and that could proceed any move - however bootstrap's ksServer.go is called from '/kfctl/apps/apply'. I don't know if this is still used but in this PR I removed references to ksonnet in bootstrap. @kunmingg should review first. 

but we could then do

1. remove ksonnet app and all ksonnet imports (requires cleanup in ksServer)
2. remove v2.zip - use single version of dependencies
3. move kfctl to kubeflow/kubeflow/kfctl. All refs to kfctl with be kubeflow/kubeflow/kfctl/v2
4. upgrade kustomize to v2.1.0
5. cleanup kustomize workarounds due to limitations in v2.0.3

**Comment by jlewi** [comment]
@kkasravi I was thinking that maybe a good way to proceed would be to start by imports to "github.com/ksonnet/ksonnet/.

Rather than try to update the calling code to work with out ksonnet; I would just replace the code that uses it with a NotImplementedError.

In particular I think 
https://github.com/kubeflow/kubeflow/blob/master/bootstrap/pkg/kfapp/ksonnet/ksonnet.go

Is the main code that is still using ksonnet; so we can just update that module to return errors rather than call ksonnet code.

The advantage of this approach is

1. We can eliminate ksonnet from our dependencies
1. We don't have to update all the caller code in one go
    * e.g. KsServer can be updated in follow on PRs to replace calls to ksonnet with code that will work
      without ksonnet.

**Comment by kkasravi** [comment]
closing this PR since the approach is to break this up into small pieces and have the ksonnet app return [NotImplementedError](https://github.com/kubeflow/kubeflow/pull/3528#issuecomment-511241258)

**Pull request closed without merging**
