### PR TITLE
Cherry pick 3857 to v0.6-branch

### PR DESCRIPTION
**Pull request by yanniszark**
Cherry pick #3857 to v0.6-branch.
The PR #3857 renames the existing_arrikto config file to conform with the other config file names.

cc @kunmingg

/assign @gabrielwen @kkasravi 

---
This change is [Reviewable](https://reviewable.io/reviews/kubeflow/kubeflow/3884)

### CODE REVIEW

**Comment by jlewi** [comment]
Is this going to break people who expect the old file  name on the 0.6-branch?

**Comment by yanniszark** [comment]
> Is this going to break people who expect the old file name on the 0.6-branch?

No, the current website config URIs point to master.
Once this change is in, we will also pass a PR pointing the configs URIs to v0.6-branch.
Relevant Website PR: https://github.com/kubeflow/website/pull/1071

**Comment by yanniszark** [comment]
@gabrielwen @jlewi 
Tests are passing now.
Can you please take a quick look and approve if everything is ok?
It's only a file rename.

**Pull request merged**
