### PR TITLE
disable gpu test

### PR DESCRIPTION
**Pull request by lluunn**
It's failing in presubmit
/cc @ankushagarwal

---
This change is [Reviewable](https://reviewable.io/reviews/kubeflow/kubeflow/547)

### CODE REVIEW

**Comment by lluunn** [comment]
simple-tfjob failed... not sure why.

**Comment by lluunn** [comment]
simple-job is failing consistently in this PR, but passing in other PRs..

**Comment by ankushagarwal** [comment]
My suspicion is that it is related to this commit which was merged yesterday in tf-operator : https://github.com/kubeflow/tf-operator/commit/a7511ff284621e4d88dba2354b048d57965a4011#diff-a21c288bd7c0a85dba041751952f4e29 

The simple-tfjob seems to be stuck in the function `wait_for_pods_to_be_deleted`

The last commit in this repo updated the tf-operator image

**Comment by lluunn** [comment]
just synced

**Pull request merged**
