### PR TITLE
JWA: Fix backend unittests and add GH Action

### PR DESCRIPTION
**Pull request by kimwnasptd**
In this PR I:
1. Fixed the broken unittests we had in the JWA's backend
2. Introduced a GH Action for running these tests

We can also re-use this action for the frontend integration/unit tests as well

cc @orfeas-k

### CODE REVIEW

**Comment by kimwnasptd** [comment]
We'll need to also setup some basic K8s cluster, since to even start the app the K8s client expects a configured kubeconfig

```
======================================================================
ERROR: apps.common (unittest.loader._FailedTest)
----------------------------------------------------------------------
ImportError: Failed to import test module: apps.common
Traceback (most recent call last):
  File "/home/runner/work/kubeflow/kubeflow/components/crud-web-apps/common/backend/kubeflow/kubeflow/crud_backend/api/apis.py", line 5, in <module>
    config.load_incluster_config()
  File "/opt/hostedtoolcache/Python/3.7.[15](https://github.com/kubeflow/kubeflow/actions/runs/3396177321/jobs/5646949898#step:5:16)/x64/lib/python3.7/site-packages/kubernetes/config/incluster_config.py", line 1[21](https://github.com/kubeflow/kubeflow/actions/runs/3396177321/jobs/5646949898#step:5:22), in load_incluster_config
    try_refresh_token=try_refresh_token).load_and_set(client_configuration)
  File "/opt/hostedtoolcache/Python/3.7.15/x64/lib/python3.7/site-packages/kubernetes/config/incluster_config.py", line 54, in load_and_set
    self._load_config()
  File "/opt/hostedtoolcache/Python/3.7.15/x64/lib/python3.7/site-packages/kubernetes/config/incluster_config.py", line 62, in _load_config
    raise ConfigException("Service host/port is not set.")
kubernetes.config.config_exception.ConfigException: Service host/port is not set.
```

I'll use the logic we have for setting up a kind cluster https://github.com/kubeflow/kubeflow/tree/master/components/testing/gh-actions

**Comment by elikatsis** [comment]
@kimwnasptd thanks for extending the automated testing!

I've got one minor comment: Since the GH action runs JWA's unittests which don't trigger any part that concerns its integration with other software, I suggest renaming the YAML you introduced from `jwa_integrations_tests.yaml` to `jwa_backend_unittests.yaml`.

**Comment by kimwnasptd** [comment]
@elikatsis done!

**Comment by elikatsis** [comment]
Thanks!
/lgtm
/approve

**Pull request merged**
