### PR TITLE
Use informer / indexer to cache rolebindings

### PR DESCRIPTION
**Pull request by DavidSpek**
Closes: https://github.com/kubeflow/kubeflow/issues/5190

Recreated from https://github.com/kubeflow/kubeflow/pull/5202 due to inactivity of the contributor. 

/cc @yanniszark

### CODE REVIEW

**Comment by DavidSpek** [comment]
It looks like the access-management Kaniko build will need the same configuration to change the memory limit on the pod as implemented in https://github.com/kubeflow/kubeflow/pull/5627. I will create a PR for this soon.

**Comment by robbertvdg** [comment]
Great work @DavidSpek, I tested it for our +/- 200 users cluster and saw the request times drop from 15s to 200ms. Awesome!

**Comment by DavidSpek** [comment]
@robbertvdg Credits should go to @thetko85 from https://github.com/kubeflow/kubeflow/pull/5202 for this. Thanks for testing it though, that sounds like an amazing improvement. 

@yanniszark We should probably merge this quickly after https://github.com/kubeflow/kubeflow/pull/5697 is merged.

**Comment by yanniszark** [comment]
@DavidSpek thanks for re-opening the PR. Ping me again once the blocking PR is merged.
Looks like it's already under active review.

**Comment by DavidSpek** [comment]
@yanniszark The blocking PR was just merged and the test build for access-management just passed. This PR can be merged whenever you feel it is ready.

**Comment by yanniszark** [comment]
/lgtm
/approve

Thanks @DavidSpek

**Comment by DavidSpek** [comment]
@robbertvdg Thanks for testing this. In case you are interested, the image that was built after merging this PR is `public.ecr.aws/j1r0q0g6/notebooks/access-management:master-6b10fdb1`

**Comment by robbertvdg** [comment]
Awesome, was about to ask! Thanks for the PR.

**Comment by DavidSpek** [comment]
Sadly it wont. After the move to the working groups, Google is no longer providing the testing infrastructure or image registry for the components other than Pipelines. The components in this repository have moved over to the infrastructure provided by AWS, and also the AWS registry. This shift is part of what caused the delay for the 1.3 release. You can find all the components that currently have their images on AWS by going to https://gallery.ecr.aws/?page=1&searchTerm=j1r0q0g6 (the new notebook images might also be interesting to you, if you have questions you can message me on Slack).

**Comment by robbertvdg** [comment]
That is unfortunate, thanks for the explanation, I will check out the other images.

**Pull request merged**
