### PR TITLE
Use controller-gen for PodDefaults

### PR DESCRIPTION
**Pull request by kimwnasptd**
Right now we rely on manual changes to:
* deepcopy files
* the crd

We should instead rely on `controller-gen` for automating this task, just like we do for the rest of the controllers

/cc @discordianfish @alembiewski

### CODE REVIEW

**Comment by kimwnasptd** [comment]
Putting this in WIP state until I've verified the manifests can also be applied when we have the previous ones in a cluster

**Comment by kimwnasptd** [comment]
Verified that:
1. The CRD can be applied in the cluster with the previous CRD present, so no special upgrade instructions are needed
2. The controller handles the deepcopy code as expected [ PodDefaults can be mounted as expected ]

@discordianfish @alembiewski this is ready for review

**Comment by discordianfish** [comment]
Thanks!

/approve

**Comment by kimwnasptd** [comment]
I think it also needs the lgtm label

**Pull request merged**
