### PR TITLE
Add CI/CD for Volumes Web App

### PR DESCRIPTION
**Pull request by DavidSpek**
This PR adds the CI/CD for the Volumes Web App from https://github.com/kubeflow/kubeflow/pull/5684. 

/cc @kimwnasptd

### CODE REVIEW

**Comment by kimwnasptd** [comment]
@DavidSpek I see changes for the Tensorboards web app CI/CD, which I guess are for #5693 right?

**Comment by DavidSpek** [comment]
@kimwnasptd No, just fixing a type I spotted (`testibg`, instead of `testing`) in the `twa_tests.py` file.

**Comment by kimwnasptd** [comment]
Nice! I also run the `_runner.py` scripts and the workflow is as expected. Thanks for the PR @DavidSpek!

/lgtm
/approve

**Pull request merged**
