### PR TITLE
Update image tags in 1.4 release branch

### PR DESCRIPTION
**Pull request by kimwnasptd**
Will use the `v1.4-rc.0` tag for the first RC.

/cc @elikatsis @yanniszark

### CODE REVIEW

**Comment by kimwnasptd** [comment]
@PatrickXYS I see that the E2E tests workflows do not get triggered. Is this because it's on a branch other than `master`? Is there some manual work needed to be done to enable this?

**Comment by PatrickXYS** [comment]
@kimwnasptd  This is expected since we haven't configured v1.4-branch in prow, you can add entry here 
https://github.com/kubeflow/testing/blob/master/aws/User/clusters/optional-test-infra-prow/namespaces/prow/configmap/config.yaml#L136-L138

**Comment by PatrickXYS** [comment]
Prow may need 30second reconciler duration to sync changes, let's wait a bit

**Comment by PatrickXYS** [comment]
Here we go

/test kubeflow-kubeflow-presubmit

**Comment by kimwnasptd** [comment]
Thank you for the very quick support and help on this @PatrickXYS! :rocket:  

We are good to go!
cc @elikatsis

**Pull request merged**
