### PR TITLE
added notebook-controller and jupyter-web-app as part of kf deployment

### PR DESCRIPTION
**Pull request by zabbasi**
This change is [Reviewable](https://reviewable.io/reviews/kubeflow/kubeflow/2764)

### CODE REVIEW

**Comment by zabbasi** [comment]
@kimwnasptd @lluunn can you please check if all required components are added?

**Comment by lluunn** [comment]
/lgtm
/approve
/hold
for @kunmingg

**Comment by kunmingg** [comment]
/lgtm
/hold cancel
Thanks!

**Comment by zabbasi** [comment]
@kunmingg

**Pull request merged**
