### PR TITLE
Add base href for correct link in Argo UI

### PR DESCRIPTION
**Pull request by andreyvelich**
Fixes https://github.com/kubeflow/kubeflow/issues/1694

---
This change is [Reviewable](https://reviewable.io/reviews/kubeflow/kubeflow/1865)

### CODE REVIEW

**Comment by Jeffwan** [comment]
@andreyvelich  just like to confirm this PR will only work behind Ambassador?  If I install argo individually, this will not work.

**Comment by andreyvelich** [comment]
@Jeffwan Yes, that's true. Right now Argo UI only supports work behind Ambassador. 
f you want to use Argo UI individually you have to remove this variable: 
https://github.com/kubeflow/kubeflow/blob/master/kubeflow/argo/argo.libsonnet#L161
and remove this annotation from the service: 
https://github.com/kubeflow/kubeflow/blob/master/kubeflow/argo/argo.libsonnet#L201

**Comment by Jeffwan** [comment]
Cool. Thanks for the confirmation.  @andreyvelich

**Pull request merged**
