### PR TITLE
proposal: Introduce a PVCViewer Controller in Kubeflow

### PR DESCRIPTION
**Pull request by apo-ger**
Provide a design doc as a proposal for introducing a PVCViewer Controller in Kubeflow. PVCViewers enable users to open a web app UI on arbitrary persistent volume claims, letting them inspect, download, upload and manipulate data.

Our proposal is in markdown format and follows the guidelines of the [kubeflow/components/proposal/README.md](https://github.com/kubeflow/kubeflow/blob/master/components/proposals/README.md) guide.

On-going effort: https://github.com/kubeflow/kubeflow/pull/6876

### CODE REVIEW

**Comment by apo-ger** [comment]
cc @kimwnasptd

**Comment by kimwnasptd** [comment]
Thanks @apo-ger! Will take a more detailed look by EOW

/cc @TobiasGoerke

**Comment by TobiasGoerke** [comment]
Thanks, @apo-ger! I'm currently on vacation and only able to read this on my mobile but from what I've read this looks very good to me! My only remark: I'm still unsure about whether a restart functionality makes sense or is required, so we might need to evaluate this in a future iteration.

**Comment by kimwnasptd** [comment]
I think we can go on and merge this PR, considering that we've had a lot of back and forth on this and in the initial gdoc.

Thanks for your efforts on this @apo-ger @TobiasGoerke!

/lgtm
/approve

**Pull request merged**
