### PR TITLE
add willb to approvers

### PR DESCRIPTION
**Pull request by willb**
This change is [Reviewable](https://reviewable.io/reviews/kubeflow/kubeflow/542)

### CODE REVIEW

**Comment by jlewi** [comment]
/lgtm
/approve

GPU tests are failing they will be disabled by #547

**Comment by jlewi** [comment]
Tests should be fixed. But you might need to resync.

**Comment by willb** [comment]
@jlewi this is passing after a rebase -- could you `lgtm` it again when you have a chance?

**Pull request merged**
