### PR TITLE
Add additional APIs to Central Dashboard roles

### PR DESCRIPTION
**Pull request by prodonjs**
Necessary to enable the functionality in #2935 which addresses #2885.

---
This change is [Reviewable](https://reviewable.io/reviews/kubeflow/kubeflow/3097)

### CODE REVIEW

**Comment by avdaredevil** [comment]
@prodonjs I cannot find which PR has the code for this demo, but could you please change the CSS for `.link` to now only have a padding of `.25em` instead of the `.5em 1em` value it currently has, as the boxes look very bloated.

Before | After
--- | ---
image | image

**Comment by prodonjs** [comment]
/unassign @abhi-g 
/assign @jlewi 

Jeremy - can you approve this? This change enables GCE project-specific links to show up from the KF landing page.

**Comment by prodonjs** [comment]
@avdaredevil I'll make that correction in a subsequent PR and assign for your approval.

**Comment by jlewi** [comment]
This is great.

Feel free to create an OWNERs file and make yourselves approvers.

Also just an FYI we'll need to make the corresponding change in the kustomize file.
https://github.com/kubeflow/manifests/tree/master/common/centraldashboard/base

/lgtm
/approve

**Comment by prodonjs** [comment]
@avdaredevil I think this should be ready for your final review / approval.

**Pull request merged**
