### PR TITLE
Start instructions for creating a release

### PR DESCRIPTION
**Pull request by jlewi**
* Start putting instructions together for how one could release Kubeflow.
* The instructions are rather adhoc and reflect what one could do today
* They do not reflect what we think our release process should look like.
* The current instructions only cover building and releasing TFJob operator and the TFServing images

* Refactor the TFServing image E2E workflow so we can use it to build release images
    * We want to run a different cluster in a different project for releases and publish to a different GCR
       registry
    * We move the default parameters into the .libsonnet file; The number of parameters was getting
       large so I think it makes sense to pass them as a dictionary and not as a list of arguments
    * Make buildTemplate a local variable so we automatically inherit the values of the parameters
      and don't have to pass a bunch of arguments every time we build it.

* Update the actual image used by TFSerivng to the newly built image.

* @willb and some others are putting together a proposal for our release process. Hopefully this PR will help inform that work and help us figure out how to iterate.

* Related to #215 

---
This change is [Reviewable](https://reviewable.io/reviews/kubeflow/kubeflow/298)

### CODE REVIEW

**Comment by jlewi** [comment]
The workflow for building the TF serving image didn't even seem to run the checkout step.

Lets try rerunning.

/test all

**Comment by jlewi** [comment]
I did

```
kubectl describe wf $WFNAME
```

Error is 

```
Status:
  Finished At:  2018-02-28T13:58:22Z
  Message:      invalid spec: template 'e2e' steps[1].create-pr-symlink.template 'create-pr-symlink' undefined
  Phase:        Failed
  Started At:   2018-02-28T13:58:22Z
```
Looks like maybe a bad merge.

**Comment by lluunn** [comment]
Review status: 0 of 10 files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[releasing.md, line 24 at r4](https://reviewable.io:443/reviews/kubeflow/kubeflow/298#-L6TrYL_Pc3iq6sTyEPm:-L6TrYL_Pc3iq6sTyEPn:b-gsbwju) ([raw file](https://github.com/kubeflow/kubeflow/blob/037df12363c0c84a97557585e0744b6dd8e1ef4e/releasing.md#L24)):*
> ```Markdown
> [kubeflow/testing#42](https://github.com/kubeflow/testing/issues/42) will simplify this.
> 
> ```
> ```

should cd to the workflow dir?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/kubeflow/kubeflow/298)*

**Comment by jlewi** [comment]
Review status: 0 of 10 files reviewed at latest revision, 1 unresolved discussion.

---

*[releasing.md, line 24 at r4](https://reviewable.io:443/reviews/kubeflow/kubeflow/298#-L6TrYL_Pc3iq6sTyEPm:-L6TxIG09ngzX55z7ltG:b-896fix) ([raw file](https://github.com/kubeflow/kubeflow/blob/037df12363c0c84a97557585e0744b6dd8e1ef4e/releasing.md#L24)):*
<details><summary><i>Previously, lluunn (Lun-Kai Hsu) wrote…</i></summary><blockquote>

should cd to the workflow dir?
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/kubeflow/kubeflow/298)*

**Pull request merged**
