### PR TITLE
Upgrade tf-serving version to 1.6.0

### PR DESCRIPTION
**Pull request by pdmack**
General bump of TF deps. For my part, I'm specifically trying to get at the s3 support that came out with 1.5.0.

/cc @jlewi 
/cc @elsonrodriguez

---
This change is [Reviewable](https://reviewable.io/reviews/kubeflow/kubeflow/608)

### CODE REVIEW

**Comment by lluunn** [comment]
We pinned 1.4  in #512 because of https://github.com/tensorflow/serving/issues/819 

Have you verified the image works? Our current testing currently doesn't rebuild the image.

**Comment by elsonrodriguez** [comment]
Pinning to 1.5 might be a nice workaround, gets you S3 without that bug.

**Comment by pdmack** [comment]
@elsonrodriguez @lluunn yep. Got 1.6.0 CPU working but GPU has LD-related issues with CUDA. Will work on it a bit more but may just aim for 1.5.0 if progress isn't happening.

**Comment by pdmack** [comment]
@lluunn @elsonrodriguez PTAL

```
# docker run --rm 1.6.0-tf-serving-test-cpu:mine /usr/bin/tensorflow_model_server --help | head -3
usage: /usr/bin/tensorflow_model_server
Flags:
	--port=8500                      	int32	port to listen on
# docker run --rm 1.6.0-tf-serving-test-gpu:mine /usr/bin/tensorflow_model_server --help | head -3
usage: /usr/bin/tensorflow_model_server
Flags:
	--port=8500                      	int32	port to listen on
```

@DjangoPeng, do these [flags](https://github.com/pdmack/kubeflow/blob/7c3ec41acdd7d697d141ecd9e1e26cb2a6a7dcb3/components/k8s-model-server/images/Dockerfile.gpu#L45) still look appropriate for 1.6.0? I enabled s3 flag.

**Comment by jlewi** [comment]
FYI Per #468 we'd eventually like to produce multiple TF Serving images corresponding to different TF versions.

**Comment by jlewi** [comment]
I think its fine to bump things to the latest version as a quick fix; as long as we don't overwrite the existing images people who need the older image tag can use that.

If we follow the approach we are taking for Jupyter notebooks, then we should be able to build multiple versions of TF Serving from master (i.e. not needing separate branches).

We could do this by having separate requirements.txt files and either separate Dockerfiles or parameterized Dockerfiles. Then in our Argo workflow we can just configure the build step as needed.

**Comment by pdmack** [comment]
Do people strongly feel we need a proper progression through 1.4.1 and 1.5.0 before this change? Otherwise, I agree with @jlewi that we put it in and work out the general refactoring in the backlog.

**Pull request merged**
