### PR TITLE
delete kubeflow/kubeflow/py

### PR DESCRIPTION
**Pull request by gabrielwen**
Related: kubeflow/kfctl#77

We've migrated codes to the kfctl repo, deleting the codes here and make kfctl repo source of truth.

---
This change is [Reviewable](https://reviewable.io/reviews/kubeflow/kubeflow/4577)

### CODE REVIEW

**Comment by jlewi** [comment]
@gabrielwen I think you were a little zealous.

It doesn't look like the following scripts migrated to kubeflow/kfctl so should we keep them around
* rebuild_manifests.sh
* application_util.py
* update_jupyter_web_app.py
* test_data (used by application_util_test.py)

**Comment by jlewi** [comment]
I think only the files named "kfctl_*" need to be deleted?

**Comment by gabrielwen** [comment]
@jlewi updated.  yea on second thought you are right.

**Pull request merged**
