### PR TITLE
Proposed notebooks refactor

### PR DESCRIPTION
**Pull request by DavidSpek**
Closes: https://github.com/kubeflow/kubeflow/issues/5575

In this PR I've applied the changes I proposed in the above issue. I have removed the old releaser, a startup script that was not used, outdated README info, the image building script as a new solution will need to be made, and, most importantly, the version folders which haven't been updated in a year and contain only versions with many security vulnerabilities. 

Remarks:

- While I am aware that duplication of code is not best practice, and having many essentially duplicate Dockerfiles seems like something to avoid, the reasoning behind this decision is that this allows Renovate (or other dependency management bots) to automatically create PRs for updating the images. It might be possible to avoid the need for this duplication with an advanced Renovate configuration, but before that is looked into this is the easiest solution. 
- All pip dependencies are listed in the `requirements.txt` file, again this allows Renovate (or other dependency management bots) to automatically create PRs for updating the dependencies. The versions are not pinned at the moment, but Renovate should create a PR to pin them. 
- Due to the expansion of the image selection with PyTorch, R-Studio and Code Server (VS-Code), it seemed like a good idea to have a more general `notebook-images` folder (while maybe not the best name anymore). 
- In the new `notebook-images` folder, a folder for `third-party` images is created, where I placed the `contrib` folder that contains some community examples I believe. Also, it contains a folder for AWS images which is something that was previously discussed. If this third-party folder moves forward, it might be worth considering removing or reducing the GCP, AWS and Azure specific packges from the default images. 

Update:
New images have been created according to what was discussed in the Notebooks Working Group meeting of 04-02-2021. A base image was created starting from`buster-slim`, on top of which PyTorch and TensorFlow images have been made. 
A couple notes:
- Python is installed through conda, but other packages are installed with pip. Thus users can use both pip and conda for packages. This choice was made as pip resulted in a smaller image. 
- PyTorch is installed with pip rather than conda, as the pip image was 3 GB smaller than the conda image, and that was even before I added the `--no-cache-dir` to the pip command. 

| Image      | Size | File | Packages | Dockerhub |
| ----------- | ----------- | ----------- | ----------- | ----------- |
| webide-base | 381 MB | [link](https://github.com/kubeflow/kubeflow/pull/5582/files#diff-8f96b5653ae574488a22135cc94a0a8d803bc07ec66a30f15185a042ee22a6f9) | <details><summary>APT</summary><br>nodejs, yarn</details> | `davidspek/kubeflow-ubuntu-webide-base:0.2` |
| jupyter-base | 1.19 GB | [link](https://github.com/kubeflow/kubeflow/pull/5582/files#diff-82960a78f358fd43487a5524b7c75606cc56ee067dd59d6b38fedaf445cdef9d) | <details><summary>APT</summary><br>bash, bzip2, ca-certificates, curl, git, gnupg, locales, lsb-release, software-properties-common, sudo, tzdata, unzip, vim, wget, zip, kubectl</details> <details><summary>Other</summary><br>Miniforge3, conda 4.9.2, Tini v0.19.0</details> <details><summary>Conda</summary><br>Python 3.8.6, pip</details> <details><summary>Pip</summary><br>notebook 6.2.0, jupyterlab 3.0.5, ruamel_yaml 0.16.12, kubeflow-fairing 1.0.2, kfserving 0.4.1, kfp 1.0.4, kfp-server-api 1.0.4, [link to requirements.txt](https://github.com/kubeflow/kubeflow/pull/5582/files#diff-10c56992d5a84d2d7883e4108e97d1280ffdf373f9d8436548df30fc90a8b299)</details> | `davidspek/kubeflow-ubuntu-jupyter-base:0.5` |
| pytorch-base | 1.8 GB | [link](https://github.com/kubeflow/kubeflow/pull/5582/files#diff-b07cd3fc15bed0545b85e2e35498d5a23b5c1479f20e2477e90dde4f443075a4) | <details><summary>Pip</summary><br>torch 1.7.1+cpu, torchvision 0.8.2+cpu, torchaudio 0.7.2, [link to requirements.txt](https://github.com/kubeflow/kubeflow/pull/5582/files#diff-c5a673fe88dc6e99d7725b76adb9407fe5ff2b3266de70b1ee03c7402406533f)</details> | `davidspek/kubeflow-ubuntu-pytorch-base:0.1` |
| pytorch-full | 2.95 GB | [link](https://github.com/kubeflow/kubeflow/pull/5582/files#diff-d85ea562d87f664abcf3bc283bfc883547d76d99a64fb7f65da900e05061421a) | <details><summary>Pip</summary><br>ipywidgets 7.6.3, ipympl 0.6.3, cloudpickle 1.6.0, dill 0.3.3, bokeh 2.2.3, seaborn 0.11.1, scipy 1.6.0, scikit-learn 0.24.1, scikit-image 0.18.1, pandas 1.2.1, matplotlib 3.3.4, xgboost 1.3.3, torchelastic 0.2.1, fastai 2.2.5, [link to requirements.txt](https://github.com/kubeflow/kubeflow/pull/5582/files#diff-b51be28fbb7207947e6515c0338b540039368f04289634846b0c61107c8a85df)</details> | `davidspek/kubeflow-ubuntu-pytorch-full:0.1` |
| pytorch-base-cuda | 4.11 GB | [link](https://github.com/kubeflow/kubeflow/pull/5582/files#diff-ed925f33be88520d070cbaede04b35174f6bd448b4ff7764981dcb93982c843a) | <details><summary>Pip</summary><br>torch 1.7.1+cu110, torchvision 0.8.2+cu110, torchaudio 0.7.2, [link to requirements.txt](https://github.com/kubeflow/kubeflow/pull/5582/files#diff-17c1aa6cae338eb7a8600eeae7cc954969238e3d3d562b951e727ac766b76875)</details> | `davidspek/kubeflow-ubuntu-pytorch-base:0.1-cuda` |
| pytorch-full-cuda | 5.26 GB | [link](https://github.com/kubeflow/kubeflow/pull/5582/files#diff-217120383857d5b03ea6c0f2040c6c241ea12f134f33938ac3e3d9f44d8a9b50) | <details><summary>Pip</summary><br>ipywidgets 7.6.3, ipympl 0.6.3, cloudpickle 1.6.0, dill 0.3.3, bokeh 2.2.3, seaborn 0.11.1, scipy 1.6.0, scikit-learn 0.24.1, scikit-image 0.18.1, pandas 1.2.1, matplotlib 3.3.4, xgboost 1.3.3, torchelastic 0.2.1, fastai 2.2.5, [link to requirements.txt](https://github.com/kubeflow/kubeflow/pull/5582/files#diff-b51be28fbb7207947e6515c0338b540039368f04289634846b0c61107c8a85df)</details> | `davidspek/kubeflow-ubuntu-pytorch-full:0.1-cuda` |
| tensorflow-base | 2.25 GB | [link](https://github.com/kubeflow/kubeflow/pull/5582/files#diff-0e672f36b9b9806b922392df0e59c051b052f0568b29b536e869a90f2ccc23ac) | <details><summary>Pip</summary><br>tensorflow 2.4.1, [link to requirements.txt](https://github.com/kubeflow/kubeflow/pull/5582/files#diff-f14b7af9474f4da6f287d29890536e08d1d71b2cd7bc8f18e62ca3b82e993ab6)</details> | `davidspek/kubeflow-ubuntu-tensorflow-base:0.1` |
| tensorflow-full | 3.21 GB | [link](https://github.com/kubeflow/kubeflow/pull/5582/files#diff-50ecae543d3010ab316c167941774c42baa6ffb91b200f1ba9c5caf587b837df) | <details><summary>Pip</summary><br>ipywidgets 7.6.3, ipympl 0.6.3, cloudpickle 1.6.0, dill 0.3.3, bokeh 2.2.3, seaborn 0.11.1, scipy 1.6.0, scikit-learn 0.24.1, scikit-image 0.18.1, pandas 1.2.1, matplotlib 3.3.4, xgboost 1.3.3, keras 2.4.3, [link to requirements.txt](https://github.com/kubeflow/kubeflow/pull/5582/files#diff-fa890d2ac2a231cf907764a75e1585df3b58ba7969c84c8f9df61eff8c9fe25a)</details> | `davidspek/kubeflow-ubuntu-tensorflow-full:0.1` |
| tensorflow-base-cuda | 7.83 GB | [link](https://github.com/kubeflow/kubeflow/pull/5582/files#diff-8655f4e7927913ffc8e4b49474b529fd3c4a5eb1d9e4b8932ef20eb29077231f) | <details><summary>APT</summary><br>cuda-cudart-11-1, cuda-compat-11-1, libcublas--11.1, cuda-nvrtc-11.1, libcufft-11.1, libcurand-11.1, libcusolver-11.1, libcusparse-11.1, libcudnn8 8.0.5.39-1+cuda11.1, libfreetype6-dev, libhdf5-serial-dev, libzmq3-dev,  pkg-config, cm-super, libnvinfer7 7.2.2-1+cuda11.1, libnvinfer-plugin7 7.2.2-1+cuda11.1</details> <details><summary>Pip</summary><br>tensorflow-gpu 2.4.1, [link to requirements.txt](https://github.com/kubeflow/kubeflow/pull/5582/files#diff-107096ddeb27aed13da3f404d15415641f872dc3e098de28e69a5e245a0800ff)</details> | `davidspek/kubeflow-ubuntu-tensorflow-base:0.1-cuda` |
| tensorflow-full-cuda | 8.78 GB | [link](https://github.com/kubeflow/kubeflow/pull/5582/files#diff-db67efdfb64d91ba730f781de3e1a2ca1f5dbb0b90c8bf5c1047c99e89a77173) | <details><summary>Pip</summary><br>ipywidgets 7.6.3, ipympl 0.6.3, cloudpickle 1.6.0, dill 0.3.3, bokeh 2.2.3, seaborn 0.11.1, scipy 1.6.0, scikit-learn 0.24.1, scikit-image 0.18.1, pandas 1.2.1, matplotlib 3.3.4, xgboost 1.3.3, keras 2.4.3, [link to requirements.txt](https://github.com/kubeflow/kubeflow/pull/5582/files#diff-fa890d2ac2a231cf907764a75e1585df3b58ba7969c84c8f9df61eff8c9fe25a)</details> | `davidspek/kubeflow-ubuntu-tensorflow-full:0.1-cuda` |
| datascience-base | 3 GB | [link](https://github.com/kubeflow/kubeflow/pull/5582/files#diff-a8613072422b4a075d741f30d57ab1b4968817b429e44920b950b5f388ceb294) | <details><summary>Other</summary><br>Julia 1.5.3</details> <details><summary>Conda</summary><br>r-irkernel 1.1*, r-base 4.0.3</details> | `davidspek/kubeflow-ubuntu-datascience-base:0.2` |
| datascience-full | 5.47 GB | [link](https://github.com/kubeflow/kubeflow/pull/5582/files#diff-e15dcb321c155a0bf68034bb170f2f10eb3fa3a4295ce174647d8b25199f4469) | <details><summary>Pip</summary><br>ipywidgets 7.6.3, ipympl 0.6.3, cloudpickle 1.6.0, dill 0.3.3, bokeh 2.2.3, seaborn 0.11.1, scipy 1.6.0, scikit-learn 0.24.1, scikit-image 0.18.1, pandas 1.2.1, matplotlib 3.3.43, [link to requirements.txt](https://github.com/kubeflow/kubeflow/pull/5582/files#diff-78a3e3e0aef71625b8f61f235c6c517d24ceb35963c04d9b0943ad8cbf103f6d)</details> <details><summary>Conda</summary><br>r-caret 6.0*, r-crayon 1.3*, r-devtools 2.3*, r-forecast 8.13*, r-hexbin 1.28*, r-htmltools 0.5*, r-htmlwidgets 1.5*, r-nycflights13 1.0*, r-randomforest 4.6*, r-rcurl 1.98*, r-rmarkdown 2.6*, r-rsqlite 2.2*, r-shiny 1.5*, r-tidyverse 1.3*, rpy2 3.4*</details> | `davidspek/kubeflow-ubuntu-datascience-full:0.3` |
| spark-base | 1.94 GB | [link](https://github.com/kubeflow/kubeflow/pull/5582/files#diff-b096131a86d9c4531827e4a1ea9814162385a1d6798719c4006458e75aefe451) | <details><summary>APT</summary><br>openjdk-11-jre-headless</details> <details><summary>Other</summary><br>spark-3.0.1-bin-hadoop3.2</details> <details><summary>Pip</summary><br>pyspark 3.0.1, pyarrow 3.0.0, [link to requirements.txt](https://github.com/kubeflow/kubeflow/pull/5582/files#diff-c41d7e2996079191899071b52ed25edf32b287fdbc975b407b381376ef1c5988)</details> | `davidspek/kubeflow-ubuntu-spark-base:0.2` |
| code-server-experimental | 1.08 GB | [link](https://github.com/kubeflow/kubeflow/pull/5582/files#diff-3d57bacc28687dfec7d7d8d6d799473f4dbd5263862e836fac3c31141c9b7db6) | <details><summary>APT</summary><br>jq, nano, net-tools, nodejs, yarn, python3-pip, apache2</details> <details><summary>Other</summary><br>[code-server latest](https://github.com/cdr/code-server/releases), [s6 overlay v2.2.0.1](https://github.com/just-containers/s6-overlay/releases/tag/v2.2.0.1)</details> <details><summary>Pip</summary><br>kfp 1.3.0, kfp-server-api 1.3.0, kubeflow-fairing 1.0.2, kfserving 0.4.1, [link to requirements.txt](https://github.com/kubeflow/kubeflow/pull/5582/files#diff-66b3ebdaf6a3b3a5c21c8af5ec45c3cb83ca87efd46d0856739ffc4aecfad181)</details> <details><summary>Extensions</summary><br>None yet</details> | `davidspek/kubeflow-ubuntu-code-server-experimental:0.4` |
| r-studio-experimental | 1.97 GB | [link](https://github.com/kubeflow/kubeflow/pull/5582/files#diff-feed8d8a63395f07f5b393b4657be3d0204e366dae031dda433ac903558fb404) | <details><summary>APT</summary><br>less, libopenblas-base, dirmngr, gpg, gpg-agent, r-base-dev 4.0.3, file, libapparmor1, libgc1c2, libclang-dev, libcurl4-openssl-dev, libedit2, libobjc4, libssl-dev, libpq5, psmisc, procps, python-setuptools, apache2</details> <details><summary>Other</summary><br>R-Studio 1.4.1103, [s6 overlay v2.2.0.1](https://github.com/just-containers/s6-overlay/releases/tag/v2.2.0.1)</details> <details><summary>RSPM</summary><br>littler, docopt</details> | `davidspek/kubeflow-ubuntu-rstudio-experimental:0.17` |

If there are people that want to test the images (especially the GPU ones), feedback is very welcome. Furthermore, what packages are installed can further be discussed. 

Update 2:
Due to the popularity of the datascience-notebook from the official jupyter-stacks (which contains python, Julia and R) I have added an almost identical image for Kubeflow (it has a few less python packages). The Dockerfile is mostly copied from the official Jupyter Dockerfile, as I first wanted to test if the kernels actually ran when using the common buster-slim base image. 

Update 3:
I have changed the base image from `buster-slim` to `ubuntu:20.04` as this solves a few issues and the ubuntu image is only 3.7 MB larger than `buster-slim`. I have also reworked the images to have a common base image, along with base images for pytorch, tensorflow and datascience which do not contain any additional packages and are meant for people to use as a base image when creating custom images. The `-full` versions of the images contain several often used packages such as `pandas`, `scipy` and others. I will update the information above in a moment, but here is an initial flow-chart of how the images are setup. Code-server (VS-Code) has been added to this PR and uses the common WebIDE-base image. Note: tensorflow GPU has been fixed, but it could probably still use some optimization. 

Overview of the images in this PR, along with packages and sizes. 
images-reworkv6

### CODE REVIEW

**Comment by blairdrummond** [comment]
CC @ca-scribner

**Review by PatrickXYS — COMMENTED** [review]
A few comments here

1. I think it should be better to not mix conda and pip. We should bind to one single solution let's say pip, if user prefer conda, they can install it by themselves, vice versa. 
2. Have you tested those images on your kubeflow notebook server, both CPU and GPU? Any issue have you found so far?
3. I'm a bit concerning about making `NBUser` as `sudo`, thus, it will make deleting important files in volume possible for each of users
4. I'd suggest not use personal dockerhub as base image (e.g, davidspek/kubeflow-buster-base:0.14-pip), we should use official one instead. If that's not feasible in one PR, let's move this part into following PR.

**Comment by DavidSpek** [comment]
@PatrickXYS 

1. The reason for the mixture is because many data scientists use conda, however, pip produces much smaller images and is easier for automated version control. I don't think there is a negative effect by using conda installed python but pip installed packages. If there is, I'm interested in learning. 
2. I have not yet tested the GPU images, CPU images I have tested very minimally (import pytorch/tensorflow, check terminal and conda, execute simple commands in notebooks). 
3. I'm also not sure if giving the user `sudo` privileges is a good move. Luckily it is an easy thing to remove, for the dev work on the images it does make life a little easier. 
4. I agree that my dockerhub should not be used as a base image. This will be changed once we have a naming scheme setup and start building the images, the personal dockerhub link is just for the current development as I believe numerous things will still change from the received feedback.

**Comment by DavidSpek** [comment]
For those wondering how popular the datascience image is, here are some stats from the official Jupyter docker-stacks:
image

**Comment by PatrickXYS** [comment]
> @PatrickXYS
> 
> 1. The reason for the mixture is because many data scientists use conda, however, pip produces much smaller images and is easier for automated version control. I don't think there is a negative effect by using conda installed python but pip installed packages. If there is, I'm interested in learning.
> 2. I have not yet tested the GPU images, CPU images I have tested very minimally (import pytorch/tensorflow, check terminal and conda, execute simple commands in notebooks).
> 3. I'm also not sure if giving the user `sudo` privileges is a good move. Luckily it is an easy thing to remove, for the dev work on the images it does make life a little easier.
> 4. I agree that my dockerhub should not be used as a base image. This will be changed once we have a naming scheme setup and start building the images, the personal dockerhub link is just for the current development as I believe numerous things will still change from the received feedback.

Thanks @DavidSpek 

1. I'm not against data scientists use conda for package management. But from the perspective of a base-image, if we already have one package management tool (pip OR conda), then it may be non-necessary to have another one. 

> I agree that my dockerhub should not be used as a base image. This will be changed once we have a naming scheme setup and start building the images, the personal dockerhub link is just for the current development as I believe numerous things will still change from the received feedback.

2. Then let's not do big refactoring in one single PR, we can make the change smoother by dividing into several following PR but to keep process comply to normal routine. E.g, you don't need to go back-and-forth to change your dockerhub image.

**Comment by DavidSpek** [comment]
@PatrickXYS 
For the datascience notebook that I pushed in the last commit, conda is needed for isntalling R and it's packages. I think it adds a layer of flexibility that can be handy for people. 

I'm not expecting to actually merge this PR, but split it up into a few pieces. With this PR, I want to discuss the Dockerfiles and proposed restructuring of the folders. When the workflows for creating images are in place and we know what the naming and tagging scheme of the images will be, I will split up the PR. 

Also, I am just now in the process of testing the PyTorch GPU image, model loaded to the GPU properly but I still need to test training on the GPU. After this I will do the same for the TensorFlow image.

**Comment by DavidSpek** [comment]
I just tried training Cifar10 on the PyTorch GPU image and it seems to be working as expected.

**Comment by DavidSpek** [comment]
The TensorFlow GPU image is not finding my GPU. I'll need to further investigate if this is a comparability thing with the new RTX 3000 series GPUs, or if something in the image is not working properly.

**Comment by DavidSpek** [comment]
For those wondering what the difference is between the tensorflow-base-cuda and the official `tensorflow/tensorflow:2.4.1-gpu-jupyter` GPU image, here is a diff created using `container-diff`. For example, `libcudnn8` version `8.0.5.39-1 cuda11.1` is 2 GB while `8.0.4.30-1 cuda11.0` in the official image is 1.5 GB. 
[tensorflow-base_tensorflow-dockerhub_diff.txt](https://github.com/kubeflow/kubeflow/files/5946424/tensorflow-base_tensorflow-dockerhub_diff.txt)

**Comment by DavidSpek** [comment]
Ping for those following this PR as I have updated the original post with a table showing the image name, it's size, a link to the Dockerfile, the packages that are installed for the various package managers and a link to the image on Dockerhub for testing purposes for all the latest images.

**Comment by DavidSpek** [comment]
I have added an experimental R-Studio image that uses the new webide-base image as a base, rather than the Rocker image that is used in https://github.com/kubeflow/kubeflow/pull/5570. The table and flowchart have been updated with the new R-Studio image.

**Comment by juliusvonkohout** [comment]
@davidspek did you make sure that all of those images run as non-root? If possible with an arbitrary user ?

**Comment by DavidSpek** [comment]
@juliusvonkohout Does this section answer your question?
https://github.com/kubeflow/kubeflow/pull/5694/files#diff-653fc34c1739e3016f7862a72acb34b43170bbaed9177528747b81878fa0e5c1R32

**Pull request closed without merging**
