### PR TITLE
Don't mutate the go installation during build.

### PR DESCRIPTION
**Pull request by holdenk**
This isn't an issue in CI since it runs as root.

---
This change is [Reviewable](https://reviewable.io/reviews/kubeflow/kubeflow/3385)

### CODE REVIEW

**Comment by gabrielwen** [comment]
most likely due to #3387

**Comment by gabrielwen** [comment]
#3387 is fixed, please merge with master to pick the fix up.

**Comment by holdenk** [comment]
So I don't believe this is related to https://github.com/kubeflow/kubeflow/issues/3387 , this is the go build not the notebooks.
So as it says in the issue ( https://github.com/kubeflow/kubeflow/issues/3383 ):
We can just build with ```all=-N``` appears to try and rebuild go core libraries without optimizations resulting in permission denied errors when not running as root.

> make build-kfctl
> go build -i -gcflags 'all=-N -l' -ldflags "-X main.VERSION=v0-164-g390a3381" -o bin/kfctl cmd/kfctl/main.go
> go build errors: open /usr/local/go/pkg/linux_amd64/errors.a: permission denied
> go build runtime/internal/atomic: open /usr/local/go/pkg/linux_amd64/runtime/internal/atomic.a: permission denied
> go build internal/cpu: open /usr/local/go/pkg/linux_amd64/internal/cpu.a: permission denied
> go build math/bits: open /usr/local/go/pkg/linux_amd64/math/bits.a: permission denied
> go build runtime/internal/sys: open /usr/local/go/pkg/linux_amd64/runtime/internal/sys.a: permission denied
> go build internal/race: open /usr/local/go/pkg/linux_amd64/internal/race.a: permission denied
> go build unicode/utf8: open /usr/local/go/pkg/linux_amd64/unicode/utf8.a: permission denied
> go build sync/atomic: open /usr/local/go/pkg/linux_amd64/sync/atomic.a: permission denied
> go build encoding: open /usr/local/go/pkg/linux_amd64/encoding.a: permission denied
> go build unicode/utf16: open /usr/local/go/pkg/linux_amd64/unicode/utf16.a: permission denied
> go build container/list: open /usr/local/go/pkg/linux_amd64/container/list.a: permission denied
> go build unicode: open /usr/local/go/pkg/linux_amd64/unicode.a: permission denied
> go build crypto/internal/subtle: open /usr/local/go/pkg/linux_amd64/crypto/internal/subtle.a: permission denied
> go build internal/x/crypto/cryptobyte/asn1: open /usr/local/go/pkg/linux_amd64/internal/x/crypto/cryptobyte/asn1.a: permission denied
> go build crypto/subtle: open /usr/local/go/pkg/linux_amd64/crypto/subtle.a: permission denied
> go build internal/nettrace: open /usr/local/go/pkg/linux_amd64/internal/nettrace.a: permission denied
> go build runtime/cgo: open /usr/local/go/pkg/linux_amd64/runtime/cgo.a: permission denied
> go build internal/x/crypto/curve25519: open /usr/local/go/pkg/linux_amd64/internal/x/crypto/curve25519.a: permission denied
> make: *** [Makefile:91: build-kfctl] Error 1
> 

Instead we can try building with ```-N``` instead of ```all=-N```.

> make build-kfctl && echo $?
> go build -i -gcflags '-N -l' -ldflags "-X main.VERSION=v0-164-g390a3381" -o bin/kfctl cmd/kfctl/main.go
> 0
>

**Comment by holdenk** [comment]
It seems like, from https://github.com/golang/go/issues/21837 , we could also try not using `-i`, would that be better @kkasravi ?

**Comment by holdenk** [comment]
Ping @kkasravi ?

**Comment by kkasravi** [comment]
GoLand always seems to add the -i

**Comment by yanniszark** [comment]
I also had the same problem in Ubuntu.
I was using a Golang Snap installation and building with `-i` caused it to try to rhttps://tip.golang.org/doc/go1.10#buildebuild core golang libraries, which failed with `Read Only Filesystem` (because it was a Snap).

Removing the `-i` fixes the issue and doesn't seem to incur much of a performance penalty.
Also, from the [Go 1.10 release notes](https://tip.golang.org/doc/go1.10#build):

>The go build command now maintains a cache of recently built packages, separate from the installed packages in $GOROOT/pkg or $GOPATH/pkg. The effect of the cache should be to speed builds that do not explicitly install packages or when switching between different copies of source code (for example, when changing back and forth between different branches in a version control system). The old advice to add the -i flag for speed, as in go build -i or go test -i, is no longer necessary: builds run just as fast without -i. For more details, see go help cache. 


> GoLand always seems to add the -i flag

Maybe it's a relic from old best practices, as explained in the excerpt from the Go 1.10 release docs.

**Comment by holdenk** [comment]
/retest
Awesome!

**Comment by yanniszark** [comment]
@holdenk can you please rebase and force push to trigger the tests again?
I'd love to get this into master!

**Comment by holdenk** [comment]
Sure let me do that today.

**Comment by holdenk** [comment]
I've rebased it @yanniszark  can you give it LGTM again?

**Comment by holdenk** [comment]
cc @kkasravi

**Comment by yanniszark** [comment]
@holdenk thanks a lot :smile: 

/lgtm
/approve

**Comment by holdenk** [comment]
I’m confused because when I click on the detail link it says 50/50 test pass. If that’s correct can we push the merge @yanniszark

**Comment by holdenk** [comment]
It's still showing 50/50 pass. Can we merge this? Or is there a secret failure that isn't showing up? cc @jlewi ?

**Pull request merged**
