### PR TITLE
Fix setup/teardown of VM for minikube.

### PR DESCRIPTION
**Pull request by jlewi**
* deploy step should wait for VM to be created and report any errors
if the VM can't be created; e.g. because of insufficient quota.

* teardown step should ensure the VM's disk is deleted so that we don't
  leak disks.

* Fix a bug in wait for VM; there is no op_id since we are trying to
ssh into the VM and not executing a GCE operation.

Related to #618

---
This change is [Reviewable](https://reviewable.io/reviews/kubeflow/kubeflow/620)

### CODE REVIEW

**Comment by pdmack** [comment]
:-) No way for me to test this so...
/approve
/lgtm

**Comment by jlewi** [comment]
@pdmack The code is tested by the presubmit which runs the minikube E2E test. Could you re "LGTM" since there were changes due to resolving the merge conflict.

**Comment by jlewi** [comment]
Manually merged since CLA check will never pass.

**Pull request merged**
