### PR TITLE
update default image for TF serving

### PR DESCRIPTION
**Pull request by lluunn**
/cc @ankushagarwal

---
This change is [Reviewable](https://reviewable.io/reviews/kubeflow/kubeflow/940)

### CODE REVIEW

**Comment by lluunn** [comment]
The gpu 1.7 image might have some problem..

**Comment by lluunn** [comment]
```
2018-06-15 00:00:58.472487: I external/org_tensorflow/tensorflow/contrib/session_bundle/bundle_shim.cc:360] Attempting to load native SavedModelBundle in bundle-shim from: gs://kubeflow-models/inception/1
2018-06-15 00:00:58.513090: I external/org_tensorflow/tensorflow/cc/saved_model/loader.cc:242] Loading SavedModel with tags: { serve }; from: gs://kubeflow-models/inception/1
2018-06-15 00:00:58.577468: I external/org_tensorflow/tensorflow/core/common_runtime/gpu/gpu_device.cc:1423] Adding visible gpu devices: 0
2018-06-15 00:00:58.577542: E external/org_tensorflow/tensorflow/core/common_runtime/direct_session.cc:167] Internal: cudaGetDevice() failed. Status: CUDA driver version is insufficient for CUDA runtime version
2018-06-15 00:00:58.587926: I external/org_tensorflow/tensorflow/cc/saved_model/loader.cc:291] SavedModel load for tags { serve }; Status: fail. Took 115356 microseconds.
2018-06-15 00:00:58.587999: E tensorflow_serving/util/retrier.cc:38] Loading servable: {name: inception-gpu version: 1} failed: Internal: Failed to create session.
```

CUDA driver version is insufficient for CUDA runtime version

**Comment by lluunn** [comment]
1.7 is cuda9.1 and cudnn7: https://github.com/kubeflow/kubeflow/blob/master/components/k8s-model-server/images/versions/1.7gpu/version-config.json

1.6 is cuda 8.0 and cudnn 6: https://github.com/kubeflow/kubeflow/blob/master/components/k8s-model-server/images/versions/1.6gpu/version-config.json

So that should be the difference(?)

**Comment by ankushagarwal** [comment]
FWIW The CUDA driver version on the nodes is `384.111`

**Comment by lluunn** [comment]
Seems 384.11 supports up to 9.0

**Comment by lluunn** [comment]
@ankushagarwal how about we update gpu version to 1.6 for now.

**Comment by ankushagarwal** [comment]
SGTM

**Comment by lluunn** [comment]
updated. cpu using 1.7, gpu using 1.6. Please re-LGTM. Thanks

**Pull request merged**
