### PR TITLE
Revert "kfctlClient is a simple utility for sending requests to click to deploy (#3830)

### PR DESCRIPTION
**Pull request by jlewi**
See #3883
This reverts commit b0315cb4e95af11eb40257d7d97e294a04678ca4.

---
This change is [Reviewable](https://reviewable.io/reviews/kubeflow/kubeflow/3889)

### CODE REVIEW

**Comment by jlewi** [comment]
Test failure

```
 time="2019-08-13T19:11:31Z" level=error msg="Creating kfctl-db7e error: &{Code:RESOURCE_ERROR Location:/deployment
s/kfctl-db7e/resources/kfctl-db7e Message:{\"ResourceType\":\"gcp-types/container-v1beta1:projects.locations.clusters\",\"ResourceErrorCode\":\"400\",\"Re
sourceErrorMessage\":{\"code\":400,\"message\":\"The required node image is not available.\",\"status\":\"INVALID_ARGUMENT\",\"statusMessage\":\"Bad Reque
st\",\"requestPath\":\"https://container.googleapis.com/v1beta1/projects/kubeflow-ci-deployment/locations/us-east1-d/clusters\",\"httpMethod\":\"POST\"}}
ForceSendFields:[] NullFields:[]}" filename="gcp/gcp.go:347"
util.py                     71 INFO     Error: couldn't apply KfApp:  (kubeflow.error): Code 500 with message: coordinator Apply failed for gcp:  (kubeflo
w.error): Code 400 with message: gcp apply could not update deployment manager Error could not update deployment manager entries; Creating kfctl-db7e erro
```

This is #3886

**Comment by kunmingg** [comment]
/lgtm
/approve
Thanks!

**Pull request merged**
