### PR TITLE
Model Server Component documentation triage.

### PR DESCRIPTION
**Pull request by elsonrodriguez**
- Made it so that the image created in the instructions is utilizied
- Removed downloaded model due to incompatibility with recent TF server versions
- Made tf-serving image configurable
- Minor flow/grammar tweaks

### CODE REVIEW

**Comment by elsonrodriguez** [comment]
Should I also add an example of using the inception client to the user_guide?

**Comment by jlewi** [comment]
I thought @nkashy1 already added an example of using the client?

**Comment by elsonrodriguez** [comment]
They did, but in the component documentation, not the user_guide. It's a bit of repetition, but might make things easier to understand.

If yes I can do in another PR.

**Comment by jlewi** [comment]
How about creating an E2E example using inception? Some things that might be demonstrated

    * Generating predictions from outside the cluster (e.g. via secure reverse proxy)
    * A web app that can act as a FE [here's](https://github.com/vishh/container-engine-accelerators/tree/example-gpu/example/inception-golang/src) the code used in our demo at Kubecon
     * Clear docs for running the sample

Should we centralize all the docs and code specific to inception in one location and avoid duplication?

I think everything in components/  should be generic and not be specific (e.g. inception). We could create an examples/inception directory, although I think my preference would be to create a separate repository #174.

**Comment by jlewi** [comment]
@elsonrodriguez since @lluunn LGTM'd this I'm happy to merge it once its sync'd and we can follow up in another issue PR regarding a more complete example for inception.

**Comment by elsonrodriguez** [comment]
@jlewi synced

**Pull request merged**
