### PR TITLE
boostrapper install istio by default

### PR DESCRIPTION
**Pull request by lluunn**
For #2052 

/cc @kunmingg 
/cc @jlewi

---
This change is [Reviewable](https://reviewable.io/reviews/kubeflow/kubeflow/2505)

### CODE REVIEW

**Comment by jlewi** [comment]
@lluunn Is this going to affect what gets deployed via Click to Deploy? If it is how can we guard that change so that we don't change what gets deployed for 0.4? Only for later versions should we change what gets deployed.

**Comment by lluunn** [comment]
ah good point
/hold

**Comment by kunmingg** [comment]
@lluunn 
Do we have istio available on kfctl binary?

**Comment by lluunn** [comment]
@kunmingg not yet
filed @2507

**Comment by jlewi** [comment]
@lluunn In that case the best bet might be to add it to kfctl go binary first. @gabrielwen is going to work on adding new handlers to click to deploy to use the new go binary. So that might help guard it.

**Pull request closed without merging**
