### PR TITLE
Remove kfctl.sh

### PR DESCRIPTION
**Pull request by holdenk**
Remove the broken `kfctl.sh` script, folks should use the go program now instead.

---
This change is [Reviewable](https://reviewable.io/reviews/kubeflow/kubeflow/4084)

### CODE REVIEW

**Comment by jlewi** [comment]
Thanks @holdenk for picking this up.

For scripts/gke I think we should be a bit conservative and only delete scripts/gke/util.sh. The other scripts aren't directly tied to ksonnet I don't think and might still be used in a couple places.

**Comment by holdenk** [comment]
Sounds reasonable, I didn't see any refs to them so I figured it was OK to clean up, I'll revert that tomorrow and just cleanup the util side of the gke stuff.

**Comment by jlewi** [comment]
Thanks @holdenk;

BTW I generally skip over PRs with WIP in the title so when its ready to review please remove WIP from the title.

**Comment by jlewi** [comment]
Thanks @holdenk 
/lgtm
/approve

**Pull request merged**
