### PR TITLE
Add support for Python 2 kernels to the tensorflow notebook images.

### PR DESCRIPTION
**Pull request by ojarjur**
The Dockerfiles for these images previously tried to install the
Python 2 kernel, but omitted the `source activate` step prior
to the install step.

The result was that rather than installing the Python 2 kernel
at the user level, it reinstalled the Python 3 kernel which simply
duplicated the existing, globall-installed kernel.

With this change "Python 2" now shows up as an option in the Jupyter
UI when creating a new notebook, and in an existing notebook you
can switch from a Python 3 to a Python 2 kernel using the "kernel"
menu.

This change is a prerequisite to addressing #244, as the tf.Transform
library relys on Apache Beam, which currently only supports Python 2.

After this change lands, we should be able to add tf.Transform to
the `ipykernel_py2` Conda environment, and then it will be usable
in Python 2 kernels.

---
This change is [Reviewable](https://reviewable.io/reviews/kubeflow/kubeflow/314)

### CODE REVIEW

**Comment by jlewi** [comment]
@ojarjur Thanks for the quick fix!
Do you mind syncing and I'll merge it.
Note we'll need to build and push new images.

**Comment by ojarjur** [comment]
@jlewi Synced.

**Pull request merged**
