### PR TITLE
Add a README with the redoc link for the kfctl API.

### PR DESCRIPTION
**Pull request by jlewi**
This change is [Reviewable](https://reviewable.io/reviews/kubeflow/kubeflow/3176)

### CODE REVIEW

**Comment by kunmingg** [comment]
@jlewi 
Should we add status ```under development```?

**Comment by Ark-kun** [comment]
The tests are failing...

**Comment by abhi-g** [comment]
Please report in #buildcop slack channel

**Comment by jlewi** [comment]
Latest test failures are a problem trying to fetch some dependencies for kfctl.

Clearly not related to this PR since this PR is only changing the README

Attaching the logs.

[kubeflow-presubmit-unittests-3176-a486f16-6480-4577-490584372.log.txt](https://github.com/kubeflow/kubeflow/files/3162505/kubeflow-presubmit-unittests-3176-a486f16-6480-4577-490584372.log.txt)

**Pull request merged**
