### PR TITLE
macOS's custom `df` path.

### PR DESCRIPTION
**Pull request by butuzov**
This bugfix resolves error client can get if use non-standard `df` (provided by `coreutils` package) on macOS paltform.

See #3921

---
This change is [Reviewable](https://reviewable.io/reviews/kubeflow/kubeflow/3922)

### CODE REVIEW

**Comment by butuzov** [comment]
Hm. Should I resubmit PR using 0.6 branch as a base for the fix?

**Comment by butuzov** [comment]
@googlebot I consent.

**Comment by jlewi** [comment]
@butuzov Yes you should probably rebase on either the v0.6-branch or master and then resubmit.

Its usually best to submit to master and then cherrypick on to the release branch.

**Comment by butuzov** [comment]
got it.

**Pull request closed without merging**
