### PR TITLE
Add Katib e2etest for presubmits

### LINKED ISSUE #1946: Add e2etest for katib
Since we are installing katib by default, we need to make sure that the component works end to end. 

This will prevent issues like https://github.com/kubeflow/kubeflow/issues/1903 where the manifests are out of date and examples do not work properly.

### PR DESCRIPTION
**Pull request by richardsliu**
Add an e2etest to minikube and kfctl presubmits to verify that a StudyJob can be launched. Also verify that katib is installed correctly.

Fixes #1946 

This change is [Reviewable](https://reviewable.io/reviews/kubeflow/kubeflow/2296)

### CODE REVIEW

**Comment by richardsliu** [comment]
@hougangliu Fixed, please take a look.

**Comment by hougangliu** [comment]
@richardsliu  I think this PR depends on #2301 to make a studyJob's condition `Running`

**Comment by hougangliu** [comment]
@richardsliu Thanks!
/lgtm

**Pull request merged**
