### PR TITLE
jupyter-web-app rewrite

### PR DESCRIPTION
**Pull request by thesuperzapper**
Hi all, this is a pretty big PR which rewrites large portions of the `jupyter-web-app` UI.

This PR is a first step towards a better UI, I expect significant iteration before Kubeflow 1.2.

## Backend Changes:
- upgrade `Flask_Cors`, `Flask`, and `kubernetes` python packages
  - WARNING: don't forget to run `pip install -r requirements.txt` before testing
- implement PATCH API for Notebooks (used by start/stop feature)

## UI changes (General):
  - specify typography/font settings in `index.html` `<body>` with angular class, rather than star selector in `styles.scss`
  - move from NPM `material-icons` to `material-design-icons-iconfont` (actually has all of the material icons)

## UI changes (Notebook Table):
- overview:
  - see: **((PICTURE 1))**
- reduced the number of columns in the table, and made rows "expandable" to display further info: 
  - see: **((PICTURE 2))**
- implemented "start/stop" feature for notebook servers (as discussed in #4857)
  - see: **((PICTURE 3))**
  - this feature is created by PATCHing a `kubeflow-resource-stopped=true` annotation onto the Notebook Resource
- improved clarity of warning popup for delete/pause of notebooks 
  - see: **((PICTURE 4))**
- ensure notebook age is correctly reported if web server is not in UTC timezone

## UI changes (Notebook Spawner):
- **General:**
  - see: **((PICTURE 5))**
  - improved config descriptions
  - disabled form fields values are now submitted in the backend REST API POST (this is safe because our backend ignores when the user manipulates fields which are `readonly`)
- **Image:**
  - if images are `readonly` users can now select from the administrator provided list, rather than only the default image
- **CPU/RAM:**
  - administrators can set CPU/RAM to `null` (and no cpu/ram request will be made)
    - this allows spawning with only affinity configs (where requests may get in the way)
  - limits introduced by PR #5118 are now disabled by default
    - can be re-enabled with: `.cpu.setLimit` and `.memory.setLimit`
  - warnings will display in the UI if limits are enabled: 
    - see: **((PICTURE 6))**
- **GPU:**
  - administrators can set a list of valid "numbers of GPUs" for the dropdown: `.gpus.value.nums`
- **Volumes (General):**
  - administrators can set default values for volumes added with "new volume": `.dataVolumes.default.*`
  - UI now displays existing volume size
  - UI now disables 'new' type if no DefaultStorageClass exists in the cluster (and we are using `class={none}`)
  - better logic for detecting when a user is finished editing a volume name (no longer immediately flip to `existing` type)
  - UI correctly displays the `{notebook-name}` template before a notebook name is entered
  - UI resets to default volume settings when the notebook name is reset to `""`
- **Volumes (Workspace):**
  - administrators can set mount point to not be readonly: `.workspaceVolume.mountPath.readOnly`
  - UI now hides the volume panel when "No Workspace Volume" is checked
- **Volumes (Data):**
  - "add volume" will now increment the numerical ID properly
  - administrators can configure where the ID will appear in the name with `{volume-id}` template
- **PodDefaults:**
  - "Configurations" have been renamed to "PodDefaults"  to reduce confusion
- **Advanced Options:**
  - added popup to explain what "Enable Shared Memory" does

## Important Notes:
  - this PR has probably broken the ROK UI (I have no way of validating this, as the ROK is a proprietary tool)
  - I believe we should try and remove the ROK UI:
    - we can implement its features in the main UI behind config flags, this will reduce the complexity for future UI changes

## Future Work:
  - `notebook-controller` should fix notebook `containerState` getting stuck on `waiting: PodInitializing` for stopped Notebooks (this makes UI sometimes show paused Notebook Servers as pending)
  - we should implement a [material stepper](https://material.angular.io/components/stepper/overview) for notebook spawning, rather than the current form
  - we should perform proper linting/formatting on frontend typescript/javascript and backend python
  - we should fix `npm test` tests, as they are failing (even before this change)

### 1 - Notebook Table Page
picture_1

### 2 - Expanded Notebook Table Row
picture_2

### 3 - Notebook Stop/Start
picture_3

### 4 - Notebook Warning Dialog
picture_4

### 5 - Notebook Spawner Page
picture_5

### 6 - Notebook Spawner CPU/RAM Limit Warning
picture_6

### CODE REVIEW

**Comment by thesuperzapper** [comment]
@jlewi it seems like the CI server has run out of space, who should I ask?

**Comment by thesuperzapper** [comment]
@kimwnasptd this one is huge, but can you help review?

**Comment by kimwnasptd** [comment]
@thesuperzapper I'll take a look at this tomorrow

**Comment by yanniszark** [comment]
@thesuperzapper great work! I saw the message for the CPU/RAM requests and thought I would chip in, as I think the text misunderstands what it is.

First of all, requests are used for scheduling ONLY (run this Pod ONLY if you have this much RAM available for it).
A Pod can exceed its requested CPU/RAM and nothing will happen.

Limits are what prevent a Pod from using more CPU/RAM than specified.
Do we set limits for Jupyter Notebooks right now?

Finally, since CPU is an elastic resource, if a program tries to use more CPU than available, it will just be throttled, not restarted.
On the contrary, RAM is not an elastic resource and running out of available RAM will result in OOM (Out Of Memory) restarts.

**Comment by jlewi** [comment]
@thesuperzapper #buildcop in slack

**Comment by thesuperzapper** [comment]
@yanniszark 
> ...
> First of all, requests are used for scheduling ONLY (run this Pod ONLY if you have this much RAM available for it).
> A Pod can exceed its requested CPU/RAM and nothing will happen.

I think you are misunderstanding picture_5, it represents an **additional warning** which displays when the Kubeflow administrator enables the new configs, `.cpu.setLimit` or `.memory.setLimit`, which causes a limit to be set *equal to the request by the user*.

> Limits are what prevent a Pod from using more CPU/RAM than specified.
> Do we set limits for Jupyter Notebooks right now?

See above, only if those configs are set. (They are `false` by default)

> Finally, since CPU is an elastic resource, if a program tries to use more CPU than available, it will just be throttled, not restarted.

What would be a better warning text for when the CPU limit is set?

**Comment by thesuperzapper** [comment]
@kimwnasptd gentle bump

**Comment by thesuperzapper** [comment]
@yanniszark I have updated the text, is this better?

Please note, these warnings only display when the `setLimit` config is set.

picture5_new

**Comment by kimwnasptd** [comment]
@thesuperzapper please see this comment [here](https://github.com/kubeflow/kubeflow/pull/5237#issuecomment-683704911). We are working in a significant refactoring on the way to integrate the Jupyter web app with the common code of the other web apps, so that we can re-use code and build new functionality easier going forward.

Since a lot of things will change, I would gladly help with rebasing your changes on the updated code. Let's discuss live to get you up-to-speed.

**Comment by ca-scribner** [comment]
Really like how things look.  Personally would prefer the CPU/GPU numbers not hidden behind an extra click, but understand it adds clutter.  I also like the idea of a `stop` button - that sounds really nice

**Comment by thesuperzapper** [comment]
@kimwnasptd 

> @thesuperzapper please see this comment [here](https://github.com/kubeflow/kubeflow/pull/5237#issuecomment-683704911). We are working in a significant refactoring on the way to integrate the Jupyter web app with the common code of the other web apps, so that we can re-use code and build new functionality easier going forward.
 
I agree that having some common base is a good idea, but lots of that underlying code has the same errors which where found in `jupyter-web-app` pre this PR. 

In response to the proposed [components/crud-web-apps](https://github.com/kubeflow/kubeflow/tree/master/components/crud-web-apps): from a user perspectives, I think notebooks/volumes/tensor-boards should be viewable in a single 'app' (setting aside how it's implemented from the back end). I think a 'tab' style approach would work for the overview page, with a 'tab' for Volumes, Notebooks, Tensor-boards, etc.

Also seeing the issue #5201 raised by @sylus, we might need to rethink how we are writing the backend, (but there is nothing inherently stopping hundreds of users working with flask, lol).

> Since a lot of things will change, I would gladly help with rebasing your changes on the updated code. Let's discuss live to get you up-to-speed.

I am in Australia (Melbourne Timezone), but I work late, so message me on the slack if you want to voice call.

**Comment by thesuperzapper** [comment]
@ca-scribner 

> Really like how things look. Personally would prefer the CPU/GPU numbers not hidden behind an extra click, but understand it adds clutter. I also like the idea of a `stop` button - that sounds really nice

In the future, I expect we will put way more than just simple resource info in that 'expandable' row, like "pod CPU/Memory utilisation graphs", "running processes", etc.

**Comment by brendangadd** [comment]
@thesuperzapper 

### Front-End

I share the sentiment of loving these updates, particularly allowing users to **Stop** notebook servers! We have Istio enabled which causes issues for culling, and allowing users to stop servers should help reduce idle compute in the cluster.

> In the future, I expect we will put way more than just simple resource info in that 'expandable' row, like "pod CPU/Memory utilisation graphs", "running processes", etc.

I don't think the issue is with not having enough info in the expando, but with the UX around a data scientist choosing which server to open for a particular type of workload. Resource info could be high-value enough to warrant _also_ being visible directly in the table rows.

### Back-End

Our performance issues appeared to be centred around the k8s client and not Flask. Since the back-end is essentially a thin wrapper/filter around the k8s API – and its client – we felt it warranted seeing how the Go client fared as its implementation is different.

We found that it's very efficient. It holds the state of required resources in memory and stream deltas from master, so it's very fast and saves a bunch of requests to the k8s API. It also didn't display any of the issues were experiencing that smelled of connection pooling issues. So where the old server was falling over at about ~125 users, the Go implementation continues to shine.

Anyway, we'd be delighted to share as much of our work as possible back upstream, and again, props on the really slick TLC you gave to the `jupyter-web-app` component. We're eager pull these down to our cluster. :)

**Comment by kimwnasptd** [comment]
@brendangadd @sylus regarding the backend written in Go, if you are willing to maintain the code then I'm open to including the go backend code to the repo as well. We could keep on using the python backend in the default docker image we provide in the manifests but also build official docker images with the go backend for anyone that might want to use that as well. 

If you are interested in this please open a new issue so we can further discuss the details. If you do please also link #5201 to it so we can have all the context together.

**Comment by thesuperzapper** [comment]
If anyone wants to use these features before Kubeflow 1.1, I have published a compiled version of the container on Docker Hub: 
```
kftest/jupyter-web-app:rewrite-v0.1.5
```

**You will need to do the following:**

* Replace `gcr.io/kubeflow-images-public/jupyter-web-app`, with the above image
* Update your [spawner_ui_config.yaml](https://github.com/kubeflow/kubeflow/blob/f6f7f7f094fa22914a3ac393ce6c2ff1ea7ab325/components/jupyter-web-app/backend/kubeflow_jupyter/common/yaml/spawner_ui_config.yaml) to the format introduced in this PR
* Edit `ClusterRole/jupyter-web-app-cluster-role` to allow `PATCH` on `Notebook` resources
   * This lets `ServiceAccount/jupyter-web-app-service-account` preform the required `PATCH` for the START/STOP feature

**Comment by thesuperzapper** [comment]
I have pushed a new commit, which adds a feature I needed for my own purposes, (mostly so we remember to add it to the refactored version of `jupyter-web-app`).

The feature is the ability to specify the `containerPort` and `hostPort` of the Notebook. 

**Why would you want to configure `ports`?**
* `containerPort`: setting this lets you have Jupyter/Other Docker images with ports other than `8888`
* `hostPort`: setting this to ANY value will prevent the co-location of Notebook Pods 
   * useful for giving users their own exclusive Node (especially when paired with the new `affinityConfig`)
   * make sure you have a `cluster-autoscaler` (otherwise you can only have as many Notebooks as you have Nodes!)
   * don't specify a `hostPort` which you already use anywhere in your cluster (I am using `12345`)

**Here is the new `jupyter-web-app` image:**
```
kftest/jupyter-web-app:rewrite-v0.2.0
```

**To use it you should:**
* Follow the steps I gave [here](https://github.com/kubeflow/kubeflow/pull/5280#issuecomment-695954019)
* Update your `spawner_ui_config.yaml` (if you want to make use of the `ports` configs)

**Comment by maganaluis** [comment]
@thesuperzapper We were testing your PR, and found that if we delete the Notebooks via the UI the Notebook CRD is immediately deleted, however the Statefulset and Pod remain there running. I'm guessing there still some work to be done in the controller, would you like some help?

**Comment by thesuperzapper** [comment]
@maganaluis the "deleting" feature is not new in this PR, if that is not working for you, it's something to do with your setup.

Can you confirm if this issue is present for you in the Kubeflow 1.2 (or 1.1) version?

**Comment by maganaluis** [comment]
@thesuperzapper We are actually installing from master, so should be 1.2; after reverting the jupyter-web-app changes the delete processed worked as expected. I'll look in more detail in the two weeks. I'll post back here if I find any issues.

**Comment by kd303** [comment]
> If anyone wants to use these features before Kubeflow 1.2, I have published a compiled version of the container on Docker Hub:
> 
> ```
> kftest/jupyter-web-app:rewrite-v0.1.5
> ```
> 
> **You will need to do the following:**
> 
> * Replace `gcr.io/kubeflow-images-public/jupyter-web-app`, with the above image
> * Update your [spawner_ui_config.yaml](https://github.com/kubeflow/kubeflow/blob/f6f7f7f094fa22914a3ac393ce6c2ff1ea7ab325/components/jupyter-web-app/backend/kubeflow_jupyter/common/yaml/spawner_ui_config.yaml) to the format introduced in this PR
> * Edit `ClusterRole/jupyter-web-app-cluster-role` to allow `PATCH` on `Notebook` resources
>   
>   * This lets `ServiceAccount/jupyter-web-app-service-account` preform the required `PATCH` for the START/STOP feature

@thesuperzapper I have a cluster deployed in 1.1 and since I have users using it, to avoid downtime if I want to use this particular feature when you say replace the image what do you mean by it? Do you mean during installation or is there way I can change this somewhere else? Also I have a one-prem deployment so can you give full URL of the repo that I can white list for testing? 
This is a super feature and it solves lot of my current problems.. pls suggest.

**Comment by TomasPihrt** [comment]
@thesuperzapper I'm testing the START/STOP feature with [kfctl_istio_dex.v1.2.0 manifests](https://raw.githubusercontent.com/kubeflow/manifests/v1.2-branch/kfdef/kfctl_istio_dex.v1.2.0.yaml), but after patching the GCR image with `kftest/jupyter-web-app:rewrite-v0.1.5` when I navigate to *Central Dashboard > Notebook Servers and choose the namespace* only Kubeflow menu is displayed, otherwise blank screen.

In browser console I can see a few errors:
```
runtime.5a09a3ce9d0d6e716b47.js:1 Uncaught SyntaxError: Unexpected token '<'
polyfills.33be5ef0e73aeb02f33c.js:1 Uncaught SyntaxError: Unexpected token '<'
main.a00418141f4f42e32356.js:1 Uncaught SyntaxError: Unexpected token '<'
```
Can you help please?

**Comment by TomasPihrt** [comment]
> @thesuperzapper I'm testing the START/STOP feature with [kfctl_istio_dex.v1.2.0 manifests](https://raw.githubusercontent.com/kubeflow/manifests/v1.2-branch/kfdef/kfctl_istio_dex.v1.2.0.yaml), but after patching the GCR image with `kftest/jupyter-web-app:rewrite-v0.1.5` when I navigate to _Central Dashboard > Notebook Servers and choose the namespace_ only Kubeflow menu is displayed, otherwise blank screen.
> 
> In browser console I can see a few errors:
> 
> ```
> runtime.5a09a3ce9d0d6e716b47.js:1 Uncaught SyntaxError: Unexpected token '<'
> polyfills.33be5ef0e73aeb02f33c.js:1 Uncaught SyntaxError: Unexpected token '<'
> main.a00418141f4f42e32356.js:1 Uncaught SyntaxError: Unexpected token '<'
> ```
> 
> Can you help please?

It seems that deleting browser cache and refreshing the page solves that issue.

**Comment by karlschriek** [comment]
@thesuperzapper, @TomasPihrt anything else preventing this from being merged? Looks like it just needs a lgtm

**Comment by karlschriek** [comment]
Would be nice if this could be included in the upcoming KF 1.3 release.

**Comment by karlschriek** [comment]
Should have pinged the reviewers I guess. @prodonjs, @vkoukis?

**Comment by marcjimz** [comment]
bump on this. what is needed to push this into the release? we would really like to see this merged.

**Comment by kimwnasptd** [comment]
Apologies for not giving a heads up in this PR, for people following it.

We've refactored a lot of the web app's code for 1.3 https://github.com/kubeflow/kubeflow/pull/5332 https://github.com/kubeflow/kubeflow/pull/5463  and also included features which were also introduced in this PR. For reference the newest web app will allow users to start/stop Notebook servers and allow users to spawn RStudio and VSCode servers https://github.com/kubeflow/kubeflow/pull/5646.

@thesuperzapper since this PR is modifying the old code I propose to create new issues to track the features that were not included in 1.3  and close this PR.

**Pull request closed without merging**
