### PR TITLE
Revert "upgrade ks app for E2E test to 0.3.0"

### PR DESCRIPTION
**Pull request by lluunn**
Reverts kubeflow/kubeflow#2338, because it breaks the deployapp e2e test

/cc @jlewi

---
This change is [Reviewable](https://reviewable.io/reviews/kubeflow/kubeflow/2471)

### CODE REVIEW

**Comment by jlewi** [comment]
@lluunn based on your comment
https://github.com/kubeflow/kubeflow/pull/2338#issuecomment-463419365

Could we just update the testworker image used by the deployapp test?

**Comment by jlewi** [comment]
Seems like that image was already updated
https://github.com/kubeflow/kubeflow/blob/1349971ba8dd340c4d4ed00c397d09a2b90ae9c9/testing/workflows/components/click_deploy_test.jsonnet#L35

So is the problem submitting the workflow? or something else?

**Comment by jlewi** [comment]
Here's a recent failed run of deployapp
http://testing-argo.kubeflow.org/workflows/kubeflow-test-infra/kubeflow-periodic-master-deployapp-775-98a9?tab=workflow&nodeId=kubeflow-periodic-master-deployapp-775-98a9-3443922472&sidePanel=logs%3Akubeflow-periodic-master-deployapp-775-98a9-3443922472%3Amain

It looks like there was a problem building the go binary

```
+ go build -gcflags 'all=-N -l' -o bin/bootstrapper cmd/bootstrap/main.go
cmd/bootstrap/app/k8sAuth.go:6:2: cannot find package "cloud.google.com/go/container/apiv1" in any of:
        /usr/local/go/src/cloud.google.com/go/container/apiv1 (from $GOROOT)
        /mnt/test-data-volume/kubeflow-periodic-master-deployapp-775-98a9/src/cloud.google.com/go/container/apiv1 (from $GOPATH)
```

**Comment by kunmingg** [comment]
Looks like this line: https://github.com/kubeflow/kubeflow/blob/master/bootstrap/build_image.sh#L22
requires base image: https://github.com/kubeflow/testing/blob/master/images/Dockerfile
to support go modules (have go 1.11.5 installed)

Feels https://github.com/kubeflow/kubeflow/blob/master/bootstrap/build_image.sh#L22
can be removed.

**Comment by lluunn** [comment]
gcr.io/kubeflow-ci/test-worker/test-worker:v20190116-b7abb8d-e3b0c4 this one is not updated, the go version is 1.9, we need 1.11.

Yeah we can also fix all the images that was changed. I will do it tmr

**Pull request closed without merging**
