### PR TITLE
fix(centraldashboard) - Fix the central dashboard get start document's links

### PR DESCRIPTION
**Pull request by haoxins**

### CODE REVIEW

**Review by Arhell — COMMENTED** [review]
/ok-to-test

**Comment by umka1332** [comment]
Broken links were partially updated in already merged PR #6192. So this one should be at least rebased.

**Comment by haoxins** [comment]
> Broken links were partially updated in already merged PR #6192. So this one should be at least rebased.

Done, and the link `https://www.kubeflow.org/docs/distributions/microk8s/kubeflow-on-microk8s/` is still broken (404)

**Pull request closed without merging**
