### PR TITLE
Delete the tf-job package.

### LINKED ISSUE #1049: TFJob prototype's default TFVersion should be v1alpha2
TFOperator defaults to v1alpha2 but TFJob defaults to v1alpha1 
https://github.com/kubeflow/kubeflow/blob/master/kubeflow/core/prototypes/tf-job-operator.jsonnet#L12
https://github.com/kubeflow/kubeflow/blob/master/kubeflow/tf-job/tf-job.libsonnet#L47

Defaults should be same for consistency.

### PR DESCRIPTION
**Pull request by jlewi**
* The tf-job package only contains an outdated prototype for TFJobs. This is
  currently broken because the version was changed to v1alpha2 but the spec
  wasn't actually updated.

* Per discussions elsewhere we are moving towards structuring templates for
  TFJobs as prototypes in the examples package. We want the full spec
  to be in the prototype so that when a component is generated from the
  prototype users can easily modify it to do advanced customizations.

Fix #1049

---
This change is [Reviewable](https://reviewable.io/reviews/kubeflow/kubeflow/1091)

### CODE REVIEW

**Comment by johnugeorge** [comment]
Can you clarify ? What is the recommended way to create a tf job now ? I
think, we still need a easy way that can be used to create a basic job.
 If we are going ahead with deleting  TFjob, we have to update readme and
user guide.

**Comment by jlewi** [comment]
The preferred way to create a TFJob v1alpha2 is

```
ks generate tf-job-simple tf-job-simple
```

**Comment by jlewi** [comment]
Sent kubeflow/website#71 to update the website.

**Comment by jlewi** [comment]
/test all

Looks like there was a timeout waiting for workflows but the workflows actually ran too completion.

**Comment by jlewi** [comment]
@kunmingg ping

**Comment by kunmingg** [comment]
And the 2 config file [here](https://github.com/kubeflow/kubeflow/tree/master/bootstrap/config)

**Comment by kunmingg** [comment]
Will cherry-pick to release branch once merged. Thanks!

**Pull request merged**
