### PR TITLE
Use informer / indexer to cache rolebindings

### PR DESCRIPTION
**Pull request by thetko85**
To solve https://github.com/kubeflow/kubeflow/issues/5190

Found most of the issue to occur when listing the rolebindings when there are many namespaces as it does a loop. Query the shared index to list and get the rolebindings.

* Note: first commit and if there are procedures I am missing, please let me know.

### CODE REVIEW

**Comment by thetko85** [comment]
@googlebot I fixed it.

**Comment by yanniszark** [comment]
@thetko85 thanks a lot for the pr.
Because the client-go and controller-runtime packages already solve this problem and are widely used, I would strongly suggest reusing them.
More specifically, client-go informers or controller-runtimer manager can be used for getting a caching client without needing to reimplement the caching logic.
Can you take a look at those? I'll try to come back with some examples but feel free to explore.

**Comment by thetko85** [comment]
@yanniszark thanks for pointing me in the right direction. makes a lot more sense now that you mentioned it. I have refactored the code to utilise the informer and the indexer to get the rolebindings.

let me know if there is something that I am missing.

Cheers,

**Comment by yanniszark** [comment]
@thetko85 thanks for the prompt response and nice work on using an Informer!
Now that you use an informer, the `RoleBindingRepo` abstraction is not really necessary.
You can use `factory.Rbac().V1().RoleBindings().Lister()` which has Get/List methods that use the informer's cache.

**Comment by thetko85** [comment]
@yanniszark Thanks for the pointers. I have refactored the code to utilise the lister api. One question I do have is the stopper channel for the informers. Are there any implications for not explicitly stopping the channel in cases of panics or errors to the http server?

**Comment by yanniszark** [comment]
@thetko85 sorry for the late response, this is a PTO period.

> Are there any implications for not explicitly stopping the channel in cases of panics or errors to the http server?

That's a good question. I expect that the informer uses the stop channel so that it is informed of when the program needs to shut down, so that it can stop and cleanup the watches on the API Server. In a previous controller I wrote, I see that I created a channel that captures certain shutdown signals:
https://github.com/rook/rook/blob/0bcf040bd7653d8ce6b13a276ee24125f30ceb4c/cmd/rook/cassandra/operator.go#L80-L85

I would suggest doing the same here.

**Comment by yanniszark** [comment]
On another sidenote, in case you want to improve the code even more, we can use the controller-runtime package's caching client. This client encapsulates caching for all types, so you don't need to make a lister/informer dance for every type that's needed:
https://godoc.org/sigs.k8s.io/controller-runtime/pkg/manager#DefaultNewClient

**Comment by yanniszark** [comment]
ping @thetko85, any updates on this?
The only changes needed is to add a stop channel to the informer that catches signals, as detailed here:
https://github.com/kubeflow/kubeflow/pull/5202#issuecomment-676575622

**Comment by DavidSpek** [comment]
@yanniszark Is this something we should try and have included in release 1.3?

**Comment by yanniszark** [comment]
@DavidSpek it seems the original author won't continue this effort. Do you want to open a new PR for this? I don't think it's a blocker, but it's good to continue the effort :)

**Comment by DavidSpek** [comment]
@yanniszark I will open a PR for this then. I'm not sure how best to test image though (notebook controller is pretty easy to see if it is broken).

**Comment by DavidSpek** [comment]
@yanniszark I'm closing this PR as I have opened https://github.com/kubeflow/kubeflow/pull/5673 instead.
/close

**Pull request closed without merging**
