### PR TITLE
Fix vendortooltip typo

### PR DESCRIPTION
**Pull request by leetdavid**
There was a missing 'r' in one of the tooltip texts, and it was bugging me.

### CODE REVIEW

**Review by Arhell — COMMENTED** [review]
/ok-to-test

**Comment by MartinForReal** [comment]
@leetdavid Could you please  rebase the code first?

**Comment by leetdavid** [comment]
Sorry, I'm still quite new to making pull requests. 

If there are any other things I need to fix, please tell me and I'll try my best.

**Pull request merged**
