### PR TITLE
Removing unnecessary rbac authorization for tf operator

### PR DESCRIPTION
**Pull request by johnugeorge**
Configmaps are not used in operator anymore. Unnecessary rules are also removed

/hold

---
This change is [Reviewable](https://reviewable.io/reviews/kubeflow/kubeflow/3565)

### CODE REVIEW

**Comment by jlewi** [comment]
@johnugeorge Do we also need to update 
https://github.com/kubeflow/manifests ?

ksonnet is no longer really used.

**Comment by johnugeorge** [comment]
Yes. I just thought of keeping the changes in sync. I will make same changes in manifests also

**Comment by jlewi** [comment]
@johnugeorge I think its fine to commit this.

**Pull request merged**
