### PR TITLE
Support gpu-manager vGPU resource for notebook

### PR DESCRIPTION
**Pull request by typhoonzero**
Support [gpu-manager](https://github.com/tkestack/gpu-manager) vGPU resource for jupyter notebook.

Will add vGPU support for Kubeflow Pipeline later.

### CODE REVIEW

**Review by Arhell — COMMENTED** [review]
/ok-to-test

**Comment by typhoonzero** [comment]
@Arhell Anything else I should do so that this PR can be merged?

**Comment by Arhell** [comment]
> @Arhell Anything else I should do so that this PR can be merged?

https://github.com/kubeflow/kubeflow/blob/master/OWNERS

**Pull request closed without merging**
