### PR TITLE
remove jupyterhub code

### LINKED ISSUE #3719: Delete jupyterhub code
https://github.com/kubeflow/kubeflow/tree/master/components/jupyterhub

We no longer user JupyterHub so this code can be deleted.

### PR DESCRIPTION
**Pull request by yeya24**
Signed-off-by: yeya24 <yb532204897@gmail.com>

fix #3719

---
This change is [Reviewable](https://reviewable.io/reviews/kubeflow/kubeflow/3748)

### CODE REVIEW

**Comment by yeya24** [comment]
@jlewi  Could you please give a review?

**Comment by lluunn** [comment]
#4297 to remove jsonnet test

**Comment by nrchakradhar** [comment]
In the prow dashboard the message is like below:
Test started yesterday at 9:26 PM is still running after 15h47m15s. (more info)
@yeya24 Can be please rebase to the latest and submit. It might help resolve this issue.

**Pull request merged**
