### PR TITLE
Update RAPIDS AI Dockerfile

### PR DESCRIPTION
**Pull request by pdmack**
Updated to pull latest RAPIDS CUDA 9.2 image. Some minor package changes.

`gcr.io/kubeflow-dev/kubeflow-rapidsai-notebook:cuda9.2-devel-ubuntu16.04`

---
This change is [Reviewable](https://reviewable.io/reviews/kubeflow/kubeflow/3010)

### CODE REVIEW

**Comment by pdmack** [comment]
Newer image from Nvidia. 
And not sure there's any appreciable difference in image size.

**Comment by r2d4** [comment]
we probably want `base` instead of `devel`

```
base - contains a RAPIDS environment ready for use.
Use this image if you want to use RAPIDS as a part of your pipeline.
runtime - extends the base image by adding a notebook server and example notebooks.
Use this image if you want to explore RAPIDS through notebooks and examples.
devel - extends the runtime image by adding the compiler toolchain, the debugging tools, the headers and the static libraries for RAPIDS development.
Use this image to develop RAPIDS from source.
```

https://ngc.nvidia.com/catalog/containers/nvidia:rapidsai:rapidsai

**Comment by pdmack** [comment]
runtime, right?
We want the notebooks.

**Comment by r2d4** [comment]
Looks like we install jupyterhub later on in the image anyways. Not sure if we want to manage it or let the base image do it.

**Comment by pdmack** [comment]
Switched to the runtime image. They just roll with JupyterLab.

**Comment by pdmack** [comment]
@r2d4 bump?

**Pull request merged**
