### PR TITLE
Cherry-Pick #7230 into v1.8-branch

### PR DESCRIPTION
**Pull request by TobiasGoerke**
See https://github.com/kubeflow/kubeflow/pull/7230

### CODE REVIEW

**Comment by axel7083** [comment]
Hey @TobiasGoerke the v2.24.X version of the filebrowser seems to have some issues since the integration of TUS protocol, particularly with cloudflare as cdn. Maybe a prior version until fixed for Kubeflow 1.8 release ?

See https://github.com/filebrowser/filebrowser/pull/2145#issuecomment-1680594302 for details

**Comment by TobiasGoerke** [comment]
> Hey @TobiasGoerke the v2.24.X version of the filebrowser seems to have some issues since the integration of TUS protocol, particularly with cloudflare as cdn. Maybe a prior version until fixed for Kubeflow 1.8 release ?
> 
> See [filebrowser/filebrowser#2145 (comment)](https://github.com/filebrowser/filebrowser/pull/2145#issuecomment-1680594302) for details

Indeed, there's a couple of issues which all seem to be related to cloudflare blocking HEAD requests. We might be better off downgrading to v2.23.0 if we're going to support cloudflare users

**Comment by TobiasGoerke** [comment]
@kimwnasptd wdyt? Shall we fix this before testing / pre-release phase? Also, how? PR on both master and v1.8-branch?

**Comment by TobiasGoerke** [comment]
Just cherry-picked https://github.com/kubeflow/kubeflow/pull/7247 to downgrade filebrowser

**Comment by kimwnasptd** [comment]
Ah, I completely missed this one

/lgtm
/approve

**Pull request merged**
