### PR TITLE
Cherry-pick pipeline-runner ClusterRole changes (#2556) to pipelines branch

### PR DESCRIPTION
**Pull request by elikatsis**
This change is [Reviewable](https://reviewable.io/reviews/kubeflow/kubeflow/3293)

### CODE REVIEW

**Comment by neuromage** [comment]
Hi @elikatsis 

For my understanding, what is the purpose behind this permission change? Apologies, as I'm lacking some context here. 

/cc @IronPan

**Comment by elikatsis** [comment]
@neuromage 
Hello Ajay,
To use kubeflow/pipelines#926, `pipeline-runner` needs to be able to manipulate PVCs and VolumeSnapshots.

I didn't know I should have PR'd on `pipelines` branch, so I had made it on `master` (see #2556).
Now that I'm adding E2E tests to cover the aforementioned PR (kubeflow/pipelines#1342), I've seen that kubeflow is deployed using `pipelines` branch, and the permissions are needed for the test to be successful.

**Comment by neuromage** [comment]
Got it, thanks for the explanation.

/lgtm
/approve

**Pull request merged**
