### PR TITLE
permission bug fix and image tag update

### PR DESCRIPTION
**Pull request by kunmingg**
1. fix https://github.com/kubeflow/kubeflow/issues/657#issuecomment-382922523
2. fix cross namespace permission
3. typo fix

---
This change is [Reviewable](https://reviewable.io/reviews/kubeflow/kubeflow/699)

### CODE REVIEW

**Comment by ankushagarwal** [comment]
While we're at this, can you also fix the bootstrapper typo?

**Comment by ankushagarwal** [comment]
Can you also merge upstream changes? I have already updated https://github.com/kubeflow/kubeflow/blob/master/bootstrap/Makefile#L15 to public

**Comment by kunmingg** [comment]
Thanks, updated

**Pull request merged**
