### PR TITLE
Tell user to select a namespace to access namespaced menu item

### LINKED ISSUE #6118: Issue with Central Dashboard Custom Links
/kind bug

Weird Behaviour for custom internal links in kubeflow central dashboard when no namespace is specified.

**What steps did you take and what happened:**

Docker Image for Central dashboard: public.ecr.aws/j1r0q0g6/notebooks/central-dashboard:v1.4-rc.0

Links Configuration
```yaml
        {
          "type": "item",
          "link": "/{ns}/mlflow/",
          "text": "MLFlow",
          "icon": "editor:show-chart"
        }
```

Clicked on the MLFlow link in the sidebar with no namespace selected. This opened up another iframe for the centraldashboard within the centraldashboard. 

Screen Shot 2021-09-02 at 13 57 15

**What did you expect to happen:**

CentralDashboard to raise an error, prompt user to select a namespace. 

Note: That that custom link works correctly when the namespace is selected.

**Anything else you would like to add:**

- Feature Issue: https://github.com/kubeflow/kubeflow/issues/5863
- Kubeflow version: 1.3
- CentralDashboard Image: public.ecr.aws/j1r0q0g6/notebooks/central-dashboard:v1.4-rc.0 This contains the fix from #5871.

cc: @toshi-k

### PR DESCRIPTION
**Pull request by toshi-k**
Fix
#6118

Although namespaced menus items will be available for KF1.4 (#5871), there is room for improvement.
@munagekar pointed out the message that is shown for the user when he tries to access the namespaced item without  namespace selection.

This PR makes it possible to show the user-friendly message "Please select a namespace from the top bar" for such users.

@munagekar I appreciate if you help discussions for this PR.

/cc @kimwnasptd @jbottum @munagekar

### CODE REVIEW

**Comment by kimwnasptd** [comment]
@toshi-k first of all thanks for helping improve this part of the CentralDashboard! And apologies for the very late review.

Could you also provide a step-by-step description of the unhappy path? It will help me further understand the current problem and how someone can bump to it.

**Comment by toshi-k** [comment]
@kimwnasptd OK, I try to explain.

STEP1: Cluster admin creates two users by DEX (user1, user2).
STEP2: Create a new profile (Prof1). User1 is a owner of Prof1 and Assign user2 to Prof1 as a member.
STEP3: When user1 login to the central dashboard, his profile is selected automatically. He will see **Prof (Owner)** at the namespace selection (This is not a issue).
STEP4: When user2 login to the central dashboard, no profiles are selected automatically. He will see **Select namespace** at the namespace selection. If he chose a namespaced menu item before choosing a profile, he will see **Sorry, /{ns}/mlfow is not a valida page**. This is not a use friendly message and this is a issue of #6118.

In another case, a new user who is not assigned to any projects would also see the same message.

If these are not enough explanation, I hope @munagekar who raised issue #6118 explains more.

**Comment by kimwnasptd** [comment]
I see, now I'm synced. Thanks for the explanation @toshi-k!

The changes LGTM, will wait to ensure tests pass and will merge the PR. Also, as a side note, you could add yourself to the Kubeflow org so that tests run automatically in the future. Here's a relevant PR to do it https://github.com/kubeflow/internal-acls/pull/472, I'd be happy to sponsor you since you've done a lot of work in the CentralDashboard!

/ok-to-test

**Comment by kimwnasptd** [comment]
The error seems to be with Karma, but looking at the dockerfile the problem seems to be that we are using the `edge` branch to install packages!
```
22 12 2021 16:13:39.187:INFO [launcher]: Starting browser ChromeHeadless
22 12 2021 16:13:39.301:ERROR [launcher]: Cannot start ChromeHeadless
        Error relocating /usr/lib/chromium/chrome: wl_proxy_marshal_flags: symbol not found
```

I'll create a dedicated issue for this

**Comment by kimwnasptd** [comment]
@toshi-k could you rebase your changes on top of the latest master branch and force push? This should solve the tests failures we see

**Comment by toshi-k** [comment]
@kimwnasptd I rebased this PR on top of the master branch. I'm not sure if I can rerun tests by myself, but I think it's OK to proceed the review process.

**Comment by kimwnasptd** [comment]
The tests passed, so we are good to go!

/lgtm
/approve

**Pull request merged**
