### PR TITLE
Add support for Tolerations and Affinity in Notebooks

### PR DESCRIPTION
**Pull request by thesuperzapper**
This PR adds support for toleration and affinity configs in the Notebook Spawner UI.

Resolves: #4433

Options presented to the user are specified inside `spawner_ui_config.yaml`. This example config allows users to ask for exclusive access to a node within node-pool called `notebook-n1-standard-2`:
```yaml
spawnerFormDefaults:
  ...
  affinityConfig:
    # The default `configKey` from the options list
    # If readonly, the default value will be the only option
    value: "none"
    # The list of available affinity configs
    options:
      - configKey: "none"
        displayName: "None"
        affinity: {}
      # (DESC) Pod gets an exclusive "n1-standard-2" Node
      # (TIP) set PreferNoSchedule taint on this node-pool
      # (TIP) enable cluster-autoscaler on this node-pool
      # (TIP) dont let users request more CPU/MEMORY than the size of this node
      - configKey: "exclusive__n1-standard-2"
        displayName: "Exclusive: n1-standard-2"
        affinity:
          # (Require) Node having label: `node_pool=notebook-n1-standard-2`
          nodeAffinity:
            requiredDuringSchedulingIgnoredDuringExecution:
              nodeSelectorTerms:
                - matchExpressions:
                    - key: "node_pool"
                      operator: "In"
                      values:
                        - "notebook-n1-standard-2"
          # (Require) Node WITHOUT existing Pod having label: `notebook-name`
          podAntiAffinity:
            requiredDuringSchedulingIgnoredDuringExecution:
              - labelSelector:
                  matchExpressions:
                    - key: "notebook-name"
                      operator: "Exists"
                namespaces: []
                topologyKey: "kubernetes.io/hostname"
    readOnly: false
  tolerationGroup:
    # The default `groupKey` from the options list
    # If readonly, the default value will be the only option
    value: "none"
    # The list of available tolerationGroup configs
    options:
      - groupKey: "none"
        displayName: "None"
        tolerations: []
      - groupKey: "group_1"
        displayName: "Group 1: description"
        tolerations:
          - key: "key1"
            operator: "Equal"
            value: "value1"
            effect: "NoSchedule"
          - key: "key2"
            operator: "Equal"
            value: "value2"
            effect: "NoSchedule"
    readOnly: false
```

Here is a picture:
new_jupyter_form

### CODE REVIEW

**Comment by thesuperzapper** [comment]
I have a significant cleanup of the notebook UI which I will create PR for after this gets merged.

**Comment by thesuperzapper** [comment]
@vkoukis or @prodonjs can you please review?

**Comment by thesuperzapper** [comment]
or perhaps @kimwnasptd

**Comment by kimwnasptd** [comment]
@thesuperzapper I'll take a stab at this shortly.

One first quick comment is that from now on, I think, it would make sense to see how we could refactor the UI and not have the form grow indefinitely in height.

**Comment by kimwnasptd** [comment]
With a first look at the code it looks good, nice work @thesuperzapper!

I'll also be deploying the web app locally to make further testing and will report back

**Comment by thesuperzapper** [comment]
@kimwnasptd can we get this merged, I have a massive re-write of the UI which depends on these commits.

**Comment by kimwnasptd** [comment]
Tested the code and it works as expected. Thanks for the PR @thesuperzapper, this is a functionality that a lot of user will use.

> I have a massive re-write of the UI which depends on these commits.

We will have to coordinate on this, since I'm also planning on sending PRs for a rewrite I've done on the entire app in order to utilize the common code #5164 #5252 between the other web apps, for Tensorboards #3578 and a future Volumes web app #4758. 

I'll also be submitting a PR for creating a Notebooks WG so we can discuss this in this new work group's calls. If you'd like to start this discussion sooner then lets create an issue for the rewrite of the app and discuss there.

**Comment by kimwnasptd** [comment]
Also @thesuperzapper could you create another PR in the manifests to update the [config.yaml](https://github.com/kubeflow/manifests/blob/master/jupyter/jupyter-web-app/base/configs/spawner_ui_config.yaml) there as well?

**Comment by supertetelman** [comment]
I'm just deploying v1.2 using the istio manifest and using the Dex manifest, but I do not see this UI change.. Should I expect to see a UI similar to the one depicted here or has that been punted to v1.3 given all the other related UI rewrites?

**Comment by fakeburst** [comment]
@supertetelman It seems to be intended as there is a line in [the official blog post](https://blog.kubeflow.org/release/official/2020/11/18/kubeflow-1.2-blog-post.html) telling that _The artifacts for the updated Notebooks web app will be available in 1.2.1 or later_

You can still make use of this feature by bumping jupyter-web-app image version to `gcr.io/kubeflow-images-public/jupyter-web-app:vmaster-ge4456300`. We've done it in our cluster the other day, so far so good

**Comment by thesuperzapper** [comment]
@supertetelman @fakeburst you are correct that you need to use `gcr.io/kubeflow-images-public/jupyter-web-app:vmaster-ge4456300` for these features to work.

However, that image __was intended__ for Kubeflow 1.2 (so I will try and get that fixed).

For now, you can edit the `kustomization.yaml` in the `kubeflow-apps` folder generated by `kfctl build ...` to fix this:
```yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - XXXXX
# ----------------
# ↓ our changes ↓
# ----------------
images:
  - name: gcr.io/kubeflow-images-public/jupyter-web-app
    newName: gcr.io/kubeflow-images-public/jupyter-web-app
    newTag: vmaster-ge4456300
```

**Comment by zoltan-fedor** [comment]
Hi @thesuperzapper,
Even after pulling image `vmaster-ge4456300`, I still am not seeing the UI changes - see screens below.
Any ideas?

The new image has been pulled:
image

Still no annotations or tolerations options in the UI:
image

**Comment by zoltan-fedor** [comment]
Please ignore, I needed to clean the browser cache to see the changed UI.
Thanks!

**Pull request merged**
