### PR TITLE
Add PVC to Katib

### PR DESCRIPTION
**Pull request by inc0**
Add persistency to Katib database in ksonnet prototye

---
This change is [Reviewable](https://reviewable.io/reviews/kubeflow/kubeflow/1687)

### CODE REVIEW

**Comment by swiftdiaries** [comment]
@inc0 `ERROR : /mnt/test-data-volume/kubeflow-presubmit-unittests-1687-c606bc2-3637-2799/src/kubeflow/kubeflow/kubeflow/katib/vizier.libsonnet is not formatted`

**Comment by jlewi** [comment]
/assign @jlewi 
It looks like the most recent failure was a flake building the notebook images. I wouldn't have expected that to be triggered.

**Comment by jlewi** [comment]
Not sure why CLA check is stuck. Lets try reopening the PR.

**Comment by inc0** [comment]
Maybe something to do with me leaving Intel? I still have individual CLA tho...

**Pull request merged**
