### PR TITLE
Fix typo in notebook creation form

### PR DESCRIPTION
**Pull request by tmc**
This fixes a typo in the notebook creation advanced options form.

---
This change is [Reviewable](https://reviewable.io/reviews/kubeflow/kubeflow/3865)

### CODE REVIEW

**Comment by jlewi** [comment]
/assign @nrchakradhar 
/assign @kimwnasptd 

@nrchakradhar and @kimwnasptd can you please help get this PR merged?

/test all

**Comment by lluunn** [comment]
test failure is jsonnet..

**Comment by lluunn** [comment]
#4297 to remove jsonnet test

**Pull request closed without merging**
