### PR TITLE
Kubebench operator ksonnet package

### PR DESCRIPTION
**Pull request by andreyvelich**
Fixes: https://github.com/kubeflow/kubeflow/issues/2110. 
Related to: https://github.com/kubeflow/kubebench/issues/155. 
This is ksonnet package for kubebench operator CRD.

---
This change is [Reviewable](https://reviewable.io/reviews/kubeflow/kubeflow/2111)

### CODE REVIEW

**Comment by andreyvelich** [comment]
/hold 
Wait https://github.com/kubeflow/kubebench/pull/156, which build image for kubebench operator.

**Comment by jlewi** [comment]
Can you add an OWNERs file please?
Can you also file an issue to add a jsonnet unittest?

**Comment by andreyvelich** [comment]
@jlewi Done.

**Pull request merged**
