### PR TITLE
Automated cherry pick of #3080: Scripts for replicating Docker images using GCB to #3111: Improve the scripts for mirroing images to support VPC Cherry pick of #3080 #3111 on v0.5-branch. #3080: Scripts for replicating Docker images using GCB to #3111: Improve the scripts for mirroing images to support VPC

### PR DESCRIPTION
**Pull request by jlewi**
This change is [Reviewable](https://reviewable.io/reviews/kubeflow/kubeflow/3124)

### CODE REVIEW

**Comment by lluunn** [comment]
do we need a new 0.5.1 for this?

**Comment by jlewi** [comment]
@lluunn I don't think we have to. Since the only changes are in the ksonnet config; I think users could just supply do

```
kfctl init --version=v0.5-branch
```

Or the hash of the ocmmit.

**Comment by jlewi** [comment]
Looks like the failures were timeouts building the TF notebook images.
http://testing-argo.kubeflow.org/workflows/kubeflow-test-infra/kubeflow-presubmit-tf-notebook-release-3124-5274cdf-2448-7e5a?tab=workflow

/test all

**Comment by jlewi** [comment]
Most recent failure was a quota issue

```
util.py                     71 INFO     time="2019-04-29T13:48:44Z" level=error msg="Creating kfctl-3215 error: &{Code:RESOURCE_ERROR Location:/deployment
s/kfctl-3215/resources/kfctl-3215 Message:{\"ResourceType\":\"gcp-types/container-v1beta1:projects.locations.clusters\",\"ResourceErrorCode\":\"403\",\"Re
sourceErrorMessage\":{\"code\":403,\"message\":\"Insufficient regional quota to satisfy request: resource \\\"INSTANCE_GROUPS\\\": request requires '1.0'
and is short '1.0'. project has a quota of '400.0' with '0.0' available. View and manage quotas at https://console.cloud.google.com/iam-admin/quotas?usage
=USED&project=kubeflow-ci-deployment.\",\"status\":\"PERMISSION_DENIED\",\"statusMessage\":\"Forbidden\",\"requestPath\":\"https://container.googleapis.co
m/v1beta1/projects/kubeflow-ci-deployment/locations/us-east1-d/clusters\",\"httpMethod\":\"POST\"}} ForceSendFields:[] NullFields:[]}" filename="gcp/gcp.g
o:278"
```

**Comment by jlewi** [comment]
Looks like: /kubeflow/testing#361

**Pull request merged**
