### PR TITLE
chore: update node in crud-web-apps from 12 to 16

### PR DESCRIPTION
**Pull request by tariq-hasan**
# Motivation

This PR is an offshoot from https://github.com/kubeflow/katib/pull/2384 in `kubeflow/katib`.

https://github.com/kubeflow/katib/pull/2384 attempts to resolve errors in e2e tests for cypress in Katib UI and requires that the node version be upgraded from 12 to 16 for `kubeflow/kubeflow`.

# What does this PR do?

This PR therefore addresses the version upgrade for node from 12 to 16 for `kubeflow/kubeflow` as well as the following dependent components:
- jupyter
- tensorboards
- volumes
- centraldashboard-angular

# Test Plan

All the Github Action workflows have been run and tested on my fork: https://github.com/tariq-hasan/kubeflow/actions.

### CODE REVIEW

**Review by andreyvelich — COMMENTED** [review]
Thank you so much for this effort!
It will finally unblock the broken Katib UI CI/CD, since we can't merge any PRs since April.
Please take a look at this change.

/assign @kimwnasptd @orfeas-k @ederign 
/ok-to-test

**Comment by ederign** [comment]
@andreyvelich, I'll probably have time to look at this by the end of this week! I'll keep everyone posted!

**Comment by andreyvelich** [comment]
> @andreyvelich, I'll probably have time to look at this by the end of this week! I'll keep everyone posted!

Thank you for much for your time!
@kubeflow/wg-notebooks-leads Please can you trigger the GitHub actions ?

**Comment by andreyvelich** [comment]
cc @james-jwu @zijianjoy  I think, you also should be able to trigger GitHub actions.

**Comment by andreyvelich** [comment]
Hi @kimwnasptd @orfeas-k @ederign are we ready to merge this PR to unblock Katib E2Es ?

**Comment by andreyvelich** [comment]
@tariq-hasan Please can you check why Cypress tests fails ?

**Comment by tariq-hasan** [comment]
I am looking into it.

**Comment by tariq-hasan** [comment]
The [JWA Frontend Tests](https://github.com/kubeflow/kubeflow/actions/runs/10522695111) failed when @rimolive triggered Github Actions for this PR but when I ran the same test in a copy of the branch in my fork it succeeded: https://github.com/tariq-hasan/kubeflow/actions/runs/10748617448.

If we can re-trigger the Github Actions for this PR perhaps we can undersytand the issue better.

**Comment by thesuperzapper** [comment]
I triggered them just now @tariq-hasan

**Comment by tariq-hasan** [comment]
The Cypress tests succeed on my local.

Is the issue occurring due to test flakiness?

**Comment by tariq-hasan** [comment]
@thesuperzapper I upgraded Cypress to 13.14.0 instead of 13.13.3: https://github.com/kubeflow/kubeflow/pull/7637/commits/8a74e01fdee2aef63cfe0d4516a35e2d9eb091cd#diff-9f86874cf004f00e992b404d1a7469dca7d5a93f3def85ab82c7b1e998ccd38cL68.

I was wondering if you would be able to trigger the workflow again.

**Comment by tariq-hasan** [comment]
This is actually odd behavior. The tests happen to succeed or fail at random when running on my local or on a copy of the branch in Github Actions.

**Comment by andreyvelich** [comment]
@tariq-hasan What error do you see when you run tests locally ?

**Comment by tariq-hasan** [comment]
Hi @andreyvelich

The issue is specific to cypress and not a bug in the code.

When running the application from a development server using `npm run serve` and then navigating to `localhost:4200/new`, we find that there is an option to add a new volume at the bottom of the page.

Screen Shot 2024-10-03 at 11 41 20 PM

After clicking the button to add a new volume we do find the new volume created with the appropriate settings.

Screen Shot 2024-10-03 at 11 41 40 PM

That said, when running the tests from cypress using `npx cypress open`, we find that the second and third tests in `form-page.cy.ts` show flaky behavior and pass or fail randomly depending on the browser being tested.

Screen Shot 2024-10-03 at 11 56 42 PM

Screen Shot 2024-10-03 at 11 59 15 PM

**Comment by andreyvelich** [comment]
@ederign @tariq-hasan @kimwnasptd Any thoughts on how we can fix it ?

**Comment by ederign** [comment]
@andreyvelich Cypress is not my area of experience. @Griffin-Sullivan is helping us with Cypress tests on Model Registry. I wonder if you can take a look?

**Comment by Griffin-Sullivan** [comment]
I can't get it to fail locally. It's running on Chrome and Firefox and passing every time for both. Can we try running the tests again? Also is the test flakiness new to this PR or a previous issue?

**Comment by andreyvelich** [comment]
After the test restart it is getting the same error:
```
 New notebook form
    ✓ should have a "New notebook" title (1505ms)
    ✓ should auto update mount value when name change (1425ms)
    1) should not auto update mount value when it is dirty
    ✓ should update panel header name according to the name input field (676ms)
    ✓ should update name input field according to the ConfigMap (506ms)
    ✓ should update size input field according to the ConfigMap (482ms)
    ✓ should update access mode input field according to the ConfigMap (482ms)
  6 passing (10s)
  1 failing
  1) New notebook form
       should not auto update mount value when it is dirty:
     AssertionError: Timed out retrying after 4000ms: Expected to find element: `.last[data-cy="data volumes"]`, but never found it.
      at Context.eval (webpack://frontend/./cypress/e2e/form-page.cy.ts:45:7)
```

**Comment by tariq-hasan** [comment]
Is Cypress an absolute necessity for these tests - in so far as Jupyter is concerned? What options for frameworks do we have other than Cypress than can run the same tests? @Griffin-Sullivan @ederign

**Comment by tariq-hasan** [comment]
I have replaced Cypress with Playwright for the e2e tests in Jupyter. Can you please re-run the workflows? @thesuperzapper

**Comment by tariq-hasan** [comment]
Thanks for running the workflows.

JWA Frontend Tests have passed finally!

Can we re-run CentralDashboard-angular Frontend Tests? I have not seen this fail before.

**Comment by tariq-hasan** [comment]
All the tests have passed. Thanks @andreyvelich and @thesuperzapper.

Please review and let me know if anything needs to be changed @kimwnasptd @thesuperzapper @orfeas-k.

**Comment by andreyvelich** [comment]
Thank you for this effort @tariq-hasan!
@ederign @thesuperzapper @kimwnasptd @Griffin-Sullivan Please can you /lgtm this PR since it will unblock the Katib UI development.
/lgtm

**Comment by andreyvelich** [comment]
@tariq-hasan Did you get a chance to deploy your Docker images to verify that all WebApps (Jupyter WebApp, TensorBoard, Volumes WebApp) are working ?

**Comment by tariq-hasan** [comment]
Hi @andreyvelich I am deploying the Docker images to verify that all WebApps (Jupyter WebApp, TensorBoard, Volumes WebApp) are working. I will update here shortly.

**Comment by tariq-hasan** [comment]
There was a flag removed from the build scripts that I have added back in. All the web apps  - Jupyter, TensorBoards and Volumes - are functional from my local now when deployed through built Docker images.

Kubeflow Home
Kubeflow Notebooks
Kubeflow TensorBoards
Kubeflow Volumes
Kubeflow Katib Experiments
Kubeflow KServe Endpoints
Kubeflow Manage Contributors

**Review by andreyvelich — COMMENTED** [review]
Thank you for all of these tests @tariq-hasan!
We should be fine to merge this and unblock the Katib UI CI/CD.
@kimwnasptd @juliusvonkohout @thesuperzapper @ederign Can you `/lgtm` this please ?
/lgtm

**Comment by juliusvonkohout** [comment]
> Thank you for all of these tests @tariq-hasan!
> We should be fine to merge this and unblock the Katib UI CI/CD.
> @kimwnasptd @juliusvonkohout @thesuperzapper @ederign Can you `/lgtm` this please ?
> /lgtm

/lgtm

Since we definitely need this to reduce CVEs as well. We should even go to node 22 in follow up prs https://nodejs.org/en/about/previous-releases#release-schedule

**Comment by juliusvonkohout** [comment]
/assign @thesuperzapper 

Since I do not have approver rights

**Pull request merged**
