### PR TITLE
lists roadmap in reverse chronological order

### PR DESCRIPTION
**Pull request by mkbhanda**
addresses #6047 
Signed-off-by: Malini Bhandaru <mbhandaru@vmware.com>

### CODE REVIEW

**Comment by mkbhanda** [comment]
@pdmack and @bobgy, this is a trivial patch, just reverse ordering the roadmap entities. Shall submit a separate PR that adds in 1.4 roadmap.

**Comment by jbottum** [comment]
@mkbhanda I think this fine as a temporary fix.    We should have a goal to update with 1.4 info (and clean up some of the older items i.e. 1.3 is now released) by the end of month.

/lgtm

**Comment by kimwnasptd** [comment]
/lgtm

Thanks Malini!

**Comment by Bobgy** [comment]
Thanks! Makes total sense to me.
/approve

**Pull request merged**
