### PR TITLE
fix #1075, user_guide link is dead

### LINKED ISSUE #1075: user_guide link is dead
the link https://github.com/kubeflow/kubeflow/blob/master/user_guide.md#troubleshooting in https://github.com/kubeflow/kubeflow/blob/master/README.md is dead now

### PR DESCRIPTION
**Pull request by theofpa**
fix #1075

---
This change is [Reviewable](https://reviewable.io/reviews/kubeflow/kubeflow/1077)

### CODE REVIEW

**Comment by theofpa** [comment]
@googlebot, I signed it!

**Comment by johnugeorge** [comment]
Thanks for PR @theofpa I see that there are multiple sections in README that reference the user_guide. Can you please fix them too?

**Comment by theofpa** [comment]
Done!

**Pull request merged**
