### PR TITLE
Upgrade the google cloud monitoring node.js client

### PR DESCRIPTION
**Pull request by haoxins**
ref: #6202

### CODE REVIEW

**Comment by kimwnasptd** [comment]
Thanks for the PR @haoxins and apologies for the late review.

From your testing as well, as part of https://github.com/kubeflow/kubeflow/issues/6202, have you found any other points we should be aware of while upgrading two major versions of the package? I wouldn't expect so, but I'd like to confirm.

**Comment by haoxins** [comment]
Agree, and I also draft another PR https://github.com/kubeflow/kubeflow/pull/6237
but so large 😂
Maybe we need a plan to split these works to multi parts.

**Comment by haoxins** [comment]
@kimwnasptd I just picked the broken changes from the changlog.md

```
1.0.0 (2019-05-20)

⚠ BREAKING CHANGES

upgrade engines field to >=8.10.0 (#241)

2.0.0 (2020-05-08)

⚠ BREAKING CHANGES

Drop support for TimeSeriesQueryLanguageCondition as an alert condition type
The library now supports Node.js v10+. 
The last version to support Node.js v8 is tagged legacy-8 on NPM.

```

**Comment by kimwnasptd** [comment]
Looks good, thanks!

/ok-to-test

**Comment by kimwnasptd** [comment]
It seems that the tests are failing because we are reaching maximum quotas for Docker
https://argo.kubeflow-testing.com/workflows/kubeflow-test-infra/kubeflow-kubeflow-presubmit-cdash-test-6210-838ecd0-5392-2ad2?tab=workflow&nodeId=kubeflow-kubeflow-presubmit-cdash-test-6210-838ecd0-5392-2ad2-1306359580
```
INFO[0000] Retrieving image node:12.18.3-alpine from registry index.docker.io
error building image: GET https://index.docker.io/v2/library/node/manifests/sha256:0b5c7eb38785da1ad4c105930faca0bc546dfcceb0464724456e2
77fd5e3f6e2: TOOMANYREQUESTS: You have reached your pull rate limit. You may increase the limit by authenticating and upgrading: https:/
/www.docker.com/increase-rate-limit
```

Creating a distinct issue for this, since it's quite important
cc @theofpa

**Comment by kimwnasptd** [comment]
@haoxins the tests continued, but it seems that the docker build fails. Can you build the image locally?

There seems to be an issue with `node_modules/google-gax/build/src/fallback.d.ts(136,10): error TS1005: 'from' expected.` and `grpc`.
https://argo.kubeflow-testing.com/workflows/kubeflow-test-infra/kubeflow-kubeflow-presubmit-cdash-test-6210-838ecd0-3984-1f2a?tab=workflow&nodeId=kubeflow-kubeflow-presubmit-cdash-test-6210-838ecd0-3984-1f2a-1435842634

**Comment by haoxins** [comment]
We need to upgrade `ts` also, I'll check it.

**Comment by haoxins** [comment]
https://devblogs.microsoft.com/typescript/announcing-typescript-4-0/

Looks safe for us to upgrade `ts` to v4.

And maybe we should consider to migrate from `tslint` to `eslint`.
because

```
TSLint has been deprecated in favor of ESLint. Please see https://github.com/palantir/tslint/issues/4534 for more information.
```

I'll raise another PR to do this if we want.

**Comment by haoxins** [comment]
another PR for `ts-node` https://github.com/kubeflow/kubeflow/pull/6242

**Comment by haoxins** [comment]
is this ready to merge? I'll submit next PRs for central dashboard also affect the package lock file.

**Comment by kimwnasptd** [comment]
Yep, should be good to go. Thanks @haoxins!

> And maybe we should consider to migrate from tslint to eslint.

Yes, this is also a good direction to take since tslint is being deprecated.

/lgtm
/approve

**Pull request merged**
