### PR TITLE
Upgrade jupyter-web-app to Angular 8

### PR DESCRIPTION
**Pull request by thesuperzapper**
This PR upgrades `jupyter-web-app` to Angular to 8 (the current LTS version).

Additionally it upgrades:
* `fortawesome`
* `lodash`
* `protractor`
* `karma`

### CODE REVIEW

**Comment by thesuperzapper** [comment]
@kimwnasptd can you please review?

**Comment by kimwnasptd** [comment]
@thesuperzapper sure! It should be merged by today

**Comment by thesuperzapper** [comment]
@kimwnasptd tests were flaked, can you re-approve

**Pull request merged**
