### PR TITLE
jwa(front): Auto update mount path

### PR DESCRIPTION
**Pull request by tasos-ale**
Fix an issue in JWA's form and change the volume's mount path when the volume's name changes. This feature is already working for workspace volumes. Also, add one more e2e test for the volume's mount path.

### CODE REVIEW

**Review by orfeas-k — COMMENTED** [review]
Tested the image and it fixes the issue. Also, the code looks good. Small nit would be to rename `volGroupPrv` to `prvVolGroup` since that's what we do in the rest of the code as far as I'm concerned but it's not essential. Αlso, recently we switched to the term `UI tests` instead of e2e for Cypress tests. Thank you @tasos-ale 
cc @kimwnasptd 
/lgtm

**Comment by tasos-ale** [comment]
@orfeas-k I pushed the changes you mentioned. cc @kimwnasptd

**Comment by orfeas-k** [comment]
Thank you @tasos-ale!
/lgtm

**Comment by YQ-Wang** [comment]
@tasos-ale Could you take a look at this issue? https://github.com/kubeflow/notebooks/issues/33 It seems to be introduced by this PR.

**Pull request merged**
