### PR TITLE
Restricting controller access with Gatekeeper

### PR DESCRIPTION
**Pull request by richardsliu**
Fixes https://github.com/kubeflow/kubeflow/issues/3623

Design: https://bit.ly/2yJeU5u

Note - this doesn't change any Kubeflow behavior by default. The cluster admin needs to follow the instructions in README.md to configure Gatekeeper in the cluster.

---
This change is [Reviewable](https://reviewable.io/reviews/kubeflow/kubeflow/3984)

### CODE REVIEW

**Comment by jlewi** [comment]
Thanks @richardsliu should we make this a kustomize package in kubeflw/manifests rather than a component in kubeflow/components?

I don't have a strong oppinion.

If we make it a kustomize manifest that might make it easier to customize; and  potentially starting to auto-deploy it by including it in KFDef.Spec.Applications

**Comment by johnugeorge** [comment]
@richardsliu  
Isn't deploying via kustomize manifest the better option ?

**Comment by richardsliu** [comment]
I wasn't sure if automatically deploying this as a kustomize package is the right way. There are a couple of problems here:
- Gatekeeper dependencies are in https://raw.githubusercontent.com/open-policy-agent/gatekeeper/master/deploy/gatekeeper.yaml. If we want to build a kustomize package for it, we'll have to maintain a copy of this file in the manifests repo. Can we point a kustomize resource to a Github URL?
- The cluster admin would have to manually configure the constraint anyway (e.g. setting the service account names and labels, etc). We can expose these as parameters, but that adds extra maintenance for users who don't need this feature.

Suggestions?

**Comment by johnugeorge** [comment]
@richardsliu Is this planned to be an optional component for a cluster?

**Comment by jlewi** [comment]
@richardsliu I agree with you we shouldn't be installing it by default. That's a good question about whether kustomize can use a GitHub URL.

Since turning it into a kustomize package might require some effort it might make sense to leave it for the future.

Nonetheless would it be better to check the YAML files and directions in this repo into kubeflow/manifests? I think we might want to centralize all manifests (e.g. DM configs etc...) in kubeflow/manifests. Even if it isn't a kustomize package; is that a better location?

**Comment by richardsliu** [comment]
I will close this PR and open a separate one for kubeflow/manifests.

**Pull request closed without merging**
