### PR TITLE
update katib releaser

### PR DESCRIPTION
**Pull request by YujiOshima**
Add studyjob controller and metrics collector to katib releaser.
Relate to https://github.com/kubeflow/katib/pull/141

Signed-off-by: YujiOshima <yuji.oshima0x3fd@gmail.com>

---
This change is [Reviewable](https://reviewable.io/reviews/kubeflow/kubeflow/1400)

### CODE REVIEW

**Comment by jlewi** [comment]
@YujiOshima @lluunn Is there anything blocking this PR?

We'd like to get updated Katib images this week as part of cutting a 0.3 RC (#1541)

**Comment by richardsliu** [comment]
Hi @YujiOshima, please sync with the latest changes and resolve the conflict.

**Comment by jlewi** [comment]
The latest plan #1574 is that we should be using prow to manage our image builds.

This means the Argo workflows building the images should be in the same repo (kubeflow/katib) in this case that contains the source for the images. This way we can trigger the image builds when the code changes.

So we should close this PR and move the relevant workflows into kubeflow/katib and treat them like other E2E tests.

**Comment by jlewi** [comment]
Closing this in favor of kubeflow/katib#174

**Pull request closed without merging**
