### PR TITLE
change clusterrole to role

### PR DESCRIPTION
**Pull request by swiftdiaries**
Addresses issue: https://github.com/kubeflow/kubeflow/issues/1450. 
Assuming all kubeflow components are going to installed to a single namespace, CentralUI does not need cluster level scope. This PR is to restrict CentralUI's scope down to a single namespace.

---
This change is [Reviewable](https://reviewable.io/reviews/kubeflow/kubeflow/1728)

### CODE REVIEW

**Comment by jlewi** [comment]
Would you mind adding some unittests as part of this PR to verify that the manifests are correct?
Here's an example
https://github.com/kubeflow/kubeflow/tree/master/kubeflow/core/tests

**Comment by jlewi** [comment]
Looks like you just need to format the jsonnet files.

**Comment by swiftdiaries** [comment]
Thanks 👍

**Pull request merged**
