### PR TITLE
Delete user_guide.md; it is now part of the website

### PR DESCRIPTION
**Pull request by johnugeorge**
Delete user_guide.md; it is now part of the website 

~~Added doc for~~
~~1. Installation of Pytorch operator package~~
~~2. Running Pytorch distributed mnist sample app~~

---
This change is [Reviewable](https://reviewable.io/reviews/kubeflow/kubeflow/1038)

### CODE REVIEW

**Comment by jlewi** [comment]
@johnugeorge Would you mind moving user_guide.md over to kubeflow/website and then make the changes there. You shouldn't need to make any additional changes other than adding a header like the other files.

You can then update this PR to remove the user_guide.md from this repo so we don't duplicate docs.

/cc @abhi-g

**Comment by abhi-g** [comment]
@johnugeorge please put it under content/docs/ in the kubeflow/website repo.

**Comment by johnugeorge** [comment]
@jlewi Added https://github.com/kubeflow/website/pull/60

**Comment by jlewi** [comment]
Thanks @johnugeorge Can you update this PR to instead remove user_guide.md so we don't end up with it in two places?

**Comment by johnugeorge** [comment]
@jlewi updated

**Comment by jlewi** [comment]
Thank you
/lgtm
/approve

**Pull request merged**
