### PR TITLE
notebooks: notebook controller config RESTClient QPS and Burst in com…

### PR DESCRIPTION
**Pull request by mofanke**
notebooks: notebook controller config RESTClient QPS and Burst

### CODE REVIEW

**Review by Arhell — COMMENTED** [review]
/ok-to-test

**Comment by mofanke** [comment]
https://github.com/kubeflow/kubeflow/issues/6452

**Comment by kimwnasptd** [comment]
@mofanke could you rebase on top of the latest master branch?

**Comment by mofanke** [comment]
@kimwnasptd rebase done

**Pull request merged**
