### PR TITLE
Ci for components

### PR DESCRIPTION
**Pull request by kkasravi**
this does ci/cd for the following components
- admission-webhook
- centraldashboard
- jupyter-web-app
- notebook-controller
- profile-controller

using tekton pipelines. The follow use case is enabled:

1. A PR is merged into kubeflow/kubeflow updating the component
1. The merged commit is 1234
1. This tekton pipelinerun is triggered to build the component image from commit @1234.
1. The pipelinerun edits manifests/common/centraldashboard/base/kustomization.yaml (using kubeflow-bot repo) and adds the new image tag
1. The pipelinerun calls `make generate; make test`
1. If successful then
1.   The pipeline checks in the changes
1.   Opens a PR with the updated kubeflow/manifests that uses the newly built image
1.   Approvers LGTM the PR to kubeflow/manifests and it gets merged

---
This change is [Reviewable](https://reviewable.io/reviews/kubeflow/kubeflow/4238)

### CODE REVIEW

**Comment by jlewi** [comment]
@kkasravi How are we going to trigger these pipelines?
Do we already have this pipeline setup and working for one application?

**Comment by jlewi** [comment]
Is the base kustomize package really a base package?

IIUC the base package is defining Tekton Tasks and Pipelines. These resources are reused using Tekton not using kustomize.

For each application we are using kustomize to define a PipelineRun that will reference the Tekton resources defined in the base package but not using overlays.

**Comment by jlewi** [comment]
Would it be better to put the kustomize package defining the CI/CD pipeline into the directory releasing?

Longer term should we move the definition of that pipeline into kubeflow/testing?

**Comment by swiftdiaries** [comment]
And optionally, do we have a way to turn on/off the CI? 
For times when we have to update/fix?
Not sure if this is a major concern but when there's a drift, it'd nice to be able to turn it off -> patch in fixes and turn it on again. 
And +1 to the move to `kubeflow/testing`

**Comment by jlewi** [comment]
/hold
  * Were there changes you wanted to get in before commiting it?

/lgtm
/approve

**Comment by jlewi** [comment]
#4020 is the issue tracking this work.

**Pull request merged**
