### PR TITLE
templatize istio k8s version for aws

### PR DESCRIPTION
**Pull request by M00nF1sh**
make istio version templatized to use KUBEFLOW_VERSION

---
This change is [Reviewable](https://reviewable.io/reviews/kubeflow/kubeflow/3340)

### CODE REVIEW

**Comment by Jeffwan** [comment]
@lluunn could you help review and approve the PR?

**Comment by jlewi** [comment]
@Jeffwan  please create an OWNERs file in scripts/aws so you can and others can approve these changes.
/lgtm
/approve

**Pull request merged**
