### PR TITLE
Fix(Jupyter): Fix the ImageGroup object path

### LINKED ISSUE #6572: Cannot create notebook through web UI
/kind bug

**What steps did you take and what happened:**
[A clear and concise description of what the bug is.]
1. Install Kubeflow on local-cluster ( kind )
2. go to web UI and login with default user http://localhost:8080/_/jupyter/new?ns=kubeflow-user-example-com
3. Go to notebook panel and create a default one
4. After click "Launch", got error "[500] An error occured in the backend. http://localhost:8080/jupyter/api/namespaces/kubeflow-user-example-com/notebooks"
5. After check the pod "jupyter-web-app-deployment" log, found 

2022-07-13 09:20:24,419 | apps.common.form | INFO | Using provided value for 'workspace': {'mount': '/home/jovyan', 'newPvc': {'metadata': {'name': 'notebook1-volume'}, 'spec': {'accessModes': ['ReadWriteOnce'], 'resources': {'requests': {'storage': '10Gi'}}}}}
2022-07-13 09:20:24,419 | kubeflow.kubeflow.crud_backend.errors.handlers | ERROR | Caught and unhandled Exception!
2022-07-13 09:20:24,419 | kubeflow.kubeflow.crud_backend.errors.handlers | ERROR | create_notebook() got an unexpected keyword argument 'dry_run'
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/flask/app.py", line 1523, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.7/site-packages/flask/app.py", line 1509, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/usr/local/lib/python3.7/site-packages/kubeflow/kubeflow/crud_backend/decorators.py", line 18, in wrapper
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/kubeflow/kubeflow/crud_backend/decorators.py", line 40, in runner
    return func(*args, **kwargs)
  File "/src/apps/default/routes/post.py", line 48, in post_pvc
    api.create_notebook(notebook, namespace, dry_run=True)
TypeError: create_notebook() got an unexpected keyword argument 'dry_run'

**What did you expect to happen:**
Create notebook server

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Environment:**

- Kubeflow version: (version number can be found at the bottom left corner of the Kubeflow dashboard): build version dev_local (under left corner of UI dashboard)
- kfctl version: (use `kfctl version`):
- Kubernetes platform: (e.g. `minikube`) kind
- Kubernetes version: (use `kubectl version`):

-WARNING: This version information is deprecated and will be replaced with the output from kubectl version --short.  Use --output=yaml|json to get the full version.
Client Version: version.Info{Major:"1", Minor:"24", GitVersion:"v1.24.2", GitCommit:"f66044f4361b9f1f96f0053dd46cb7dce5e990a8", GitTreeState:"clean", BuildDate:"2022-06-15T14:22:29Z", GoVersion:"go1.18.3", Compiler:"gc", Platform:"linux/amd64"}
Kustomize Version: v4.5.4
Server Version: version.Info{Major:"1", Minor:"23", GitVersion:"v1.23.4", GitCommit:"e6c093d87ea4cbb530a7b2ae91e54c0842d8308a", GitTreeState:"clean", BuildDate:"2022-03-06T21:32:53Z", GoVersion:"go1.17.7", Compiler:"gc", Platform:"linux/amd64"}

- OS (e.g. from `/etc/os-release`):
Ubuntu 18.04

### PR DESCRIPTION
**Pull request by haoxins**
Fix #6572

### CODE REVIEW

**Comment by kimwnasptd** [comment]
Thanks! I tested this as well and confirm it solves the issue. I'll cherry-pick it to the release branch as well

/lgtm
/approve

**Comment by kimwnasptd** [comment]
Hmm, I think I tested using a different branch (?) than the one from the PR. Testing it again, and building the docker image as well, does not solve the initial problem.

@haoxins doing
```javascript
*ngIf="parentForm.get('imageGroupOne')?.options?.length > 0"
```

should not work, since the form control only gets the `.value` field and not the `options` from the ConfigMap https://github.com/kubeflow/kubeflow/blob/master/components/crud-web-apps/jupyter/frontend/src/app/pages/form/form-default/utils.ts#L123

Did the above PR work for you though?

**Comment by haoxins** [comment]
> Did the above PR work for you though?

my config doesn't have group one and two :(

it seems that we can only revert this change, if we don't want to make big change

**Comment by haoxins** [comment]
or, we can add extra fields for this, i will submit a PR

**Comment by haoxins** [comment]
https://github.com/kubeflow/kubeflow/pull/6599/files

using `Input`

**Pull request merged**
