### PR TITLE
Clarify JupyterHub and Jupyter description in component readme

### PR DESCRIPTION
**Pull request by willingc**
- Add reference to Project Jupyter a non-profit open source academic research project
- Edit text and links related to Jupyter, JupyterLab, and JupyterHub
- Correct minor typos and grammar

---
This change is [Reviewable](https://reviewable.io/reviews/kubeflow/kubeflow/333)

### CODE REVIEW

**Comment by jlewi** [comment]
@willingc Thank you. Can you please resync the files got out of date.

**Comment by jlewi** [comment]
@willingc If you'd like your non-profit to be listed as one of the participants in Kubeflow (e.g. in slides like [this](https://docs.google.com/presentation/d/1p82_DKJmIPjFS69EJ8p4StCClJW-JjGgxSWfhzw7Abw/edit#slide=id.g30f6ce7d33_0_305)

Just let myself and/or @aronchick know.

**Comment by willingc** [comment]
> @willingc If you'd like your non-profit to be listed as one of the participants in Kubeflow (e.g. in slides like this

> Just let myself and/or @aronchick know.

Thanks @jlewi. It would be nice to add Project Jupyter as a non-profit participant. 

cc @minrk @yuvipanda @ellisonbg @fperez

**Comment by jlewi** [comment]
@willingc Updated the slides.

Can you please resync when you have a chance files got out of sync again?

**Comment by willingc** [comment]
Thanks @jlewi for the update.

Is there a particular workflow that you recommend to avoid the resyncs?

**Pull request merged**
